### ISSUE TITLE
Notes can't connect to Sync on another browser connected to Sync

### ISSUE THREAD

**Issue by matijakovacevic** [mozilla/notes#1010]
### [Description]:
Can't sync notes on other browser instances connected to Sync.

### [Affected versions]:
Firefox Notes 4.0.0
Firefox Developer Edition 60.0b15 (64-bit)
Linux 16.04 x64

### [Prerequisites]:
Notes Pilot addon

### [Steps to reproduce]:
Installed Firefox notes on home browser. Logged into Sync, everything fine.
Installed on another browser (connected to sync).
Opened Notes Sidebar.
Logged in to Sync.
Went "Verify your Account".
After it closes the popup, it show's message "Reconnect to Sync".
Doesnt' go further than that..
By clicking the message, it opens the popup yet again, to login to Sync, and the same steps start over.

### [Expected result]:
After verifiying the account, sync all notes.

### [Actual result]:
No sync, no notes.

### [Additional Notes]:
No additional notes.
Not even original ones.

**Comment by matijakovacevic** [comment]
anyone?

**Comment by lennonrich** [comment]
Having the same/similar issues

[Description]:
Can't sync notes on other instances connected to Sync.

[Affected versions]:
- Firefox Notes
- Firefox Quantum 61.0.1 (64-bit)
- Windows 10 1709

[Prerequisites]:
- Notes addon

[Steps to reproduce]:
- Installed Firefox Notes on Desktop.
- Installed Firefox Notes on Android
- On Android, logged in to sync, everything fine.
- On Desktop, opened Notes Sidebar.
- Log in to Sync.
- Went "Verify your Account".
- After it closes the popup, it show's message "Reconnect to Sync".

By clicking the message, it opens the popup yet again, to login to Sync, and the same steps start over.

[Expected result]:
After verifiying the account, sync all notes.

[Actual result]:
Keeps asking me to reconnect to sync

**Comment by grahamperrin** [comment]
Is this still an issue? Distinct from #1350?

**Comment by matijakovacevic** [comment]
yep, still an issue. 
tested it this morning, same result.

ran https://firefox-storage-test.glitch.me/ and got the same result as **inextor**

by all that i've read, seems like it's the same bug as #1350

**Comment by grahamperrin** [comment]
OK, thanks. 

> ran https://firefox-storage-test.glitch.me/ and got the same result as inextor

If you're lucky – if there's simply offending cruft in the file system hierarchy – then you might resolve the issue by removing the cruft.

**Comment by matijakovacevic** [comment]
> If you're lucky – if there's simply offending cruft in the file system hierarchy – then you might resolve the issue by removing the cruft.

can you be more specific? Honestly, I didn't understand a thing you said :D

**Comment by matijakovacevic** [comment]
Hi.

This morning I tried connecting the browser that was throwing this error before and SUCCESS :)
Everything works!

**Comment by grahamperrin** [comment]
👍

Sorry for not offering a plain English explanation re: cruft in the file system. (I did draft a reply, but it disappeared … probably lost through a sessionstore bug.)
