### ISSUE TITLE
Implement our own Snackbar so we can Animate.parallel the FAB

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#1018]
@sebastienbarbier let's replace the paper snackbar with our own, so we have direct access to the animation and stacking order

**Comment by vladikoff** [comment]
We can copy pasta the component from here https://github.com/callstack/react-native-paper/pull/305 and simplify it

**Comment by sebastienbarbier** [comment]
This issue will be fixed in PR #1012

![floatingfab](https://user-images.githubusercontent.com/3018618/39516880-6d2c0984-4e28-11e8-8357-7851b110dfba.gif)
![floatingfabdelete](https://user-images.githubusercontent.com/3018618/39516882-6d8f537c-4e28-11e8-976c-8e9832da4dc8.gif)
