### ISSUE TITLE
[Android] The side menu cannot be dismissed if it is opened in the notes view mode

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1024]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2003) installed.
- Have enough notes in order to reach the maximum storage limit.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the "New Note" button and write something.
3. Swipe left on the side menu and observe the behavior.

**[Expected result]:**
- The side menu is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- If the swipe action is performed over the "Log out" button, you are wrongly logged out from "Notes".
- If the swipe action is performed over the "Feedback" button, the feedback page is opened.
- The issue is not reproducible if you tap outside the side menu.
- Attached a screen recording of the issue:
![rec of the issue 2](https://user-images.githubusercontent.com/31243259/39531112-24144382-4e33-11e8-9f15-999eeb87fa9d.gif)

**Comment by vladikoff** [comment]
This is a good find, thank you

**Comment by sebastienbarbier** [comment]
🎉

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2129 custom built on 15.05.2018) installed. Verified on on Samsung S8 (Android 8.0.0) and Pixel (Android 8.0.0).
