### ISSUE TITLE
Should we go back to the deleted note after `undo`?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#1030]
Hey @antlam, should we go back to the delete note after we `undo` or just add it back to the note list?

![image](https://user-images.githubusercontent.com/128755/39586429-00c5484e-4ec5-11e8-8808-aced5d694a45.png)

**Comment by antlam** [comment]
I would say go back to the Home view, that is, the full list of notes.

**Comment by vladikoff** [comment]
@antlam should there be any feedback after you press `Undo`?

**Comment by antlam** [comment]
Nope, the user will see that the note they just deleted has reappeared

**Comment by vladikoff** [comment]
@antlam excellent 👍 that's what we have now. Thank you!
