### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#104]
Load testing.  Let's do it!

https://bugzilla.mozilla.org/show_bug.cgi?id=1311510 has notes on previous kinto load testing, so maybe there isn't anything we need to do here?

@jasonthomas -- what date can we get stage running?

@pdehaan -- is the above bug good enough or should we do more?

**Comment by pdehaan** [comment]
Do we have Kinto support in V1? It looks like it was removed in #88.

**Comment by vladikoff** [comment]
We do not have Kinto for v1

**Comment by pdehaan** [comment]
Interesting. So what, if anything, would we need to load test for V1 still?

**Comment by Natim** [comment]
We still plan on shipping with Kinto as soon as FxA Oauth Keys retrieving features are deployed in prod.
So I guess it could be nice to plan ahead and to see how the deployed stack handle the potential load.

**Comment by pdehaan** [comment]
> We still plan on shipping with Kinto as soon as FxA Oauth Keys retrieving features are deployed in prod.

@vladikoff Do we have an ETA on the FxA work being deployed to prod?

@Natim +1 on planning ahead, but we may have to delay the load testing a bit until after the other 2 experiments are load tested.

**Comment by chartjes** [comment]
@pdehaan Before I went away on extended PTO in August, it was relayed to me through Karl Thiessen that the kintowe is doing well in production and there were currently no concerns about current or future load

**Comment by Natim** [comment]
Let's close this bug then because the stack for test pilot will be the same will much less data and users.
