### ISSUE TITLE
[Android] The "Text Selector" is wrongly displayed over the side menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1044]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2067 custom built on 09.05.2018) installed.
- Have at least a note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open any note and tap on any word from it.
3. Swipe from left to right.
4. Observe the "Text Selector".

**[Expected result]:**
- The "Text Selector" is covered by the side menu and is no longer visible.

**[Actual result]:**
- The "Text Selector" is displayed over the side menu.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/39819205-8f509f24-53ab-11e8-81ec-c7f10acdaacf.gif)

**Comment by vladikoff** [comment]
@sebastienbarbier why is the drawer showing in the Editor view? I Don't think we want it there.

**Comment by vladikoff** [comment]
@sebastienbarbier let's disable the drawer in the editor view, navigate to listview and show drover on reconnect sync

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed. Now the drawer is disabled in the note view.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
