### ISSUE TITLE
[Android] Side menu is not displayed when you swipe from left to the right in the latest build

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#1047]
**[Affected Platforms]:**
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Swipe from left to the right.

**[Expected result]:**
- Side menu is displayed.
    	
**[Actual result]:**
- Nothing happens.  

**[Notes]:**
- Side menu is also not dismissed when swipping from right to left.
- This issue is not reproducible with  notes-1_0-qa-v2067 version.
- Attached a screen recording of the issue:
![20180510_051516](https://user-images.githubusercontent.com/37875464/39867830-83b1047e-545f-11e8-8027-a0cce14783d9.gif)

**Comment by Softvision-AndreeaCupsa** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2083.apk) installed. Verified on Huawei P8 Lite (Android 6.0), Pixel (Android 8.0.0) and Samsung S8 (Android 8.0.0).

**Comment by vladikoff** [comment]
Thank you!
