### ISSUE TITLE
[Android] The side menu is not dismissed when the phone's "Back" button is tapped

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1048]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077 custom built on 10.05.2018) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap on the hamburger menu button from the top left part of the page.
3. Tap the phone's back button and observe the behavior.

**[Expected result]:**
- The side menu is dismissed.

**[Actual result]:**
- Nothing happens or the application is sent to background.

**[Notes]:**
- This behavior is not reproducible with the "Play Store" application, there the side menu is closed when the phone's "Back" button is tapped.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/39874431-660ebb20-5476-11e8-9e2a-323903769304.gif)

**Comment by vladikoff** [comment]
This should be fixed! Seems okay on my devices here

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
