### ISSUE TITLE
Hook Firefox Notes up to Test Pilot

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#105]
1) We need to make this repository match the spec at https://github.com/mozilla/testpilot/blob/master/docs/development/hosting.md

2) @relud to add this repository to the watcher

**Comment by pdehaan** [comment]
@clouserw @johngruen Do we have an ETA on when these new experiments will be posted up on https://testpilot.dev.mozaws.net/?

**Comment by vladikoff** [comment]
@pdehaan John is working on it

**Comment by SoftVision-PaulOiegas** [comment]
Would be nice to have at least a couple of weeks to thoroughly test them with the existing experiments before launching them to the Test Pilot release population. They must play nice with each other. 😄

**Comment by wresuolc** [comment]
^ yes, that's on john's plate.

For this issue though, the production branch of notes is now being built at https://testpilot.firefox.com/files/@notes/latest .  If you install that add-on, you'll also get updates.
