### ISSUE TITLE
[Android] Spaces are temporarely deleted if you pass two times with the text selector over them

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#1050]
**[Affected Platforms]:**
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "Create New Note" button.
3. Add 2 strings with a space between them.
4. Tap once inside the note to select the text selector.
5. Hold the text selector and pass twice with the text selector over the space between the strings.

**[Expected result]:**
- Text selector moves but the text is not changed.
    	
**[Actual result]:**
- The space between the words is deleted.

**[Notes]:**
- The space is correctly displayed after going back to notes list preview.
- Attached a screen recording of the issue:

![space issue](https://user-images.githubusercontent.com/37875464/39874593-eea976e6-5476-11e8-8bab-8754f0150fd0.gif)

**Comment by vladikoff** [comment]
Moved to Stretch

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (1.0.3 RC2) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
