### ISSUE TITLE
[Android] "&" character is not displayed correctly in notes list preview

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#1051]
**[Affected Platforms]:**
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "Create New Note" button.
3. Tap on the "&" character from the keyboard.
4. Go back to notes list preview and observe it.

**[Expected result]:**
- "&" character is correctly displayed in notes list preview.
    	
**[Actual result]:**
- "&" character is displayed as "`&amp;`" in notes list preview. 

**[Notes]:**
- The character is correctly displayed in the note.
- Attached a screen recording of the issue:

![character issue](https://user-images.githubusercontent.com/37875464/39874928-da97fbc2-5477-11e8-9269-94aed1cbdf9e.gif)

**Comment by vladikoff** [comment]
@sebastienbarbier removing your assignment from this

**Comment by vladikoff** [comment]
Moved to Stretch

**Comment by Softvision-AndreeaCupsa** [comment]
I have verified this issue and is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2355.apk) installed. Verified on Huawei P8 Lite (Android 6.0), Pixel (Android 8.0.0) and Samsung S8 (Android 8.0.0). Now the "&" character is properly displayed in notes list preview without any other characters.
