### ISSUE TITLE
[Android] You can not log in the App if Firefox is the only browser installed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#1056]
[Affected Platforms]:
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.
- Have Firefox set as the default browser.
- Only have the Firefox browser installed.

[Steps to reproduce]:
1. Open the Notes application and log out if needed.
2. Tap the "Sign In" button.
3. Enter valid credentials and tap "Sign in".
4. Confirm your account if needed and observe the behavior.

[Expected result]:
- The Notes view is displayed.
    	
[Actual result]:
- You are stuck on a landing page that does not redirect and you are not logged in.

[Notes]:
- The issue is not reproducible if Google Chrome or a proprietary browser are the only ones on the phone.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1G7pEhvD7xB6DqBnN39MfgXjqeSDBhld4).

**Comment by vladikoff** [comment]
This is wacky

**Comment by vladikoff** [comment]
It's not clear to me how to fix this yet. First assumption is that Firefox for Android is missing a component to capture a redirect

**Comment by SoftVision-CiprianMuresan** [comment]
@vladikoff, I was using Firefox release, but the issue is reproducible with Firefox Beta and Nightly as well.

**Comment by vladikoff** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1463620

**Comment by vladikoff** [comment]
I have to downgrade this to Stretch, due to upstream issues

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (app-release-signed custom built on 7/31/2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
Now the login flow is managed by the app.
