### ISSUE TITLE
[Android] Sign In form is wrongly opened in the Chrome webview if Firefox is set as the default Browser

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#1057]
[Affected Platforms]:
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.
- Have Firefox set as the default browser.
- Have Chrome installed.

[Steps to reproduce]:
1. Open the Notes application and log out if needed.
2. Tap the "Sign In" button.
3. Tap the hamburger menu from the newly opened webview.
4. Observed the bottom part of the dropdown menu.

[Expected result]:
- Powered by Firefox is displayed.
    	
[Actual result]:
- Powered by Chrome is displayed.

[Notes]:
- If Chrome is uninstalled/disabled, then the sign-in form will be opened in Firefox.
- Attached a screen recording of the issue: [Link](https://drive.google.com/open?id=1l4aTpz15vZW1gGutfkl5bO4XexHsvYlT).

**Comment by vladikoff** [comment]
Yeah, this is "by design" for now

**Comment by vladikoff** [comment]
We might be able to tweak the Auth library to try and open firefox, but not for release

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (app-release-signed custom built on 7/31/2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
