### ISSUE TITLE
[Android] A white screen is wrongly displayed if you quickly dismiss the Sign In form

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#1058]
[Affected Platforms]:
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)
- Samsung S8 (Android 8.0.0)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2077) installed.

[Steps to reproduce]:
1. Open the Notes application and log out if needed.
2. Tap the "Sign In" button and quickly double tap the devices' "Back" button.
3. Tap the devices' "Back" button again.
4. Observe the behavior.

[Expected result]:
- The Sign In page is displayed.
    	
[Actual result]:
- A white screen is displayed.

[Notes]:
- The app needs to be restarted in order to function correctly again.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/18304511/39923306-c7cadf32-552b-11e8-9e00-907958eee939.gif)

**Comment by vladikoff** [comment]
Good find!
