### ISSUE TITLE
If there is a blank line in mobile note, it says "Take a note" in ListView

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#1060]
If the first line in a note is blank line in mobile note, it says "Take a note" in ListView

Not sure if dup.

**Comment by vladikoff** [comment]
Out of v5

**Comment by El-Dringo-Brannde** [comment]
Can I take this issue for a OSS class?

**Comment by vladikoff** [comment]
ref https://github.com/mozilla/notes/issues/1144
