### ISSUE TITLE
[Android][Intermittent] Some strings are not successfully synchronized between the browser and the mobile application

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1064]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2092 custom built on 14.05.2018) installed.
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.1.0dev custom built on 14.05.2018) installed.
- Have the "Firefox Notes" sidebar opened in the browser.
- You are logged with the same account in both "Notes" instances.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the Notes application and log in if needed.
3. Focus the browser and click the "New Note" button.
4. Enter any string (eg. "also").
5. Swipe down to sync in the mobile app.
6. Observe the note created at step 4 in the mobile app.
7. Repeat steps 2 through 6 at least 5 times and observe the behavior.

**[Expected result]:**
- The strings are identical in both "Notes" instances.

**[Actual result]:**
- The strings are truncated (usually just the first letter from the string is displayed).

**[Notes]:**
- The issue is reproducible if the mobile application is reopened.
- The issue is also reproducible with other strings regardless of how long they are.
- If, after following the steps, a sync action is performed in the browser, the truncated notes will be synchronized and displayed in the browser application as well.
- Attached a screen recording of the issue:
![rec of the issue 2](https://user-images.githubusercontent.com/31243259/40007252-f03bab7e-57a4-11e8-8332-ccc6007e13a7.gif)

**Comment by sebastienbarbier** [comment]
From PR #1084 :
> I had the same issue on the mobile app and could found a fix, but did not apply it to the browser add-on 😓. It's basically a conflict between the create request from the first letter and the update request for the followings.
> 
> Current solution consist to delay the create note and see if an update event follow to just ignore it.
> 
> Also, was really hard to reproduce on my machine, might be some condition making this more obvious in some case so might need special care while testing 😉.

This error should also exist between two browsers since mobile app is not the cause of the but.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
