### ISSUE TITLE
[Android] The snackbar is wrongly displayed for a second after tapping the "Settings" key from keyboard

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#1069]
[Affected Platforms]:
- Samsung J3 (Android 7.0)
- Samsung Galaxy S8 (Android 8.0.0) -  Intermittent

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2192 custom built on 15.05.2018) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open the Notes application and log in if needed.
3. Tap the "New Note" button.
4. Tap inside the note's content in order to trigger the keyboard.
5. Tap the "Settings" key from the keyboard and observe the behavior.

[Expected result]:
- The keyboard is dismissed and the keyboard settings screen is displayed.

[Actual result]:
- The snackbar is displayed for a second after the keyboard is dismissed.

[Notes]:
- This is also reproducible when strings are typed inside the note. 
- This seems to be specific to Samsung devices, on Pixel (Android 8.0.0) and Huawei P8 Lite (Android 6.0) I didn't manage to reproduce the issue.
- Attached a screen recording of the issue:

![snackbar_issue](https://user-images.githubusercontent.com/26000308/40056162-27616522-5853-11e8-8397-48eb29e8b397.gif)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
