### ISSUE TITLE
2 Androids failing to sync between 2 devices after password change 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#1073]
* Have some notes
* Change password
* Connect on another device, only new notes will appear

**Comment by vladikoff** [comment]
Maybe: delete last sync after "Reconnect Sync"

**Comment by sebastienbarbier** [comment]
`Reconnect Sync` already clear `lastSyncTimestamp` 😓.
Could reproduce between android and webext, but not sure yet how to fix.
