### ISSUE TITLE
[Android] The "Notes" application crashes if you double tap the "Undo" button

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1075]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2129 custom built on 15.05.2018) installed.
- Have at least a note in the application.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Delete a note.
3. Tap the "Undo" button twice and observe the behavior.

**[Expected result]:**
- The previously deleted note is redisplayed.

**[Actual result]:**
- The application crashes.

**[Notes]:**
- You can find the logs here: https://goo.gl/Bxjq5P .
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40062788-a8ddcc42-5864-11e8-8894-d8e9fa66e743.gif)

**Comment by vladikoff** [comment]
Good find!

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/40063115-98cf89ce-582a-11e8-8d4c-869065b6da68.png)

cc @sebastienbarbier

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/40063162-b775b2ae-582a-11e8-84df-591e1f434e41.png)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2213 custom built on 17.05.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
