### ISSUE TITLE
[Android] The drawer cannot be opened from the "Hamburger" menu, if it was previously double tapped

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1077]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2129 custom built on 15.05.2018) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Double tap the "Hamburger" menu button.
3. Tap on the "Hamburger" menu button again and observe the behavior.

**[Expected result]:**
- The drawer is opened.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is still reproducible after the app is brought back from background. 
- The issue is no longer reproducible after the drawer is opened by swiping the screen from left to right.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40067727-84dbbe02-586f-11e8-87e5-73f5019913ba.gif)

**Comment by Softvision-MariusComan** [comment]
I have verified this issue and it seems that it is partially fixed. Tested on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0) with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2213 custom built on 17.05.2018) installed. 

Now, the drawer is not opened at the first tap on the "Hamburger" menu button but is opened correctly at the second tap.
Considering this I am reopening the issue.
![rec of the issue](https://user-images.githubusercontent.com/31243259/40181274-691f903e-59f1-11e8-8c4c-d36d7a1710f3.gif)

**Comment by vladikoff** [comment]
Thanks!

**Comment by vladikoff** [comment]
This should be fixed in latest mobile build

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2516 custom built on 25.06.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
