### ISSUE TITLE
Images, Hyperlinks and other types of content can be dragged into Firefox Notes

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#108]
[Notes]:
- This issue is also reproducible for other kinds of content(GIFs, styled text, etc.)

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on version (1.3 -dev, built on 23/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to any webpage and drag an Image into Firefox Notes.
3. Observe the Firefox Notes content area.

[Expected result]:
- The image is not displayed in Firefox Notes.

[Actual result]:
- The image is displayed in Firefox Notes.

[Additional Notes]:
- Attached a screen recording of the issue:
![notes_dragging_content](https://user-images.githubusercontent.com/20083658/27480942-f61f676a-5822-11e7-9d2e-81d4167c18da.gif)

**Comment by Natim** [comment]
Awesome feature 💃

**Comment by vladikoff** [comment]
Hm pretty sure I disabled this , I will double check

**Comment by vladikoff** [comment]
https://github.com/quilljs/quill/issues/191

**Comment by vladikoff** [comment]
Gifs are fine, but once you start adding hyperlinks then they do not fit anymore with the current CSS Styles. I posted a work in progress patch to remove ability to drop into the notes area

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Firefox Notes version (1.5.0dev built on 07/07/2017).

**Comment by vladikoff** [comment]
Yay!
