### ISSUE TITLE
"Notes Synced" snackbar without text is wrongly displayed after deleting an empty note

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#1081]
[Affected Platforms]:
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2184 alpha release) installed.

[Steps to reproduce]:
1. Open the Notes application and log in if needed.
2. Tap the "New note" button.
3. Tap the "3 dots" button and select the "Delete" option.
4. Observe the snackbar.

[Expected result]:
- "Notes Deleted" snackbar is displayed.

[Actual result]:
- "Notes Synced" snackbar (without text) is displayed. 

[Notes]:
- The "Notes Deleted" snackbar is spotted for a second only when the previous one starts to be dismissed.
- Attached a screen recording of the issue:

![issue_delete_blank_note](https://user-images.githubusercontent.com/26000308/40108331-43be9e50-5903-11e8-815b-4be4a3d747af.gif)

**Comment by vladikoff** [comment]
@sebastienbarbier this build seems after we moved the paper provider in https://circleci.com/gh/mozilla/notes/2182?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
