### ISSUE TITLE
[Android] The "Notes" application crashes if the "Undo" button is pressed after syncing

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1083]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2184) installed.
- Have at least a note in the application.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Swipe down to sync and select any note.
3. Tap the "Delete" button from the top right part of the screen while the "Notes synced!" banner is still displayed.
4. Tap the "Undo" button and observe the behavior.

**[Expected result]:**
- The deleted note is redisplayed.

**[Actual result]:**
- The application crashes.

**[Notes]:**
- The crash does not occur if the Undo action is made by itself.
- You can find the logs here: https://goo.gl/2NEBs3.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40109854-1530c4ec-5907-11e8-95b3-a79f07bebbe9.gif)

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/40119581-0d8f7af6-58eb-11e8-88cd-97e58593868c.png)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2213 custom built on 17.05.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
