### ISSUE TITLE
[Android] You are wrongly redirected to the FxA landing page if the phone is locked while signing in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1087]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2184) installed.

**[Steps to reproduce]:**
1. Open the Notes application and tap the "SIGN IN" button.
2. Enter you credentials and tap the "Sign in" button.
3. Lock your phone while the log in animation is still displayed.
4. Unlock the phone and observe the behavior.

**[Expected result]:**
- You are successfully logged into "Notes".

**[Actual result]:**
- The FxA landing page is displayed and you are not logged in.

**[Notes]:**
- This issue is reproducible regardless of the browser used to log in.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40126792-bc057a54-5936-11e8-8580-315bdf03fd3e.gif)

**Comment by vladikoff** [comment]
This is truly a good find 👍

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (app-release-signed custom built on 7/27/2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
