### ISSUE TITLE
[Android] The text caret is wrongly moved at the beginning of the, if the app is synced from the drawer

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1101]
**[Affected Platforms]:**
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2213 custom built on 17.05.2018) installed.
- Have at least a note in the application.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open any note and place the text caret at the end of the note.
3. Swipe from left to right in order to open the drawer and tap on the "Sync" button from the bottom part of it.
4. Observe the text caret position.

**[Expected result]:**
- The text caret remains in the same position as in step 2.

**[Actual result]:**
- The text care is moved at the content's beginning.

**[Notes]:**
- The issue is reproducible regardless of the place where the text caret is placed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40311205-dde2c278-5d17-11e8-8443-ca2bfd9a0ec6.gif)

**Comment by vladikoff** [comment]
The drawer should not be available in that view. This should be fixed now

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2276 custom built on 23.05.2018) installed. Now the drawer is disabled in the note view.
Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
