### ISSUE TITLE
[Enhancement][Android] Long tapping a note should select it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#1104]
[Affected Platforms]:
- Samsung Galaxy S8 (Android 8.0.0)
- Pixel (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2228 custom built on 18.05.2018) installed.
- Have at least one note.

[Steps to reproduce]:
1. Open the Notes application and log in if needed.
2. Long tap a note and observe the behavior.

[Expected results]:
- The note is selected.

[Actual results]:
- The note is opened.

[Additional notes]:
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/18304511/40313116-726cb016-5d1d-11e8-8129-5755bb07d294.gif)

**Comment by vladikoff** [comment]
@cedricium if you have an android device this is a good first issue to check out 

Source: https://github.com/mozilla/notes/blob/master/native/app/components/ListItem.js#L72

We should be able to add a `onLongPress`, example: https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#onlongpress and perform a toggle, just like the `onPress` here: https://github.com/mozilla/notes/blob/master/native/app/components/ListItem.js#L74
