### ISSUE TITLE
Handle the Refresh Token flow

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#111]
When we authenticate we get:

- An access_token (valid for a few time)
- A refresh_token (valid for ever that allow us to ask for a fresh access_token)
- keys

We want to refresh the `access_token` each time we open the sidebar, so that we can make sure the keys were not reset since the last time we'd sync.

Also using the `refresh_token` allows us to avoid failing with a staled `access_token`

[0] https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#post-v1token

**Comment by vladikoff** [comment]
Added Refresh Token flow in https://github.com/mozilla/notes/pull/313/commits/98c2a7302f87d0f1d77502a721508423127958da
