### ISSUE TITLE
[Android] The "Notes" application lags when typing in a note

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1118]
**[Affected Platforms]:**
- Pixel (Android 8.0.0)
- Samsung S8 (Android 8.0.0)
- Huawei P8 Lite (Android 6.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2314 custom built on 31.05.2018) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "New Note" button.
3. Start typing in the note and observe the behavior.

**[Expected result]:**
- The string is correctly displayed without any lags or freezes.

**[Actual result]:**
- The application becomes slow and lags while typing.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/40775494-e3b403c2-64d0-11e8-881c-877d7c48af63.gif)

**Comment by vladikoff** [comment]
hm anything that maybe causing this? I cannot repro this yet

**Comment by vladikoff** [comment]
Ok thanks!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2355 custom built on 04.06.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
