### ISSUE TITLE
"Notes" sidebar flickers when it's opened from the toolbar button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#113]
[Notes]:
- This is also reproducible while changing the sidebars from the "Notes" doorhanger.

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on version (1.3 -dev, built on 28/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Show sidebars" button from the toolbar.
3. Observe the process of displaying the Notes sidebar. 

[Expected result]:
- The "Notes" sidebar is displayed smoothly, without flickering while rendering.

[Actual result]:
- The "Notes" sidebar is slightly flickering while rendering.

[Additional notes]:
- Attached a screen recording of the issue:

![flicker](https://user-images.githubusercontent.com/26000308/27641528-cc386dce-5c24-11e7-9c19-9617338daf1c.gif)

**Comment by Natim** [comment]
Do you mind filing this bug in Bugzilla?

**Comment by Natim** [comment]
Maybe fixing #137 will help fixing this one. Can you verify it after #149 gets merged?

**Comment by vladikoff** [comment]
This should be fixed 👍

**Comment by SoftVision-CarmenFat** [comment]
I tested this with the latest Notes version (1.5.1dev built on 7/19/2017).
The Notes sidebar still flickers when it's opened or switched between the other existing sidebars.
