### ISSUE TITLE
New/edited notes are wrongly moved at the bottom of the list if the app is in offline mode

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1135]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0android-c2359) installed from "Google Play".
- Have no internet connection.
- Have the "Notes" application closed.
- Have at least three notes in the application.

**[Steps to reproduce]:**
1. Open the Notes application.
2. Edit the first note from the list or create a new one.
3. Observe the position of the note from step 2.

**[Expected result]:**
- The note is displayed in the first position.

**[Actual result]:**
- The note is displayed in the last position.

**[Notes]:**
- This issue is not reproducible if the application was opened when the internet connection was lost.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41042233-c6d68bac-69a9-11e8-9049-0eba67466845.gif)

**Comment by vladikoff** [comment]
Cannot repro on a Pixel and a few other devices, this is strange

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2516 custom built on 25.06.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
