### ISSUE TITLE
"Undo" option is not working if the text was previously deleted through "Delete" key 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#114]
[Notes]:
- This is not reproducible when deleting the text through context menu option.

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on version (1.3 -dev, built on 28/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Show sidebars" button from the toolbar.
3. Write something on the "Notes" editable area.
4. Select the written text and press "Delete" key.
5. Right click on the editable area.
6. Click on "Undo" option and observe what happens next.

[Expected result]:
- The previously deleted text is displayed again in the editable area.

[Actual result]:
- Nothing happens, the deleted text is not displayed.

[Additional notes]:
- Attached a screen recording of the issue:

![delete key](https://user-images.githubusercontent.com/26000308/27641735-682e9d66-5c25-11e7-8a65-5727dc854a6e.gif)

**Comment by Natim** [comment]
However the ctrl+z shortcut works.

**Comment by Natim** [comment]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1379584#c7:
```
This is site bug and there is no spec to turn off undo stack of browser.

If delete selection (step. 3) is handled by browser, undo will work.  But step.
3 is handled by site's JS unfortunately.  So this operation isn't added into
our undo stack.
```

**Comment by Natim** [comment]
Refs https://github.com/w3c/editing/issues/150

**Comment by Natim** [comment]
This would be handled with the beforeinput event implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=970802
