### ISSUE TITLE
[Android] If two notes are deleted one after the other, the first note is wrongly brought back at undo

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1142]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2393 custom built on 08.06.2018) installed.
- Have at least two notes is the application.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Select any note and tap the delete button.
3. While the "Undo" banner is still displayed, delete another note.
4. Tap the "Undo" option and observe the behavior.

**[Expected result]:**
- The second note is brought back.

**[Actual result]:**
- The first note is brought back.

**[Notes]:**
- The issue is not reproducible if you delete the second note after the "Undo" banner is no longer displayed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41166609-5f630170-6b49-11e8-80b4-a1e1bdfe7544.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/1151 by @Natim
