### ISSUE TITLE
[Android] The "Take a note..." title is wrongly displayed in the mobile app, if the first row in the note is empty

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1144]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2393 custom built on 08.06.2018) installed.
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 11.06.2018) installed.
- You are logged with the same account in both "Notes" instances.

**[Steps to reproduce]:**
1. Open the "Notes" mobile application and log in if needed.
2. Open the browser with the profile from prerequisites.
3. Click on the "New Note" button and press the "Return" key.
4. Write something and go to the mobile instance of "Notes".
5. Sync your notes and observe the note from step 4.

**[Expected result]:**
- The note's title is correctly displayed in the list view.

**[Actual result]:**
- The "Take a note..." message is displayed.

**[Notes]:**
- This issue is also reproducible on the browser if you press the "Return" key on a new created notes on mobile app.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41241585-01e8bee0-6da6-11e8-84cf-b73ff4dd8dc0.gif)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/notes/issues/1060 , closing that in favour of this

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2427 custom built on 15.06.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
