### ISSUE TITLE
"Sync Your Notes" notification doesn't display a "Close" button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#115]
[Notes]:
- Since the notification doesn't go away and there is no "X" button to close it, the user has to click again on the "Sync Your Notes" button in order to dismiss the notification.

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes Notes add-on version (1.3 -dev, built on 28/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Show sidebars" button from the toolbar.
3. Click on "Sync Your Notes" button from the bottom of the sidebar.
4. Observe the yellow Sync notification above the previously clicked button.

[Expected result]:
- "X" (close) button is displayed on the top right side of the notification.

[Actual result]:
- "X" (close) notification is not displayed. 

[Additional Notes]:
- Attached a screenshot of the issue:

![sync](https://user-images.githubusercontent.com/26000308/27691699-87dcf0b8-5ced-11e7-8d1b-e092213953f5.png)

**Comment by cedricium** [comment]
Currently working on a solution for this, will make a PR soon.

**Comment by vladikoff** [comment]
@cedricium there should be an svg icon for this in the source already

**Comment by cedricium** [comment]
@vladikoff thanks for the heads up! Guess I don't need to use the multiplication sign anymore haha

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Firefox Notes version (1.5.0dev built on 07/11/2017).
The "Close" button is displayed and correctly works on all Firefox channels.
