### ISSUE TITLE
The text caret disappears and you cannot type anymore, if you click anywhere under the last created row

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1152]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 14.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button and click anywhere in the sidebar except on the first row.
3. Observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The text caret disappears and you cannot type anymore.

**[Notes]:**
- This issue is not reproducible with the TxP version of "Firefox Notes".
- This issue is no longer reproducible if you click on the first row (in case of an empty note) or on an area that contains text.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41417903-4a388ede-6ff7-11e8-8a02-04c795eb4152.gif)

**Comment by Natim** [comment]
Related #1157 #1154

**Comment by vladikoff** [comment]
This should be fixed

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 20.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
