### ISSUE TITLE
The "Heading" dropdown menu is not fully displayed if the note is empty

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1153]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 14.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button and click the "Font Size" button.
3. Observe the behavior.

**[Expected result]:**
- The dropdown menu is opened and all the headings are fully visible.

**[Actual result]:**
- Only the "Heading 1" option is visible.

**[Notes]:**
- This issue is not reproducible with the TxP version of "Firefox Notes".
- This issue is no longer reproducible if the dropdown menu is opened over an area that contains text.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41418248-02e40f80-6ff8-11e8-9d1e-bc6274f00ce8.gif)

**Comment by vladikoff** [comment]
This should be fixed

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 20.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
