### ISSUE TITLE
The formatting toolbar is not fixed and disappears after the content is scrolled

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1154]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 14.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "New Note" button.
2. Write or paste any text until the content is scrolled.
3. Observe the behavior.

**[Expected result]:**
- The formatting toolbar remains on its position.

**[Actual result]:**
- The formatting toolbar is scrolled together with the content.

**[Notes]:**
- This issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41418473-6caad728-6ff8-11e8-95f9-7cf0b3bcb2dd.gif)

**Comment by Softvision-RemusDranca** [comment]
After further investigations , I found that after following the STR from the above comment, if you click outside then inside of the side bar, the formatting toolbar is displayed over the title toolbar. Also, if you delete a part of the text, an empty space is wrongly displayed where the formatting toolbar position was original placed.

Here is a screen recording of the described behavior:
![display](https://user-images.githubusercontent.com/40061643/41424447-bd6744a4-7006-11e8-8390-492a9d62d214.gif)

**Comment by vladikoff** [comment]
This should be fixed

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 20.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
