### ISSUE TITLE
The background of the area that contains text wrongly remains white, if the dark theme is enabled

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1156]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 14.06.2018) installed.
- Have the dark theme enabled from 'about:addons>Extensions>Firefox Notes".
- Have text copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste the text from prerequisites and observe the note's background.
3. Observe the behavior.

**[Expected result]:**
- The note's background has a dark blue color.

**[Actual result]:**
- A white background is displayed under the note's content.

**[Notes]:**
- This issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41419157-ff62368c-6ff9-11e8-9dc5-0996efe581aa.gif)

**Comment by Natim** [comment]
@cedricium would you like to give it a look? I guess it is a CSS issue

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 21.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
