### ISSUE TITLE
The scrollbar is no longer displayed in the note view

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/notes#1157]
[Affected versions]:
- Firefox 60.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 06.14.2018) installed.
- Have a note that contains a large amount of text open.

[Steps to reproduce]:
1.Open the browser with the profile from prerequisites.
2.Copy and paste all text from the note a few times. 
3.Observe the behavior.

[Expected result]:
-The scrollbar is displayed.

[Actual result]:
-The scrollbar is not displayed.

[Notes]:
- This issue is not reproducible in the list view.
- This issue is not reproducible with the TxP version of Firefox Notes.
- The text can be scrolled by using the keyboard arrows.
- Attached is a screen recording of the issue:
![notes scrollbar](https://user-images.githubusercontent.com/40061643/41420398-f767a2f2-6ffc-11e8-9d90-117a5cd4caeb.gif)

**Comment by Natim** [comment]
Related to #1154

**Comment by vladikoff** [comment]
This was fixed

**Comment by Softvision-RemusDranca** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 20.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x 64, Mac 10.13 and Ubuntu 14.04 x 64.
