### ISSUE TITLE
"Notes" icon is not displayed in sidebar switcher button and its door hanger

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#116]
[Notes]:
- On v54.0 the icon is displayed in the door hanger opened after clicking the "Show sidebars" toolbar button.
- On Mac OS the icon is displayed in the door hanger's sidebar switcher button on all Firefox channels.

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes Notes add-on version (1.3 -dev, built on 28/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Show sidebars" button from the toolbar.
3. Observe the items of the "Notes" sidebar switcher button.
4. Click the "Notes" sidebar switcher button.
5. Observe the way the "Notes" sidebar option is displayed.

[Expected result]:
3. The icon of the "Notes" sidebar is displayed on the left side of the button.
5. The icon of the "Notes" sidebar is displayed on the left side of "Notes" text.

[Actual result]:
3. The icon of the "Notes" sidebar is not displayed on the left side of the button.
5. The icon of the "Notes" sidebar is not displayed on the left side of "Notes" text.

[Additional Notes]:
- Attached a screenshot of the issue:

![icon missing](https://user-images.githubusercontent.com/26000308/27692308-0e5753ee-5cef-11e7-923a-4559a343a06d.png)

**Comment by wresuolc** [comment]
@johngruen is this critical?

**Comment by vladikoff** [comment]
This is Photon only ( Nightly? )

**Comment by SoftVision-CarmenFat** [comment]
The issue is reproducible on all Firefox channels, although on Release is a bit different:
- there isn't any "Notes" sidebar switcher button, but only the generic Sidebar button located in the toolbar; in this case, I'm not sure if the "Notes" icon should be displayed next to "Notes" sidebar title.
- if clicking the Sidebar button from the toolbar, a door hanger with all sidebars is displayed; in this case, only Notes displays its icon, unlike the other sidebars that don't show any of their icons.

For more details, please see the screenshot below:

![icon notes](https://user-images.githubusercontent.com/26000308/28024661-05631206-659a-11e7-8153-d06919d04964.png)

**Comment by Natim** [comment]
Can you see if this is till the case with 2.0.0a2?

**Comment by SoftVision-CarmenFat** [comment]
- Tested this with latest Notes v. 2.0.0a2 using latest Nightly 58.0a1 (2017-10-11), Beta 57.b7 and the "Notes" icon is displayed on both sidebar switcher button and its door hanger.
- However, on Firefox Release 56.0 the icon is not displayed at all, as you can see in the following screenshot:
![rel](https://user-images.githubusercontent.com/26000308/31487176-8c0a4170-af42-11e7-977b-679d6511d0a4.png)

**Comment by vladikoff** [comment]
This should be fixed in FF57 now  👍

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest version of Notes built on 11/23/2017.
