### ISSUE TITLE
The "Welcome Note" is no longer displayed, even if the extensions is installed on a new profile and a new account is used

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1164]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 15.06.2018) installed.
- Have a new FxA account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sign in to Sync" button from the bottom part of the sidebar.
3. Enter the credentials from prerequisites and log in.
4. Observe if the "Welcome Note" is displayed in the list view.

**[Expected result]:**
- The "Welcome Note" is displayed.

**[Actual result]:**
- No notes are displayed.

**[Notes]:**
- This issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41471488-7bca7eba-70bc-11e8-9265-6d5451a1e86e.gif)

**Comment by vladikoff** [comment]
cc @natim

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 19.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
