### ISSUE TITLE
The text sent in a note with the "Add to Notes" option is not saved

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1170]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0dev custom built on 15.06.2018) installed.
- Have any website opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "New Note" button.
2. Select any text from the website from prerequisites.
3. Right click the selected text and select the "Add to Notes" option.
4. Go back to the list view and observe the recently created note.

**[Expected result]:**
- The note from step 2 is correctly saved and displayed.

**[Actual result]:**
- The note from step 2 is not saved.

**[Notes]:**
- The note is successfully saved if you will click on the note's content after the text was sent to notes.
- This issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41472720-f64067a6-70bf-11e8-95f5-8905c1fe13a0.gif)

**Comment by vladikoff** [comment]
@Natim do you have any time to take a look at this? 

I think we don't send a redux on content add in this case

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 21.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
