### ISSUE TITLE
The spelling error underline flickers in the other windows when writing in a window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#119]
[Notes]:
- The issue is also reproducible with more than two windows.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.3 -dev, built on 30/06/2017) installed.
- Have a few words with spelling errors in Firefox Notes.
- Have two windows opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type any character in Firefox Notes.
3. Observe the spelling error underline from the other window.

[Expected result]:
- The spelling error underline from the other window doesn't flicker.

[Actual result]:
- The spelling error underline from the other window flickers.

[Additional Notes]:
- Attached a screen recording of the issue:
![notes_flicker_wrongspellwords](https://user-images.githubusercontent.com/20083658/27739919-e4918a1e-5db8-11e7-9f8e-20cd6a8c0a44.gif)

**Comment by Natim** [comment]
We could try to apply a delta on the Quill arrea rather than resetting the whole content each time it changes. However I am not 100% sure it will fix the issue.

**Comment by n1k0** [comment]
A simple way to mitigate the effect is to buffer & debounce renders, eg. every 250ms.

**Comment by Natim** [comment]
Closing since we now have the debounce implemented.
