### ISSUE TITLE
Setup a .well-known endpoint for `assetlinks.json`

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#1192]
@rfk it seems that Android App Links require `/.well-known` to be on the root of the domain.

This probably means we cannot use the `github.io` redirect infrastructure 

![image](https://user-images.githubusercontent.com/128755/41804369-7846691e-7663-11e8-90d9-7b4a44043f18.png)

Results in:

![image](https://user-images.githubusercontent.com/128755/41804366-6682418a-7663-11e8-9a7e-149392738c7a.png)

Should we CNAME the github pages to some url? what should it be? I'm guessing Lockbox CNAME'd their redirect?

**Comment by rfk** [comment]
Lockbox have started using https://lockbox.firefox.com/ rather than the github URL, but I also don't think they've had to grapple with applinks yet because they're using a webview rather than the system browser.

**Comment by rfk** [comment]
So I guess we need to get a root domain for notes...some options we could consider:

* See about acquiring https://notes.firefox.com
* Host something ourselves under e.g. https://<clientid>.oauth.accounts.firefox.com.
* Buy a custom domain for this purpose.

I expect the first will be the best option if we can swing it, but I don't know what the policy is for hanging domains off of firefox.com.  Let's reach out to the lockbox folks for advice if you want to go that route.

**Comment by vladikoff** [comment]
https://notes.apps.firefox.com -> and use *.apps.firefox.com
