### ISSUE TITLE
[Android] A loading spinner is continuously displayed after the user is redirected to the Notes view if signing in with a newly created account

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#1204]
[Affected Platforms]:
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

[Prerequisites]:
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2516 custom build created on 25.06.2018) freshly installed.

[Steps to reproduce]:
1. Open the freshly installed Notes mobile application.
2. Click the "Sign in" button from the "Splash" screen.
3. Complete the input fields and press the "Create account" button.
4. Open the email client on a new tab and check for the confirmation email.
5. Tap the "Activate Now" button.
6. Tap the "Continue" button and observe what happens next.

[Expected result]:
- The Notes view is displayed and the user can start taking notes.

[Actual result]:
- A continuous loop is displayed after the user is redirected to the Notes view.

[Notes]:
- Also attached the logs: https://tinyurl.com/yb3vhogd
-This issue is also reproducible for users who already have an account, but without any notes in it.
- Attached a screen recording of the issue:

![huaweii_issue](https://user-images.githubusercontent.com/26000308/41851460-9c1c6580-7890-11e8-8ffc-151e905e408c.gif)

**Comment by vladikoff** [comment]
This is strange....

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (1.0android-c2791) installed from Google Play. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
