### ISSUE TITLE
[Android] The empty notes are wrongly saved

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1205]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v2516 custom build created on 25.06.2018) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "New Note" button.
3. Go back to the list view and observe the behavior.

**[Expected result]:**
- The note from step 2 is not saved.

**[Actual result]:**
- An empty note with the "Take a note..." title is saved.

**[Notes]:**
- The issue is also reproducible if you delete all the content from a note and then you go back to the list view.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/41851654-47881108-7891-11e8-8ad0-4cb116ffa7c7.gif)

**Comment by vladikoff** [comment]
@Softvision-MariusComan I'm thinking we should keep this, except rename 'Take a note' to 'Empty Note'. Evernote and Keep do this, thoughts?

**Comment by Softvision-MariusComan** [comment]
Hi Vlad, I think it would be a good idea to keep the empty notes, but, for the sake of consistency, we should do the same in the webextension.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (1.0.3 RC2) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
