### ISSUE TITLE
Signing in to sync from "Notes" is no longer possible after an invalid age is entered when creating an account

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#1207]
Also logged in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1470902
***

**[Affected versions]:**
- Firefox 60.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have "Notes" experiment enabled from https://testpilot.firefox.com/experiments/notes on a new clean profile.

**[Steps to reproduce]:**
1. Open Firefox and open the "Notes" sidebar
2. Click the "Sign in to Sync" button from the bottom left of the "Notes" sidebar.
3. Enter a valid e-mail adress and a valid password.
4. Enter an invalid age (under 13).
5. Click the "Create account" button and close the "accounts.firefox.com" tab.
6. Click the "three dot" button from the "Notes" sidebar and cancel the setup.
7. Click the "Sign in to Sync" button and observe the "accounts.firefox.com" page.

**[Expected result]:**
- The "Sign in" page is displayed.

**[Actual result]:**
- "Cannot create account" message is displayed.

**[Notes]:**
- The issue remains even if the browser is restarted.
- This issue is also reproducible with Screenshots Dev (installed from https://screenshots.dev.mozaws.net/homepage/install-test-local.html), when you attempt to create a new account with an invalid age.
- This issue is not reproducible if you create a new account with an invalid age using the Firefox' Sync service. 
- Attached a screen recording of the issue:

![sync sign in](https://user-images.githubusercontent.com/37875464/41858449-9ce090f6-78a2-11e8-8303-71b746469cf8.gif)

**Comment by vladikoff** [comment]
@stomlinson @rfk thoughts?

**Comment by vladikoff** [comment]
from meeting: we discussed this with @shane-tomlinson and others and you have to restart the browser to get back in. No other changes planned at this time.
