### ISSUE TITLE
The List View cannot be scrolled using the keyboard

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#1209]
**[Affected versions]:**
- Firefox 60.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the "Firefox Notes" [v4.2.0 RC2](https://github.com/mozilla/notes/pull/1193#issuecomment-399770993) add-on installed.
- Have enough notes so that the vertical scrollbar is displayed in the sidebar.
- Have the Notes sidebar opened in the List View.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the scrollbar.
2. Press the "Page Down" key and observe the behavior.

**[Expected result]:**
- The content is correctly scrolled.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is also reproducible using the latest Firefox Notes v4.2.0dev (custom built on 2018-06-26).
- Here is a screen recording of the issue: 
![notes - scroll using keyboard](https://user-images.githubusercontent.com/31244235/41901945-ea67e5e8-793a-11e8-9f7c-e577b7ed44c4.gif)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.3.0dev custom built on 10/19/2018) installed, on the latest Firefox Release (62.0.3) and Nightly (64.0a1). Verified on Windows 10 x64, Arch Linux and Mac 10.13.3.
