### ISSUE TITLE
The lists lose the format and order after copy/pasting it from a rich document

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/notes#1211]
[Affected versions]:
- Firefox 60.0.2 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest version of "Firefox Notes" add-on (4.2.0 RC2) installed.
- Have the Notes opened in note view.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Copy a list from a rich document.
3. Paste the copied list in the notes view and observe the list.

[Expected result]:
- The formatting options persists.

[Actual result]:
- The formatting options are not kept.

[Notes]:
- This issue is also reproducible if you copy a list from "LibreOffice".
- The text order is also changed.
- Other behaviors have been observed, sometimes the Bold, Strikethrough and Underlined format is also not kept (see also #630).
- Attached is a screen recording of the issue:

![notes issue](https://user-images.githubusercontent.com/40061643/41915882-7468b910-795f-11e8-8d17-07b54825c132.gif)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/notes/issues/447
