### ISSUE TITLE
Consider notes@mozilla.com vs hoverpad@mozilla.com

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#122]
hoverpad@mozilla.com is what is on the allowlist to avoid the Legacy label in the add-ons manager (from https://bugzilla.mozilla.org/show_bug.cgi?id=1354682).  I think being signed by the new Mozilla Extensions cert will also not show the Legacy label (@aswan can you confirm?)

This issue is to decide if we want to change the ID for this add-on in order to avoid the Legacy label or ignore that and just sign with the new cert when it is ready (sometime before 57 but after we launch this project).  

/cc @johngruen

**Comment by aswan** [comment]
confirmed that signing with "Mozilla Extensions" should avoid the legacy label in `about:addons`

**Comment by Natim** [comment]
Which one is the legacy one? hoverpad@mozilla.com or notes@mozilla.com?

Currently we are using the latter: https://github.com/mozilla/notes/blob/master/src/manifest.json#L9

**Comment by wresuolc** [comment]
Let's leave it at notes@m.c
