### ISSUE TITLE
[Android] Sign in does not work with Firefox as the default browser

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/notes#1250]
### [Description]:
If Chrome is disabled on my phone, the login does not complete.

### [Affected versions]:
1.0android-c2654
Sony Xperia XZ1 compact, Android 8.0.0

### [Prerequisites]:
Chrome disabled on the device, Nightly and Focus installed as browsers to choose

### [Steps to reproduce]:
1. Install and open Notes.
1. Click sign-in button.
1. FxA login page opens in Nightly (or a custom tab if enabled).
1. Finish the login.

### [Expected result]:
- The Notes app is signed to the account.

### [Actual result]:
- After the FxA login is successful, some "redirect" landing page appears (on mozilla.github.io), but it does not redirect/return back to the app.
- If you go back to the Notes app manually (or close the custom tab), a popup appears that the login has failed.

### [Additional Notes]:
- The solution for me was do enable Chrome, complete the sign in process there, and than disable it again.

**Comment by vladikoff** [comment]
@MikkCZ Thanks for the issue, it is dup of 

Ref: https://github.com/mozilla/notes/issues/1056

WORKAROUND is when "After the FxA login is successful, some "redirect" landing page appears" click the "..." menu in Firefox and click "Open in...." , select "Notes". 

Also ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1463620

**Comment by MikkCZ** [comment]
Oh, thank you @vladikoff . I have watched the screencast and can confirm this is a duplicate.

As for the rest of the Notes app after login, so far no issues found. :)
