### ISSUE TITLE
Pasting inserts extra spaces 

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#127]
<img width="381" alt="screen shot 2017-07-07 at 4 20 09 pm" src="https://user-images.githubusercontent.com/3323249/27975452-32c14ee6-6330-11e7-84a8-40f2e086b3a4.png">

becomes
```
notSupportedHeader = Your browser is not supported.

notSupportedHeader = Unfortunately this browser does not support the web technology that powers Firefox Send. You'll need to try another browser. We recommend Firefox!

// Note Firefox name should not be localized in button, but subhead should

downloadFirefoxButtonSub = Free Download

// note the sentence lower on this page is the same as uploadPageExplainer. Also the link on this page should be removed as Send wont work on this browser anyway
```

when copy pasted

**Comment by Natim** [comment]
Copy/paste from where?

If I copy/paste the content below to the pad, I don't have an issue.

```
downloadingPageHeader = Downloading {filename] ({size})
downloadingPageMessage = Please leave this tab open while we fetch your file and decrypt it.

errorPageHeader = Something went wrong!
errorPageMessage = There has been an error transferring your file and this connection has been closed. Your frind will have to try again and send you a new link.
errorPageLink = Send another file

expiredPageHeader = This link has expired or never existed in the first place!
// note the sentence lower on this page is the same as uploadPageExplainer, so we can recycle that key
```

**Comment by Natim** [comment]
Ok, I got it, copy pasting from the pad to the github textarea does add newlines for each paragraph:

```
downloadingPageHeader = Downloading {filename] ({size})

downloadingPageMessage = Please leave this tab open while we fetch your file and decrypt it.


errorPageHeader = Something went wrong!

errorPageMessage = There has been an error transferring your file and this connection has been closed. Your frind will have to try again and send you a new link.

errorPageLink = Send another file


expiredPageHeader = This link has expired or never existed in the first place!

// note the sentence lower on this page is the same as uploadPageExplainer, so we can recycle that key
```

**Comment by Natim** [comment]
My understanding is that it is the OS copy/paste behaviour to convert `<p>` as `\n\n` I have no idea if we can do something about it at our level.

**Comment by Natim** [comment]
That's the implemented behaviour when pasting HTML in a text area.
The only thing we could try to do is to use `<br>` instead of `<p>` when pressing enter. Refs https://github.com/quilljs/quill/issues/252

**Comment by Natim** [comment]
This could be a workable solution: https://github.com/quilljs/quill/issues/252#issuecomment-271930644

**Comment by Natim** [comment]
The idea is that if you copy something from a textarea in the pad and then copy it back in the textarea you should have the same presentation.

In order to do that we need to handle `<br/>` as well as `<p>` @ryanfeeley suggested that we handle `br` on `shift+p` which is what I have started in #131

We also need to make sure that a paste in the pad uses `<br/>` whenever necessary.

**Comment by Natim** [comment]
It appears that we can't reproduce the bug with Chrome and it might be a Firefox Bug.

**Comment by Natim** [comment]
This is the bug that implemented the behaviour: https://bugzilla.mozilla.org/show_bug.cgi?id=1119503

**Comment by Natim** [comment]
Ok I found out how to fix this: https://github.com/quilljs/quill/issues/861
