### ISSUE TITLE
[Android] You are wrongly notified that you are logged with a different account other than the actual one

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1270]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0.3 RC4) installed.
- The application's cache and data are cleared
- Have two valid Firefox accounts.

**[Steps to reproduce]:**
1. Open the Notes application and log in with the first account.
2. Log out from "Notes" and log in with the second account.
3. Observe the system notification message.

**[Expected result]:**
- The system notification informs you that you are logged with the second account.

**[Actual result]:**
- The system notification informs you that you are logged with the first account.

**[Notes]:**
- This issue is not reproducible with the "notes-1_0-qa-v2516.apk" build and I have encountered for the first time on the "notes-1_0-qa-v2593.apk" build. It seems that is related to the changes made on the "Log In" screen.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/42371278-a5847844-8117-11e8-8630-bc0db83d6791.gif)

**Comment by vladikoff** [comment]
Fixed in RC5, thanks @Softvision-MariusComan ! https://github.com/mozilla/notes/pull/1234#issuecomment-403036302

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (1.0.3RC5) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
