### ISSUE TITLE
App Crashed After Sign-In with 2FA

### ISSUE THREAD

**Issue by davismtl** [mozilla/notes#1274]
### [Description]:
I installed the app and then logged in to my account. After entering my 2FA code, the app crashed.

When I reopened the app, I was not signed in but it already had my email filled and my profile picture displayed.

When I entered my password again, it crashed after the redirect where it is loading with the Notes logo on the page. It did not ask me for TOTP code.

### [Affected versions]:
Not sure of number but according to Google Play, it is the version updated July 5th.

 I am on a Nexus 5 running Android 5.1.1

### [Steps to reproduce]:
- Install app
- Login
- Enter 2FA code (TOTP)

### [Expected result]:
Successful login

### [Actual result]:
Crashed

### [Additional Notes]:
I still can't sign-in. It crashes every time.

**Comment by davismtl** [comment]
I will update my OS to see if it changes anything.

**Comment by davismtl** [comment]
I updated to 6.0.1 and that seems to have resolved the crash. I will leave this bug open in case you intend to support Lollipop.

**Comment by vladikoff** [comment]
Thanks for letting me know!
