### ISSUE TITLE
Notes app crashed on login

### ISSUE THREAD

**Issue by jhb** [mozilla/notes#1288]
### [Description]:
When logging in the app crashes

### [Affected versions]:
1.0android-2791

### [Prerequisites]:
Galaxy Note 3, Android 5.0

### [Steps to reproduce]:
Hitl login, chrome opens, enter details, wait 5 secs, notes starts then crashes

### [Expected result]:
Notes starts and works 

### [Actual result]:
Crash

**Comment by GitHubCommunityProjects** [comment]
Same, on android 5. So confuse to sync.
