### ISSUE TITLE
Style Sync button with hover and active states

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#129]
Button should have visible states.

**Comment by ryanfeeley** [comment]
Getting pixel specifics, but should match Photon (see attached)
![hover](https://user-images.githubusercontent.com/68213/28025646-fb179a20-6561-11e7-8a0f-e5d7a7a5b4b4.gif)

**Comment by Natim** [comment]
Ok thanks @ryanfeeley

**Comment by cedricium** [comment]
Assuming [these are the correct colors](http://design.firefox.com/photon/visual/color.html#grey), I can work on this issue.

**Comment by vladikoff** [comment]
cc @ryanfeeley ^.


That would be great @cedricium !!

**Comment by ryanfeeley** [comment]
@cedricium Seems to be using alphas. https://mozilla.invisionapp.com/share/PYC5LJJXG#/229940647_Toolbars

**Comment by cedricium** [comment]
@ryanfeeley thanks for the resource, I'll see what I can do!

**Comment by Natim** [comment]
@ryanfeeley can you just give us the reference for the E color we should use? I don't think we can access the theme value from the add-on.

**Comment by cedricium** [comment]
I found theme here: https://mozilla.invisionapp.com/share/PYC5LJJXG#/screens/229940646

Any reference to a color in the rest of that presentation just uses an alpha based off of those A-G colors it appears.

**Comment by Natim** [comment]
Yes ok great!!
