### ISSUE TITLE
Can't sign in on Android and get confusing message

### ISSUE THREAD

**Issue by nsrosenqvist** [mozilla/notes#1290]
### [Description]:
I downloaded the app for Android and attempted to sign in with my Firefox account. After signing in a plain unstyled html page shows up saying: "To continue open this page using the Notes application. Use the browser menu button and select 'Open in Notes'."

This makes no sense to me. I'm already in the Notes app and in a gecko web view opened by the app. If I press the close button I get a toast message saying authentication error. 

### [Affected versions]:
1.0android-c2791

### [Steps to reproduce]:
Install app, press sign-in button, authenticate, boom, there it is

### [Expected result]:
Should be logged in

### [Actual result]:
Not logged in and confused by the instructions in the message

### [Additional Notes]:
Worth noting is that I haven't installed the extension in my browser. Is that a requirement?

**Comment by paulstodghill** [comment]
I have the same problem. I was able to authenticate in the Notes app on a phone (Android 7.0), but failed as above on a tablet (Android 5.0).

**Comment by SoftVision-CiprianMuresan** [comment]
This could be related to #1056. 

@nsrosenqvist, is Firefox the only browser you have installed or is it set as your default browser?

@paulstodghill, Android 5.0 is not a supported Android version. Notes works on Android 6.0 and above.

**Comment by nsrosenqvist** [comment]
I have both Chrome and Firefox installed but Firefox is set as my default browser
