### ISSUE TITLE
Synced time is shown in 12-hour format

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/notes#1292]
### [Description]:
In the mobile app in the sidebar, the synced time at the bottom is shown in 12-hour AM/PM format. But for Czech the correct format is 24-hour.

### [Affected versions]:
1.0android-c2748

**Comment by gbcox** [comment]
Good point... I noticed that also.  The app should pickup the time format settings from the system settings.  I'm using it on Android Pie and it reports 12-hr. time when my system is set to display time in the 24 hr format.

**Comment by MikkCZ** [comment]
Closing (as won't fix) given the app development seems stopped anyway.
