### ISSUE TITLE
copy/paste should keep the newline.

### ISSUE THREAD

**Issue by tianzhuqiao** [mozilla/notes#1312]
copy/paste should keep newlines (Firefox 61.0.1):
1) paste multiple line text to notes
2) copy the text from notes and paste to somewhere, the newlines are lost.

**Comment by Softvision-MariusComan** [comment]
Hi Tianzhuqiao, thanks for reporting this issue, however this behavior is already reported in #677. Considering this I will close this issue as a duplicate.
