### ISSUE TITLE
[Enhancement] Mouse pointer should reflect that action is not allowed when trying to drop content into sidebar

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#132]
[Notes]:
- Since the drag and drop feature was disabled, the cursor should also reflect that this action is not allowed when the user tries to drop content into Firefox Notes.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes dev v1.5

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.5 -dev, built on 10/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a webpage and drag any content over the Firefox Notes sidebar.
3. Observe the mouse pointer icon.

[Expected result]:
- The mouse pointer changes when Notes sidebar is hovered to reflect that the drag and drop action is not allowed.

[Actual result]:
- The mouse pointer changes into a "drop" icon instead, even if the action is not performed when released.

[Additional Notes]:
- Attached a screen recording of the issue:
![mousepoiner_issue](https://user-images.githubusercontent.com/20083658/28027422-af70e398-65a1-11e7-8128-e1d0f3402491.gif)

**Comment by Natim** [comment]
This can be handled in Javascript by binding the drag start and drag stop events.

**Comment by SoftVision-EmilPasca** [comment]
The issue is still reproducible on the latest Firefox Notes version (1.5.1dev built on 07/19/2017), re-tested on Mac OS 10.12 and Windows 10 x64.

**Comment by Natim** [comment]
After discussion on the Quill.js front, we discovered that it also happens to be a bug with textarea themselves.

A bug has been open here: https://bugzilla.mozilla.org/show_bug.cgi?id=1381759

**Comment by Natim** [comment]
Closing since drag and drop is now available.
