### ISSUE TITLE
[Android] The application crashes if the internet connection is lost while logging in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1320]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 7/27/2018 installed.
- You are not logged into "Firefox Notes".
- Have a valid Firefox Account.

**[Steps to reproduce]:**
1. Open the Notes application and tap the "Sign In" button.
2. Enter the email from prerequisites and tap the "Continue" button. 
3. Enter the password from the account from prerequisites and tap the "Sign In" button.
4. Turn off the internet connection while the app is still in the loading screen.
5. Observe the behavior.

**[Expected result]:**
- An error message is displayed.

**[Actual result]:**
- The application crashes.

**[Notes]:**
- You can find the logs [here](https://goo.gl/g2PU1T).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43319784-b8af5220-91ae-11e8-8ccf-f6e128f45c86.gif)

**Comment by vladikoff** [comment]
cc @carolng

**Comment by vladikoff** [comment]
cc @carolkng

**Comment by vladikoff** [comment]
Thanks so much for the attached logs!

```
07-27 14:57:57.725: E/AndroidRuntime(28912): FATAL EXCEPTION: ForkJoinPool.commonPool-worker-3
07-27 14:57:57.725: E/AndroidRuntime(28912): Process: org.mozilla.testpilot.notes, PID: 28912
07-27 14:57:57.725: E/AndroidRuntime(28912): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter raw
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at mozilla.components.service.fxa.OAuthInfo.<init>(Unknown Source:2)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlow$1.invoke(FirefoxAccount.kt:62)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at mozilla.components.service.fxa.FirefoxAccount$completeOAuthFlow$1.invoke(FirefoxAccount.kt:7)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at mozilla.components.service.fxa.RustObject$Companion$safeAsync$1.doResume(RustObject.kt:60)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:162)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:26)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1152)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1990)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1938)
07-27 14:57:57.725: E/AndroidRuntime(28912): 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
07-27 14:57:57.770: E/SPPClientService(18752): [b] SharedConstants.WHAT_PUSH_NETWORK_NOT_AVAILABLE
```

**Comment by carolkng** [comment]
I've added a stopgap to fix the issue in Notes in e606dad, but it should be reverted once https://github.com/mozilla-mobile/android-components/pull/523 is merged, and the new fxa android-component release is tagged.

**Comment by Softvision-MariusComan** [comment]
This issue is still reproducible with the latest version of "Firefox Notes" application (app-release-signed custom built on 7/31/2018) on Pixel (Android 8.0.0), Samsung S8 (Android 8.0.0) and Huawei P8 Lite (Android 6.0)
Considering this I am reopening this issue.

**Comment by vladikoff** [comment]
@carolkng i think this is the crash log:

![](http://v14d.com/i/5b6071e77f6e8.png)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (app-release-signed custom built on 8/01/2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).

**Comment by vladikoff** [comment]
thanks for checking again 👍
