### ISSUE TITLE
[Android] You are wrongly returned to the email screen if the screen orientation is changed while you are in the password screen

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1322]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 7/27/2018 installed.
- You are not logged into "Firefox Notes".
- Have a valid Firefox Account.
- Have the "Auto Rotate" system feature enabled.

**[Steps to reproduce]:**
1. Open the Notes application and tap the "Sign In" button.
2. Enter the email from prerequisites and tap the "Continue" button. 
3. Turn the phone horizontally and observe the behavior.

**[Expected result]:**
- The screen orientation is turned to landscape.

**[Actual result]:**
- The screen orientation is turned to landscape, but the page is reloaded and you are returned to the email screen.

**[Notes]:**
- This issue is also reproducible if the screen orientation is changed from landscape to portrait.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43327040-06bf25e4-91c3-11e8-8602-f3514a3612c0.gif)

**Comment by vladikoff** [comment]
cc @carolkng
