### ISSUE TITLE
[Android] The app crashes if multiple "Sign In" windows are opened and you try to go back to the home screen

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1337]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 8/1/2018 installed.
- You are not logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the Notes application and tap the "Sign In" button.
2. Tap the system's "Back" button and quickly tap the "Sign In" button again. 
3. Tap the system's "Back" button after the e-mail field is displayed.
4. Tap the "Back" button again and observe the behavior.

**[Expected result]:**
- You are returned to the "Login" screen.

**[Actual result]:**
- The app crashes.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43528957-d33dc042-95b2-11e8-9767-93675a3ed539.gif)

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/notes/commit/689a4fe84ff9ed94954387c2019b7f953e7517db
