### ISSUE TITLE
No hint about progress during sign in when system animation is turned off

### ISSUE THREAD

**Issue by sivaraam** [mozilla/notes#1342]
### [Description]:
There is not hint of progress during "Sign in" when the animation has been disabled in Android

### [Affected versions]:
Android 5.1.1 on a Samsung Galaxy J1 ace

### [Prerequisites]:
1. Enable "Developer options" in the device and disable animation by setting the values of the menus "Window animation scale", "Transition animation scale", "Animator duration scale" to "Animation off" in the "Drawing" section.
1. You're not logged into the Notes app

### [Steps to reproduce]:
1. Open the app
1. Tap on "Sign in"

### [Expected result]:
There's a hint of progress like a fallback animation for device in which animation has been disabled.
Example screencast: https://drive.google.com/open?id=1oRNXSofdElgC33UZtPahiguXAxqCs0Hd

### [Actual result]:
There's no hint of progress.

### [Screenshots]:
Screenshot showing lack of progress:
![screenshot_2018-08-05-11-54-51](https://user-images.githubusercontent.com/12448084/43683803-ed304b2c-98b0-11e8-8754-f7dfd038ebc0.png)

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @sivaraam, thanks for the report. However "Notes" doesn't support Android 5 at this time. We do have a fallback image for this case on Android versions >5 if animations are set to OFF:

![notes_login_static_image](https://user-images.githubusercontent.com/18304511/43705083-4a932c44-996a-11e8-93f2-6fef9624e2df.png)

![screenshot_20180806-111307](https://user-images.githubusercontent.com/18304511/43704954-ebdbf41a-9969-11e8-8bc0-0c5b166e63fc.png)
