### ISSUE TITLE
[Android] The "Reconnect to Sync" message is wrongly displayed if the internet connection is lost during any sync action

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1346]
**[Notes]:**
- This issue could be easily encounterable depending on the user's location while using mobile data (signal loss) or on the quality of the mobile data signal (less than 3G). 

**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 8.0.0 (Samsung S8)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 8/6/2018 installed.
- Have at least five notes in the app.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Swipe down the screen and quickly disable the internet connection. 
3. Observe the behavior.

**[Expected result]:**
- The application enters in the "Offline" mode.

**[Actual result]:**
- The "Reconnect to Sync" message is displayed.

**[Additional Notes]:**
- This issue is reproducible regardless how the sync action was made.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43723976-a061031c-99a1-11e8-8b41-410a715a32c3.gif)

**Comment by Ilphrin** [comment]
Hi! Tried on a local build, and could not reproduce the issue, it may have been already resolved ^^
