### ISSUE TITLE
[Android] The "Reconnect to Sync" message wrongly disappears after a note is deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1347]
**[Affected Platforms]:**
- Android 8.0.0 (Samsung S8)
- Android 8.0.0 (Google Pixel)
- Android 6.0 (Huawei P8 Lite)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (app-release-signed) custom built on 8/7/2018 installed.
- Have at least a note in the app.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Navigate to https://accounts.firefox.com/reset_password and change your "Firefox Account" password.
3. Go to the "Notes" app and delete any note.
4. Observe the behavior.

**[Expected result]:**
- The "Undo" banner is displayed over the "Reconnect to Sync" one and after few seconds the "Undo" banner disappears leaving the "Reconnect to Sync" one displayed.

**[Actual result]:**
- The "Reconnect to Sync" banner disappears and the "Undo" banner is not displayed. Also, the "Reconnect to Sync" message from the drawer is replaced by the "Last synced[hour]" one.

**[Notes]:**
- After any sync action, the "Reconnect to Sync" message is correctly redisplayed.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/43766627-a07a6e34-9a3b-11e8-9ace-0ed22dbf265b.gif)

**Comment by gna582** [comment]
For me its not just the button that is wrongly shown. I am actually disconnected. This is really annoying as I can't be sure to keep my notes synced defeating the whole point of the application for me.
