### ISSUE TITLE
Reconect To sync

### ISSUE THREAD

**Issue by inextor** [mozilla/notes#1350]
### [Description]:
Notes do not sync
i also disable/enable,remove the extension, restart the browser and same behavior

### [Affected versions]:
Firefox developer Edition 62.0b15 (64-bit)

### [Prerequisites]:

Try to sync notes

### [Steps to reproduce]:
Cancel Setup
Sing in to sync
-it opens a new window and enter credentials then it logins and the window is closed automatically
-Show a message "Reconnect to Sync"

### [Expected result]:
Sync notes

### [Actual result]:
Do not sync and show message Reconect to sync in the status bar

### [Additional Notes]:
On broser Console shows:
```

[Show/hide message details.] win.gBrowser is undefined CustomizableWidgets.jsm:364
onCreated
resource:///modules/CustomizableWidgets.jsm:364:11
wrapWidgetEventHandler/aWidget[aEventName]
resource:///modules/CustomizableUI.jsm:2516:16
buildWidget
resource:///modules/CustomizableUI.jsm:1521:9
getWidgetNode
resource:///modules/CustomizableUI.jsm:986:16
buildArea
resource:///modules/CustomizableUI.jsm:816:32
registerToolbarNode
resource:///modules/CustomizableUI.jsm:764:9
registerToolbarNode
resource:///modules/CustomizableUI.jsm:3160:5
toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:39:11
next self-hosted:570:9 toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:25:13
next self-hosted:570:9 toolbar_XBL_Constructor
chrome://browser/content/customizableui/toolbar.xml:25:13
update
chrome://browser/content/tabbrowser.js:4914:19
onBeforeInitialXULLayout
chrome://browser/content/browser.js:1218:5
<anonymous>
chrome://browser/content/browser.js:1146:5
Invalid chrome URI: /
Invalid chrome URI: /
IndexedDB UnknownErr: ActorsParent.cpp:600
DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code." sync.js:319:7
syncKinto/<
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/sync.js:319:7
IndexedDB UnknownErr: ActorsParent.cpp:600
Unhandled promise rejection null kinto-http.js:596:2166
onUnhandled/</r<
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:596:2166
perform
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:596:1452
onUnhandled/<
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:596:2016
[45]</module.exports
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:133:82
<anonymous>
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:312:601
run
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:312:420
listener
moz-extension://0d3e89cb-8642-4ca6-8d95-a6296b71659b/vendor/kinto-http.js:312:447
IndexedDB UnknownErr: ActorsParent.cpp:600
<unavailable> activity-stream.bundle.js:5586:11
init/<
resource://activity-stream/data/content/activity-stream.bundle.js:5586:11
step
resource://activity-stream/data/content/activity-stream.bundle.js:5240:183
step/<
resource://activity-stream/data/content/activity-stream.bundle.js:5240:402
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
The resource at “https://ssl.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More] notes
Loading failed for the <script> with source “https://ssl.google-analytics.com/analytics.js”. notes:1
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Invalid chrome URI: /
The resource at “https://www.google-analytics.com/r/collect” was blocked because tracking protection is enabled.[Learn More] issues
The resource at “https://www.google-analytics.com/collect” was blocked because tracking protection is enabled.[Learn More] issues
Invalid chrome URI: /
Invalid chrome URI: / 



```

**Comment by vladikoff** [comment]
```
IndexedDB UnknownErr: ActorsParent.cpp:600
DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code." sync.js:319:7
```

Could be an IndexedDB issue in your profile

**Comment by inextor** [comment]
vladikoff, What can I do to Sync my notes?

**Comment by vladikoff** [comment]
@inextor could you check this page: https://firefox-storage-test.glitch.me/

See what it reports to you? Did you reuse the same Firefox profile between different versions of Firefox (Stable , Dev Edition, Nightly) ?

**Comment by inextor** [comment]
I been using the same version version until now when it was unable to sync, then 
i tried everything, tried with other versions of firefox it fails also, reset all what i know it can be reset, remove all the extensions, 


https://firefox-storage-test.glitch.me/ Says

Overview:
Storage is broken. This is your first visit or all storage was automatically cleared.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Bad: Totally Broken. (fullyBroken)
IndexedDB
    Bad: Totally Broken. (fullyBroken)
Cache API
    Bad: Totally Broken. (fullyBroken)

Debug Info:

storage.estimate() threw: The expression cannot be converted to return the specified type.
Failed to create "persistent" IDB.
Failed to create "transient" IDB.

{
  "v": 1,
  "curVersion": 62,
  "prevVersion": 0,
  "ls": {},
  "qm": {
    "lastWorkedIn": 0
  },
  "idb": {
    "persistentCreatedIn": 0,
    "persistentLastOpenedIn": 0,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 0,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 0
  }
}

**Comment by inextor** [comment]
I Fixed, uninstall firefox
intall firefox
Reset Firefox
https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings
Install notes again
And it syncs now, all my notes are gone
On my other device sync notes
and now sync notes on the problematic device, the old notes they appeared now.
