### ISSUE TITLE
Syncing from a third party Notes client

### ISSUE THREAD

**Issue by dapgo** [mozilla/notes#1351]
### [Description]:
The sync feature among browser/server/app offered by Mozilla is great, but at least for the android app, it is too basic.  However , at the moment there are 'better' opensource Note-taking apps.

So, in my opinion it would be great to open the service to other  apps or just forking an existing opensource app (such as [Omni-notes](https://github.com/federicoiosue/Omni-Notes)) and making it sync with the Mozilla service.

**Comment by dapgo** [comment]
In the past I said that android client was too basic. 
However, after changing of phone in the new phone it just doesn't work (Error FXA-KEYCHAIN_FAILED), so I  think strongly that the service open to other notes apps or at least fork a more powerful and supported app.

**Comment by heyakyra** [comment]
I requested this in Gnome-notes: https://gitlab.gnome.org/GNOME/gnome-notes/issues/120#note_776456

With a link to https://github.com/mozilla/notes/issues/1430#issuecomment-457678649
