### ISSUE TITLE
Open Notes on tab

### ISSUE THREAD

**Issue by biboc** [mozilla/notes#1356]
### [Description]:
I like to open Notes on sidebar to write comment about a website but sidebar can't be maximize.
I think we should also be able to open Notes on a full windows tab so it is easier to take Notes and this become an Notes application which is sync with Firefox account. 

(If there is a better place to suggest feature, I can move this issue)

### [Affected versions]:
-

### [Prerequisites]:
-

### [Steps to reproduce]:
-

### [Expected result]:
-

### [Actual result]:
-

### [Additional Notes]:
-

**Comment by KhushilMistry** [comment]
Hey, I want to work on this enhancement. Can I?

**Comment by biboc** [comment]
I don't know the process but I think you can start yes

**Comment by grahamperrin** [comment]
+100 to this enhancement. 

[Provide a button to open notes in a Tab · Issue #470 · mozilla/notes](https://github.com/mozilla/notes/issues/470)

**Comment by grahamperrin** [comment]
[Add menu item to open notes in a tab rather than in the sidebar. by Natim · Pull Request #559 …](https://github.com/mozilla/notes/pull/559)

**Comment by dapgo** [comment]
Maybe without the current fully dependence on sidebar, the extension would be compatible with the basic webextension support of Firefox 52.
