### ISSUE TITLE
Android - Error FXA-KEYCHAIN_FAILED  - 1.2android-c3011

### ISSUE THREAD

**Issue by dapgo** [mozilla/notes#1359]
### [Description]:
trying lo log, produces an error "FXA-KEYCHAIN_FAILED"

### [Affected versions]:
1.1android-c2942

### [Steps to reproduce]:

Update from Play to new version, 

Clicking on "Sign in", enter email address, 

An Email is received- Subject: "Confirm new sign-in to Notes"   
   (device IP address: X.X.X.X) hh:mm:ss (CEST) Monday, 27 Aug 2018   
   Click on email "Confirm Sign in" button

Enter password for account 

A new email subject "New sign-in to Notes" with following content is received:
  Chrome Mobile WebView on Android 6.0.1
  location,country (estimated)
  IP address: X.X.X.X    
 hh:mm:ss (CEST) Monday, 27 Aug 2018Chrome Mobile WebView on Android 6.0.1

### [Expected result]:
Load notes 

### [Actual result]:
error "FXA-KEYCHAIN_FAILED"

### [Additional Notes]:

During the 1st attempt  the device IP was different, and email was received 
Email "Confirm new sign-in to Notes"   (device IP address: Y.Y.Y.Y) 15:21:17 (CEST) Monday, 27 Aug 2018   was received and confirmed

There is not "New sign-in to Notes" email for this IP,

**Comment by vladikoff** [comment]
@dapgo Hey ! We saw this error in testing when [Android's Secure Store](https://developer.android.com/training/articles/keystore) would fail, Restarting the phone would fix this, let me know how it goes.

**Comment by dapgo** [comment]
After restarting the phone the failure is still.
Also from "Accounts.firefox, Devices & apps" I disconnected the websessions and revoke the notes app, and after try it failed again.

BTW, I have a Samsung with Android 6.0.1

**Comment by dapgo** [comment]
I tried the new version 1.2android-c3011 with not much success. In fact above failure is still the same in the same device.
After login on app and verify access through email, the notes app start on a loop of displaying a void white screen and blue and so on.
After closing the app, and login,  error "FXA-KEYCHAIN_FAILED" is displayed. :(

**Comment by dapgo** [comment]
Now it is working fine but I dunno what was the cause of failure.
I haven't tried notes for months but recently i decided to uninstall it and install again and notes were synced.  
As the Notes app is the same version, I suppose that changes were done at Mozilla server
