### ISSUE TITLE
[Windows] Formatting option tooltips are wrongly displayed on the latest Nightly

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#136]
[Affected versions]:
- Nightly 56.0a1, Build ID: 20170711030203

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on (version 1.5-dev) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover the formatting option buttons("Bold","Italic","Ordered list", etc.) from "Notes" sidebar.
3. Observe the displayed tooltips.

[Expected result]:
- The tooltips are displayed correctly below the corresponding buttons.

[Actual result]:
- The tooltips appear very far to the right of the button.

[Regression]:
With Nightly 56.0a1, Build ID: 20170710030203, the issue is not reproducible.
Last good revision: 392ed89ec2730a48d10b1cec741e86a242d28aa3
First bad revision: a625a2e9b3333a8e76982ea65f077cfded6ac224
Pushlog: https://goo.gl/N1DhXR

[Notes]:
- Attached a screen recording of the issue:
![tooltips_nightly](https://user-images.githubusercontent.com/20083658/28115821-153770ac-670f-11e7-9542-194535d8af37.gif)

**Comment by vladikoff** [comment]
Wow! Firefox bug?

**Comment by Natim** [comment]
Yes :)

**Comment by Natim** [comment]
@SoftVision-EmilPasca Can you file this bug in bugzilla?

**Comment by SoftVision-EmilPasca** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1380294

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Nightly 57.0a1, Build ID:  20170807113452.
