### ISSUE TITLE
Reduce startup states

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#137]
This slowed-down clip of switching to Notes shows about six different states. Is there a way that we can reduce this to one?
[slowmo.mp4.zip](https://github.com/mozilla/notes/files/1143208/slowmo.mp4.zip)

**Comment by cedricium** [comment]
Not sure if this affects the slow start up, but maybe waiting until the entire DOM loads (using the `DOMContentLoaded` event) before applying the toolbar button tooltips may help.

**Comment by ryanfeeley** [comment]
@vladikoff Notes is still slow for me to open in Nightly. Why is this closed?

**Comment by vladikoff** [comment]
It takes time to open but there is one state now @ryanfeeley
