### ISSUE TITLE
[Android] On Android 5 devices, at login, the "Notes" application is wrongly sent to the background and you are not logged in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1379]
**[Affected Platforms]:**
- Android 5.1 (LG G4)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.2.0) installed.
- Have valid "Notes" account credentials.

**[Steps to reproduce]:**
1. Open the "Notes" application and tap the "Sign In" button.
2. Enter the email from prerequisites and tap the "Continue" button.
3. Enter the password from prerequisites and tap the "Sign In" button.
4. Observe the behavior.

**[Expected result]:**
- You are successfully logged in and the list view is displayed.

**[Actual result]:**
- You are not logged in and the application is sent to the background.

**[Notes]:**
- This issue is also reproducible if you create a new account instead using an existing one.
- This issue is not reproducible on Android 6 or 8 devices.
- You can find the logs [here](https://goo.gl/gBUH8v).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/48491244-c7eb6580-e82f-11e8-9f29-37113288cfde.gif)

**Comment by Redpillbug** [comment]
this issue also happens on galaxy s5 model android 5.0. sign in, sents verification email, check it, go back in, loads, and crashes. The app show to enter firefox account email again.Hope this gets fixed.

**Comment by kelvinchin12070811** [comment]
have the same issue here with Samsung Galaxy S4 with android 5.0.1
