### ISSUE TITLE
[Android] Continuing to write a string after placing it in bold wrongly duplicates it

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/notes#1380]
**[Affected Platforms]:**
- Android 8.0.0 (Google Pixel)
- Android 7.1.1 (Nokia 6)

**[Prerequisites]:**
- The notes-1_2_0_signed.apk is installed.
- Logged in with a valid "Firefox" account.

**[Steps to reproduce]:**
1. Open the Notes application and add a new note.
2. Enter a string of text with "**" before and after the it.
3. Without pressing space type another character and observe the behavior.

**[Expected result]:**
- A single character is displayed after the string.

**[Actual result]:**
- The bolded string is duplicated.

**[Notes]:**
- This issue is also reproducible with underscores.
- This issue is also reproducible with italics.
- Deleting the duplicated string and a character from the bolded one cause the bolded string to be replaced with the string before it.
- Attached a screen recording of the issue:
![notes_duplicate](https://user-images.githubusercontent.com/40393891/48556847-b799c000-e8ed-11e8-995a-13fe46136575.gif)

**Comment by Ilphrin** [comment]
Hi! Coulc not reproduce this issue on version 1.3.0, Android 9 (Lineage OS)
