### ISSUE TITLE
The heading style format is wrongly kept when copying a text into Notes

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#139]
[Notes]
- The value "14" is displayed in the formatting bar for each selected heading styled text, although its size is different.
- After changing the text size for the heading styled text to another value, when changing back to "14", the text is displayed with the heading style size and not with corresponding "14" size.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes dev v1.5

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.5 -dev) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to a webpage that has different heading styled text (eg: https://goo.gl/bxz3cf).
3. Copy the heading styled text into Notes.
4. Observe the text.

[Expected result]:
- The text is copied without the heading style format.

[Actual result]:
- The text is copied with the heading style format.

[Additional Notes]:
- Attached a screen recording of the issue:
![heading_text_issue](https://user-images.githubusercontent.com/20083658/28170565-7a17b916-67ee-11e7-9710-493357190528.gif)

**Comment by vladikoff** [comment]
I think this is due https://github.com/mozilla/notes/blob/master/src/sidebar/panel.js#L7 

We can remove it

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Firefox Notes version (1.5.1dev built on 07/18/2017).
