### ISSUE TITLE
The text caret cannot be moved inside of a note using the click action

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1390]
**[Affected versions]:**
- Firefox 65.0a1 Build ID - 20181203093109

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.3.0dev) custom built on 12/03/2018 installed.
- Have any website opened.
- Have at least a note in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open the note from prerequisites.
3. Click on any word from the note and observe the behavior.

**[Expected result]:**
- The text caret is moved in the area where the click action was performed.

**[Actual result]:**
- Nothing happens.

**[Regression window]:**
Considering the fact that this issue is not reproducible on latest Firefox Release and Beta builds, using the Mozregression tool I've managed to find the following regression window:

Last good revision: f17b7ba6d0aa737d4f69a0fc3206da8c539225e5
First bad revision: 8e88421b280c2afda62f4ba704ce29701c30549f
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=f17b7ba6d0aa737d4f69a0fc3206da8c539225e5&tochange=8e88421b280c2afda62f4ba704ce29701c30549f

From the pushlog it seems that the Bug 1506547 has caused this regression.

**[Notes]:**
- This issue is reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible with the latest Firefox Release build.
- The text caret can be moved only left and right using the "Arrow" keys".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/49383030-7d6b5380-f720-11e8-9914-0b4d22864b61.gif)

**Comment by HRussellZFAC023** [comment]
You can still move the caret using the right mouse click

**Comment by Standard8** [comment]
#1431 should fix this.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.1) installed, on the latest Firefox Nightly (66.0a1 Build ID - 20190109092644). Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
