### ISSUE TITLE
Firefox Notes have disappeared

### ISSUE THREAD

**Issue by leem2602** [mozilla/notes#1393]
### [Description]:
Sorry, never used github before, just need some help. Using Firefox 64 Windows 7.
All my notes are gone, the sidebar is now empty. I had hundreds of notes, not backed up, because I didn't know how to back them up.
Restarted Firefox, then restarted the computer but the notes have not reappeared. Please help

**Comment by vladikoff** [comment]
@leem2602 have you tried on a fresh profile or in safe mode?

**Comment by leem2602** [comment]
Thank you very much for responding.
No luck in safe mode, the notes sidebar is not available at all.
Looking up in Mozillazine about how to use a fresh profile in FF, sorry I'm not very experienced with this.  Firefox's help pages are amazingly out of date, lots of references to Win XP.  
Will get back to you re fresh profile.  Have looked in the extensions for the existing profile, but 'Notes' is not listed there. Does it go by another name, or doesn't it count as an 'extension/addon'?

**Comment by parassharma1612** [comment]
@leem2602 Have you tried building the project again?
