### ISSUE TITLE
Unable to select text in new or existing note

### ISSUE THREAD

**Issue by JKoehler11** [mozilla/notes#1394]
### [Description]:
Unable to select text in Notes using the mouse

### [Affected versions]:
Firefox 65.0b4 64-bit Windows 10

### [Prerequisites]:
Install Notes through Test Pilot

### [Steps to reproduce]:
Open Notes
Select an existing note
Attempt to select text with the mouse

### [Expected result]:
Text is selected

### [Actual result]:
No text is selected

### [Additional Notes]:
I've noticed this happening for all of the 65 beta releases. This is working in 64.

**Comment by HRussellZFAC023** [comment]
As a workaround, use the right mouse click to change the position of the cursor

**Comment by kbtzr** [comment]
For me up/down keys don't work as well, I can insert a new line with enter but up/down arrows just move the cursor to the start/end of the current line.

I'm also on 65 so the source of the issue could be the same.

**Comment by WebMechanic** [comment]
same here with `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0`
No arrow keys, no **regular** mouse usage.
Just installed Testpilot and Notes on Nightly. For me Notes is currently unusable.
No editing/typing issues with the Android app though.

**Comment by vladikoff** [comment]
We have a bugzilla bug on file for this in https://bugzilla.mozilla.org/show_bug.cgi?id=1511391 

Sorry about this, hopefully this doesn't spill into release

**Comment by vladikoff** [comment]
cc @mixedpuppy

**Comment by vladikoff** [comment]
This is now fixed in the 4.1.2 release, sorry about the delay!
