### ISSUE TITLE
[Question] ways to integrate with notes.

### ISSUE THREAD

**Issue by ngortheone** [mozilla/notes#1430]
If I want to write my own CLI tool that would show me notes stored in FF Notes - where is the good place to start? Is there an API description somewhere?

**Comment by heyakyra** [comment]
Would love an API to be able to integrate with Gnome Notes: https://gitlab.gnome.org/GNOME/gnome-notes/issues/120

**Comment by ngortheone** [comment]
@heyakyra 
I did some research and found out that there are couple of moving parts here:

1) Auth and Login - done with Firefox Accoutns (FxA)
* https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction
* https://github.com/mozilla/fxa
* Only JS Client available and maintained at the moment: https://github.com/mozilla/fxa-js-client


2) Kinto Server - the data storage for notes iteslf
https://www.kinto-storage.org/
Mozilla's public endpoint is here:
`export const KINTO_SERVER_URL = 'https://testpilot.settings.services.mozilla.com/v1';`

So if I got everything right one needs to implement login flow using the client and then talk to kinto server to store/retrieve notes
