### ISSUE TITLE
A "Bad Request" error is displayed after the "Sign in to Sync" button is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1440]
**[Affected versions]:**
- Firefox 64.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" add-on (4.3.0) installed from the "TxP" website.
- Have valid "FxA" credentials.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sign in to Sync" button from the bottom part of the "Notes" sidebar.
3. Observe the behavior.

**[Expected result]:**
- The "Log In" window is opened.

**[Actual result]:**
- A "Bad Request" error is displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51393773-32c36080-1b41-11e9-871f-b5e99b91f1da.gif)

**Comment by vladikoff** [comment]
Thanks, a server change probably broke this

**Comment by vladikoff** [comment]
Yea, this is a server only change, doesn't have to do anything with 4.3.0 release. Server is being rolled back soon. Good catch!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.3.2) installed, on the latest Firefox Release and Nightly. Verified on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.16.6 x64.
