### ISSUE TITLE
There is an old version (1.3) of the "Firefox Notes" add-on available in AMO

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#1446]
**[Affected versions]:**
- Firefox 64.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the https://addons.mozilla.org" page and perform a search using the "Notes" string.
3. Observe the search results.

**[Expected result]:**
- Only the "Notes by Firefox" add-on (4.3.2 version) is displayed.

**[Actual result]:**
- The "Notes" add-on (1.3 version) is also displayed.

**[Notes]:**
- Also, the older version of the "Notes" add-on is listed in the first position of the search results.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/51476841-5e3b8a80-1d8f-11e9-8804-d1805b2fce52.gif)

**Comment by grahamperrin** [comment]
Given https://github.com/mozilla/addons-linter/issues/2158  (don't use the word _Firefox_) and #1376, maybe amend the AMO page for old extension ID `{e88004b6-ab81-49dd-b716-4ad1e7aa4a7b}` to present a name that will be distinct from _Notes_. Maybe: 

> **Notes (legacy)**

(It's not _exactly_ a legacy add-on, but I should not expect end users to split hairs in this case.)

----

More generally, is there any reason to keep the AMO page? 

For posterity: 

- http://web.archive.org/web/20180930191418/https://addons.mozilla.org/en-US/android/addon/fxa-notes/
- http://web.archive.org/web/20181002014608/https://addons.mozilla.org/en-US/firefox/addon/fxa-notes/
- http://web.archive.org/web/20190127034342/https://addons.mozilla.org/fr/android/addon/fxa-notes/
- http://web.archive.org/web/20190127034349/https://addons.mozilla.org/fr/firefox/addon/fxa-notes/

**Comment by vladikoff** [comment]
I think it's gone!
