### ISSUE TITLE
[Android] Allow Google Analytics to be disabled

### ISSUE THREAD

**Issue by lnicola** [mozilla/notes#1450]
### [Description]:

The Firefox extension supposedly follows the DNT setting, but there's no way to disable GA in the Android version.

**Comment by Natim** [comment]
To be honest, I would even get rid of Google Analytics now that it is not a Test Pilot experiment anymore, there are no reason to use it anymore.

**Comment by mirh** [comment]
Test Pilot not existing anymore doesn't mean this isn't beta software anymore (or that dev info aren't needed, still). 
And DNT (_advertisement_, right?) is not the same of analytics. 

Anyway, this should be made possible, if not any at least for #1316

**Comment by vladikoff** [comment]
Removed GA in WebExtension in https://github.com/mozilla/notes/pull/1455

**Comment by vladikoff** [comment]
GA was removed in Android via https://github.com/mozilla/notes/pull/1471
