### ISSUE TITLE
The slow reaction when continuously changing the cursor position.

### ISSUE THREAD

**Issue by xuxinhang** [mozilla/notes#1454]
### [Description]:

The editing textarea reacts really slowly when editing a note with many characters or with the  complicatedly formatted contents. The reaction-delay may be more obvious when change the cursor position, no matter clicking mouses or pressing arrow keys of keyboards. 

### [Affected versions]:
Here is the version 4.3.3

### [Prerequisites]:
Just one note with many complicatedly-formatted contents. 

For example,
![default](https://user-images.githubusercontent.com/22539142/53181199-15971b80-3632-11e9-9f00-a9d101cd2844.PNG)

### [Steps to reproduce]:

1. Open a note with many complicatedly-formatted contents. 
2. Press down and keep one arrow key in your keyboard. (Of course, that is just one way to make this plugin runs slowly.)

### [Expected result]:

The smoothly reaction would be good.

### [Actual result]:

The low FPS.

### [Additional Notes]:

The debugger devtool said the min fps had reached 0.75, and there were numerous "callback" items.

**Comment by zslayton** [comment]
I've been experiencing this too. The longer the note gets, the less stable the UI feels. At some point (possibly related to blur/focus on the note?) input stops working altogether. If/when that occurs, I can fix it by backing out to the Notes list and then selecting the note I wish to edit again. While this allows me to enter more input, it does not fix the lag/chop.
