### ISSUE TITLE
[Feature Request] Add tag(s) to notes

### ISSUE THREAD

**Issue by carbontracking** [mozilla/notes#1457]
### [Description]:

Allow the user to add tag(s) to a note. This would require a separate area in the "New Note" screen, for example see the highlighted area in the image below.
![image](https://user-images.githubusercontent.com/44807/54981531-c6ce0000-4fa8-11e9-8b18-b0fc69aca881.png)
This would need to be linked to the feature request #1453 "Search on Notes list". Searching on Tags could be specified by prepending a # symbol to the search term in the search field, e.g searching for #cooking would return all notes with the tag "cooking"

Each note can have multiple tags.

An alternative to a separate tag field when editing a note would be to implement tags as words with a # in the title(first line) e.g. with a title such as "Really excellent cookies #recipes #highcalories" the tags recipes and highcalories would be added to the note.

### [Affected versions]:

All

### [Prerequisites]:

feature request #1453 "Search on Notes list"

### [Expected result]:

A filtered display of notes that only contained the searched for tag(s)

**Comment by tradewatcher** [comment]
I think there's not enough space for such a feature. I like the idea but wouldn't it be a better option to set titles like #1467 and set your Tag in title? Search bar to filter title only..

Also groups can handle this better or not? Make a group for "recipes" and a sub group for "highcalories" like requested in #1465

**Comment by carbontracking** [comment]
@tradewatcher 
I think that putting a tag preceded by # in the title would be fine. 
It would give a chance to see if the tagging feature is heavily used or not.

That still leaves the prerequisite feature request #1453 "Search on Notes list" to be implemented beforehand however.

As for groups, I see a disadvantage insofar as this enforces a strict tree hierarchy. The advantages of tags is the freedom to reuse tags across different topics,

e.g. you could have an irish recipe note tagged as #recipes #Ireland and an irish sport note tagged as #sport #Ireland without needing to duplicate a group or sub-group #Ireland

**Comment by tradewatcher** [comment]
It could be interesting to link between notes with such tags. If title start with # its a tag.
If I write an already used "#tag" its a hyperlink and open the specific note.

Yes you are right it doesnt replace the option to use a tree structure. This is a personal preference.
