### ISSUE TITLE
[Feature Request] Shortcuts

### ISSUE THREAD

**Issue by nov3o** [mozilla/notes#1479]
### Shortucts
I want to have shortcuts that I can do things faster.
Actually, it will be convenient to focus on notes when I open sidebar.

I would like to create notes when I press "N" button on my keyboard and leave note editing with "Esc" button
And it will be good with text editor shortcuts like you did in Firefox's style editor: vim and Sublime Text shortcuts. It will be nice to write something and easily move current line or just cut it. But it optional. The most important is common app shortcuts

**Comment by tradewatcher** [comment]
You can go to about:addons, open Addon shortcuts and set Firefox Notes to your preferred keybinding.

**Comment by nov3o** [comment]
> You can go to about:addons, open Addon shortcuts and set Firefox Notes to your preferred keybinding.

Where is Addon shortcuts? The only preference I can change is theme

**Comment by Najrim** [comment]
Found it! 

Preferences > Extensions > Settings Cogwheel > Manage Extension Shortcuts
