### ISSUE TITLE
Deleted notes show up on other devices

### ISSUE THREAD

**Issue by leo-unglaub** [mozilla/notes#1484]
Hi,
i am using Notes on 3 different devices. My desktop (Firefox Developer Edition on Windows), my Laptop with Firefox on OpenBSD and my Android Phone with the Notes app. Changes get synced very well between the devices, but every time i delete a note it continues to show up on the other devices.

I am on Notes version 4.3.5. 
Is there anything more you need in order to debug this?

Thanks and greetings
Leo

**Comment by aashish108** [comment]
I get this same issue also.

**Comment by TyDraniu** [comment]
#metoo.
