### ISSUE TITLE
Prevent Notes from logging users out

### ISSUE THREAD

**Issue by pwd-github** [mozilla/notes#1490]
### [Description]:
Notes periodically logs users out, despite a Firefox account existing on the device.

### [Affected versions]:
All

### [Steps to reproduce]:
Leave Notes for a week or so

### [Expected result]:
When a user reloads Notes, users should remain logged in.

### [Actual result]:
Users are logged out

### [Additional Notes]:
I believe the latest application services should fix this.

**Comment by mirh** [comment]
The funny thing is that on the [account settings](https://accounts.firefox.com/settings/clients) you are instead still "confirmed" logged in.

**Comment by pwd-github** [comment]
Maybe, though the problem is the most frustrating on Android.

**Comment by mirh** [comment]
Somebody, anyone?
It's getting frustrating to the point that I can't even go more than ***3*** days without re-logging.

**Comment by DavidBE-UK** [comment]
Usually I only want to use Notes once a week or so, and EVERY TIME I have to log back in to my Firefox account in Notes on the Android phone .... and it's not just going through entering name and  password, but I then have to wait for an email to click the confirm in, and on top of that I always actually get TWO identical emails, both of which have to be dealt with in my email client either on the phone or on the laptop.

This is so frustrating I now just use Google Keep or Microsoft Sticky Notes, in both of which I just enter the text in a new Sticky Note in the PC App or Keep note in the Firefox Keep sidebar, and the text just appears immediately on the phone without all the re-logging in.

Originally I thought I would like to use Mozilla's Notes rather then the Microsoft or Google apps, but the logging back into my account each time with (duplicated) confirming emails has driven me right away.

**Comment by sebastianreloaded** [comment]
as much as i love the app, it doesnt make sense to use it.
apart from always having to relogin, the login is also kind of not working correctly. i always have to sign in two times.
guess i'll try onenote/stickynotes or google keep...

**Comment by mirh** [comment]
Aside of those, I could also mention other FOSS ones: [Omni Notes](https://github.com/federicoiosue/Omni-Notes), [Simple Notes](https://github.com/SimpleMobileTools/Simple-Notes), [Standard Notes](https://github.com/standardnotes/mobile) and [Joplin](https://github.com/laurent22/joplin/)

**Comment by bapch** [comment]
Still not assigned ? This is a real show stopper.

**Comment by sebastianreloaded** [comment]
yeah, i switched to joplin with a microsoft onedrive backend.
