### ISSUE TITLE
Firefox notes are not opening on some windows

### ISSUE THREAD

**Issue by jeremiawuzza** [mozilla/notes#1491]
### [Description]:
Firefox notes only on some windows

### [Affected versions]:
Quantum 67.0 64 bit

### [Prerequisites]:
Multiple browser windows open 

### [Expected result]:
I have been using Firefox Notes for the last two months and in fact I had six pages of useful notes. Now I can't access them. The icon is still on my tab bar but clicking it has no effect. I could reinstall but I worry I will lose my notes Is there anything I can do? 

### [Additional Notes]:
The problem just got stranger - only some of my browser windows have notes. The others refuse to load them
Also Is there a way to save them to a local drive?

**Comment by fatichar** [comment]
Workaround: Use keyboard shortcut: ALT+SHIFT+W
