### ISSUE TITLE
Firefox Notes on Linux shows wrong timezone

### ISSUE THREAD

**Issue by berenddeschouwer** [mozilla/notes#1499]
### [Description]:

Notes sidebar on Firefox on Linux shows a synchronised time at the bottom.  This time is in the wrong timezone.  It's displaying UTC time and not local time.

### [Affected versions]:

Firefox on Linux, FF 68, Notes 4.3.5
Android shows local time

### [Expected result]:

Synchronised time shows in local timezone.

**Comment by eikenb** [comment]
Setting "privacy.resistFingerprinting" in about:config to "true" will do this.
