### ISSUE TITLE
Notes for Android is unavailable, "early access program" full

### ISSUE THREAD

**Issue by skierpage** [mozilla/notes#1501]
### [Description]:
I love the idea of this but when I go to install it on my Pixel 2 running latest Android, Google's Play Store reports 
> The early access program is currently full. Space may open up later.

:-(

### [Affected versions]:
? all?

### [Prerequisites]:
none

### [Steps to reproduce]:
Try to install Notes by Firefox on Android via Google's Play Store.

### [Expected result]:
Either let me install it, or inform people it's **temporarily available for Android** wherever you mention the Android app, e.g. https://addons.mozilla.org/en-US/firefox/addon/notes-by-firefox/

### [Actual result]:
Couldn't install for Android.

### [Additional Notes]:
Is the Android app available through other means such as the FDroid store?

**Comment by vladikoff** [comment]
Woah, I haven't heard of this!

**Comment by M-ZubairAhmed** [comment]
Can relate, its still unavailable on android

**Comment by DanAtkinson** [comment]
As the Play Store link isn't in this issue, this is it:
https://play.google.com/store/apps/details?id=org.mozilla.testpilot.notes

![image](https://user-images.githubusercontent.com/23440/65432244-5fcfbd80-de0a-11e9-892b-c68fc95f38c2.png)

**Comment by Podesta** [comment]
Problem still present. Can't install it from Play Store, and app also not present on F-Droid.

**Comment by vladikoff** [comment]
@johngruen any ideas ?

**Comment by myns23** [comment]
any update?

**Comment by Podesta** [comment]
I was able to install it this week.

**Comment by daveloyall** [comment]
Seems to be full again.

**Comment by myns23** [comment]
download apk from here:
https://www.apkmirror.com/apk/mozilla/notes-by-firefox-a-secure-notepad-app/
installed and update from Google play.

**Comment by immanuelfodor** [comment]
"The early access program is currently full. Space may open up later" :sob:

**Comment by jmmacak** [comment]
Checking in, Notes is still unavailable!

**Comment by aquaspy** [comment]
@jmmacak  @immanuelfodor @troskop @myns23 
You guys can use Aurora web store to download it. Works very well!

https://f-droid.org/en/packages/com.aurora.store/

And idk if this is the place for it, but I have some feedback about notes.
1-I really love the simplicity
2-I miss dark mode on android and desktop too
3-Are the notes encrypted locally desktop version (firefox addon)? If my computer is stolen, can the thief access the notes even without knowing my OS password? (I use linux)
