### ISSUE TITLE
Importing Notes from a Back-up

### ISSUE THREAD

**Issue by KateHikes** [mozilla/notes#1516]
### [Description]:
Hello, I recently backed-up my storage folder from Roaming, and now I want to carry over the notes I had there to my new storage.

### [Affected versions]:
Uh, latest?

### [Prerequisites]:
Notes

### [Steps to reproduce]:
Back-up storage folder, delete storage folder, new storage folder is made, attempt to port over notes from old storage folder

### [Expected result]:
Bada bing bada boom old notes on new storage folder

### [Actual result]:
Notes screen is just blank and dead inside

### [Additional Notes]:
Thank you for your time!!!

**Comment by kpils** [comment]
I think that the notes are encrypted and will usually have to be transferred between two logged in Firefox clients.
