### ISSUE TITLE
Notes Based on current website 

### ISSUE THREAD

**Issue by Goddard** [mozilla/notes#1531]
When I first got this extension I thought that this would be how it worked.  It looks like it is just notes and it doesn't changed based on the website I visit.

Not really that useful honestly.

Should get permission to view current website and have maybe a config option that allows only loading notes based on current website.

Would be really useful and helpful to organize notes for my development.  Otherwise no point in using this notes feature over a text editor to save a note honestly.

Is this a planned feature, or is it already working and I am totally missing it some how?

Thanks, Ryein

**Comment by akissz** [comment]
I think its a great idea. But also would be good to have a set of 3 or 5 notes on the top of the list that display on top of the ones for the current website. Like 3 or 5 stared notes can be kept on top of the list.
