### ISSUE TITLE
Sync is not working?

### ISSUE THREAD

**Issue by dan-leo** [mozilla/notes#1536]
I can't seem to sync Notes between two different Firefox browsers signed into the same account. Each browser is running on a Linux and Windows device, respectively.

**Comment by faizalr25** [comment]
Is it ever working before?

**Comment by zephyrer** [comment]
In the release note of version 4.3.7 (the last), there is a comment "* Added a note about turning off the Sync servers".

**Comment by faizalr25** [comment]
Thank you. 

On 5 Oct 2021, at 2:39 PM, Efisio ***@***.***> wrote:

﻿
In the release note of version 4.3.7 (the last), there is a comment "* Added a note about turning off the Sync servers".

**Comment by iaxat** [comment]
Can notes sync be turned on?

**Comment by benzhaidang** [comment]
i have the same issue, the sidebar note is very useful. but i can not make them sync.

**Comment by iaxat** [comment]
Yeah, it would be great if it can be synced.
It is upsetting they cancelled the notes' app. At a time when journal apps are such a boom, why would you cancel that. It should have been an amazing app for web and phones, could have turned out to be a competitor of Google Docs.
