### ISSUE TITLE
Recover notes from "Old Firefox Data"?

### ISSUE THREAD

**Issue by D-Groenewegen** [mozilla/notes#1537]
### [Description]:
Firefox suggested to me in a message at the top of the page that I hadn't refreshed the browser in a while so I hit refresh as suggested. Unfortunately, what was meant by refresh is a reset that removed the countless notes I had accumulated over the last six months or so. Quite some valuable stuff in there. Firefox did create a backup of some of my data in a folder called "Old Firefox Data". 

Is it possible for me, and users like me, to recover the lost notes?

**Comment by Nad43** [comment]
Hi! Did you find a solution for this problem?
I'm having the same issue right now.

**Comment by D-Groenewegen** [comment]
I'm afraid I haven't been able to come up with a solution. I'm assuming, in my case at least, that the data are irretrievably lost. I did come across some suggestions on the web, but they didn't work for me.

**Comment by Newman5** [comment]
I'm having the same issue.  Looking for a solution
