### ISSUE TITLE
Placeholder missing when boilerplate text deleted

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#154]
When the notepad is blank, much like a GitHub comment that says "Leave a comment", the light placeholder "Take a note…" should appear.

**Comment by vladikoff** [comment]
@ryanfeeley run `npm run build` and try again please

**Comment by Natim** [comment]
This might be related to the Quill 1.3.0 update.

**Comment by Natim** [comment]
Refs https://github.com/quilljs/quill/issues/1594

**Comment by vladikoff** [comment]
:+1:
