### ISSUE TITLE
Notes UI elements are wrongly displayed if installed using the Windows Registry Editor

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#156]
[Affected versions]:
- Firefox 56.0a1
- Firefox Notes dev v1.5.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have the latest Firefox Notes add-on xpi (version 1.5.1 -dev, built on 07/18/2017) unpacked in a local folder.
- The pref "xpinstall.signatures.required" is set to "false".
- Have a string variable with the value name "notes@mozilla.com" and value data "C:\Users\username\Downloads\firefox_notes-1.5.1dev" (path to the add-on folder) under the "HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Firefox\Extensions" registry folder. Details [here](https://developer.mozilla.org/en-US/Add-ons/Adding_extensions_using_the_Windows_registry).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" and click on the "Extensions" tab.
3. Enable "Firefox Notes".
4. Click on the "Show sidebars" toolbar button.
5. Click on the "Sidebar switcher" button and switch to "Notes".
6. Observe the "Notes" UI elements in the sidebar.
7. Resize the sidebar and observe elements behavior.

[Expected result]:
6. The "Notes" UI elements are correctly displayed.
7. The "Notes" UI elements doesn't suffer any changes.

[Actual result]:
6. The "Notes" UI elements are wrongly displayed.
7. The "Notes" UI elements are wrongly resized.

[Notes]:
- After enabling Firefox Notes addon, the attached error message is displayed in the browser console:
![error_registry_notes](https://user-images.githubusercontent.com/20083658/28328196-5fa41184-6bee-11e7-9f4f-91638167eeed.jpg)
- Attached a screen recording of the issue:
![notes_registry_issue](https://user-images.githubusercontent.com/20083658/28328198-652fdaac-6bee-11e7-94cc-fb206468de8c.gif)

**Comment by Natim** [comment]
It looks like you didn't build the addon with the last locale messages.

**Comment by Natim** [comment]
We look at it with @SoftVision-EmilPasca and we realize it was the case for other webextensions too.
@SoftVision-EmilPasca will open a bug in Bugzilla about it.

**Comment by SoftVision-EmilPasca** [comment]
Refs: https://bugzilla.mozilla.org/show_bug.cgi?id=1382180

**Comment by vladikoff** [comment]
Wow!

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1385057

**Comment by vladikoff** [comment]
We have a FF bug for this, but please do not install via Registry editor, super edge case :)
