### ISSUE TITLE
Formatting buttons are not highlighted with blue when formatting from the keyboard a part of an word 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/notes#167]
**[Affected versions]:**
- Firefox 56.0a1, Build ID: 20170724030204
- Firefox latest release v54.0.1
- Firefox Notes dev v1.6.2

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Firefox Notes add-on version (1.6.2 -dev, built on 07/25/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open "Notes" in the sidebar.
3. Write a longer word.
4. Select a part of that word and format the text with Bold, Italic and Strikethrough from keyboard.

**[Expected result]:**
- After the text was formatted, the text format button for the specific formatting is highlighted with blue.

**[Actual result]:**
- Formatting buttons are not highlighted with blue when formatting parts of an word.

**[Notes]:**
- Attached a screen recording of the issue:
![text formatting buttons](https://user-images.githubusercontent.com/9248513/28562155-dcfbcede-7129-11e7-8f1f-272bd3dddb70.gif)

**Comment by wresuolc** [comment]
"just add focus to these"  --jgruen

**Comment by Natim** [comment]
Refs https://github.com/quilljs/quill/issues/1553

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest "Firefox Notes" add-on version (2.2.0dev) installed
