### ISSUE TITLE
Enable drag&drop of content in the sidebar.

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/notes#168]
**[Affected versions]:**
- Firefox 56.0a1, Build ID: 20170724030204
- Firefox latest release v54.0.1
- Firefox Notes dev v1.6.2

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Firefox Notes add-on version (1.6.2 -dev, built on 07/25/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open "Notes" in the sidebar.
3. Open a wiki page (e.g. https://en.wikipedia.org/wiki/Firefox)
4. Select some text and drag it into Notes.

**[Expected result]:**
- The text is pasted into Notes.

**[Actual result]:**
- Nothing happens. Cannot paste text from websites with drag&drop.

**[Notes]:**
- Attached a screen recording of the issue:

![drag drop](https://user-images.githubusercontent.com/9248513/28562873-a20f3e2a-712c-11e7-9f0c-58d7953d3256.gif)

**Comment by wresuolc** [comment]
This is disabled to avoid people dragging links and pictures in.   If we re-enable lets make sure we do it safely.

There is a metrics event to watch for drag-drop to see how many people try it.

**Comment by jeremyredhead** [comment]
@wresuolc Out of curiosity, what are dangers of letting things be dragged in?

**Comment by vladikoff** [comment]
Text drag and drop was enabled 👍
