### ISSUE TITLE
Text size value cannot be selected if it was previously selected

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/notes#171]
**[Affected versions]:**
- Firefox 56.0a1, Build ID: 20170724030204
- Firefox latest release v54.0.1
- Firefox Notes dev v1.6.2

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Firefox Notes add-on version (1.6.2 -dev, built on 07/25/2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open "Notes" in the sidebar.
3. Click on the text size selector button.
4. Select a text value.
5. Click again on the text size selector button and select the same text value as the one from step 4.

**[Expected result]:**
- Text size value is selected on click regardless if it was previously selected or not.

**[Actual result]:**
- If a text size value was previously selected it cannot be selected again.

**[Notes]:**
- Attached a screen recording of the issue:

![select value](https://user-images.githubusercontent.com/9248513/28584415-53298c7c-7175-11e7-884c-7edd8d3a85b0.gif)

**Comment by Natim** [comment]
We should file issues related to QuillJS in https://github.com/quilljs/quill

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest "Firefox Notes" add-on version (2.2.0dev) installed
