### ISSUE TITLE
Consider a keyboard shortcut to open the notes sidebar?

### ISSUE THREAD

**Issue by imyxh** [mozilla/notes#176]
I can open history with ctrl-h and bookmarks with ctrl-b. It would be great if I could open notes with alt-n or something.

**Comment by gowri-sankar** [comment]
I instantaneously searched for a shortcut after installing, that is so necessary

**Comment by vladikoff** [comment]
> It would be great if I could open notes with alt-n or something.

@imyxh @gowri-sankar Thanks for the suggestion, we are trying to figure out what combination of keys makes sense for this. `Alt-N` might be a bit confusing, ideas welcome!

**Comment by ryanfeeley** [comment]
Is there a systematic way for us to pick a decent keyboard shortcut?

Can we query the "namespace" some way to know what is used and what is free?

Choosing one seems so arbitrary, and popular add-ons also make use of keyboard shortcuts.

It's the main reason the Synced Tabs sidebar doesn't have a keyboard shortcut. We couldn't find a decent method for choosing a good one.

**Comment by ryanfeeley** [comment]
Is there a systematic way for us to pick a decent keyboard shortcut?

Is there a way to query the "namespace" to know what is used and what is free?

Choosing one seems so arbitrary, and popular add-ons also make use of keyboard shortcuts.

It's the main reason the Synced Tabs sidebar doesn't have a keyboard shortcut. We couldn't find a decent method for choosing a good one.

Would be great to have one with N in it, because it's closed to B and H for the bookmarks and history sidebars.

**Comment by vladikoff** [comment]
@ryanfeeley you commented twice

@ryanfeeley you commented twice

**Comment by ryanfeeley** [comment]
@vladikoff Odd, draft showed in Firefox after restart so I just added a bit and submitted it. I guess it had submitted.

**Comment by johngruen** [comment]
@Natim will open a bugzilla issue to figure out if there is a process for picking something here.

**Comment by Natim** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1389124

**Comment by johngruen** [comment]
Lot of requests, this is in the backlog, we'll triage it out.

**Comment by johngruen** [comment]
I can also reach out to @andymckay about webext shortcuts

**Comment by andymckay** [comment]
What @ryanfeeley said its really hard to pick one. A ui for choosing one would be nice, that's https://bugzilla.mozilla.org/show_bug.cgi?id=1303384.

**Comment by vladikoff** [comment]
# Alt+Shift+W

(W) - for Write

**Comment by Natim** [comment]
Released in 1.7.0 https://github.com/mozilla/notes/issues/188
