### ISSUE TITLE
Notes dropdown - UI should be better.

### ISSUE THREAD

**Issue by MadhuriQA** [mozilla/notes#178]
![notes_ui](https://user-images.githubusercontent.com/26246696/28859527-63519440-7775-11e7-83ab-2fa36ca64555.png)

Drop down should be fit enough to look good according to UI measures. It can be shift a bit downward as usually a drop down appears.

**Comment by pdehaan** [comment]
Possibly related to #116

**Comment by johngruen** [comment]
We have no control over this. This is a Firefox UI issue.

**Comment by Natim** [comment]
@MadhuriQA as a follow up could you create a bug in bugzilla and paste the link here so that we can follow the bug being Fixed in Firefox?

**Comment by MadhuriQA** [comment]
Sure @Natim and thanks to consider it as a follow up. 

The bugzilla link for above issue is - https://bugzilla.mozilla.org/show_bug.cgi?id=1390855

**Comment by MadhuriQA** [comment]
Seems to be fixed now with latest Nightly build id : 20170816100153 on Win 10 X 64. Still suggestions are welcome. :) Please refer the latest screenshot attached.
![notes_ui_latest](https://user-images.githubusercontent.com/26246696/29405754-7b0a184e-835c-11e7-82bd-ad1fdf6094ff.png)

**Comment by Natim** [comment]
Thank @MadhuriQA for the update 👍
