### ISSUE TITLE
links should be underlined and clickable.

### ISSUE THREAD

**Issue by MadhuriQA** [mozilla/notes#179]
![2017-08-02_11h27_59](https://user-images.githubusercontent.com/26246696/28859566-b0be20cc-7775-11e7-9a85-a18bfbf6a3db.png)

- Links added in the notes should have color blue as links appears with an underline on hover. 
- It should also be clickable from the notes panel itself so that a link can be opened from the same.

**Comment by johngruen** [comment]
We want to do this! adding links in the backlog, for further triage.

**Comment by MadhuriQA** [comment]
@johngruen so, we will see this feature soon...am i right ?? :-)

should I create it in bugzilla as well just to have a track or follow up ?

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by Natim** [comment]
@ajomadlabs you can give it a try unless @cedricium is already working on it.

**Comment by cedricium** [comment]
@Natim this should be closed, fixed via #302 (0804612)
