### ISSUE TITLE
Add Dark Theme to Notes

### ISSUE THREAD

**Issue by tradesmanhelix** [mozilla/notes#181]
Many users prefer dark themes for their browsers as it's easier on the eyes than light themes when using your computer for long hours.

Could we add a dark theme option to Firefox Notes?

**Comment by imyxh** [comment]
Hmm, I would like it, but I think it would also feel out of place while the History and Bookmarks pages remain light-themed.

**Comment by tradesmanhelix** [comment]
Could be something super simple like:

![dark-notes](https://user-images.githubusercontent.com/2421172/28890459-2afa26a0-7795-11e7-9833-5419457a7e2b.png)

**Comment by vladikoff** [comment]
@ryanfeeley Thoughts on Dark Themes 🕶 ?

**Comment by ryanfeeley** [comment]
@vladikoff Love it! Why is "Sync Your Notes" wrapping?

**Comment by vladikoff** [comment]
@ryanfeeley issue https://github.com/mozilla/notes/issues/153

**Comment by imyxh** [comment]
Here's a mockup to make it look like the compact dark theme. Like I said, might look out of place though.

![image](https://user-images.githubusercontent.com/12703838/28899186-8867fbec-779e-11e7-83e0-602f2ba47dff.png)

**Comment by Natim** [comment]
Very nice @imyxh

**Comment by johngruen** [comment]
@natim can we get a review for this one...seems like an easy win

**Comment by Natim** [comment]
Sure

**Comment by Natim** [comment]
Released in 1.7.0 https://github.com/mozilla/notes/issues/188
