### ISSUE TITLE
Unable to install, get "Installing..." for over ten minutes

### ISSUE THREAD

**Issue by bjherbison** [mozilla/notes#182]
I tried to install from https://testpilot.firefox.com/experiments/notes and after getting the "Test Pilot is installed" pop-up the page says "Installing..." for as long as I have waited. Refreshing the page reverts back to the "Install Test Pilot and Enable Notes" button. (Test Pilot was previously installed)

**Comment by vladikoff** [comment]
@bjherbison Are you on Linux + Nighly? Could be https://github.com/mozilla/testpilot/issues/2689

**Comment by bjherbison** [comment]
That's it. I'll follow that issue and try again when it gets fixed. Thanks for the pointer.

**Comment by vladikoff** [comment]
@bjherbison Sounds good! Sorry about that :(

**Comment by SoftVision-PaulOiegas** [comment]
@bjherbison people that encountered this issue too, mentioned some workarounds untill the issue gets fixed:
1. Turned off sandboxing, everything works. Installing experiments and turning sandboxing back on again works as well.
2. Install Test Pilot and desired experiments on the Firefox release version and after switch back to Nightly on the same profile. This will bypass the Nightly issue.
