### ISSUE TITLE
Enable markdown markup for formatting the notes

### ISSUE THREAD

**Issue by normcyr** [mozilla/notes#183]
It's cool to have user-friendly icons to format the notes. But it would be even cooler to enable markdown markup to format the notes.

**Comment by Natim** [comment]
@vladikoff and I talked about that a little bit for a couple of days but we were having a hard time finding out how this should play in terms of UX.

Do you have an idea in mind of how it would looks like from a UX perspective?

**Comment by vladikoff** [comment]
@normcyr do you want 2 tabs, one editor and one rendered view? or side-by-side? 

I don't see how a side-by-side view would fit into the sidebar

**Comment by marcelo140** [comment]
The two tabs seems great as long as we `tab` (or other keyboard shortcut) to easily jump between them. As @vladikoff pointed, the side by side view would be way too narrow in a sidebar.

**Comment by normcyr** [comment]
@vladikoff I had the "two-tabs" option in mind. This would work for both people used to reading plain markdown and people willing to see a rendered notes.

Alternatively, having a way to highlight the syntax directly similarly to the way it is done in certain text editior (_eg_ atom) would avoid the dual tabs.

**Comment by bbenoit** [comment]
I second @normcyr's suggestion. I don't know the underlying format used for _Notes_, but displaying Markdown formatted text with in-line formatting (more or less like some editor -- e.g. http://cdn.appstorm.net/mac.appstorm.net/files/2011/08/macchiatoapp-620x609.png or http://www.redchar.net/fp-content/images/rscite-60/markdown-scite.png) would be great.

Either two tabs or a button at the far right of the _Notes_' toolbar could allow to switch from one view to the other. Maybe the tool buttons might be used in both cases to apply formatting.

Markdown formatted text can the be easily copied/pasted without losing the formatting.

**Comment by johngruen** [comment]
We all like this idea, it's in the backlog which we will triage next

**Comment by StefanoCecere** [comment]
i guess you already discussed about having the original note test saved as CommonMark (the standard Markdown) format, right? it would be a really nice choice for Mozilla and a killer feature for Firefox itself to have an integrated markdown note editor!

**Comment by StefanoCecere** [comment]
maybe this plugin for CKeditor could be a solution? https://ckeditor.com/cke4/addon/markdown

**Comment by Natim** [comment]
It is already available in the last version see https://medium.com/firefox-test-pilot/testpilot-notes-v1-9-0-b166c6cd7353
