### ISSUE TITLE
Text getting dropped with Notes open in multiple windows

### ISSUE THREAD

**Issue by 6a68** [mozilla/notes#185]
Congrats on the experiment launch! 🚀

If I have the Notes sidebar open in multiple windows at once, it seems to eagerly send over each character as I'm typing, but will sometimes miss the last few.

Possibly a separate bug, but I've also had cases where my typed text in window 1 was incompletely copied to the sidebar in window 2, then a moment later, window 1 was updated to delete the last few characters I'd typed.

**Comment by vladikoff** [comment]
cc @Natim

**Comment by Natim** [comment]
> Possibly a separate bug, but I've also had cases where my typed text in window 1 was incompletely copied to the sidebar in window 2, then a moment later, window 1 was updated to delete the last few characters I'd typed.

Interesting, I guess we need to make sure that the update on the updated sidebar doesn't trigger itself an text-change event if the change wasn't made from the keyboard.

**Comment by johngruen** [comment]
@Natim any chance we could resolve this, seems to be problematic for user trust

**Comment by Natim** [comment]
Released in 1.7.0 https://github.com/mozilla/notes/issues/188 @6a68 can you verify that it fixes your issue?

**Comment by 6a68** [comment]
@Natim Hey! Sorry, got behind on bugmail. Yes, the bug seems fixed for me 🎉

**Comment by Natim** [comment]
Thanks 👍
