### ISSUE TITLE
Delete-Word deletes new line

### ISSUE THREAD

**Issue by marcelo140** [mozilla/notes#186]
Hi, when there's only one word left in the line and I use the delete-word command (ctrl-backspace), the new-line is also deleted, sending me to the previous line. Don't know if it's intended but it gets quite annoying.

**Comment by johngruen** [comment]
hmmm, i didn't even know this existed :( @SoftVision-EmilPasca

**Comment by SoftVision-EmilPasca** [comment]
I have managed to reproduce this issue.

**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest Firefox Notes add-on version (1.6.3 -dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click inside the "Notes" sidebar.
3. Press the "Enter" key for two times and write any word.
4. Press "Ctrl-Backspace" and observe the behavior.

**[Expected result]:**
- The word is successfully erased and the caret is displayed in the same line.

**[Actual result]:**
- The word and the last line are erased and the caret is displayed in the first line.

**[Notes]:**
- Attached a screenshot of the issue:
![notes_caret_displayed](https://user-images.githubusercontent.com/20083658/29360895-afc52972-828d-11e7-9f6d-c60d877507e2.gif)

**Comment by vladikoff** [comment]
Thank you @SoftVision-EmilPasca !

**Comment by Natim** [comment]
Can you file this bug upstream?

**Comment by SoftVision-EmilPasca** [comment]
Sure, but I have also tested this on [QuilJS playground](https://quilljs.com/playground/) and is not reproducible there. Are we sure this is a QuillJS issue?
See the attached a screen recording:
![notes_quill](https://user-images.githubusercontent.com/20083658/31389197-fb5e343e-add8-11e7-8925-510f479fabe8.gif)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
