### ISSUE TITLE
[Feature Request] Add the ability to link to a certain tab

### ISSUE THREAD

**Issue by dannyhajj** [mozilla/notes#193]
Personally, I rarely close tabs, so I always end up with 1k+ tabs opened. I switch between them by searching for them in the awesome bar.
In addition to #179, it would be pretty awesome if, inside our notes, we are able to link/pin certain text to a specific tab in Firefox.
It could either be by drag dropping the tab inside our notes, or an option similar to "Link current tab" inside the notes panel.

**Comment by johngruen** [comment]
Hey @dannyhajj we are working on UX to tie specific notes to URLS, but the feature you describe here would involve significant work on Firefox to implement. I'm going to close this issue since our team does not have the resources to make it possible :(
