### ISSUE TITLE
[Feature request] Add ability to simply insert current page's URL

### ISSUE THREAD

**Issue by bbenoit** [mozilla/notes#194]
As seen with Firefox 54.0 (Linux) + Note 1.6.3dev

Clicking in the Note area with right button calls the context menu. Nor this menu nor the buttons in the toolbar allow to **paste the currents page's URL at cursor position**.

_Note_: if this feature is implemented, it can maybe also allow to paste different things, like the title of the current page, the selected text if any, the current date (and time) etc.

**Comment by johngruen** [comment]
@bbenoit we've added this to our backlog tracker, and it's under consideration!
