### ISSUE TITLE
[Windows] Fix Notes in multitab Firefox windows 

### ISSUE THREAD

**Issue by joshhazelhurst123** [mozilla/notes#195]
![notes firefox bug](https://user-images.githubusercontent.com/30138699/29105781-6552c6c4-7d24-11e7-8fe1-13e9916dbabd.jpg)
[Notes]:

Notes is not showing for me. Notes was working when I installed the add on. I installed privacy badger firefox add on immediately after installing notes. Maybe that has affected Notes. Notes was working, now it is not. 

[Affected versions]:

    Firefox 55.0

[Affected Platforms]:

     Windows 8 64 bit, Toshiba Satellite skullcandy. 

[Prerequisites]:

    install notes. install privacy badger

[Steps to reproduce]:

    Open the browser with notes and privacy badger installed. 
    Click on the "Show sidebars" button from the toolbar.
    Observe the way the "Notes" sidebar option is displayed.

[Expected result]:
- Notes to work as it did before. 

[Actual result]:
- Notes is not working. No UI or anything. See screenshot. 

[Additional Notes]:

    Attached a screenshot of the issue:
I did get this to work again. I had to disable the add in then re add it back on. Think this is still a genuine issue. Not sure why it stopped working.

**Comment by SoftVision-EmilPasca** [comment]
I have tested this issue on Windows 10, 8.1 and 8 x64 with Firefox Release 55.0 and the latest Nightly(57.0a1-20170808114032) with the steps provided and haven't managed to reproduce the issue.
After enabling Notes and badger (Privacy Badger 2017.7.24), the "Notes" sidebar was successfully loaded and the UI was correctly displayed.

If you encounter this issue again, can you please provide more information, the complete list of installed add-ons and also the messages that may appear in the Browser Console?

Thank you.

**Comment by joshhazelhurst123** [comment]
More details are as follows, hopefully this helps: windows 8.1 x64 Firefox release 55.0.
adds on are:
 - privacy badger 2017.7.24.
- test pilot 2.0.2-dev-0d66c35 
as plugins I have:
- shockwave flash 26.0.0.151 Widevine Content Decryption Module provided by Google Inc 1.4.8.903
- OpenH264 Video Codec provided by Cisco Systems, Inc. 1.6
I will check the browser console if this error happens again. Thank you for your reply.

**Comment by johngruen** [comment]
So, we are unable to reproduce this issue. Can you see other sidebars?

**Comment by joshhazelhurst123** [comment]
Yes I can see other sidebars @johngruen . Notes is working now. I can't reproduce the error again. Sidebars working, bookmarks, history, synced tabs, notes. All working fine.

**Comment by Natim** [comment]
Ok thanks for confirming.

**Comment by johngruen** [comment]
I guess some weird error on sidebar initialization. I tend to chalk stuff like this up to deep Gecko weirdness which Test Pilot experiments have a way of exposing. @joshhazelhurst123 let us know if you see this again and we'll reopen for further investigation.

**Comment by joshhazelhurst123** [comment]
thanks.
