### ISSUE TITLE
Disable Google Analytics

### ISSUE THREAD

**Issue by hackel** [mozilla/notes#197]
When attempting to activate Notes for the firs time, I get asked if I wish to allow Notes to "Access your data for ssl.google-analytics.com".  This shouldn't be necessary, and is certainly going to scare off a lot of potential users.  I block Google Analytics on a system level, and I assume (hope) uBlock will affect this extension as well, but still, this looks really bad.

I don't know if it's possible to ask for a permission *after* installing, but that would be the ideal way to go about this if you are determined.  Of course I would choose a more trustworthy provider!

**Comment by cedricium** [comment]
Hey @hackel, see #175. Because this is an experiment, the team collects data to see how this experiment (Notes) is being used so that future development decisions can be made based on analysis.

**Comment by johngruen** [comment]
Hey @hackel if you have Do Not Track set in your browser we don't collect anything at all. You can verify this by looking at your network monitor. For more details about how to set the Do Not Track feature check this out: https://github.com/mozilla/testpilot/blob/master/docs/faq.md#why-do-test-pilot-experiments-ask-me-to-allow-google-analytics
