### ISSUE TITLE
Adding the option for Font color change-suggestion 

### ISSUE THREAD

**Issue by abinabrahamanchery** [mozilla/notes#201]
Add an option to select the font color so that the Items in the notes can be represent in a good manner and it will also help to organize the content in the note accordingly to the Priority based on the color code 

-Please include the Sync option in the note 
- Include Export option or Download Option 
-Please include a proper documentation so that others can also contribute to the project 
-If there is any IRC channel please mention

**Comment by Divya063** [comment]
I would like to work on this feature

**Comment by johngruen** [comment]
Hey @Divya063 we are currently evaluating features to add based on user feedback, and will add font-color changing to the list. We are not sure this feature would necessarily merge, since it conflicts with other feature requests such as markdown support but we are happy to see demos.

**Comment by Divya063** [comment]
Thanks for the response @johngruen I'm working on demo

**Comment by abinabrahamanchery** [comment]
any update on this enhancement ? @Divya063 @johngruen
