### ISSUE TITLE
The wrong version of Firefox Notes is installed when enabling the experiment from Test Pilot

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#207]
**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Navigate to https://testpilot.firefox.com/experiments/notes page.
2. Click on "Install Test Pilot & Enable Notes".
3. Navigate to "about:addons" page.
4. Click on the "More" link for "Firefox Notes".
5. Observe the "Firefox Notes" displayed version.

**[Expected result]:**
- "Firefox Notes" release version(1.4) is displayed.

**[Actual result]:**
- "Firefox Notes" dev version(1.6.3dev) is displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![notes_wrong_version](https://user-images.githubusercontent.com/20083658/29363068-2cf7b622-8297-11e7-8537-d3ea2ea0d534.gif)

**Comment by johngruen** [comment]
@SoftVision-EmilPasca will verify and close

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest Firefox Notes version (1.7.0).
