### ISSUE TITLE
Window content flickers when opening or closing the sidebar

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#213]
**[Notes]:**
- This issue is also reproducible without installing Firefox Notes.

**[Affected versions]:**
- Firefox Latest Release 54.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Steps to reproduce]:**
1. Navigate to https://testpilot.firefox.com/experiments/notes page.
2. Click on "Install Test Pilot & Enable Notes".
3. Close and reopen the Notes Sidebar (keyboard shortcut Alt+Shift+W).
4. Observe the browser behaviour.

**[Expected result]:**
- The window content doesn't flicker.

**[Actual result]:**
- The window content flickers for a milisecond.

**[Additional Notes]:**
- Bugzilla issue: [Bug 1117253](https://bugzilla.mozilla.org/show_bug.cgi?id=1117253)
- Attached a screen recording of the issue:
![notes_sidebar_issue](https://user-images.githubusercontent.com/20083658/29467251-6f503686-8448-11e7-91cd-a8c92d31e3d6.gif)

**Comment by johngruen** [comment]
Closing for upstream version
