### ISSUE TITLE
Default to dark theme if devtools.theme is "dark"

### ISSUE THREAD

**Issue by Caspy7** [mozilla/notes#216]
If devtools.theme (in about:config) is set to "dark" this means that the user has chosen to use a dark motif for the browser and the theme should reflect this.

**Comment by cedricium** [comment]
I like the idea, it makes sense. And it should be fairly simple to implement given there's a `devtools.panels.themeName`<sup>1</sup> API for WebExtensions. If the Notes team wants to go forward with this I'd be willing to do the implementation.

<sup>1</sup>: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels/themeName

**Comment by vladikoff** [comment]
@cedricium it's not clear to me if this theme api is only for dev tools or browser wide

**Comment by cedricium** [comment]
@vladikoff it's listed as part of the JavaScript APIs in MDN, which in my experience all seem to work browser-wide. The one I listed above is essentially just a getter that returns one of the following themes that is currently set for the user's devtools theme: 'light', 'dark', or 'firebug'. I can play around with it this weekend and see if this is feasible.

**Comment by Caspy7** [comment]
@vladikoff 
Just checked and this pref is still what sets the light/dark theme for Photon.

**Comment by Natim** [comment]
@cedricium I am adding it in the next sprint, don't hesitate to give it a try 👍

**Comment by Natim** [comment]
I tried in #360 but I have devtools is not defined and browser.devtools is not defined.

**Comment by Natim** [comment]
> Like all the devtools APIs, this API is only available to code running in the document defined in the devtools_page manifest.json key

Ok let me try this.

**Comment by Natim** [comment]
No luck either.

**Comment by Natim** [comment]
After speaking with @rpl on IRC it seems impossible to access this webextension API from outside the scope of the devtools extension.

**Comment by Natim** [comment]
It actually works only if the devtool panel is open...

**Comment by rpl** [comment]
Currently the only way to have the DevTools theme name in the sidebar is to forward it from a devtools_page (e.g. by using the browser.runtime.sendMessage API call from the devtools_page and browser.runtime.onMessage API event on the sidebar page side).

It is also worth to mention that the devtools page is an invisible page, like the background page, but unlike the background page:

- it doesn't exist until the DevTools are opened on a tab
- there will be one devtools_page instance per DevTools toolbox opened

**Comment by Caspy7** [comment]
This bug just landed in 58 to let extensions obtain information about the current theme.
https://bugzilla.mozilla.org/show_bug.cgi?id=1349944
Would that allow this?
