### ISSUE TITLE
Notes extension icon is not pixel snapped

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#217]
I was pretty sure that this was provided at a pixel snapped size (so that right angles are not anti-aliased), but in Nightly it's been scaled/moved a little. How to fix?
<img width="136" alt="screen shot 2017-08-24 at 3 23 26 pm" src="https://user-images.githubusercontent.com/68213/29684568-749bccf8-88e0-11e7-8315-ddbe153d2c75.png">

**Comment by ryanfeeley** [comment]
For comparison, check out the Synced Tabs icon:
<img width="164" alt="screen shot 2017-08-24 at 3 26 26 pm" src="https://user-images.githubusercontent.com/68213/29684631-b548bab8-88e0-11e7-9a26-80f0c6689ebd.png">

**Comment by johngruen** [comment]
i think you can use a 32px square SVG and set `fill="context-fill"`

**Comment by ryanfeeley** [comment]
Is this better @vladikoff? Where does it go?
[notepad-tweaked.svg.zip](https://github.com/mozilla/notes/files/1268474/notepad-tweaked.svg.zip)

**Comment by Natim** [comment]
@ryanfeeley What is the course of action for this issue? Shall I close #224?

**Comment by ryanfeeley** [comment]
@Natim I think it was my SVG. Argh! Try this one? (which is also grey)
[universal-notepad-large.svg-centered.zip](https://github.com/mozilla/notes/files/1333481/universal-notepad-large.svg-centered.zip)

**Comment by Natim** [comment]
![news-icon-linux](https://user-images.githubusercontent.com/229453/30865400-c27178c8-a2d6-11e7-830d-be6c1d32de8e.png)

**Comment by Natim** [comment]
Seems to be awesome now :)
