### ISSUE TITLE
Add the ability to add checkbox list items

### ISSUE THREAD

**Issue by mikeconley** [mozilla/notes#218]
Especially in software like Evernote, I find myself using the checkbox list item feature to add things to a TODO list that I can, well, check off as I proceed. Having something like that that I can edit and tick off in the sidebar would be super handy.

**Comment by Natim** [comment]
I @mikeconley You can add checkbox by entering `[]` in the pad.

**Comment by johngruen** [comment]
Let's leave this open since it might be nice to expose in the menu as an option.
