### ISSUE TITLE
Theme options are hidden when first visiting the Notes "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#220]
[Notes]:
- The issue is intermittently reproducible on Italian (it),  Frisian - (fy-NL), Hungarian (hu), Malay (ms), Norwegian Nynorsk (nn-NO), Serbian (sr), Slovak (sk), Slovenian (sl), Sorbian Lower (sl).
- The issue is no longer reproducible after navigating to an other page and then back to the "about:addons" page.

[Affected versions]:
- Firefox 55.0.3
- Firefox Notes v1.7.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.7.1) loaded as a temporary add-on.

[Steps to reproduce]:
1. Open an Italian localized browser with the profile from prerequisites.
2. Navigate to about:addons page.
3. Click on the "Extensions" button.
4. Click on the "More" link for Firefox Notes add-on.
5. Observe the "Theme" options.

[Expected result]:
- The theme options are correctly displayed.

[Actual result]:
- The theme options are hidden after a few miliseconds.

[Additional Notes]:
- Attached a screen recording of the issue:
![issue_teme_options_are_hidden](https://user-images.githubusercontent.com/20083658/29885599-12a051e2-8dc0-11e7-9d9c-e33e66e31943.gif)

**Comment by vladikoff** [comment]
> The issue is intermittently reproducible on Italian (it), Frisian - (fy-NL), Hungarian (hu), Malay (ms), Norwegian Nynorsk (nn-NO), Serbian (sr), Slovak (sk), Slovenian (sl), Sorbian Lower (sl).

So some l10n / translation issue is to blame?

**Comment by vladikoff** [comment]
Does it work for en-US all the time?

**Comment by cedricium** [comment]
@vladikoff I've seen this issue before with the en-US locale. I'm only ever able to reproduce when starting Notes via `npm start` then immediately navigating to the Settings page. This is similar to what @SoftVision-EmilPasca shows in the screen recording by uploading the manifest file then going directly to the Settings page.

Seems like by navigating to the Settings page as Notes is starting up the page stops getting rendered.

**Comment by vladikoff** [comment]
Sounds like a "Firefox Bug" :o

**Comment by johngruen** [comment]
@vladikoff will file a bug and close this
