### ISSUE TITLE
[Windows] "Notes" sidebar is not shown after restarting the browser

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#222]
[Notes]:
- The issue is not reproducible on Mac OS.
- The issue doesn't occur on the latest Firefox Release 55.0.3.
- The issue is reproducible only with a new Firefox profile.

[Affected versions]:
- Firefox 57.0a1
- Firefox Notes v1.7.1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.7.1) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Restart the browser.
3. Observe the "Notes" sidebar.

[Expected result]:
- The "Notes" sidbear is successfully showen.

[Actual result]:
- The "Notes" sidbear is not showen after restart.

[Regression]:
Last good revision: 3aa4bc482372340ca890b1b0b5fd0937d21b725d
First bad revision: b80466887686fbefe5a67aebc86f6f4aaf5feac8
Pushlog: https://goo.gl/zGTduu

[Notes]:
- Attached a screen recording of the issue:
![notes_restart](https://user-images.githubusercontent.com/20083658/29914409-10476b7a-8e41-11e7-8c18-154f1f451be7.gif)

**Comment by SoftVision-EmilPasca** [comment]
Refs: https://bugzilla.mozilla.org/show_bug.cgi?id=1385630

**Comment by johngruen** [comment]
This is upstream and has a bug filed

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible on the latest Nightly(58.0a1-20170921220243) with the latest Notes (1.8.0 dev).
