### ISSUE TITLE
Organize Notes (One line, one note)

### ISSUE THREAD

**Issue by kekkc** [mozilla/notes#223]
Hi,

why not organize the notes like other notes application (Scrapbook addon, Opera 8). Here's a screen from the standard Opera 8 dinosaur:
![notes sketch](https://user-images.githubusercontent.com/6283064/29920089-3b0ab78a-8e4c-11e7-91a5-d8681e28fb5b.png)

And one from the old Scrapbook Addon:
![notes sketch 2](https://user-images.githubusercontent.com/6283064/29920781-68499dda-8e4f-11e7-8390-25532bb889fa.png)

**Comment by Natim** [comment]
@kekkc we are currently starting a round of User Research interview about these new features. Thank you for the feedback.

@ryanfeeley That's very close to your current mock-up can you share yours here?

**Comment by johngruen** [comment]
I'm going to close this as a dupe...we're user testing this feature already #40
