### ISSUE TITLE
Notes "Sign in" window is wrongly opened even if already signed in

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#227]
[Affected versions]:
- Firefox 55.0.3
- Firefox Notes v1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.8.0dev) loaded as a temporary add-on.
- Have a firefox account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button from the "Notes" sidebar.
3. After the "Sign in" window is displayed, enter your firefox account credentials and click "Sign in".
4. After the "Sign in" window is closed click on the "Synced" button from the "Notes" sidebar.

[Expected result]:
- The "Sign in" window is not opened since the user is already signed in.

[Actual result]:
- The "Sign in" window is opened asking for the user to sign in.

[Notes]:
- Attached a screen recording of the issue:
![alreadysign_in_issue](https://user-images.githubusercontent.com/20083658/30274621-ea976898-9706-11e7-960f-6b45553cf362.gif)

**Comment by Natim** [comment]
Fixed in #241
