### ISSUE TITLE
"Unknown account" message is displayed when trying to sign in to Firefox Notes

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#228]
[Notes]:
- The user has to create a new Firefox account (optional, using the same email and password) in the "Firefox Notes" sign-in window in order to successfully log in.

[Affected versions]:
- Firefox 55.0.3
- Firefox Unbranded 55.0.1
- Firefox Notes v1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.8.0dev) loaded as a temporary add-on.
- Have a Firefox account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and sign in with your Firefox account.
2. Click the "Sync Your Notes" button from the "Notes" sidebar.
3. After the "Sign in" window is displayed and click "Have an account? Sign in" link button.
4. Enter your Firefox account credentials and click "Sign in".
5. Observe the browser behaviour.

[Expected result]:
- The user is successfully sign in into Firefox Notes.

[Actual result]:
- "Unkown account" message is displayed.

[Notes]:
- Attached a screen recording of the issue:
![account_issue](https://user-images.githubusercontent.com/20083658/30279618-66a22c66-9716-11e7-8b01-eb9edb92d7db.gif)

**Comment by vladikoff** [comment]
This is because the Extension and Firefox are using 2 different servers, (accounts.firefox.com vs scoped key domain)
