### ISSUE TITLE
[Windows] "Sync Your Notes" button is not actionable on Firefox Beta and Nightly

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#229]
[Affected versions]:
- Nightly (57.0a1-20170910220126)
- Firefox Beta  (56.0b2-20170810113054)
- Firefox Notes v1.8.0dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes add-on version (1.8.0dev).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button from the "Notes" sidebar.
3. Observe the browser behavior.

[Expected result]:
- Firefox Notes "Sign in" window is displayed.

[Actual result]:
- Nothing happens.

[Notes]:
- Attached Browser Console messages:
`[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowWatcher.openWindow]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://extensions/content/ext-c-identity.js :: openOAuthWindow :: line 69"  data: no]  (unknown)
Unchecked lastError value: DataCloneError: The object could not be cloned.  ExtensionCommon.jsm:407
Error: An unexpected error occurred`
- Attached a screen recording of the issue:
![syncyournotesbuttons](https://user-images.githubusercontent.com/20083658/30281367-d9e13b32-971a-11e7-8d48-ed5694b35b93.gif)

**Comment by vladikoff** [comment]
I cannot reproduce this issue, Can you try with latest Nightly? Any ideas?

**Comment by vladikoff** [comment]
@rfk tried this on Windows and Mac. This seems to be a Window issue, is there a chance you could please file this on BugZilla @SoftVision-EmilPasca ?

**Comment by SoftVision-EmilPasca** [comment]
Refs: [Bug 1399070](https://bugzilla.mozilla.org/show_bug.cgi?id=1399070).

**Comment by SoftVision-EmilPasca** [comment]
I have verified this issue on Mac OS 10.12, Windows 10 x64 and Ubuntu 14.04 x64 with the latest Nightly(57.0a1-20170917220255) and it is no longer reproducible.
