### ISSUE TITLE
Do not merge conflict Intro Text

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#23]
Hey @Natim, merge conflict worked well. Only thing is we don't want to merge conflict the intro text. 

Not sure if it is easy to detect the intro text or not

**Comment by Natim** [comment]
I can do a change so that we won't never sync the intro text.
However if you change it we will sync it and it won't be the Intro text anymore.

Would that cover your issue?

**Comment by vladikoff** [comment]
>However if you change it we will sync it and it won't be the Intro text anymore.

Exactly this! :D
