### ISSUE TITLE
Content is heavily multiplied when shyncronizing two profiles and opening a new window

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#230]
**[Notes]:**
- If you synchronize one profile and open a new window on the other profile right after the step 3, the content is heavily multiplied and after a while the browser freezes and stops responding. But this also depends on the amount of data stored in Notes. 

**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Latest Firefox Unbranded (55.0.4)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with Firefox Notes 1.8.0dev installed.
- You must be logged with the same sync account on both profiles.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. In one instance write something in the "Notes" sidebar and leave the other one blank.
3. After the profiles sync, open a new window in the instance with the blank "Notes" sidebar.
4. Observe the "Notes" sidebar content in the newly opened window.

**[Expected result]:**
- The content from step 2 is displayed.

**[Actual result]:**
- The content is heavily multiplied and after a while the instance freezes.

**[Additional Notes]:**
- If another new window is opened on the same instance, the content is multiplied even more.
- Attached a screen recording of the issue:
![notes sync](https://user-images.githubusercontent.com/31243259/30284975-43a08cbc-9725-11e7-8d0a-1dde81bad896.gif)

**Comment by Natim** [comment]
Nice catch, it looks like a terrible bug 🗡

**Comment by Softvision-MariusComan** [comment]
I've noticed another behaviour of this issue:
1. Follow the steps from the above STR, until step 3.
2. Change the content in the first browser instance (delete, add new strings, etc).
3. Observe the second's instance new window.

Actual result:

The content multiplied in the other window is changed in real time based on the changes from the other instance. See the next screen recording for more details:
![notes sync nr2](https://user-images.githubusercontent.com/31243259/30320138-6d2eea34-97ba-11e7-82c1-3cc2836b6b4a.gif)

**Comment by Natim** [comment]
This has been fixed in the sync-v4 branch.
