### ISSUE TITLE
Login loop and confirmation occurs when you try use an older testing account created

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#232]
**[Notes]:**
- Newly created accounts (created today) do not require confirmation, after it was already given at the first login. While the ones created yesterday are all displaying this behavior.

**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Latest Firefox Unbranded (55.0.4)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with Firefox Notes 1.8.0dev installed.
- Use this credentials to log in: 
	- User: testingmoz@protonmail.com
	- PSW: Mozilla123

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Sync Your Notes" button on the bottom of the Notes sidebar.
3. Click "Have an account? Sign in" and log in with the credentials from prerequisite.
4. Open the email client and confirm the account from the received email.
5. Observe the page behaviour and after click the "Sync Your Notes" button again.

**[Expected result]:**
- The sync log in window is closed and Notes correctly performs the sync operation.

**[Actual result]:**
- A log in loop request occurs at each sync attempt and each time you try to relog with the same account, you are also prompted to confirm the log in again.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![notes sign in confirmation](https://user-images.githubusercontent.com/31243259/30333106-ce8e4516-97e4-11e7-8d10-1858d417b798.gif)

**Comment by vladikoff** [comment]
cc @rfk, let's chat about next step for this

**Comment by rfk** [comment]
I'm not 100% clear on what's happening here.  In the video, why are you clicking "back" on the "confirm this sign-in" screen and signing in again?  Does the "confirm this sign-in" stay present even after you've clicked on the confirmation link in the email?

**Comment by Softvision-MariusComan** [comment]
It's not necessary to press the "Back" button. After you click the confirmation link from the e-mail, if you wait long enough, the "confirm this sign-in" page will disappear.
Attached a new screen recording of the issue:
![sign in](https://user-images.githubusercontent.com/31243259/30542263-5b0b12a2-9c87-11e7-8706-d6441a58258b.gif)

**Comment by rfk** [comment]
OK thanks.  So it looks like the login works and the notes sync correctly, but if you click on the "sync" option again then you're asked to login and do the email confirmation loop again?

@vladikoff what's the expected behaviour here?  Should you have to login again at all, should we avoid prompting for confirmation, or something else?

**Comment by Natim** [comment]
> if you click on the "sync" option again then you're asked to login and do the email confirmation loop again?

Yes that's a work in progress, we need to add @ryanfeeley menu, with it clicking will trigger a manual sync rather than asking you to log in again.

**Comment by Natim** [comment]
Marking as a Firefox bug since it is a Firefox Account policy.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.
