### ISSUE TITLE
While saving locally Editing should say Saving Changes…

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#234]
And if syncing it should say Syncing Changes…

**Comment by ryanfeeley** [comment]
And also spinning blue sync icon as per spec

**Comment by ryanfeeley** [comment]
And grey… review https://mozilla.invisionapp.com/d/main/#/console/11122662/235284916/preview

**Comment by Natim** [comment]
Fixed in 2.0.0a1 #241
