### ISSUE TITLE
Synchronization wrongly starts only when one instance is edited

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#236]
**[Notes]:**
- If one instance has content and the other does not, after focusing the latter instance and editing it, content will be wrongly shown as "Previously was" content. The older content from the first instance will be wrongly displayed as the newer content.

**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with Firefox Notes 1.8.0dev installed.
- You must be logged with the same sync account on both profiles.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. In one instance write something in the "Notes" sidebar and leave the second one blank.
3. Observe the second instance.
4. Write something in the second instance and observe the behaviour of both instances.

**[Expected result]:**
- Step 3 - Content from the first instance is successfully displayed.
- Step 4 - The sync between the instances is successfully made and the same content is displayed.

**[Actual result]:**
- Step 3 - Nothing happens 
- Step 4 - The sync is done only when editing one of the instances.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![notes sync](https://user-images.githubusercontent.com/31243259/30592083-1be59026-9d4e-11e7-9309-e859e7bc37ef.gif)

**Comment by Natim** [comment]
Fixed in #241
