### ISSUE TITLE
Blank space is wrongly synchronized between two instances

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#237]
**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with Firefox Notes 1.8.0dev installed.
- You must be logged with the same sync account on both profiles.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write something in the first instance and then in the second.
3. Select and clear all content from the second instance.
4. Select and clear all content from the first instance and observe the behaviour.

**[Expected result]:**
- There is no content.

**[Actual result]:**
- Blank space is wrongly displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![notes blank](https://user-images.githubusercontent.com/31243259/30594293-3693f3a6-9d56-11e7-95b6-e1d934bf7140.gif)

**Comment by cedricium** [comment]
@Natim is this actually a `Links` issue?

**Comment by vladikoff** [comment]
@cedricium sorry, Sync :)

**Comment by Natim** [comment]
Yes thanks :)

**Comment by Natim** [comment]
I guess this is related to Quill JS itself that trim the notepad a little bit.
Does the space stays locally if you close and reopen the sidebar?

**Comment by Natim** [comment]
Actually I wasn't able to reproduce, the space were correctly synced that time.
