### ISSUE TITLE
After sync, newer content is wrongly displayed under "Previously was" text

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#238]
**[Notes]:**
- This issue is reproducible only if both instances are opened at the same time.

**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with Firefox Notes 1.8.0dev installed.
- You must be logged with the same sync account on both profiles.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write something in the first instance and then in the second.
3. Observe the second instance.

**[Expected result]:**
- The newer content is displayed above "Previously was" text.

**[Actual result]:**
- The newer content is displayed under "Previously was" text.

**[Additional Notes]:**

- If you go back to the first instance and change or add some content the "Previously was" text is not displayed.
- Attached a screen recording of the issue:
![newer content](https://user-images.githubusercontent.com/31243259/30599194-66d2633c-9d64-11e7-8789-7123dcf19dc3.gif)

**Comment by johngruen** [comment]
See #239 for more detail

**Comment by Natim** [comment]
Fixed in #241 and 2.0.0a1
