### ISSUE TITLE
No option to open notes

### ISSUE THREAD

**Issue by prototriangle** [mozilla/notes#243]
![image](https://user-images.githubusercontent.com/18370628/30655437-ce3f53a8-9e28-11e7-8e12-a5490974d8f8.png)
![image](https://user-images.githubusercontent.com/18370628/30655462-dc76ba74-9e28-11e7-8668-80e40924aabe.png)
![image](https://user-images.githubusercontent.com/18370628/30655502-fd4de998-9e28-11e7-9222-414bc419b8e4.png)

All of the above indicators show that Notes is installed and yet:
![image](https://user-images.githubusercontent.com/18370628/30655570-3ae7e470-9e29-11e7-9310-4b62b9950352.png)
There is no option to open notes in sidebar.

I have tried uninstalling and reinstalling and enabling and disabling and restarting but to no avail.
I am running ff 53.0.2 (64-bit) on Ubuntu.

**Comment by SoftVision-EmilPasca** [comment]
@prototriangle This is a known issue ([Testpilot issue 2848](https://github.com/mozilla/testpilot/issues/2848)), in order to use Notes, you must have at least Firefox 54.0.
