### ISSUE TITLE
Implement Sync button animation

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#247]
![image](https://user-images.githubusercontent.com/128755/30873259-91ec3e66-a2ba-11e7-89cb-912bb77ddab2.png)

cc @ryanfeeley @cedricium

**Comment by vladikoff** [comment]
@cedricium, we had to revert the menu from the `master` branch, but the patch is here (also in your branch): 

[240.patch.txt](https://github.com/mozilla/notes/files/1334047/240.patch.txt)

You can create a new branch based on the `support-menu` branch and then when https://github.com/mozilla/notes/pull/141 is ready @Natim can pull the changes and merge everything.

**Comment by ryanfeeley** [comment]
If it's not clear from the static image (and why would it be) when blue, the sync icon should spin like it does in the hamburger menu.
![spin](https://user-images.githubusercontent.com/68213/30875087-51d4cc3e-a2c0-11e7-9e68-2040f1e8a546.gif)

**Comment by Natim** [comment]
Closed with #342
