### ISSUE TITLE
Add quill and kinto-http as npm dependencies?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/notes#25]
This would make building and bundling a bit trickier (`npm install` and potentially moving files), but would keep some 3rd party code out of our codebase and make it easier to upgrade libraries in the future.

For example, it looks like we're bundling [**quill@1.2.4**](https://github.com/mozilla/notes/blob/master/src/sidebar/quill.js) in our repo, but the latest is [v1.2.6](https://www.npmjs.com/package/quill).

The minified [**kinto-http**](https://github.com/mozilla/notes/blob/master/src/sidebar/kinto-http.js) file doesn't even have a copyright header or version number I can find, so I don't even know what version of the library it is, and if it is out of date. Looks like the latest version on npm is [v4.3.4](https://www.npmjs.com/package/kinto-http) though.

**Comment by vladikoff** [comment]
After V1

**Comment by pdehaan** [comment]
![](http://memeguy.com/photos/images/mrw-i-see-my-ex-in-public-and-she-makes-eye-contact-with-me-23484.gif)

**Comment by groovecoder** [comment]
This may need some new priority so Greenkeeper can make sure these dependencies stay up-to-date with security patches.

**Comment by vladikoff** [comment]
@groovecoder great yeap!
