### ISSUE TITLE
Firefox Notes specific icon is not displayed on "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#250]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc1).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to about:addons and click on "Extensions" option.
3. Observe "Firefox Notes" experiment icon.

[Expected result]:
- Experiment's specific icon is displayed on the left side of its title and description preview.

[Actual result]:
- Default add-on icon is displayed.

[Notes]:
- The issue is not reproducible on Firefox Notes installed from Test Pilot.
- Attached a screen recording of the issue:

![notes icon](https://user-images.githubusercontent.com/26000308/30911104-f42b8264-a38f-11e7-9f1a-229c6186ff16.gif)

**Comment by Natim** [comment]
I posted a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1403526
I also find out a workaround for that in #251

**Comment by johngruen** [comment]
@vladikoff needs to merge a fix to close this

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" version (1.8.0 rc3).
