### ISSUE TITLE
Pasted URLs are not automatically turned into links

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#252]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Copy any URL in the clipboard.
3. Paste the URL in the "Notes" sidebar.
4. Observe the pasted URL..

[Expected result]:
- The URL text color turns blue and the link is actionable.

[Actual result]:
- The URL text color is the same as the rest of the text and the link is not actionable.

[Notes]:
- The issue is not reproducible when manually typing a URL in "Notes" sidebar.
- Attached a screen recording of the issue:
![notes_urls](https://user-images.githubusercontent.com/20083658/30912561-bf5242ac-a395-11e7-832c-7a9129eab4a7.gif)

**Comment by Natim** [comment]
Fixed in 75c751452146e488b39e7b8c86fb38df4bdc3ecb

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" version (1.8.0 rc3), retested on Windows 10 x64 and Mac OS 10.12 on Firefox Release (56.0) and latest Nightly (58.0a1-20171001220301).
