### ISSUE TITLE
Switching back to Notes breaks the sidebar if hyperlinks were previously written in the editable area

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#254]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a valid hyperlink address into the "Notes" sidebar (eg. http://wikipedia.org)
3. Click the "Notes" sidebar switcher button.
4. Click on another sidebar (e.g Bookmarks).
5. Click the "Bookmarks" sidebar switcher button and select the "Notes" sidebar.
6. Observe "Notes" sidebar behavior.

[Expected result]:
- The hyperlink is displayed on the editable area of the "Notes" sidebar.

[Actual result]:
- The hyperlink is not displayed and the editable area of the "Notes" sidebar is useless.

[Notes]:
- This issue is not reproducible when having text written beside the Hyperlinks.
- Unlike Linux and Ubuntu, on Windows, the issue is still reproducible when switching the sidebars through keyboard shortcuts. 
- Re-enabling the experiment won't fix the issue.
- The following error is displayed in the Browser console when switching back to "Notes "sidebar:
![error](https://user-images.githubusercontent.com/26000308/30920673-3e43caf6-a3ad-11e7-9781-56fc5d7ea99e.png)

- Attached a screen recording of the issue:

![change sidebars](https://user-images.githubusercontent.com/26000308/30920679-434d65ac-a3ad-11e7-987c-3efa5e15d590.gif)

**Comment by vladikoff** [comment]
oh wow!

**Comment by vladikoff** [comment]
@SoftVision-CarmenFat thanks for thorough testing!! 🔍

**Comment by cedricium** [comment]
Reproducible before @Natim's commits, will need to investigate.

**Comment by SoftVision-CarmenFat** [comment]
I investigated this issue more and I have the following information to add:
- If the text (or hyperlink) is formatted with one of the lists formatting options, then sending a tab to a new window, the Notes sidebar from the new window has the same behavior as I described in the first comment; the difference, in this case, is that the Notes Sidebar from the main window seems that is not affected. For more details, please see the screen cast attached:

![new window list](https://user-images.githubusercontent.com/26000308/30975634-677dfae4-a47b-11e7-89af-feb3afb0fe10.gif)

**Comment by Natim** [comment]
Fixed in 75c751452146e488b39e7b8c86fb38df4bdc3ecb

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" version (1.8.0 rc3).
