### ISSUE TITLE
After pasting a link in a cleared "Notes" sidebar, you cannot continue typing, unless you click in the sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#255]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Clear all the text from "Notes" sidebar.
3. Paste a link (through keyboards or context menu).
4. Start typing anything.

[Expected result]:
- The typed text is displayed.

[Actual result]:
- The typed text is not displayed.

[Notes]:
- The caret is not displayed after pasting a link in a cleared "Notes" sidebar.
- Here is a screen recording of the issue:
![notes](https://user-images.githubusercontent.com/31244235/30921182-808d797e-a3ae-11e7-8379-85bd8bb4cdf6.gif)

- Also, if the side bar is cleared, when typing something the caret is wrongly displayed: 
![notes 2](https://user-images.githubusercontent.com/31244235/30921194-891b6a06-a3ae-11e7-9b9c-44943aa94957.gif)

**Comment by vladikoff** [comment]
I'm sad about this bug :(, but I'm happy for Kit and Rose!

**Comment by cedricium** [comment]
Reproducible before @Natim's commits, will need to investigate.

**Comment by Natim** [comment]
Fixed in 75c751452146e488b39e7b8c86fb38df4bdc3ecb

**Comment by Softvision-CristinaBadescu** [comment]
I have retested this issue and I can confirm that is no longer reproducible using the latest "Firefox Notes" version (1.8.0 rc3), on Windows 10 x64, Mac OS 10.12 and Ubuntu 14.04 x64, on Firefox Release (56.0) and latest Nightly build (58.0a1-20171001220301).
