### ISSUE TITLE
Previously cleared content is wrongly redisplayed when you reopen "Firefox Notes"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#256]
**[Affected versions]:**
- Firefox Notes 1.8.0 rc2
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write a string in the "Notes" sidebar.
3. Select all content and press the "Delete" key.
4. Close and reopen the "Notes" sidebar
5. Observe the sidebar.

**[Expected result]:**
- There is no content displayed.

**[Actual result]:**
- The string from step 3 is displayed.

**[Notes]:**
- The issue is reproducible if you switch the sidebars instead closing.
- The issue is reproducible if you restart the browser.
- The issue is also reproducible if you press the "Backspace" key at step 3.
- Attached a screen recording of the issue:
![notes clear content](https://user-images.githubusercontent.com/31243259/30966555-fcddbf4e-a461-11e7-88f4-6eb27105c975.gif)

**Comment by Natim** [comment]
Can't reproduce it anymore with 75c751452146e488b39e7b8c86fb38df4bdc3ecb

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" version (1.8.0 rc3), retested on Windows 10 x64 and Mac OS 10.12 on Firefox Release (56.0) and latest Nightly (58.0a1-20171001220301).
