### ISSUE TITLE
"Cut" and "Paste" context menu options are active when no strings are selected

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#257]
**[Affected versions]:**
- Firefox Notes 1.8.0 rc2
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Right click on the "Notes" sidebar.
3. Observe the context menu.

**[Expected result]:**
- "Cut" and "Paste" options are greyed out.

**[Actual result]:**
- "Cut" and "Paste" options are active.

**[Notes]:**
- The "Delete" option from the context menu is active only when content is selected.
- Attached a screen recording of the issue:
![cut and paste options](https://user-images.githubusercontent.com/31243259/30970721-8a749664-a46e-11e7-9633-9663da6b2ed2.gif)

**Comment by johngruen** [comment]
We believe this is an upstream bug. Leaving open until that gets filed

**Comment by Softvision-MariusComan** [comment]
I have managed to reproduce the issue on Firefox 54 and up. I've also tested the issue with Firefox Notes 1.2, 1.3 and 1.6 and it is reproducible an all tested builds.
It is also very strange that the "Delete" option is active when content is selected and greyed out when no content is selected.

@johngruen can you please post a link to the upstream bug that you guys think is causing this?

**Comment by Natim** [comment]
> Can you please post a link to the upstream bug that you guys think is causing this?

I think this might be the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=635674

**Comment by Natim** [comment]
I am going to close this in favor of the bugzilla issue.
