### ISSUE TITLE
[Enhancement] Hyperlinks that were visited should change color

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#258]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a valid hyperlink address into the "Notes" sidebar (eg. http://wikipedia.org)
3. Click the hyperlink and observe if any change occurs to it.

[Expected result]:
- The hyperlink should change from blue to another color so that the user can notice when a website was visited.

[Actual result]:
- The hyperlink doesn't change its color.

**Comment by johngruen** [comment]
"uhh nah" - @ryanfeeley
