### ISSUE TITLE
The context menu is displayed in a wrong position after moving the "Notes" sidebar to right / left

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#259]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403965

**[Affected versions]:**
- Firefox Notes 1.8.0 rc2
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Right click in the "Notes" sidebar.
3. Click on the "Notes" button from the sidebar.
4. Choose "Move sidebar to right / left" from the sidebar's dropdown menu.
5. Right click in the "Notes" sidebar and observe the context menu position.

**[Expected result]:**
- The context menu is displayed under the mouse cursor.

**[Actual result]:**
- The context menu is wrongly displayed in the other side of the screen.

**[Regression Window]:**
Last good revision: 392ed89ec2730a48d10b1cec741e86a242d28aa3
First bad revision: a625a2e9b3333a8e76982ea65f077cfded6ac224
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=392ed89ec2730a48d10b1cec741e86a242d28aa3&tochange=a625a2e9b3333a8e76982ea65f077cfded6ac224

**[Notes]:**
- If you move the sidebar back to the initial side the issue is no longer reproducible.
- The issue is no longer reproducible if you switch the sidebars.
- Attached a screen recording of the issue:
![context menu](https://user-images.githubusercontent.com/31243259/30974352-212c5b60-a478-11e7-8be2-da507a55f3e1.gif)

**Comment by johngruen** [comment]
Moving this to the current sprint pending investigation and escalating to higher priority in Photon

**Comment by Natim** [comment]
This bug is not reproducible with CKEditor and Nightly. Closing.

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible on the latest Firefox Release (57.0.4) and on the latest Nightly (59.0a1) build, with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.11.2018) installed. 
However to reproduce the issue, the context menu must be opened at least once before moving the sidebar. Considering this, I am reopening the issue.
Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34819802-6e655ea8-f6c7-11e7-8842-efec0a253d2c.gif)

**Comment by Natim** [comment]
Then we should definitely create a bugzilla issue about that. Thanks for reproducing.

**Comment by Softvision-MariusComan** [comment]
@Natim we have one created: https://bugzilla.mozilla.org/show_bug.cgi?id=1403965

**Comment by Natim** [comment]
Ok so I guess we can close this and follow its resolution in bugzilla?

**Comment by Softvision-MariusComan** [comment]
Yes, I think we could do that. Closing this issue in favor of the Bugzilla one.
