### ISSUE TITLE
Toolbar does not fit on small sidebar width 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#26]
![image](https://user-images.githubusercontent.com/128755/27093131-903a1464-5033-11e7-9bde-3dab84d5c86e.png)

**Comment by pdehaan** [comment]
Even worse, the Sync button scrolls out of view if the toolbar starts wrapping.

<img width="207" alt="mozilla_firefox_and_toolbar_does_not_fit_on_small_sidebar_width_ _issue__26_ _mozilla_notes" src="https://user-images.githubusercontent.com/557895/27207304-b1462ccc-51f2-11e7-8f76-a9f05e3887c9.png">
