### ISSUE TITLE
Some of the formatting options are reset if a tab is moved to a new window

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#261]
[Affected versions]:
- Firefox 55.0.3 and up
- Firefox Notes v1.8.0rc2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write something on the "Notes" editable area.
3. Select the written text and click on one of the following formatting options: Font Size, Bold, Italic or Strikethrough.
4. Open a new tab and right click on it.
5. Click on "Move to New Window" option.
6. Observe the "Notes" Sidebar from both windows.

[Expected result]:
- The text from the "Notes" Sidebar is correctly displayed alongside the format option chose at step 3 on both windows.

[Actual result]:
- The text from the "Notes" Sidebar is correctly displayed but the format option is reset on both windows.

[Notes]:
- Attached a screen recording of the issue:

![new window](https://user-images.githubusercontent.com/26000308/30975490-19d8c094-a47b-11e7-9b64-be9a05577fc4.gif)

**Comment by Natim** [comment]
Can you still reproduce with 2.0.0a2 and quilljs 1.3.3?

**Comment by SoftVision-CarmenFat** [comment]
Tested with Notes 2.0.0a2 and the issue is no longer reproducible.
