### ISSUE TITLE
There is no visible difference between 12px and 14px characters

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#263]
**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write a string using 12px characters and another one using 14px characters.
3. Compare the strings.

**[Expected result]:**
- There is a visible difference between the strings.

**[Actual result]:**
- The strings have the same height.

**[Notes]:**
- If you copy the string and paste elsewhere, the differences between the strings are visible.
- Also if you zoom in the "Notes" sidebar the difference becomes visible.
- Attached a screen recording of the issue:
![issue](https://user-images.githubusercontent.com/31243259/31011189-0ca55d92-a516-11e7-87c2-3e516b3568ed.gif)

**Comment by Natim** [comment]
They doesn't look to be the same size in the screencast.

**Comment by Softvision-MariusComan** [comment]
Maybe I was not very clear in the STR, however the differences between the strings can be seen only at specific zoom levels:

100% - No difference seen
110% - There is a difference
120% - There is a difference
130% - No difference seen
140% - There is a difference
150% - There is a difference
160% - There is a difference
170% - There is a difference
180% - There is a difference
190% - No difference seen
200% - There is a difference
210% - There is a difference
220% - No difference seen

**Comment by Natim** [comment]
Yes maybe they are not 12px and 14px but 13px and 14px, I will have to check that.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" version (1.8.0 rc3), retested on Windows 10 x64, Ubuntu 16.04 and Mac OS 10.12 on Firefox Release (56.0) and latest Nightly (58.0a1-20171005220204).
