### ISSUE TITLE
The mouse caret is wrongly moved when you left / right click under a word

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#266]
**[Affected versions]:**
- Firefox Notes 1.8.0dev
- Firefox 55 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write a string in the "Notes" sidebar.
3. Left / right click anywhere under a word and observe the mouse caret position.

**[Expected result]:**
- Mouse caret remains in the same position.

**[Actual result]:**
- The mouse caret is moved in the word, above the mouse cursor.

**[Notes]:**
- The issue is also reproducible with the TxP version of "Firefox Notes".
- If you right click under a misspelled word, the dictionary options are wrongly displayed in the context menu.
- Attached a screen recording of the issue:
![mouse caret](https://user-images.githubusercontent.com/31243259/31017716-26b3ee30-a532-11e7-97ff-0866fbcab307.gif)

**Comment by Natim** [comment]
Please file an upstream (Bugzilla/Firefox) bug for this one.

**Comment by Softvision-MariusComan** [comment]
Sure, [here it is](https://bugzilla.mozilla.org/show_bug.cgi?id=1405213).

**Comment by wresuolc** [comment]
@Natim please comment in the Firefox bug with details about what makes this a webextensions bug.  Thanks!

**Comment by Natim** [comment]
I don't think it is a webextension bug, but probably a Firefox bug on windows with contenteditable.

@Softvision-MariusComan can you try to load the page in a tab as Andy described to see if it is only happening in the Sidebar?

**Comment by Natim** [comment]
This bug is not reproducible with CKEditor anymore.
