### ISSUE TITLE
Text formatting set in "Notes" sidebar is not kept for pasted text or links

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#269]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc3).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Select the bold icon from the "Notes" sidebar.
3. Paste a text or a link.
4. Observe the behavior.

[Expected result]:
- The "Bold" style is applied for the pasted text or link.

[Actual result]:
- The "Bold" style is not applied for the pasted text or link.

[Notes]:
- This issue is reproducible for all text format options.
- Attached a screen recording of the issue:
![notes - formatting](https://user-images.githubusercontent.com/31244235/31075407-0806f060-a77e-11e7-8a48-6f26a28c5364.gif)

**Comment by wresuolc** [comment]
This is expected behavior (similar to many existing editors)

**Comment by Softvision-CristinaBadescu** [comment]
Yes, there are several text editors that have this behavior expected, but act in a different way. For example, in LibreOffice document text, the pasted text doesn't keep active the preexistent formatting, but if you type afterwards something, it respects the text style. In "Notes" this doesn't happen.

Moreover, there are well known text editors, for example in Google Docs, where the preexistent format is kept when pasting text or links. You can see the behavior here:  

![notes - pasting in gdoc](https://user-images.githubusercontent.com/31244235/31115085-95c37e2c-a829-11e7-934d-427341ca0a54.gif)
