### ISSUE TITLE
The newly entered letter/number key is wrongly linked if the previous hyperlink was selected

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#272]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc3).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a valid hyperlink (e.g. http://wikipedia.org).
3. Manually select the hyperlink.
4. Press any of the letters/numbers keys and see what happens next.

[Expected result]:
- The key entered is displayed as a plain text.

[Actual result]:
- The key entered is linked to the previously deleted hyperlink. 

[Notes]:
- This is not reproducible is "Ctrl"+"A" shortcut is used in order to perform the selection.
- Attached a screen recording of the issue:

![linkuit automat](https://user-images.githubusercontent.com/26000308/31077625-d8bf5022-a787-11e7-847e-75dcc4f78d27.gif)

**Comment by wresuolc** [comment]
Let's add Quill's URL modifying tool, but figure out how to adapt the style to our sidebar (eg. fit it in the top of our window, below the formatting toolbar).

**Comment by vladikoff** [comment]
cc @cedricium , can we bring back the Quill UI (the one that is hidden by CSS) and see if we can try fitting their Link modifying UI?

**Comment by cedricium** [comment]
@vladikoff @wresuolc will do 👍

**Comment by SoftVision-CarmenFat** [comment]
- Tested this with the latest Notes v.2.0.0a2 and is still reproducible.

- Also, I have another scenario that results in a much alike behavior as reported in the first comment:

STR:
1. Write a valid hyperlink (e.g. http://wikipedia.org).
2. Select all characters from the link, except the last one (e.g. case "g")
3. Press "Delete" key.
4. Observe and click on the remaining character.

- _Expected results_: The remaining character is unlinked.
- _Actual results_: The remaining character is linked and clicking it opens the previously deleted link in a new tab.

- Should I file another report for the issue described above?

**Comment by cedricium** [comment]
I think this was closed by accident, so just having this issue open should be okay.

@vladikoff @ryanfeeley is there a mockup in the works as far as how the link editing UI tooltip should look/fit in with Notes?

**Comment by cedricium** [comment]
Just brainstorming, but bringing back the link modifying tooltip may not be necessary. A `selection` matcher (https://quilljs.com/docs/api/#selection) could be added to capture when a link is highlighted and deleted, then we'd just have to set the `link` format to false for that given range.
