### ISSUE TITLE
"Space" key wrongly creates linked underline if pressed just before the hyperlink

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#273]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc3

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc3).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a valid hyperlink (e.g. http://wikipedia.org).
3. Click on the space right before the hyperlink.
4. Press "Space" key at least 3 times and see what happens next.

[Expected result]:
- The hyperlink is moved 3 spaces to the right.

[Actual result]:
- The hyperlink is moved 3 spaces to the right, but the first two spaces contain underline linked to the website.

[Notes]:
- The issue is not reproducible if plain text was previously written before the hyperlink.
- Attached a screen recording of the issue:

![underline](https://user-images.githubusercontent.com/26000308/31077880-dd636cc0-a788-11e7-8df1-c1756f873370.gif)

**Comment by vladikoff** [comment]
cc @cedricium @Natim

**Comment by SoftVision-CarmenFat** [comment]
- Tested this issue again and I can confirm it is not reproducible following the original steps to reproduce.
- However, a similar behavior is still reproducible when pressing "**Tab**" key twice, instead of "Space" key.

Tested with Firefox Notes RC5.

![again underline](https://user-images.githubusercontent.com/26000308/31282450-438bd200-aabb-11e7-8e86-e33d5685ba17.gif)

**Comment by cedricium** [comment]
@SoftVision-CarmenFat can you verify this when you get a chance, should be in the latest `master` branch.

**Comment by cedricium** [comment]
@Natim this can be closed as well.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with the latest Firefox Notes v.1.8.0dev (built today 10/23/2017), using both "Space" and "Tab" keys.
