### ISSUE TITLE
When you enlarge the sidebar too much the header border stops.

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#274]
![sidebar](https://user-images.githubusercontent.com/229453/31084709-74dd63b0-a795-11e7-898e-7f8297c7aaf1.png)

Reproducible on Linux with Nightly 58.0a1

**Comment by wresuolc** [comment]
I can't reproduce this on Nightly + Ubuntu.  Can you take a larger screenshot of the whole window?

**Comment by Natim** [comment]
![weird](https://user-images.githubusercontent.com/229453/31085397-48c94ff8-a797-11e7-842c-6940717679a9.png)
