### ISSUE TITLE
Plain text becomes linked if a hyperlink that is written just before the text is listed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#276]
[Affected versions]: 
- Firefox 56 and up
- Firefox Notes v1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0dev built on 10/3/2017).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write a string on Notes editing area.
3. Write a valid hyperlink just before the string written at step 2.
4. Click on Numbered List (or Bulleted List) button and observe what happens next.

[Expected result]:
- The hyperlink is displayed as a numbered (or bulleted) list alongside the plain text.

[Actual result]:
- The hyperlink is displayed as a numbered (or bulleted) list but the plain text also gets linked.

[Notes]:
- Attached a screen recording of the issue:

![text and hyperlink](https://user-images.githubusercontent.com/26000308/31132450-834862bc-a865-11e7-8500-18a5a50cea27.gif)

**Comment by Natim** [comment]
it is the same if you add a space at the end of tests, that's how the feature is implemented, everything part of the URL becomes an URL.

**Comment by johngruen** [comment]
Let's make `test` part of the URL as soon as the http:// is typed next to it

**Comment by Natim** [comment]
@cedricium could you have a look at it?
