### ISSUE TITLE
Add option to underline the text at the top panel

### ISSUE THREAD

**Issue by RMCoder198** [mozilla/notes#277]
Add option to underline the text at the top panel .
![mo](https://user-images.githubusercontent.com/26675957/31137317-83a1309a-a888-11e7-9d3b-9f6446f124f0.png)

I would like to work on this.

**Comment by johngruen** [comment]
@RMCoder198 we're going to sit tight on this right now b/c we're doing some refactoring of the toolbar UI this week. i'll keep you looped in to changes as warranted.

**Comment by vladikoff** [comment]
No plans to add the underline button, but shortcut works

Ref: https://mozilla.invisionapp.com/share/6VBUYHMRB#/screens/281041484_Firefox_Notes
