### ISSUE TITLE
Why notes should use google analytic?

### ISSUE THREAD

**Issue by dhra** [mozilla/notes#279]
Why notes should use google analytic? 
    Notes will collect information about your use of the feature, such as how often you create notes and how long you spend editing them, the number of characters you save in your notes, and whether you use any editing features (e.g., bold or stylized text).
    Notes will also collect information about your interaction with the add-on, such as how you access the feature, and what buttons you may click.

These are not interesting for me cause I'm care about my privacy but I want to use notes, any idea?

**Comment by Natim** [comment]
Yes you can activate the do not track feature and we won't send anything to Google Analytics.
