### ISSUE TITLE
Notes opens in New Window with its default size if previously closing the resized Sidebar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#282]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v1.8.0rc4

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc4).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click and drag the Sidebar's border to the maximum right.
3. Click on "X" button in order to close the sidebar.
4. Press "Ctrl"+"N".
5. Click de "Show Sidebars" button and observe the size of the Sidebar.

[Expected result]:
- The Sidebar from the new window has the size set by the user at step 2.

[Actual result]:
- The Sidebar has its default size.

[Notes]:
- This is also reproducible when resizing the Sidebar to the minimum.
- This is not reproducible if the resized Sidebar is not closed before opening a New Window.
- Attached a screen recording of the issue:

![close](https://user-images.githubusercontent.com/26000308/31277023-87ec9a24-aaa7-11e7-855a-9c679eaff9dc.gif)

**Comment by Natim** [comment]
Thank you for that, could you file an upstream BugZilla issue for it?

**Comment by SoftVision-CarmenFat** [comment]
Filed issue [1406367](https://bugzilla.mozilla.org/show_bug.cgi?id=1406367)

**Comment by Natim** [comment]
This bug is getting handled in the Bugzilla issue. I am closing it here.
