### ISSUE TITLE
When a string of multiple "Space" characters is pasted, only one will be displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#285]
**[Affected versions]:**
- Firefox Notes 1.8.0 rc5
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc4) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Write two characters with multiple "space" characters between them.
3. Copy the string from step 2.
4. Paste the string and observe it.

**[Expected result]:**
- The pasted string is the same as the copied one.

**[Actual result]:**
- Only one "space" character is displayed between the two other characters.

**[Notes]:**
- If at step 2 you copied a similar string from a different source instead of writing it, the issue is no longer reproducible.
- If you copy the string from step 2 and paste it to another text editor(e.g. the address bar, Google Docs, etc.) only one "space" character will be displayed between the other characters.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![space](https://user-images.githubusercontent.com/31243259/31283987-e21a0e24-aabf-11e7-905a-2416cd5455fd.gif)

**Comment by Natim** [comment]
Reproducible with QuillJS 1.3.3

Could you file an upstream QuillJS bug for it?

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
