### ISSUE TITLE
The first letter from a link is not hyperlinked when it is pasted in a Numbered/Bulleted list

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#286]
**[Affected versions]:**
- Firefox Notes 1.8.0 rc5
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc5) installed.
- Have a website link copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Numbered List" button.
3. Paste the link from the prerequisites and observe the link.

**[Expected result]:**
- The whole link is hyperlinked.

**[Actual result]:**
- The first letter from the pasted link in not hyperlinked.

**[Notes]:**
- The issue is also reproducible if at step 2 you press the "Bulleted List" button.
- Attached a screen recording of the issue:
![hyperlink](https://user-images.githubusercontent.com/31243259/31285988-7d753024-aac5-11e7-94e6-602c55ba48e5.gif)

**Comment by vladikoff** [comment]
🙀 💻

**Comment by Natim** [comment]
@cedricium could you have a look at it please?

**Comment by cedricium** [comment]
@Natim already have a fix in the works 👍

**Comment by cedricium** [comment]
@Softvision-MariusComan can you verify this when you get a chance, should be in the latest `master` branch.

**Comment by Natim** [comment]
If I understood correctly we should close it and they will validate if it is still reproducible or not :)

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.20.2017), retested on Windows 10 x64, Ubuntu 14.04 and Mac OS 10.12 on Firefox Release (56.0) and latest Nightly (58.0a1-20171020100426).
