### ISSUE TITLE
The "Save Link as" and "Save Link to Pocket" context menu options do not work

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#287]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429364

**[Notes]:**
- The issue is also reproducible on TxP version of "Notes", but only if the link is selected, because TxP version of "Notes" do not support hyperlinks. However in "Notes" 1.8.0 rc5 the issue becomes more obvious.

**[Affected versions]:**
- Firefox Notes 1.8.0 rc5
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc5) installed.
- Have a website link copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Paste the link from prerequisites to the "Notes" sidebar.
3. Right click the link.
4. Click the "Save Link as" context menu option and observe the behavior.

**[Expected result]:**
- The OS's specific dialog box is opened.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- The issue is also reproducible if at step 4 you click the "Save Link to Pocket" option.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31330332-a025e9f6-ace6-11e7-8755-dedb6da92450.gif)

**Comment by Natim** [comment]
Can you still reproduce this error?

**Comment by Natim** [comment]
I was able to reproduce this, it might be because the context menu detects it as a link while there is no link on it. We should definitely file a bug about that.

**Comment by Natim** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429364
