### ISSUE TITLE
Space between paragraphs is wrongly reset to 14 no matter of the text font size

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#288]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc6).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Clear all the text from the "Notes" sidebar.
3. Change the font size and write something.
4. Copy, press "Enter" key and paste the text.
5. Hit the "Enter" key, in order to create a paragraph.
6. Click inside the "Notes" sidebar.
7. Observe the behavior.

[Expected result]:
- The space between paragraphs corresponds to the font size.

[Actual result]:
- The space between paragraphs is wrongly set to default (14).

[Notes]:
- Here is a screen recording of the issue:
![notes - writing 3](https://user-images.githubusercontent.com/31244235/31331512-403cb70e-aceb-11e7-9398-a57c08ee7538.gif)

**Comment by Natim** [comment]
What happen if you type text? Is it back to 18?

**Comment by Natim** [comment]
Could you file the issue on https://github.com/quilljs/quill too?

**Comment by Softvision-CristinaBadescu** [comment]
@Natim even if you type text, the space between paragraph is still resetting to 14. Here is a screen recording with the behavior: 
![notes - writing test](https://user-images.githubusercontent.com/31244235/31332820-85a2d706-acf0-11e7-9696-f9cb7654638c.gif)

**Comment by Natim** [comment]
If mean the space is not styled but if you type text in it it will be correctly styled.

**Comment by Softvision-CristinaBadescu** [comment]
Yes, the text is correctly styled.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
