### ISSUE TITLE
The arrow next to the "Notes" text is slightly moved when the sidebar is resized

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#289]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0rc6

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0rc6).
- Have the "Notes" sidebar open.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Resize the sidebar and observe the position of the arrow next to the "Notes" text.

[Expected result]:
- The arrow position remains unchanged.

[Actual result]:
- The arrow is slightly moved.

[Notes]:
**On Mac 10.12.**:
- Using latest Nightly build 58.0a1 (10/08/2017) the same behavior can be observed for "Bookmarks", "Synced Tabs", and not for "History".
- Using latest Firefox release 56.0, the same behavior can be observed for "Bookmarks", "History"; and not for "Synced Tabs".

**On Windows 10 x64**:
- Using latest Nightly build 58.0a1 (10/08/2017) and Release 56.0 the same behavior can be observed for "Bookmarks"; and not for "History" and "Synced Tabs".

- Here is a screen recording of the issue:
![notes - resizing](https://user-images.githubusercontent.com/31244235/31338357-8a868d46-ad07-11e7-8b10-4762f8210d20.gif)

**Comment by Natim** [comment]
Can I let you file the bug upstream in Bugzilla?

**Comment by Softvision-CristinaBadescu** [comment]
Of course :) I've filed it [here.](https://bugzilla.mozilla.org/show_bug.cgi?id=1406930)

**Comment by Natim** [comment]
Thank you for filling this bug. I am going to close this bug as there is no much we can do about it here. Let's follow-up in the bugzilla issue.
