### ISSUE TITLE
Finish the Sync button design

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#29]
From meeting: Sync button is extremely missable

![image](https://user-images.githubusercontent.com/128755/27093378-6ed8d200-5034-11e7-8b02-27de0a8225d4.png)

**Comment by vladikoff** [comment]
Additional designs from new Synced Tabs bar: https://mozilla.invisionapp.com/share/42C41B58E#/screens

**Comment by Natim** [comment]
The current master looks like something correct to me for what we aims at for v1.
I am moving the next steps in the Syncing milestones.
