### ISSUE TITLE
The second typed listed number isn't listed automatically if previously was deleted

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#290]
[Affected versions]:
- Firefox Notes 1.8.0 rc6
- Firefox 56 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0 rc6) installed.

[Steps to reproduce]:
1. Open the browser with the profiles from prerequisites.
2. Click the "Numbered List" button and write a string.
3. Press "Enter" key and delete the "2." listed automatically.
4. Type "2." and press space.
5. Observe what happens next.

[Expected result]:
- The "2." string is automatically listed in the numbered list.

[Actual result]:
- The "2. " string is not listed.

[Notes]:
- The string is automatically numbered listed only if typing "1." instead of "2."
- Attached a screen recording of the issue:

![notes numbered list](https://user-images.githubusercontent.com/26000308/31341862-9336943e-ad13-11e7-9c79-ce3302e35ea8.gif)

**Comment by Natim** [comment]
Could you file this bug upstream at Quill?

**Comment by SoftVision-CarmenFat** [comment]
Sure, filed issue [#1749](https://github.com/quilljs/quill/issues/1749).

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
