### ISSUE TITLE
"Sync Your Notes" and "Feedback" buttons don't have any separator between them

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#296]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the "Sync your Notes" and "Feedback" buttons.

[Expected result]:
- Both buttons correctly display their surrounding borders.

[Actual result]:
- There is no border/separator between the 2 buttons. 

[Notes]:
- Attached a screen recording of the issue:

![separate](https://user-images.githubusercontent.com/26000308/31390234-0850e6ac-addc-11e7-9d30-153e76e8dde0.gif)

**Comment by Natim** [comment]
I believe this was fixed with #342

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with the latest Firefox Notes v.1.9.0dev (built today 10/31/2017).
