### ISSUE TITLE
"Opening Login..." message remains displayed after closing the "Sign in Account" window

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#299]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Sync Your Notes" button.
3. Close the newly opened window and observe the "Saved at (hour)" area.

[Expected result]:
- "Saved at (hour)" is displayed.

[Actual result]:
- "Opening Login..." string is displayed for a while.

[Notes]:
- The "Opening Login..." string is no longer displayed after editing text.
- Attached a screen recording of the issue: 

![opening login 1](https://user-images.githubusercontent.com/26000308/31394785-dc66ccf8-ade7-11e7-8cd5-b9b53e7a1a96.gif)

**Comment by Natim** [comment]
Yes only for a minute though

**Comment by Natim** [comment]
@vladikoff do we have a callback that we could listen to to know that the login windows has been closed?

**Comment by SoftVision-CarmenFat** [comment]
- The issue is no longer reproducible on the latest Firefox Notes v.1.8.0dev, built today 10/20/2017.
- "Opening Login..." string is shown for 6 seconds, followed by "Verify your account..." also shown for 6 seconds. After that, the "Saved at (hour)" string is displayed.
