### ISSUE TITLE
launchWebAuthFlow should open a tab rather than a popup

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#3]

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1305421#c8

**Comment by Natim** [comment]
@mixedpuppy in the bug you said:

> it should be a window.  Primarily because if there is any current or future api that would allow an addon to initiate oauth in a non-browser window[1], it would be fairly awkward to switch windows to do the oauth, then switch back.

It is exactly what currently happens with the current implementation of the Firefox Notes sidebar add-on.

It opens a new window, then it send an email where you need to click on a link to validate the login flow.
Then the click open a new tab with the sidebar on the side.

So you get a sidebar, a tab and a popup. You have to close the tab manually and then to wait for the popup to close itself eventually. It is really confusing.

For a sidebar add-on I wish we could start the login flow in a tab next to the sidebar which will make it much more intuitive IMO

Shane do you think you could have a look at the flow in https://github.com/Natim/notes and give me some advice of how we could improve things?

I send the message in the other bug, sorry about that it would be better to have the discussion here.

**Comment by vladikoff** [comment]
Closing for now, let's revisit this if users get really confused with the popup
