### ISSUE TITLE
string review on the onboarding string

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#30]
from meeting: @johngruen will send it to review

**Comment by Natim** [comment]
@johngruen Any news about that?

**Comment by Natim** [comment]
We should remove the story about the Android app.

**Comment by vladikoff** [comment]
Yeah this is the basic intro for now: https://github.com/mozilla/notes/blob/master/locales/en-US/notes.properties#L2

**Comment by vladikoff** [comment]
Yay!
