### ISSUE TITLE
"Editing" string is displayed for 2 seconds when opening Notes Sidebar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#300]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Show sidebars" buttons.
3. Observe the "Saved at (hour)" area.

[Expected result]:
- "Saved at (hour)" is displayed.

[Actual result]:
- "Editing" string is displayed for a couple of seconds.

[Notes]:
- This issue is also reproducible when switching Notes to the other Sidebars (Bookmarks, History, and Sync).
- Attached a screen recording of the issue:

![editing string](https://user-images.githubusercontent.com/26000308/31395715-18cf3e26-adea-11e7-8b22-8a48146ea7e6.gif)

**Comment by vladikoff** [comment]
Good find!

**Comment by SoftVision-CarmenFat** [comment]
Hi @Natim, 
	
Tested this with the latest Firefox Notes version 1.9.0dev (built today 10/31/2017) and this is what I noticed:
- "Saving changes..." is displayed instead of "Editing" string. Since I'm not doing any changes in the Sidebar, is this intended behavior?
- Must mention that the "Saving changes..." string doesn't appear if there is no text at all in the Notes Sidebar.
