### ISSUE TITLE
The text size becomes slightly larger when listing it

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#304]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type something in the editable area.
3. Press "Enter" key.
4. Repeat steps 2&3.
5. Select the text from first row.
6. Click on "Numbered List" (or "Bulleted") button and observe the text size.

[Expected result]:
- Text size remains the same.

[Actual result]:
- Text size is slightly larger.

[Notes]:
- Although the text size is visibly larger after clicking one of the Lists buttons, the size remains unchanged in the "Font Size" button.
- After deleting the List formatting option, the text shrinks to its previous size.
- Attached a screen recording of the issue:

![text size](https://user-images.githubusercontent.com/26000308/31438922-e482a0f0-ae92-11e7-876d-d56315d74857.gif)

**Comment by Natim** [comment]
This can be fixed with a CSS rule.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest "Firefox Notes"v.1.8.0 (built on 10/20/2017).
