### ISSUE TITLE
Notes hangs if continuously pasting a long string in the editing area

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#305]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type something on as many rows as possible.
3. Press "Ctrl"+"A" keys.
4. Press "Ctrl"+"C" keys.
5. Press "Ctrl"+"V" keys a few times and observe what happens next.

[Expected result]:
- Notes works as expected and the pasted strings are correctly displayed inside the editing area.

[Actual result]:
- Notes stops working and hangs.

[Notes]:
- On Windows, switching back to Notes Sidebar after the hang occurs, makes the editable area grey and useless. I also noticed that by disabling and re-enabling Notes when the hang occurs, the web extension is no longer displayed in the "Show Sidebars" button. Same behavior happens when removing and re-installing the web extension. Restarting the browser and re-installing the web extension afterward seems the only way Notes can function correctly.   
- On Linux and macOS, an "Unresponsive Script" dialog box is displayed:

![unresp ubuntu](https://user-images.githubusercontent.com/26000308/31440326-369b878a-ae98-11e7-8973-b70c04c16efe.png)

- It may take a while in order to recover and start working properly again (in my case, time varied between ~30 seconds and ~4 minutes).
- Here is the screen recording of the issue: 

![stress](https://user-images.githubusercontent.com/26000308/31440732-92484d92-ae99-11e7-996a-434dcbc20dde.gif)

**Comment by johngruen** [comment]
we could (a) chunk pasted text or (b) block long pastes
