### ISSUE TITLE
High values (3 or more digits) of the numbered list overlap the written strings

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#307]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v2.0.0a2).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Numbered List" button.
3. Type something then Press "Enter" key.
4. Repeat step 3 for 99 more times.
5. Observe the last numbered list.

[Expected result]:
- 100th number list correctly lists the written text.

[Actual result]:
- 100th number list overlaps the written text.

[Notes]:
- This is also reproducible using the Roman numeral (i, ii. iii etc).
- Attached a screenshot of the issue:

![numbers](https://user-images.githubusercontent.com/26000308/31445072-02bc1dae-aea6-11e7-82bc-7b15e3fd1fce.png)

**Comment by Natim** [comment]
This can be fixed with a great style padding.

**Comment by Natim** [comment]
I tried to fix that and it doesn't look trivial at all, I was also able to reproduce it in the quill.js playground.

**Comment by Natim** [comment]
Refs https://github.com/quilljs/quill/issues/1777

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with the latest Firefox Notes v.1.8.0dev (built today 10/23/2017).

![verif](https://user-images.githubusercontent.com/26000308/31893701-df87289c-b814-11e7-9560-a5b1d4ab71c2.png)
