### ISSUE TITLE
Disable right click mouse events in "Firefox Notes" toolbars

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#308]
**[Notes]:**
- If you click the "Save page as" option and after that you open the "htm" file, "Firefox Notes" will be displayed as a page.
- If you click the "View Page Info" option, the sidebar's "Page Info" dialog box is opened.
- The "View Background Image", "Select All" and "View page source" options from the context menu do not work at all.
- Considering the fact that the majority of the options are not working at all and the ones that are working correctly do not really help the user, in my opinion the right click mouse events should be disabled in the "Firefox Notes" toolbars.

**[Affected versions]:**
- Firefox Notes 2.0.0dev
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0dev) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Right click in the "Firefox Notes" toolbar and observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- A context menu is opened.

**[Notes]:**
- The issue is reproducible in both upper and the bottom toolbars.
- Attached a screen recording of the issue:
![right click](https://user-images.githubusercontent.com/31243259/31445779-7b12e3ea-aea7-11e7-9129-bae3da803a1a.gif)

**Comment by Natim** [comment]
I actyally agree: https://stackoverflow.com/a/737043/186202

**Comment by Natim** [comment]
Note that if we do that we remove spellchecker features.

**Comment by Softvision-MariusComan** [comment]
@Natim The bug was asking to remove right click mouse events only from the toolbars. 
Now, it seems that the right click mouse events are removed from the "Firefox Notes" body as well. This is not very good, because now we cannot access the "Undo", "Cut", "Copy" and "Paste" options that were in that context menu.

**Comment by Natim** [comment]
Oh I didn't noticed it was only for the toolbar :) I can revert that then.
