### ISSUE TITLE
The "Numbered List" is wrongly rearranged when removing an item from it

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#309]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v2.0.0a2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Notes build version (2.0.0a2) installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a website.
2. Create a "Numbered list" that contains several items.
3. Click on one item, select the "Numbered list" button and observe how the list is rearranged.

[Expected result]:
- The "Numbered list" is correctly rearranged.

[Actual result]:
- The "Numbered list" is rearranged by continuing the numbering of the items.

[Notes]:
- The issue is reproducible on QuillJS Playground, refs: [1758](https://github.com/quilljs/quill/issues/1758)
- Here is a screen recording of this issue:
![rearranging - notes](https://user-images.githubusercontent.com/31244235/31450393-f88e535e-aeb1-11e7-8cd5-c242c218df9d.gif)

**Comment by Natim** [comment]
How would you like it to work? Making Item2 part of Item1 ? I actually think this might be a working behaviour.

**Comment by Softvision-CristinaBadescu** [comment]
Hello @Natim,
I was thinking that after removing an item from the "Numbered list", the numbering will go on, without creating a new one from the start. You can see below the described behavior:
![ordering](https://user-images.githubusercontent.com/31244235/31535707-b5c84706-b004-11e7-8488-ee2e05cd6dce.gif)

**Comment by Softvision-CristinaBadescu** [comment]
In my opinion, I think this issue could be reopened as an enhancement since the described behavior from my previous comment is available in popular text editors such as Google Docs or LibreOffice document text. What do you say, @Natim?

**Comment by Natim** [comment]
I honestly have no opinion about that, I guess that's a product decision but I don't see note as a word processing tool but rather as a note taking tool so I don't see why you would use numbered list in that case?

**Comment by Softvision-CristinaBadescu** [comment]
I understand your point of view. I was suggesting to change it as an enhancement considering the familiarity of the users to this behavior for the mentioned text editors. I know "Notes" isn't necessarily designed as a text editor, but some users might perceived it this way.

Maybe we'll reconsider, in case users report this.
Thanks.
