### ISSUE TITLE
Edge Case: FullScreen view (OS X), when Enabling Sync the login window can get lost

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#31]
After V1

**Comment by Natim** [comment]
Refs https://github.com/mozilla/notes/issues/3

**Comment by Natim** [comment]
@vladikoff How do you want to play this? Should we plan on using a tab based flow instead?

**Comment by vladikoff** [comment]
@natim I think we should file a firefox bug for this

**Comment by vladikoff** [comment]
This works in OS X and FF 58, it opens the popup even though Firefox is maximized.
