### ISSUE TITLE
"Unable to connect" message is displayed when clicking the "Sync your Notes" button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#315]
**[Affected versions]:**
- Firefox Notes 2.0.0a3
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a3) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Sync your Notes" button in the "Notes" sidebar.
3. Observe the new opened window.

**[Expected result]:**
- The "Firefox Account" windows is correclty displayed.

**[Actual result]:**
- "Unable to connect" message is displayed in the new opened window.

**[Notes]:**
- Attached a screen recording of the issue:
![unable_to_connect](https://user-images.githubusercontent.com/20083658/31535647-7fde9bfe-b004-11e7-9f73-16feff786436.gif)

**Comment by Natim** [comment]
@rfk could you fix the oct10 stack or should we rollback to the previous stack?

**Comment by Natim** [comment]
Ok actually it has nothing to do with the deployment of the oct10 stack, apparently the lib FxARelier fallsback to that URL by default. I will be investigating.

**Comment by Natim** [comment]
Should be fixed in https://github.com/mozilla/notes/files/1382936/addon-2.0.0a4.zip

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible with Firefox Notes 2.0.0a4, tested on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64 with the latest Firefox Release(56,0) and Nightly(58.0a1-20171011220113).
