### ISSUE TITLE
Users can wrongly end up with two links in the same string after editing the first part of a link

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#320]
**[Affected versions]:**
- Firefox Notes 2.0.0dev
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0dev) installed.
- Copy the following string: https://google.com .

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Paste the string from the prerequisites in the "Firefox Notes" sidebar.
3. Replace "https://google" with "https://www.youtube".
4. Click the "https://www.youtube" part of the hyperlink and observe the behavior.
5. Click the ".com part" of the hyperlink and observe the behavior.

**[Expected result]:**
Step 5: "https://www.youtube.com" website is opened in a new tab.
Step 6. "https://www.youtube.com" website is opened in a new tab.

**[Actual result]:**
Step 5: "https://www.youtube" is opened in a new tab.
Step 6: "https://google.com" is opened in a new tab.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31554968-ef5a5ffc-b047-11e7-99b3-ef78c0b70292.gif)

**Comment by cedricium** [comment]
This relates to #272, but we can keep this open for tracking purposes.
