### ISSUE TITLE
Clarification Needed: what is the expected behavior when pasting text?

### ISSUE THREAD

**Issue by cedricium** [mozilla/notes#322]
I'm working on a solution for #271, which will give any pasted links the current formatting set. The solution works great if just a URL is being pasted, however, if there's some random text as well as a URL, then just the URL will get the active formatting. For example, say I copy the following:
```
http://bulma.io/

This is some random text blah blah. https://github.com/mozilla/notes/
More text.
```
and when I paste, say the `bold` and `italic` formats are active. The result will be:
![screen shot 2017-10-15 at 1 28 28 pm](https://user-images.githubusercontent.com/16343560/31588854-c72c638e-b1ac-11e7-803d-29cbaad0b5a1.png)

As you can see, only the URLs/links get the formatting, not the rest. The reason I ask for clarification is because it seems like #271 (currently open) and #269 (closed for 'expected behavior') contradict one another.

**Should all pasted text get the active formats or not (it seems wrong if just links do)?**

**Comment by Natim** [comment]
> Should all pasted text get the active formats

Yes I think so, @ryanfeeley @SoftVision-CarmenFat do you have an opinion on that?

**Comment by SoftVision-CarmenFat** [comment]
I agree with Natim, all the pasted text (+ links) should get the active formats.

**Comment by cedricium** [comment]
Got it, will make sure all text gets the active formats 👍
