### ISSUE TITLE
The sidebar is not reopened at browser restart if the "Firefox Notes" log in window is opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#324]
**[Notes]:**
- The issue is reproducible only at first install on a clean new profile.

**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Create a new Firefox profile.
- Have the "xpinstall.signatures.required" pref set to "false" in "about:config".
- Have the "extensions.legacy.enabled" pref set to "true" in "about:config".
- Do not restart, close or update the browser.

**[Steps to reproduce]:**
1. Focus the browser with the profile from prerequisites.
2. Install the latest "Firefox Notes" add-on version (2.0.0a4).
3. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
4. Restart the browser and observe the "Firefox Notes" sidebar behavior.

**[Expected result]:**
- The sidebar is displayed.

**[Actual result]:**
- The sidebar is not displayed.

**[Additional Notes]:**
- The issue is not reproducible on Mac.
- Attached a screen recording of the issue:
![notes sidebar](https://user-images.githubusercontent.com/31243259/31619431-2bd05142-b29d-11e7-8374-7af8c1934f26.gif)

**Comment by Natim** [comment]
I guess this is related to #325 too and the way Firefox reacts when one windows has the sidebar open and the other one have it closed. I am going to close it, feel free to file a bugzilla issue if you want.

If I understand correctly you would like the login windows to not be considered as a windows.
