### ISSUE TITLE
The sidebar is wrongly opened in the "Firefox Notes" sign in window if the browser is restarted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#325]
**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
3. Focus the first window, open a new window and restart the browser from the developer toolbar.
4. Focus the "Firefox Notes" sign in window and observe the displayed elements.

**[Expected result]:**
- Only the Login form is displayed.

**[Actual result]:**
- The "Firefox Notes" sidebar is also displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31653179-59378a32-b32a-11e7-9301-e315e4938b28.gif)

**Comment by Natim** [comment]
I am going to close this, feel free to create a Bugzilla issue if you want.
