### ISSUE TITLE
The "Disable Sync" option is still displayed in other windows after you log off

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#327]
**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.
- Have multiple windows opened.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Click the "Firefox Notes" menu from the bottom right part of the sidebar and select "Disable Sync" option.
3. Focus a different window and click the "Firefox Notes" menu button.
4. Observe the options.

**[Expected result]:**
- Only the "Give feedback" option is displayed.

**[Actual result]:**
- The "Disable Sync" option is also displayed.

**[Notes]:**
- If you have multiple windows opened and you log into Notes, the "Disable Sync" option will be automatically added in all opened windows.
- Attached a screen recording of the issue:
![disable sync](https://user-images.githubusercontent.com/31243259/31658195-11357424-b339-11e7-83bf-2b27f74382ac.gif)

**Comment by Natim** [comment]
Fixed with 28bfc11
