### ISSUE TITLE
Sync no longer works

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#328]
**[Notes]:**
- The sync option also no longer works on older "Firefox Notes" builds.

**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have two Firefox profiles with the latest "Firefox Notes" add-on version (2.0.0a4) installed.
- Have valid "Firefox Notes" credentials.

**[Steps to reproduce]:**
1. Open Firefox with the first profile from prerequisites.
2. Write something in the "Firefox Notes" sidebar.
3. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
4. Sign in with the credentials from prerequisites.
5. Open another instance of Firefox with the second profile from prerequisites.
6. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
7. Sign in with the credentials from prerequisites.
8. Compare the sidebars of the two browsers.

**[Expected result]:**
- The same content is displayed in both sidebars.

**[Actual result]:**
- In the second browser the placeholder text is displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![firefox notes sync](https://user-images.githubusercontent.com/31243259/31665684-5fb934f0-b352-11e7-88e7-950eec64ddb4.gif)

**Comment by Natim** [comment]
I guess this is because we use kinto.dev which is flush everynight and the current kinto.js code doesn't handle server flushed.
