### ISSUE TITLE
Share kinto backend URL between background.js and sidebar/panel.js?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/notes#33]
🔍 https://github.com/mozilla/notes/search?utf8=%E2%9C%93&q=kinto.dev&type=

Both [/src/background.js:1](https://github.com/mozilla/notes/blob/0a6ae033885de91c90d23da449f3b45f6ebbb84f/src/background.js#L1) and [/src/sidebar/panel.js:1](https://github.com/mozilla/notes/blob/0a6ae033885de91c90d23da449f3b45f6ebbb84f/src/sidebar/panel.js#L1) hardcode a Kinto URL endpoint, https://kinto.dev.mozaws.net/v1. We should see if we can share that endpoint value somehow so we don't forget to change a value in one of the files.

**Comment by vladikoff** [comment]
Thanks @pdehaan !

**Comment by Natim** [comment]
Shall we bring webpack to the mix to be able to have a CONSTANTS.js file imported in both `panel.js` and `background.js` ?

**Comment by vladikoff** [comment]
> Shall we bring webpack

Not sure, I'd rather not add webpack for now, extra complexity. I think one of the scripts should just message the other what the url is. maybe there is a simpler way

**Comment by Natim** [comment]
After thinking a bit more about this, I think we should do all Kinto calls in the background using a similar strategy to the one we used for metrics.

**Comment by Natim** [comment]
Fixed in #241
