### ISSUE TITLE
The content area from "Firefox Notes" sidebar does not gain focus when it is opened or switched

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#330]
**[Notes]:**
- When the Bookmarks or History sidebars are opened, their search bar is automatically focused.

**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.
- The sidebar is closed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Press alt+shift+w.
3. Write a string and observe the behavior.

**[Expected result]:**
- The string is written in the "Firefox Notes" sidebar.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- This issue is also reproducible when you switch from a the Bookmarks/History sidebar to the "Firefox Notes" one.
- Attached a screen recording of the issue:
![focus notes](https://user-images.githubusercontent.com/31243259/31707501-32907972-b3f5-11e7-940d-f5bab89ab049.gif)

**Comment by Softvision-MariusComan** [comment]
The issue is still reproducible on Windows 10 x64, Ubuntu 14.04 x64 and Mac 10.12, with latest Firefox release (57.0) and latest Nightly build (59.0a1) installed, using the latest master build.
It is also reproducible on 1.9.0b1 build with CKeditor

**Comment by Natim** [comment]
See https://stackoverflow.com/a/8699731/186202

**Comment by vladikoff** [comment]
@Natim I guess this never worked, not even in Quill. Firefox probably cannot focus on that sidebar?

**Comment by vladikoff** [comment]
Why did this close ? hmm

**Comment by johngruen** [comment]
Closing b/c we open into list view now

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 07/18/2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
