### ISSUE TITLE
An artefact is wrongly displayed in the top left corner of the toolbar, after pasting specific content from Wikipedia

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#331]
**[Affected versions]:**
- Firefox Notes 2.0.0a4
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.
- [Reduced test case](https://github.com/mozilla/notes/files/1394160/Wikipedia.zip).

**[Steps to reproduce]:**
1. Open the webpage from the attachment with the profile from prerequisites.
2. Select the text in both sections by dragging the mouse across them.
3. Copy the selection and paste it in the Notes Sidebar.
4. Observe the top toolbar of the Sidebar.

**[Expected result]:**
- Only the formatting options are displayed.

**[Actual result]:**
- An artefact is also displayed in the top left corner of the toolbar.

**[Notes]:**
- The issue is not reproducible if you you select all the content by pressing "Ctrl+A" or from the context menu.
- The issue was originally found on https://en.wikipedia.org/wiki/Main_Page.
- Attached a screen recording of the issue:
![notes artefact](https://user-images.githubusercontent.com/31243259/31712148-e6ced0ca-b402-11e7-8b2a-fb42497429f3.gif)

**Comment by Natim** [comment]
Does it disappear if you reopen the sidebar?

**Comment by Softvision-MariusComan** [comment]
Yes, if I reopen the sidebar then the artefact disappears.

**Comment by Natim** [comment]
It seems to be button to handle adding rows or lines to a table.

**Comment by johngruen** [comment]
🤷‍♂️🤷‍♂️

**Comment by vladikoff** [comment]
This was an issue with Quill it seems, should be fixed
