### ISSUE TITLE
The "Firefox Notes" menu button is not white on Dark Theme

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#333]
**[Notes]:**
- The issue is reproducible only on the "sync" branch of "Firefox Notes" 2.0.0a4 build.

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0a4) installed.
- Set the "Firefox Notes" theme to Dark in about:addons.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Observe the "Firefox Notes" menu button color.

**[Expected result]:**
- The color is white.

**[Actual result]:**
- The color is black.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![notes menu button](https://user-images.githubusercontent.com/31243259/31727459-45c2e402-b432-11e7-8b8f-37d26bca4c8a.png)

**Comment by cedricium** [comment]
This is a simple fix, just need to create the dark-styled `three-dots.svg` (as found here: https://github.com/mozilla/notes/blob/sync-v4/src/sidebar/styles.css#L189) and apply it to the `styles-dark.css`. I'll go ahead and fix this.

**Comment by Natim** [comment]
Fixed with #334
