### ISSUE TITLE
Investigate using another editor than Quill.JS

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#338]
We have a bunch of Quill.JS bugs.

@johngruen suggested to try https://ckeditor.com/ckeditor-5-builds/ and see if we have less bug with it that we have with Quill.JS

**Comment by vladikoff** [comment]
@cedricium if you have time see if you can prototype the swap of Quill with ckeditor 5. Let me know, feel free to pull request a prototype branch! One different thing we noticed was that ckeditor only has "headings" and not font-sizes. Might need to investigate that

**Comment by cedricium** [comment]
Have a branch setup for this:  [`cedricium/notes:ckeditor-concept`](https://github.com/cedricium/notes/tree/ckeditor-concept)

Currently working on getting all of the saving and syncing of editor contents setup locally as well as analytics working properly. Will open a PR for this prototype once that's finished.

**Comment by vladikoff** [comment]
Opened https://github.com/mozilla/notes/pull/382 just so we can see the changes, awesome work, trying it now..

**Comment by vladikoff** [comment]
Done! Thanks again @cedricium for the first prototype of this :)
