### ISSUE TITLE
The links are not actionable after approximately 10 minutes of inactivity

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#339]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes 1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (1.8.0dev version) installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Paste or write some links in the "Notes" sidebar.
3. For at least 10 minutes leave the browser inactive.
4. Come back to the browser and observe the displayed links.

[Expected result]:
- The links are hyperlinked.

[Actual result]:
- The links are not actionable.

[Notes]:
- Here is a screen shot of the issue:
![links](https://user-images.githubusercontent.com/31244235/31827160-cba773a6-b5bf-11e7-9dbf-d975ca3fd441.png)

**Comment by cedricium** [comment]
Interesting 😕, will definitely look into this. Good find!

**Comment by cedricium** [comment]
@Softvision-CristinaBadescu was this tested using `master` branch? I was not able to reproduce.

**Comment by Softvision-CristinaBadescu** [comment]
Hello @cedricium ,

When I filed the issue, the build I've used was created in the Friday morning by cloning the master branch from Notes repository.

I can confirm that I was able to reproduce again this issue, on latest Nightly build 58.0a1(2017-10-22), on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64, using Firefox Notes 1.8.0dev version (this build was also created by cloning the master branch from Notes repository).

Can you please take another look?

**Comment by cedricium** [comment]
Interesting! I noticed it looks like the entire sidebar refreshes, then when it comes back up the link formatting gets dropped.

cc: @Natim @vladikoff know why the sidebar might refresh like that? In the above video, the refresh occurs around 3:09.

**Comment by Natim** [comment]
It might be due to the `npm run start` process refreshing and failing because it looks like to when from the master version to the last released one.

**Comment by Natim** [comment]
According to #351 it might even be because TestPilot updates from 1.8.0dev to 1.8.0

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm this issue is no longer reproducible using Firefox Notes 1.9.0dev version, on latest Nightly build 58.0a1 (2017-10-25), on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
