### ISSUE TITLE
Ensure POSTs have a size limit and a request rate limit

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#34]
I think these can be set in nginx, so I'm ccing @jasonthomas 

I don't have recommendations for values here.

**Comment by wresuolc** [comment]
sigh.  https://github.com/mozilla/speaktome/issues/8

**Comment by jasonthomas** [comment]
Yes we can configure these via nginx. client_max_body_size in nginx defaults 1MB and seems like a sane value? We could also potentially rate limit by kinto bucket assuming each user has a unique bucket.  /cc @Natim for opinions.
