### ISSUE TITLE
Hyperlinks format options are canceled when choosing the numbered (or bulleted) list options if plain text was previously typed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#343]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.8.0dev version

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes version (v1.8.0dev).

[Steps to reproduce]
1. Have the "Notes" sidebar open with some text in it.
2. Change the font size, select any formatting options and click on "Numbered listed" icon.
3. Type or paste a couple of links.
4. From the link list click on one row.
5. Click on "Numbered list" icon and observe the behavior.

[Expected result]:
- The clicked row from the "Numbered list" keeps the active text formatting.

[Actual results]
- The clicked row from the "Numbered list" is not keeping the active text formatting.

[Notes]:
- This issue is not reproducible when having more than one Hyperlinks selected.
- Attached a screen recording of the issue:
![notes - numbered list - simple](https://user-images.githubusercontent.com/31244235/31830195-228fbdf6-b5c8-11e7-9c5b-d47caa140f6d.gif)

**Comment by cedricium** [comment]
Same principal issue as described here: https://github.com/mozilla/notes/issues/271#issuecomment-338247010

It involves the way the HTML elements are created or deleted when applying formats.
