### ISSUE TITLE
Extra rows are wrongly pasted when certain content is copied

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#345]
**[Notes]:**
- The issue is reproducible on the following websites:
		- https://www.youtube.com/
		- https://www.amazon.com/
		- https://9gag.com/

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.23.2017) installed.
- Change the "Youtube" location to any country other than US.
- "Youtube" material design is enabled (https://www.youtube.com/new).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to https://www.youtube.com/.
2. Drag the mouse from the "Youtube" logo to the two letter country code.
3. Copy the selected string using the "Ctrl+C" shortcut or from the context menu.
4. Paste the string from step 3 in the "Firefox Notes" sidebar and observe the pasted content.

**[Expected result]:**
- Only the copied string is pasted.

**[Actual result]:**
- The copied string is pasted together with another twenty one extra rows.

**[Additional Notes]:**
- The issue is also reproducible if you copy the "Trending" string from the "Youtube" page.
- On the old "Youtube" UI, only one extra row is pasted.
- The issue is not reproducible with the "Firefox Notes" version from TxP.
- The issue is not reproducible if you paste the content in "Google Docs" or "Libre Office".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/31942018-97d5aec0-b8cc-11e7-90a7-587e660c5013.gif)

**Comment by Natim** [comment]
@cedricium do you know if this can be related to the text-change events that we handle for links?

**Comment by cedricium** [comment]
@Natim looks like because the entire YT logo is being highlighted (not just the country code text), the contents of the clipboard has included the anchor tag from the logo itself. Yes this is related to the text-change events, most certainly the `quill.clipboard.addMatcher(Node.TEXT_NODE, function(node, delta)` function.

This is somewhat reproducible on quilljs.com (just not as many lines):

![screen shot 2017-10-26 at 9 13 13 am](https://user-images.githubusercontent.com/16343560/32064147-ec68e1fc-ba2d-11e7-9c84-2e3d0ed49c2c.png)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 07/18/2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
