### ISSUE TITLE
Last notation is kept after deleting a multilevel list

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#346]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes v.1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.24.2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Numbered List" button
3. Type something and press "Enter" key.
4. Press "Tab" key and type something.
5. Press "Ctrl"+"A" keys.
6. Press "Delete" key (or "Backspace") and observe what happens next.

[Expected result]:
- The multilevel list is deleted and the first list number is kept.

[Actual result]:
- After deleting the multilevel list, the last notation replaces the first number.

[Notes]:
- This issue is not reproducible on Quill Playground and Google doc;
- The issue is not reproducible using Firefox Notes v.2.0.0a4.
- The issue is reproducible when listing with both Roman numerals and alphabetical.
- Please see the following screencast with the difference between Notes and Quill: 

![notes vs quill](https://user-images.githubusercontent.com/26000308/31948367-6c94bdf6-b8df-11e7-875b-5e48eaf80570.gif)

**Comment by vladikoff** [comment]
@SoftVision-CarmenFat are you able to reproduce this on https://ckeditor5.github.io/ ?

**Comment by Softvision-RemusDranca** [comment]
Following the issue, in the last version of Notes (Firefox_notes-4.2.0dev from 19.06.2018),  instead of the expected result now both notations are deleted.
