### ISSUE TITLE
The bullet is wrongly placed if the selected text is on 2 rows

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#347]
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.24.2017) installed.
- Have a sentence of minimum two rows in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select the string from the prerequisites.
3. Click the "Bulleted List" button and observe the bullet position.

**[Expected result]:**
- The bullet is displayed inline with the first row.

**[Actual result]:**
- The bullet is placed at the beginning of the last row.

**[Notes]:**
- The issue is also reproducible if at step 3 you press the "Numbered list" button.
- The issue in not reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![bullet](https://user-images.githubusercontent.com/31243259/31948624-10c853a6-b8e0-11e7-9c8f-520c7373f0c3.gif)

**Comment by Natim** [comment]
i wonder why, I wasn't able to reproduce with the Quill.js playground

**Comment by johngruen** [comment]
We think this is related to the links feature.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.
