### ISSUE TITLE
When pasting a paragraph inutile spaces appear

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#348]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v.1.8.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v.1.8.0dev .

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Paste a paragraph in the "Notes" sidebar and observe its appearance.

[Expected result]:
- The pasted paragraph is compacted and correctly displayed.

[Actual result]:
- The pasted paragraph has inutile spaces in it and is not compacted.

[Notes]:
- Here is a screen recording of the issue:
![inutile spaces 2](https://user-images.githubusercontent.com/31244235/31989417-e2fea2c2-b97a-11e7-86d3-d473d1c8ecdd.gif)
- Here is a screenshot of the issue:
![space in pasted paragraph](https://user-images.githubusercontent.com/31244235/31989427-e97c15c6-b97a-11e7-92f6-d3bb1da1d872.png)

**Comment by Softvision-CristinaBadescu** [comment]
I assume this issue may also affect the active text formatting options when pasting a paragraph. I have changed the size font and select some text formatting options (Bold, Italic, Strikethrough) and observed the pasted paragraph. 

You can see the behavior below:
![formatting with inutile spaces](https://user-images.githubusercontent.com/31244235/32002167-76363e96-b9a4-11e7-8bbd-3c2e20728edf.gif)

**Comment by Natim** [comment]
I wonder why, I wasn't able to reproduce it in the QuillJS playground.

**Comment by Natim** [comment]
It seems to be somehow related to the sidebar CSS max-size 😱 .

**Comment by Softvision-CristinaBadescu** [comment]
During testing I've observed that this issue is not reproducible when pasting a paragraph from Chrome.

**Comment by Natim** [comment]
Thank you for this information, maybe it is actually a Firefox bug then.

**Comment by Softvision-CristinaBadescu** [comment]
It could be, but wouldn't the fact that the issue is not reproducible on QuillJS playground disprove this theory?

**Comment by johngruen** [comment]
putting this in sprint, but mostly as a reminder to investigate a bit further.

**Comment by Natim** [comment]
I believe this is fixed.

**Comment by Softvision-CristinaBadescu** [comment]
Indeed, this issue is no longer reproducible using Firefox Notes [v2.2.0rc5](https://github.com/mozilla/notes/pull/619#issuecomment-362590630), or Firefox Notes v2.2.0dev (custom build 2018-02-05, on latest Nightly build 60.0a1 (2018-02-04), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
