### ISSUE TITLE
Pressing Enter at the beginning of a row does not move content to a new row

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#350]
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.25.2017) installed.
- Write a sentence of minimum two rows in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the caret at the beginning of the second row.
3. Press the "Enter" key and observe the behavior.

**[Expected result]:**
- Content is moved to a new row.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is also reproducible with the "Firefox Notes" version from TxP.
- If at step 3 you press the "Enter" key twice, then the sentence moves to a new row.
- If at step 2 you click at the beginning of the first row the issue is no longer reproducible.
- Attached a screen recording of the issue:
![enter](https://user-images.githubusercontent.com/31243259/31996320-cbdaf77e-b990-11e7-8a98-48e90a50a341.gif)

**Comment by Natim** [comment]
I don't think this is a bug that's the way HTML works. If you press enter twice you will have a new row plus an empty line.

This is because we are still on the same line even if it looks like two rows.
