### ISSUE TITLE
The text caret is wrongly moved at the end of the previous row when the "Space" key is pressed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#352]
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.25.2017) installed.
- Have a sentence of minimum two rows in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the caret at the beginning of the second row.
3. Press the "Space" key and observe the behavior.

**[Expected result]:**
- A blank space is inserted.

**[Actual result]:**
- The text caret is moved at the end of the previous row.

**[Notes]:**
- The issue is also reproducible with the "Firefox Notes" version from TxP.
- The issue is not reproducible if at step 2 you move the caret at the beginning of the first row.
- Attached a screen recording of the issue:
![space issue](https://user-images.githubusercontent.com/31243259/31998781-ab6c98e0-b999-11e7-93f8-43397706e5a7.gif)

**Comment by Natim** [comment]
I don't think this is a bug, it is the way HTML works. If you had multiple spaces then they will eventually switch to the next line.
