### ISSUE TITLE
Changing the way of listing more than 200 items takes too much time

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#354]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes 1.9.0dev
- Firefox Notes 2.0.0a5

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom build from 10.25.2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on "Numbered List" button.
3. Type something then press "Enter" key.
4. Repeat step 3 for 200 more times.
5. Press on "Ctrl"+"A" keys.
6. Click on the "Bulleted List" button and observe what happens next.

[Expected result]:
- The notations change into bullets within a reasonable amount of time. 

_[e.g. For a list that has 100 items, the change is made in ~ 2 seconds;
For a list that has 150 items, the change is made in ~4 seconds]_

[Actual result]:
- It takes ~14 seconds in order to change the notations into bullets.

[Notes]:
- I noticed that if the user closes and reopens Notes during the changing process, the sidebar becomes grey and useless for a few seconds. After that, the original content is restored, without making the change.
- Attached a screen recording of the issue:

![hang changing lists](https://user-images.githubusercontent.com/26000308/32007443-36c1a88c-b9b2-11e7-901c-7d668fcb0fbe.gif)

**Comment by Natim** [comment]
This is related to heavy edits and I am wondering if the text-change event is trigger for all of them. In that case we should debounce saving locally.

**Comment by Natim** [comment]
Could you file a QuillJS bug for that?

**Comment by SoftVision-CarmenFat** [comment]
Sure, files issue [#1792](https://github.com/quilljs/quill/issues/1792)

**Comment by SoftVision-EmilPasca** [comment]
This issue is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.

**Comment by Softvision-MariusComan** [comment]
The behavior of this issue has changed. Now its enough to change the way of listing for about 40 items and the Notes sidebar freezes for ~ 4 seconds.
Also if you choose to paste a list of ~ 40 items, then the sidebar freezes again.

**Comment by vladikoff** [comment]
@Mgsy if you have time could you check this behaviour in ckeditor alpha 2 vs latest?

**Comment by Mgsy** [comment]
@vladikoff, I've checked both versions (alpha 2 and the latest master) and indeed, the browser freezes for a while, but it's not ~14 seconds. It takes around 4 seconds, but that's a lot of data, so it might be understandable. Here is my screencast with ~280 list items:

![bug_ckeditor5](https://user-images.githubusercontent.com/20988892/36965392-d2e45814-2059-11e8-934e-636def6798f2.gif)
