### ISSUE TITLE
When opening the sidebar, the sync is triggered with the wrong design

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#357]
![out ogv](https://user-images.githubusercontent.com/229453/32048255-395c3a34-ba49-11e7-81e5-a8c57e29a6c1.gif)

**Comment by sebastienbarbier** [comment]
@Natim Can't find a dedicated event on load between authenticate and text-synced ... might need your help on this one.

**Comment by Natim** [comment]
I guess you need to detect if the user has got credentials before running kinto-load event?

**Comment by Natim** [comment]
It would probably be good enought to run getLastSyncedStatus at startup.
