### ISSUE TITLE
The "Centered" or "Right" alignment is wrongly kept when pasting a text in "Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#361]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.9.0dev

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v1.9.0dev.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Have some text with a "Centered" or "Right" alignment and paste it in the "Notes" sidebar.
3. Observe the behavior.

[Expected result]:
- The text is pasted without keeping the active alignment.

[Actual result]:
- The text is pasted keeping the active alignment.

[Notes]:
- This issue is only reproducible when pasting aligned text from text editors such as LibreOffice Writer.
- This issue is also reproducible with "Right" alignment.
- Here is a screen recording of the issue:
![alignment 2](https://user-images.githubusercontent.com/31244235/32058197-124017e4-ba72-11e7-9288-58b25470c90d.gif)

**Comment by Natim** [comment]
@cedricium do you know if we could use removeFormat on pasted content? I tried to add some code about that to your clipboard handler but I don't know how to convert the delta in index and length.

**Comment by cedricium** [comment]
@Natim I've been trying to find a solution but the only way I can get it to work is to set all of the formatting options to `false`. It's by no means elegant and I'm sure there's a better way, I just can't figure it out this morning :/

See this example codepen: https://codepen.io/anon/pen/JOPqrR?editors=0010

**Comment by vladikoff** [comment]
This should be fixed in `master` with CKEditor

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest version of Notes 1.9.0dev (custom build 2017-11-23), on latest Nightly build 59.0a1 (2017-11-23) and latest Firefox Release 57.0, on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
