### ISSUE TITLE
The text is bolded when copy and pasting it from gdoc to notes if using different browsers

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#362]
[Affected versions]:
- Firefox 56.0 and up
- Firefox Notes 1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom build from 10.26.2017) installed.
- Have several Gdocs opened in different browsers (Chrome, Opera, Edge, Chromium, Safari).

[Steps to reproduce]:
1. Open a Gdoc that has some text using one of the browsers mentioned in the prerequisites.
2. Press "Ctrl"+"A" keys to select text from the Gdoc.
3. Press "Ctrl"+"C" keys.
4. Go to Firefox and focus Notes Sidebar.
5. Press "Ctrl"+"V" keys and observe the pasted text.

[Expected result]:
- The pasted text is not formatted in any way.

[Actual result]:
- The pasted text is bolded.

[Notes]:
- The issue is also reproducible with links.
- The issue is also reproducible on Quill.
- This issue is not reproducible when using Firefox.
- Attached a screen recording of the issue:

![paste diff browsers](https://user-images.githubusercontent.com/26000308/32062494-58e5d804-ba7d-11e7-8874-3c39fd883f90.gif)

**Comment by vladikoff** [comment]
This should be fixed in the master branch with ckeditor
