### ISSUE TITLE
Improve footer usability

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#367]
I appreciate your patience here gang, this is a tough one to get right.

I have already updated Firefox Notes with changes proposed in this mockup.

![hover111](https://user-images.githubusercontent.com/68213/32184387-778454f0-bd72-11e7-990d-45f028da8de1.gif)

Ideally most users are in this state most of the time.

Proposed improvements:
* Cursor should switch to pointer over clickable area
* Entire footer triggers manual sync
* The 3-dot menu only has background colour on click (mockup is wrong in this respect)
* Sync icon turns blue on hover
* Sync icon turns blue while syncing, copy in grey reads "Syncing changes…" (not shown)
* When the user is syncing, the footer should only ever show
  * Rotating blue sync icon
  * Synced {timestamp} (in dark grey)
  * or
  * Syncing changes… (in light grey)
* Not shown, but the "Sync to user@example.com" tooltip should still be there if the cursor hovers still

**Comment by Natim** [comment]
I believe this is now implemented 🙌
