### ISSUE TITLE
Text caret is wrongly moved at the beginning of a link after it is pasted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#376]
**[Notes]:**
- The issue is reproducible only if you copy the link from the "Firefox Notes" sidebar.

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.31.2017) installed.
- Have a link in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the text caret at the end of the link and press the "Space" key.
3. Copy the link from step 2 (blank space included) and delete all the sidebar's content.
4. Paste the link and observe the text caret behavior.

**[Expected result]:**
- The text caret is displayed at the end of the link, after the blank space.

**[Actual result]:**
- The text caret is displayed in the front of the link.

**[Additional Notes]:**
- The issue is not reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32228734-c35795b4-be57-11e7-9cb1-1bcf2e7d4e62.gif)

**Comment by Natim** [comment]
This doesn't seems to be the case with the current version of Notes.
