### ISSUE TITLE
The first letter of a link is not pasted together with the link

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#377]
**[Notes]:**
- The issue is reproducible only if there is a "blank space" character after the link.
- The issue is not reproducible if you copy an anchor link.
- The issue is not reproducible if you copy the link from the "Firefox Notes" sidebar (see bug https://github.com/mozilla/notes/issues/376).

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.8.0dev custom build from 10.31.2017) installed.
- Have the following link: "https://www.youtube.com/ " (blank space included) copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste the link from the prerequisites in the sidebar and observe the behavior.

**[Expected result]:**
- The link from the prerequisites is pasted and the text caret is displayed at the end of the link.

**[Actual result]:**
- The first letter is missing from the pasted link and the text caret is displayed on the next row.

**[Additional Notes]:**
- The issue is not reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32233626-7f1914d4-be63-11e7-9449-08513e06fc04.gif)

**Comment by Natim** [comment]
Currently we don't have links support yet/anymore
