### ISSUE TITLE
The active text formatting is wrongly kept only for the last pasted link

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#383]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v1.9.0dev .
- Have a link copied to your clipboard.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write something in "Notes" sidebar, without formatting.
3. Paste the copied link, select it and attribute it any text formatting option (Size, Bold, Italic, Strikethrough).
4. Paste again the link and observe the behavior.

[Expected result]:
- Both pasted links keep the active text formatting options.

[Actual result]:
- Only the second pasted link keeps the active text formatting options.

[Notes]:
- This issue is only reproducible when you have some text written in the "Notes" sidebar.
- If you paste the text, select a formatting option and press "Space" key, you'll encounter this issue: https://github.com/mozilla/notes/issues/271#issuecomment-338210997 (see Scenario 2).
- Here is a screen recording of the issue:
![active text formatting for links](https://user-images.githubusercontent.com/31244235/32381085-838698c6-c0ba-11e7-9629-220589387b71.gif)

**Comment by Natim** [comment]
Closing since we don't have links support currently.
