### ISSUE TITLE
After pasting or cutting a text, the "Undo" option from the context menu doesn't work 

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#384]
[Affected versions]:
- Firefox 56 and up
- Firefox Notes v1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v1.9.0dev.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write something in the "Notes" sidebar.
3. Copy and paste the text.
4. Right click on the editable area and choose the "Undo" option.
5. Observe the behavior.

[Expected result]:
- The pasted text is removed.

[Actual result]:
- Nothing happens.

[Notes]:
- Here is a screen recording of the issue:
![undo option context menu](https://user-images.githubusercontent.com/31244235/32382145-33fe8edc-c0bd-11e7-9550-d915e9ac21cd.gif)

**Comment by Softvision-CristinaBadescu** [comment]
I've also managed to reproduce this with the "Cut" option using "Firefox Notes" v1.9.0b2, on Windows 10 x64, Mac 10.12 and Arch Linux 4.12:

[Notes]
- This issue is not reproducible if you use "Ctrl+Z" keys combination.

[Affected versions]
- Firefox 57 and up

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Have a written text in "Notes" sidebar.

[Steps to reproduce]
1. Open the browser with the profile from prerequisites.
2. Cut the written text in the "Notes" sidebar.
3. Right click and choose "Undo" option from the context menu.


[Expected result]
- The previously cut text reappears in the "Notes" sidebar.

[Actual result]
- Nothing happens.

[Additional notes]
- Here is a screen recording of the issue:
![undo inactive for cut action](https://user-images.githubusercontent.com/31244235/33073945-1f0dddca-cecd-11e7-8b33-141e777ffb16.gif)

**Comment by vladikoff** [comment]
I think we can fix this by adding the Undo/Redo modules. Good find!

**Comment by Natim** [comment]
Refs #472  #260 #114

**Comment by Natim** [comment]
Also related to the beforeinput event implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=970802
