### ISSUE TITLE
Text size is not changed to 14, if the sidebar contains paragraphs of different sizes including 14

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#386]
**[Notes]:**
- The issue is reproducible only if you select the 14 font size value.
- The issue is not reproducible if the content does not contain a string of 14 font size value.

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom build from 11.06.2017) installed.
- Have content with multiple text sizes, including the default 14 value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and press "Ctrl+A".
3. Click the "Font Size" button.
4. Click 14 and observe the content.

**[Expected result]:**
- All content is changed to font size 14.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- The issue is reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32446844-e45aabb0-c312-11e7-95a0-e82e0bc29e2f.gif)

**Comment by vladikoff** [comment]
This is fixed with CKEditor 👍  via https://github.com/mozilla/notes/pull/394

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (1.9.0dev custom built on 11.22.2017) on the latest Firefox release and Nightly.
