### ISSUE TITLE
[Enhancement] The "Font Size" button should be blank when selecting text with multiple sizes

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#387]
**[Notes]:**
- If in the content there is a string of 14 size, then the 14 value will be displayed in the "Font Size" button.
- If the content does not contains a string of 14 size, then the "Font Size" button will display the value of the focused row.

**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom build from 11.07.2017) installed.
- Have content with multiple text sizes, including the default 14 value.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and press "Ctrl+A".
3. Observe the value displayed in the "Font Size" button.

**[Expected result]:**
- No value is displayed.

**[Actual result]:**
- 14 is displayed.

**[Additional Notes]:**
- On Google Docs and Libre Office the button is blank when selecting text with multiple sizes.
- On Thunderbird when selecting text with multiple sizes, the "mixed" message is displayed in the in the "Font Size" button
- The issue is reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![enhancement](https://user-images.githubusercontent.com/31243259/32487112-68ee2b2e-c3b1-11e7-9646-0222de30fdd2.gif)

**Comment by vladikoff** [comment]
Shows the default `Aa` in latest CkEditor

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 21.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
