### ISSUE TITLE
A gray border wrongly appears when resizing the sidebar from maximum, on pages with white background

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#388]
[Notes]
- This issue is partially reproducible on Mac OS: only the "X" button has a dark border.
- This issue is not reproducible for the "Bookmarks" and "History" sidebar.
- This issue is only reproducible when the "Notes" sidebar is located in the left side.

[Affected versions]:
- Firefox 56.0.2 and up
- Firefox Notes v1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v1.9.0dev installed.
- Have the "Notes" sidebar opened to its maximum width.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "about:addons" page.
2. Resize the "Notes" sidebar by dragging its right margin.
3. Observe the behavior.

[Expected result]:
- The sidebar resizes while being dragged.

[Actual result]:
- A gray border appears while resizing.

[Additional notes]:
- This issue is not reproducible on pages with colored background.
- This issue is easy to notice on the "about:pages", such as: about:addons, about:config, about:preferences, about:profiles.
- This issue is easy to notice on pages with clean or white background, such as https://www.wikipedia.org.
- Here is a screen recording of the issue:
![gray border](https://user-images.githubusercontent.com/31244235/32493759-b3374830-c3c7-11e7-9fd9-a5b7ad05d7c0.gif)

**Comment by Natim** [comment]
I am going to close this bug, there is no much we can do about it. Feel free to create a bugzilla issue if you want.

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing :) I've filed it here, bug [1429753](https://bugzilla.mozilla.org/show_bug.cgi?id=1429753), and I'll follow it on Bugzilla.
