### ISSUE TITLE
"Bold" characters from Google search results are wrongly displayed in "Italic" when pasted in "Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#389]
[Affected versions]:
- Firefox 56.0.2 and up
- Firefox Notes v1.9.0dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes v1.9.0dev installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://www.google.com
2. Perform a search and copy text that contains "Bold" characters.
3. Paste the text in the "Notes" sidebar and observe its appearance.

[Expected result]:
- The pasted text correctly keeps the bold characters.

[Actual result]:
- The bold characters are displayed in "Italic".

[Notes]:
- This issue is not reproducible if you paste bold text from other search engines, such as: Yahoo, Bing or DuckDuckGo.
- This issue is not reproducible if the search result contains a hyperlinked text.
- Here is a screen recording of the issue:
![paste from google searches](https://user-images.githubusercontent.com/31244235/32493986-8b925b70-c3c8-11e7-9075-c20816a31e86.gif)

**Comment by evaryont** [comment]
That's because Google uses the `<em>` element to highlight the search results, which by default has italic styling but Google overrides with emboldening in CSS. The HTML from the dev tools:

```html
<span class="st"><em>General Motors</em> is home to Buick, Cadillac, GMC and Chevrolet. Find the latest news about <em>GM</em> automotive innovations, investor relations and more.</span>
```

**Comment by vladikoff** [comment]
@johngruen tested this and it's fine now

**Comment by vladikoff** [comment]
nvm, still happens with italics
