### ISSUE TITLE
The "Firefox Multi-Account Containers" option is wrongly displayed in the sidebar's context menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#390]
**[Affected versions]:**
- Firefox 56 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" (1.9.0dev custom build from 11.06.2017) and with the latest "Multi-Account Containers" add-ons installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Multi-Account Containers" button from the browser toolbar and open a new container tab.
3. Navigate to any website.
4. Right click in the "Firefox Notes" sidebar and observe the context menu options.

**[Expected result]:**
- The default context menu options are displayed.

**[Actual result]:**
- The "Firefox Multi-Account Containers" option is also displayed in the context menu.

**[Additional Notes]:**
- The issue is reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/32611968-a8069b9c-c56f-11e7-82a4-9600508e4415.gif)

**Comment by johngruen** [comment]
This is upstream and should probably be filed in webExtensions on bugzilla 

@andymckay what say you?

**Comment by andymckay** [comment]
Sure. I think its that there is no ability to say "don't appear in a sidebar" because the sidebar is just a "page". Notes could just override context menus in the sidebar completely, there are other parts of the context menu that don't work in sidebars like "View page source".

**Comment by andymckay** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1416839

**Comment by Natim** [comment]
I am going to close this in favor of the bugzilla ticket.
