### ISSUE TITLE
Notify user when they are upgraded to Notes with new editor

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#392]
Since we may break some formatting, we should give users a little notice about the new Notes editor. The notice should have the following features:

1. I should display over part of the notes input.
2. It should be dismissable and should not return once dismissed.
3. It should include the following copy:

**A message from the Test Pilot team:** 
We replaced the text editor in Notes for greater speed and functionality, but had to remove the formatting of your existing notes. Sorry about that, but we appreciate your participation!

**Comment by ryanfeeley** [comment]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/68213/32741024-d6c36194-c872-11e7-86c3-06edea2144aa.png">

**Comment by ryanfeeley** [comment]
Icon: Close 16 http://design.firefox.com/icons/viewer/#close

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/394/commits/099c2b90cfdf75e6b17747086f485ee56b94f2be
