### ISSUE TITLE
Add links support with adjusted CSS

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#396]
* [ ] Fix CSS issue with links:

## Default CKEditor Link

<img src=https://user-images.githubusercontent.com/128755/32871127-4d5b2f7c-ca4d-11e7-87af-6ad5ba0105b6.png width=280 /> We need to get rid of the `^` and make it fit 100%

## Proposed

![image](https://user-images.githubusercontent.com/128755/32911092-1d413f84-cad9-11e7-8b14-56a9bf6ebe98.png)

**Comment by vladikoff** [comment]
@cedricium this would be an interesting project if you have time. If you branch off the ckeditor-concept branch, try to make ckeditor5-link work as @ryanfeeley designed.

* Fork https://github.com/ckeditor/ckeditor5-link and see if you can replace the Balloon logic: https://github.com/ckeditor/ckeditor5-link/blob/master/src/link.js#L15 with a toolbar that shows up below the original ckeditor toolbar. 
* You mind find it easier to work on this from https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/development/custom-builds.html instead of rebuilding the notes editor on every change.

Let me know if you have questions

**Comment by cedricium** [comment]
Commenting so I can come back to this. 👍

**Comment by cedricium** [comment]
I'm having trouble actually implementing this, would love any help and/or for someone else with more experience to pick this up.

For anyone wondering, the route I was going is outlined in #514. 
cc. @Natim @vladikoff

**Comment by vladikoff** [comment]
@cedricium sorry i was away for 2 weeks, looking at this now!
