### ISSUE TITLE
Multiple note support

### ISSUE THREAD

**Issue by pdehaan** [mozilla/notes#40]
From what I understand, this just allows me to create a single note, not an infinite number of separate notes.

I understand it's probably out of scope for V1, but we should consider adding support for multiple notes, as it somewhat limits the utility of this add-on/experiment.

I'm a complex boy, with lots of varied interests. Trying to combine all my thoughts/notes into a single, consolidated text field makes it hard to keep all my information together and easy to find in the future.

**Comment by vladikoff** [comment]
Yeah, this is something to learn from v1, if users want it or not

**Comment by vladikoff** [comment]
Closing for now, not sure if we going for this yet

**Comment by pdehaan** [comment]
If we're going to close this (versus tagging as "V2 milestone"), at the very least we should add an FAQ.md or wiki page or update the README.md. I can pretty much guarantee that you'll get this request repeatedly on the first or second day after you launch.

**Comment by vladikoff** [comment]
>  I can pretty much guarantee 

Ok I will trust you on this. Let's use this issue to keep track of that feedback.

**Comment by imyxh** [comment]
What if you guys implemented a per-url notepad along with the one for the whole browser? 
Like if I go to Wikipedia, I can switch to "per-url mode," type some notes, then go to Gmail, and I have a fresh new page. Maybe just a toggle switch in the lower right next to the feedback switch would be great.

Personally, I would also love multiple pages of notes that you can create and delete, but this idea of different notes per webpage would be simpler.

**Comment by kekkc** [comment]
In https://github.com/mozilla/notes/issues/223 johngruen mentioned that multiple note support is already being user tested. Anyone who has seen this live and can make a screen or knows how I can test it?

**Comment by Natim** [comment]
User testing was done on mockups rather than an actual working prototype.

**Comment by kekkc** [comment]
Cool, many thanks. Would be awesome if sth. would be ready before FF 57 arrives.

**Comment by johngruen** [comment]
Here's the spec: https://mozilla.invisionapp.com/share/WSDA1YM7H#/screens/250693253_Default

**Comment by ryanleesipes** [comment]
Would also like to see this, but commenting because I don't want it to be web page specific. I think that in order for notes to be truly useful it has to be able to store more than one note, instead of being a whiteboard which I have to erase parts of (and move them to other notetaking apps) or else the note becomes too long.

**Comment by vladikoff** [comment]
Main part of this landed in https://github.com/mozilla/notes/commit/3bddc69e6cbd4661c2d7bdb3ff252b39ded6abd1
