### ISSUE TITLE
The Keyboard shortcuts are not displayed for the "Strikethrough", "Number list" and "Bullet list" tooltips

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#402]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover the "Formatting" buttons from the Notes Sidebar and observe.

**[Expected result]:**
- A tooltip with the corresponding button name and keyboard shortcut is correclty displayed.

**[Actual result]:**
- The keyboard shortcut is not displayed for the "Strikethrough", "Number list" and "Bullet list" buttons.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![tooltips](https://user-images.githubusercontent.com/20083658/33022325-7f9c0632-ce0d-11e7-834c-55b7dcb7c21a.gif)

**Comment by Natim** [comment]
It is because we dont't have shortcut for them anymore.

**Comment by vladikoff** [comment]
Probably won't be adding shortcuts at this time. Let me know if you anyone has more input on this
