### ISSUE TITLE
"Heading" tooltip is wrongly displayed while hovering the "Text size" button

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#403]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover the "Text size" button from the sidebar's toolbar and observe the displayed tooltip.

**[Expected result]:**
- The "Font size" tooltip is displayed.

**[Actual result]:**
- The "Heading" tooltip is displayed.

**[Notes]:**
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33024111-e029875e-ce12-11e7-8051-f9a83528b27e.gif)

**Comment by Natim** [comment]
It is not a font-size anymore since #400

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (1.9.0dev custom built on 11.22.2017) on the latest Firefox release and Nightly.
