### ISSUE TITLE
The font size (heading) style wrongly affects the entire paragraph when applied to a selection

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#404]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select a few characters in the Notes sidebar editor.
3. Apply a different font size (heading) and observe the text.

**[Expected result]:**
- The font size (heading) for the selected characters is changed.

**[Actual result]:**
- The font size (heading) for the selected characters along with the paragraph is wrongly changed.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![textsize_selections](https://user-images.githubusercontent.com/20083658/33024720-888a27f4-ce14-11e7-9c86-744451ee0ee8.gif)

**Comment by Natim** [comment]
This is the new behavior since we switch to Markdown.
