### ISSUE TITLE
"Take a note..." placeholder text is not displayed when erasing all text from the Notes content area

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#405]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select all the text from the content area and delete it.
3. Observe the "Take a note..." placeholder text.

**[Expected result]:**
- "Take a note..." placeholder text  is displayed.

**[Actual result]:**
- "Take a note..." placeholder text is not displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![placeholdertext](https://user-images.githubusercontent.com/20083658/33025451-b3efdde2-ce16-11e7-9758-eb3cf2f21443.gif)

**Comment by Natim** [comment]
https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_viewithplaceholder.html

**Comment by vladikoff** [comment]
Ref: https://github.com/ckeditor/ckeditor5/issues/479

**Comment by Natim** [comment]
Shall we plug https://github.com/alexeckermann/ckeditor5-emptyness ?

**Comment by Natim** [comment]
@anweshknayak Do you want to tackle this one?

**Comment by anweshknayak** [comment]
Hey @Natim sure 💯 . Thanks 😄

**Comment by anweshknayak** [comment]
I don't get this one. **Take a note** placeholder. Where it is?

**Comment by Natim** [comment]
When the pad is empty (in the previous version notes) we had a placeholder telling people to take a note.

Since we moved to CKeditor we don't have it anymore.

I guess we need to plug this plugin: https://github.com/alexeckermann/ckeditor5-emptyness in order to add it back.

**Comment by vladikoff** [comment]
> [Expected result]:

> "Take a note..." placeholder text is displayed.

We improved our "Welcome" copy and probably won't be bringing the old "Take a note..." placeholder unless CKEditor makes it really easy to add it.
