### ISSUE TITLE
The previous ordered list is wrongly kept after you change to a different list

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#406]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Create a list with several items using "Bulleted list" option.
3. Press the "Enter" key twice.
4. Select "Numbered list" and write something.
5. Observe the displayed lists.

**[Expected result]:**
- The written items are correctly displayed both in "Bulleted List" and "Numbered List".

**[Actual result]:**
- Bulleted list is forced on the text.

**[Notes]:**
- This issue is also reproducible when you switch from numbered list to bulleted list.
- This issue is also reproducible on Mac 10.12 and Ubuntu 14.04 x64 if you change to a different Sidebar (for eg select "Bookmarks") and return to "Notes".
- Attached a screen recording of the issue:
![previous ordered list - notes](https://user-images.githubusercontent.com/31244235/33026872-3063762e-ce1a-11e7-897b-11310c769c94.gif)

**Comment by vladikoff** [comment]
Cannot reproduce this, will try again...

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest version of Notes 1.9.0dev (custom build 2017-11-23), on latest Nightly build 59.0a1 (2017-11-22) and latest Firefox Release 57.0, on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
