### ISSUE TITLE
There is too much space between two rows

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#408]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write a string in the "Firefox Notes" sidebar and press the "Enter" key.
3. Write another string and observe the space between the rows.

**[Expected result]:**
- There is no extra space between the rows. 

**[Actual result]:**
- There is a large space between the rows.

**[Notes]:**
- The issue is no longer reproducible if you select the content and click the "Numbered/Bulleted list" button.
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33028712-426755f2-ce1f-11e7-9310-521634fef59b.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/394/commits/911fb87325982a42177214402b2c586efb0c9473

Good find 👍

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (1.9.0dev custom built on 11.22.2017) on the latest Firefox release and Nightly.
