### ISSUE TITLE
Former "Strikethrough" shortcut reverses Note's footer items

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#409]
Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Focus Notes sidebar.
3. Press "Ctrl" (Cmd)+"Shift"+"X" keys and observe Note's footer.

[Expected result]:
- Nothing happens, the items from the footer don't change their positions.

[Actual result]:
- The items from the footer reverse their positions.

[Additional Notes]:
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:

![ex strike](https://user-images.githubusercontent.com/26000308/33028934-df406706-ce1f-11e7-8cf5-40a2f39ccd17.gif)

**Comment by Natim** [comment]
Here you have your RTL support for free :D

**Comment by vladikoff** [comment]
wait what

**Comment by vladikoff** [comment]
```
Chrome: Right-click on input or textarea elements to reveal the Writing Direction submenu. Choose either Right to Left or Left to Right. This sets the value of the element's dir attribute, which is then available to scripts.

Safari: Right-click on input or textarea elements to reveal the Paragraph Direction submenu. Choose either Right to Left or Left to Right. This sets the value of the element's dir attribute, which is then available to scripts.

Firefox: Set direction using the CTRL/CMD+SHIFT+X keyboard shortcut, which cycles through LTR and RTL. It does not set the value of the element's dir attribute, and is thus invisible to scripts.
```

From https://www.w3.org/International/questions/qa-html-dir

**Comment by vladikoff** [comment]
We removed that keyboard shortcut for now. Once we bring it back it will be tested not to do that 👍
