### ISSUE TITLE
Bulleted/Numbered list tooltips are wrongly truncated at different sidebar widths

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#410]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover over the "Numbered List" button and observe its tooltip.

**[Expected result]:**
- The tooltip is fully displayed.

**[Actual result]:**
- The tooltip is truncated.

**[Notes]:**
- This issue is also reproducible if the sidebar is resized in such a way that "Numbered List" is at the right margin.
- This issue is reproducible for the "Bulleted list" when you resize the sidebar to its minimum width
- This issue is also easy to observe on smaller screens for both "Numbered List" and "Bulleted List" buttons.
- Here is a screen recording of the issue:
![truncated tooltip](https://user-images.githubusercontent.com/31244235/33028933-dec45d14-ce1f-11e7-90b4-ad7d4c2d4b39.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/394/commits/84455292e3ecd8ed3a56abb03ab357fbce44a5e1 

Good find 👍

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest version of Notes 1.9.0dev (custom build 2017-11-23), on latest Nightly build 59.0a1 (2017-11-22) and latest Firefox Release 57.0, on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
