### ISSUE TITLE
Text cursor is not displayed when hovering Notes content

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#411]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Move the cursor over the Sidebar's content.
3. Observe the mouse cursor.

[Expected result]:
- Text cursor is displayed.

[Actual result]:
- Arrow cursor is still displayed.

[Additional Notes]:
- Notepad, Gdoc and LibreDoc are displaying the text cursor when hovering their contents.
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:

![text cursor](https://user-images.githubusercontent.com/26000308/33029034-28a4d6fc-ce20-11e7-80a3-ec6bd097ab2c.gif)

**Comment by vladikoff** [comment]
good find!

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/394/commits/b798eb51de80be7d0c9ad3ef12354b9b6ca07683 Thank you!
