### ISSUE TITLE
Pressing "Ctrl+A" keys combination wrongly greys out the "Bold", "Italic" and "Strike" buttons

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#412]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.
- Have nothing written in the add-on sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Press "Ctrl+A" keys combination and observe the text formatting options buttons.

**[Expected result]:**
- The text formatting options buttons are displayed as active and can be actioned.

**[Actual result]:**
- The the "Bold", "Italic" and "Strike" buttons are greyed out and not actionable.

**[Notes]:**
- The buttons become actionable again when clicking inside the "Notes" sidebar.
- Here is a screen recording of the issue:
![greyed out buttons](https://user-images.githubusercontent.com/31244235/33030614-70feef88-ce24-11e7-97d5-0302b9695864.gif)

**Comment by Natim** [comment]
It is only the case when the pad is empty.

**Comment by vladikoff** [comment]
Yea a strange one but does not block

**Comment by vladikoff** [comment]
Plus: it probably should not lose focus...

**Comment by vladikoff** [comment]
@Mgsy this doesn't happen in Chrome, but does happen in Firefox on https://ckeditor5.github.io/

**Comment by Mgsy** [comment]
@vladikoff, thanks for the information. The problem exists on latest master and is reproducible in Firefox and Edge. I've created a ticket in our CKEditor 5 repository - https://github.com/ckeditor/ckeditor5/issues/877.
