### ISSUE TITLE
Character notation is no longer available for multilevel numbered lists

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#413]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b1 build with CKeditor) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Numbered list" button, type something and press the "Enter" key.
3. Press the "Tab" key and and observe the list notation.

**[Expected result]:**
- Number "2." modifies into letter "a.".

**[Actual result]:**
- Number "2." modifies into number "1".

**[Notes]:**
- Attached a screen recording of the issue:
![charactr_notation](https://user-images.githubusercontent.com/20083658/33032307-75b50044-ce29-11e7-83de-18179ba46049.gif)

**Comment by vladikoff** [comment]
Files in https://github.com/ckeditor/ckeditor5-list/issues/85 

Good find 👍

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/394/commits/fdacfce2754ed848ddbfe6623c7ec0fbbe67e2bf
