### ISSUE TITLE
[Windows] Notes UI and content are not rendered correctly in High Contrast mode

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#417]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Change the Windows theme option to "High Contrast # 1" or "High Contrast # 2".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Observe the text in the "Notes" content area.
3. Click on the "Notes" sidebar switcher and observe the "Notes" text option and icon.

**[Expected result]:**
2. The text color in the "Notes" content area is white.
3. The "Notes" text option and icon color are green.

**[Actual result]:**
2. The text color in the "Notes" content area is dark grey(unreadable).
3. The "Notes" text option and icon color are white.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![highcontrast_issue](https://user-images.githubusercontent.com/20083658/33073434-9341166e-cecb-11e7-81a9-9ec28601a8a5.gif)

**Comment by vladikoff** [comment]
wow!

**Comment by Natim** [comment]
What if you use the dark theme?

**Comment by SoftVision-EmilPasca** [comment]
None of the following scenarios improve this issue in any way:
- Windows High Contrast theme with Firefox Dark theme and Notes dark/default theme
- Windows High Contrast theme with Firefox Default/Light theme and Notes dark/default theme
- Windows High Contrast theme with a custom Firefox (accessibility) Dark theme along with  Notes dark/default theme

**Comment by vladikoff** [comment]
Gonna try to fix this for v4

**Comment by vladikoff** [comment]
I tried to fix this up but I cannot take the sidebar under control of css with the high contrast theme:

![](http://v14d.com/i/5abbd77c901e6.jpg)

**Comment by vladikoff** [comment]
@SoftVision-EmilPasca I think this is a bug in Firefox

could you please file it and link these two with it: 

https://bugzilla.mozilla.org/show_bug.cgi?id=697836
https://bugzilla.mozilla.org/show_bug.cgi?id=343205

![high-contrast](https://user-images.githubusercontent.com/128755/38047947-f5aee6f8-3291-11e8-8b01-daea42525a77.gif)

**Comment by SoftVision-EmilPasca** [comment]
Filled this isssue into bugzilla: [bugzilla 1450684](https://bugzilla.mozilla.org/show_bug.cgi?id=1450684)

**Comment by Softvision-AndreeaCupsa** [comment]
I have tested this issue on latest Firefox (59.0.2) and Nightly (61.0a1) with the "Notes" (version 4.0.0) add-on installed from https://testpilot.firefox.com/.changing the Windows "High Contrast" mode, do not changes "Notes" sidebar's  UI accordingly. The UI of "Notes" sidebar's remains the same, no changes are made to it.
