### ISSUE TITLE
The text caret is wrongly moved at the beginning of the sidebar's content if certain actions are made

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#418]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Have a paragraph in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the text caret at the beginning of a word.
3. Click a text style option from the sidebar's toolbar.
4. Press the "Space" key and observe the behavior.

**[Expected result]:**
- The "blank space" character is added. 

**[Actual result]:**
- The text cared is moved at the beginning of the sidebar's content.

**[Notes]:**
- The issue is not reproducible with the Bulleted/Numbered lists.
- The issue is not reproducible with any other keys.
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33074113-adf16b92-cecd-11e7-9a46-c5cab1ecc9de.gif)

**Comment by vladikoff** [comment]
This seems fixed!

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 07/18/2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
