### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#42]
See a good example: https://github.com/bwinton/SnoozeTabs

**Comment by vladikoff** [comment]
bug `flod` about L10N

**Comment by flodolo** [comment]
This is one confusing issue subject :-) I'd suggest "Add localization support".

I'm happy to answer questions if you have, I took a quick look at the repository and couldn't spot any string, so you might check at other repositories to see how they manage extracting strings to .properties, etc.

**Comment by vladikoff** [comment]
Sorry, I typed it during the meeting. Updated

**Comment by flodolo** [comment]
Some links in the meantime
https://www.npmjs.com/package/pontoon-to-webext

File structure requested by Pontoon
https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

Pontoon can commit in master or in a branch, like it happens for SnoozeTabs.

Is this a TestPilot experiment?

**Comment by vladikoff** [comment]
> Is this a TestPilot experiment?

Yeap!

**Comment by Natim** [comment]
- [ ] Use `browser.i18n.getMessage('slug')}` everywhere we need to show a translated string.
- [ ] Add `pontoon-to-webext` as a `dev depedency`
- [ ] [List supported locale in packages.json](https://github.com/bwinton/SnoozeTabs/blob/1765637da1e1ed2f3aaf9f801458f1ae179f6d8f/package.json#L63)
- [ ] Create a [./bin/build-locales.js](https://github.com/bwinton/SnoozeTabs/blob/1765637da1e1ed2f3aaf9f801458f1ae179f6d8f/bin/build-locales.js) script and plug it in the `npm run build` step.
- [ ] Create [a locales directory](https://github.com/bwinton/SnoozeTabs/tree/1765637da1e1ed2f3aaf9f801458f1ae179f6d8f/locales) wih translations for supported locales.
- [ ] Then plug Ponton to keep locales translations in sync
- [ ] Create a [`locales/en-US/notes.properties`](https://github.com/bwinton/SnoozeTabs/blob/1765637da1e1ed2f3aaf9f801458f1ae179f6d8f/locales/en-US/snoozetabs.properties) with American translations
- [ ] Handle [langDir](https://github.com/bwinton/SnoozeTabs/blob/7fe37b61972c7b2f4d510553ae23eee8228070ae/src/lib/utils.js#L9-L10) `ltr, rtl` and [Configure Quill.js](https://quilljs.com/docs/formats/#block)

**Questions**
- What are the steps to configure Pontoon?
- Are there any missing steps you can see?
- Do we have to do anything to configure browser.i18n?

**Comment by flodolo** [comment]
> What are the steps to configure Pontoon?

That's on me as soon as soon as you create the en-US file. You'll need to tell me which repository (I assume this one) or branch to commit to, and give Pontoon's bot access to the repository.

> Are there any missing steps you can see?

I'd really like to avoid having an hard-coded list of locales (I didn't realize SnoozeTabs has one), because it's easy to forget to update it. I'm not sure how Activity Stream does it, but I don't think they use an hard-coded list.
https://github.com/mozilla/activity-stream/blob/master/docs/v1-test-pilot/localization.md

> Do we have to do anything to configure browser.i18n?

I don't think so, but some technical details are also beyond my area of expertize.

**Comment by vladikoff** [comment]
From mtg: 

* Let's add the en-US file ASAP
* Figure out how to `npm start` with an RTL locale

**Comment by udaraweerasinghege** [comment]
I can't tag you in the pr comments @flodolo ._.
Will this be sufficient for configuring pontoon on your end : https://github.com/mozilla/notes/pull/95

**Comment by flodolo** [comment]
> Will this be sufficient for configuring pontoon on your end : #95

How complete is that localization file, i.e. how many strings are missing? I'm not sure if it makes sense to start localization if the file is far from complete.

If it's just for testing Pontoon automation, I can set it up on the dev version and try to see if it can commit (still not sure if you want commits in master or a branch).

At some point we will also need an easy way to test the dev add-on, possibly without having to install it from code (not all localizers are necessarily tech savvy).

**Comment by udaraweerasinghege** [comment]
Thanks for taking a look!
> How complete is that localization file, i.e. how many strings are missing? I'm not sure if it makes sense to start localization if the file is far from complete.

The localization file is complete with all the strings currently in the project, as well as a couple extra that are in the designs but not in the project.

> If it's just for testing Pontoon automation, I can set it up on the dev version and try to see if it can commit (still not sure if you want commits in master or a branch).

^^ cc: @vladikoff

**Comment by flodolo** [comment]
The user needing access is: https://github.com/mozilla-pontoon

Also cc @mathjazz, so he's aware of the incoming invite.

P.S. you can ping random people in comments, you just need to type their nicknames completely, autocomplete is available only for collaborators of the project

**Comment by vladikoff** [comment]
@mathjazz @flodolo added @mozilla-pontoon to the repo 👍

**Comment by flodolo** [comment]
I'll try to hook the repo tomorrow morning for a test (in case you'll see an incoming Italian localization).

**Comment by flodolo** [comment]
A few more questions (I'll ask them here instead of #95, since that's already closed):
* Is Sync intended as generic synchronization, or Firefox Sync?
* `syncComplete=Synced`. Looking at the designs, do you expect to put a date after this string?
* Looks like "Verify Your Account" is not available in the file. Expected?
* What's the usage of "Notes" at the top of the panel?

**Comment by flodolo** [comment]
> Is Sync intended as generic synchronization, or Firefox Sync?

@natim already answered this one (generic sync), I'll need to add a comment in the file. Sorry for the confusion, since you saw my comment disappear in the other PR.

**Comment by Natim** [comment]
> syncComplete=Synced. Looking at the designs, do you expect to put a date after this string?

Yes

> Looks like "Verify Your Account" is not available in the file. Expected?

Yes, we know we will need this string but for this first version we removed the code related to synchronization and account management.

> What's the usage of "Notes" at the top of the panel?

That's the title of the sidebar/add-on.

**Comment by flodolo** [comment]
> That's the title of the sidebar/add-on.

Is that expected to be non localizable and identical to the add-on name?

**Comment by Natim** [comment]
Can we localize the name of the add-on? My understanding is that the values is coming from the manifest.json file directly.

**Comment by flodolo** [comment]
No, we can't. That's why I'm asking if the plan is to basically use the add-on names, or if it's a generic "annotations". For the latter, we would need a localizable string.

**Comment by Natim** [comment]
> @vladikoff commit to master or a branch?

I think it is fine to commit localization directly to master.

**Comment by flodolo** [comment]
Localization is working
https://github.com/mozilla/notes/commit/b96d7682cc074f819565b4918db9adc957c59dc9
https://github.com/mozilla/notes/commit/a1b6abdeaca68d65b558887c390498dc3cfa4bcc

At this point we could enable it on the prod server. A couple more questions:
* Does [this description](https://mozilla-pontoon-staging.herokuapp.com/it/test-pilot-notes/notes.properties/?string=166660) make sense? 
* Any idea when this will be added to Test Pilot experiments? It will be a bit hard to engage volunteers without knowing that information

**Comment by flodolo** [comment]
Correct link to current description: https://mozilla-pontoon-staging.herokuapp.com/projects/test-pilot-notes/info/

**Comment by Natim** [comment]
> Does this description make sense?

Yes

> Any idea when this will be added to Test Pilot experiments?

First weeks of July.

**Comment by flodolo** [comment]
> First weeks of July.

OK, I'm going to enable the project and send an email out to localizers. I'll also enable French: note that you will be able to submit suggestions, but you'll need someone to review them (CC @TheoChevalier so he's aware).

**Comment by flodolo** [comment]
On a side note: I wonder if you want to (and can) disable CI on these commits.

**Comment by flodolo** [comment]
Project is set up on prod
https://pontoon.mozilla.org/projects/test-pilot-notes/

Email sent to dev-l10n
https://groups.google.com/d/msg/mozilla.dev.l10n/axPllXUlh34/mjlfMMaiAwAJ

This discussion might be useful for the date part
https://github.com/bwinton/SnoozeTabs/pull/206

**Comment by flodolo** [comment]
Last thing to note: the policy for updating strings is the same as Firefox
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Changing_existing_strings

If you want your change to be noticed and considered by other languages, you need to change the string ID.

**Comment by vladikoff** [comment]
Thanks so much @flodolo !

**Comment by vladikoff** [comment]
Thanks @udaraweerasinghege !! This was fixed
