### ISSUE TITLE
The bullet changes into number and continues the numbered list series if there is no text between lists in a new window

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#421]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Press "Ctrl" (Cmd)+"N" keys.
3. In the new window, click the "Numbered List" button.
4. Type something, then press "Enter" key twice.
5. Click the "Bulleted List" button.
6. Type a character and observe what happens next.

[Expected result]:
- The character is correctly displayed in the bulleted list.

[Actual result]:
- The bulleted list changes into numbered list and continues the series.

[Additional Notes]:
- The issue is not reproducible if there is text between the numbered and bulleted lists.
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:

![bulleted in numbered](https://user-images.githubusercontent.com/26000308/33074618-79b50da0-cecf-11e7-97f3-d9f5907f668f.gif)

**Comment by vladikoff** [comment]
@Natim this one is pretty weird:

![numa](https://user-images.githubusercontent.com/128755/33084573-5287f4d2-ceb0-11e7-9f4a-0e35424a5b87.gif)

I will check if Markdown engine is to blame or not

**Comment by Natim** [comment]
It might be because the text-change even is not triggered in case we switch list type?

**Comment by vladikoff** [comment]
@Natim oooooo

**Comment by vladikoff** [comment]
@Natim Ah I see, so in the markdown parser, it stripes new lines, so the linebreak does not save the state across the different windows. This is also related to this issue: https://github.com/mozilla/notes/issues/407

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest version of Notes built on 11/23/2017.
