### ISSUE TITLE
The whole Numbered/Bulleted list is wrongly deleted after selecting it and deleting all its content

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#422]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Have a Numbered list.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select the "Numbered list".
3. Press the "Delete" key an observe the behavior.

**[Expected result]:**
- The content is deleted and the first number is displayed. 

**[Actual result]:**
- The "Numbered list" is also deleted.

**[Notes]:**
- The issue is also reproducible with the "Bulleted list".
- The issue is not reproducible with the "Firefox Notes" master build.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33074740-f2e4fb54-cecf-11e7-8d48-fbbce05e9ffc.gif)

**Comment by vladikoff** [comment]
Check with Quill, but i think this is okay for now

**Comment by vladikoff** [comment]
@johngruen says this is a WONTFIX
