### ISSUE TITLE
"Delete" action from context menu doesn't work for multiple paragraphs

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#423]
[Notes]:
- This issue is neither reproducible if you use the "Delete", nor the "Backspace" keys.
- This issue is not reproducible when deleting a single paragraph.
- This issue is not reproducible if you select multiple words from multiple paragraphs using "Ctrl"/"Cmd" and click.

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (1.9.0b2 build with CKeditor) installed.
- Have at least two written paragraphs in "Notes" sidebar.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Select the paragraphs using the mouse.
3. Right click and choose "Delete" option from the context menu.
4. Observe the behavior.

[Expected result]:
- The paragraphs are deleted.

[Actual result]:
- Nothing happens.

[Additional notes]:
- This issue is also reproducible when trying to delete different words from both paragraphs.
- Here is a screen recording of the issue:
![delete through context menu](https://user-images.githubusercontent.com/31244235/33075216-6c98b62e-ced1-11e7-911d-f4d378cde77a.gif)

**Comment by vladikoff** [comment]
@Natim I wonder where this context menu is coming from, ckeditor?

**Comment by Natim** [comment]
Firefox

**Comment by vladikoff** [comment]
CKEditor bug it seems: https://github.com/ckeditor/ckeditor5/issues/684

**Comment by Natim** [comment]
This is handled in Firefox with the two following bugs:

Bugzilla issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1379584
implement beforeInput bug: https://bugzilla.mozilla.org/show_bug.cgi?id=970802
