### ISSUE TITLE
Bulleted/Numbered list tooltips are inversed

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#428]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest "Firefox Notes" add-on version 1.9.0dev installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover over the "Bulleted List" button and observe its tooltip.

[Expected result]:
- "Bulleted List" is displayed.

[Actual result]:
- "Numbered List" is displayed.

[Notes]:
- The "Bulleted list" tooltip is wrongly displayed for the "Numbered List" button.
- Here is a screen recording of the issue:
![inversed tooltips](https://user-images.githubusercontent.com/31244235/33130170-20c19444-cf9b-11e7-909b-113465d901c3.gif)

**Comment by vladikoff** [comment]
Good find!

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using latest version of Notes 1.9.0dev (custom build 2017-11-23), on latest Nightly build 59.0a1 (2017-11-22) and latest Firefox Release 57.0, on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
