### ISSUE TITLE
Numbers written in a paragraph are wrongly changed to a Numbered list after a blank space is added

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#429]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest version of Notes (1.9.0-dev) installed on a clean new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Write at least two numbers in a new paragraph and press space.
3. Observe the behavior.

[Expected results]:
- A blank space is added after the numbers.

[Actual results]:
- The paragraph is transformed in a numbered list.

[Notes]:
- The issue is also reproducible when you write a single number. (eg. type 5 and press space)
- The issue is not reproducible if the paragraph contains letters.
- Attached a screen shot of the issue:
![numbers becoming numbered list](https://user-images.githubusercontent.com/18304511/33134851-79669064-cfa9-11e7-8dd4-259718fe6ebd.gif)

**Comment by vladikoff** [comment]
Bug in the Markdown editor. only `1.` should make this formatting change

**Comment by vladikoff** [comment]
Filed: https://github.com/ckeditor/ckeditor5-markdown-gfm/issues/17

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version of Notes built on 11/23/2017.
