### ISSUE TITLE
The formatting options are greyed out if the "Notes" scrollbar is clicked in a new window

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#434]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest "Firefox Notes" add-on v1.9.0dev installed.
- Have enough text written in the "Notes" sidebar, so the scrollbar appears.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new window and click the "Notes" scroolbar.
3. Observe the formatting option buttons.

[Expected result]:
- The formatting option buttons are correctly displayed and actionable.

[Actual result]:
- The formatting option buttons are greyed out. All the text is moved down a row and the text caret appears at the beginning of the sidebar.

[Notes]:
- This issue is also reproducible when you switch back to the Notes sidebar.
- The issue is also reproducible if you right click inside the Notes sidebar.
- After you click inside the sidebar, the buttons become active and actionable again.
- Here is a screen recording of the issue:
![greyed out formatting options new window](https://user-images.githubusercontent.com/31244235/33174130-5d948af6-d05f-11e7-890c-96e3e82ff7b2.gif)

**Comment by vladikoff** [comment]
This should be fixed

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 07/18/2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
