### ISSUE TITLE
The content is not scrolled down by one page when the "Page Down" key is pressed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#435]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom built on 11.23.2017) installed.
- Have enough content so that the vertical scrollbar is displayed in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Place the text caret anywhere (except on the first row) in the sidebar's content..
3. Press the "Page down" key and observe the behavior.

**[Expected result]:**
- The content is scrolled down by one page. 

**[Actual result]:**
- The content is scrolled down to the row where the text caret was placed.

**[Notes]:**
- The issue is reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33174568-4978a4e2-d061-11e7-9747-82a5fd4d096a.gif)

**Comment by Natim** [comment]
I believe this is fixed with Notes 2.2.0

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6 build) installed, on the latest Firefox release and Nightly.
