### ISSUE TITLE
Text can be wrongly inserted in the "Notes" sidebar with drag and drop

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#436]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a new Firefox profile with the latest "Firefox Notes" add-on v1.9.0dev installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a page that has text.
2. Select text then drag and drop it inside the "Notes" sidebar.
3. Observe the behavior.

[Expected result]:
- The text is not inserted in the sidebar.

[Actual result]:
- The text is inserted in the sidebar.

[Notes]:
- This issue is not reproducible on Google Docs.
- Text can also be dragged and dropped from Libre Office Document (.odt).
- Here is a screen recording of the issue:
![drag and drop text](https://user-images.githubusercontent.com/31244235/33175816-9175927e-d065-11e7-9fdf-2ae76054d5ad.gif)

**Comment by Natim** [comment]
Apparently it works as well as the copy/paste, we had to deactivate it for Quill because it allowed unallowed content in the sidebar but it doesn't seems to be the case wit CKEditor.
