### ISSUE TITLE
The default "Firefox Notes" text is not correctly formatted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#437]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- "xpinstall.signatures.required" pref is set to false in "about:config".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:addons" page and install the latest "Firefox Notes" add-on version (1.9.0dev).
2. Observe the default sidebar content.

**[Expected result]:**
- The "Hello" string has the "H2" font size and the rest of the text is on a new row. 

**[Actual result]:**
- "## Hello" is displayed with "P" text size and the rest of the text continues on the same row.

**[Additional Notes]:**
- The issue is not reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33180147-72bf8682-d074-11e7-9f19-5cd210157acc.gif)

**Comment by vladikoff** [comment]
@Softvision-MariusComan 

```
Open the browser with the profile from prerequisites.
```

Is this some cached profile? Does it have cached data locally? 
Try the same with a fresh profile, do you get a proper heading?

**Comment by Softvision-MariusComan** [comment]
@vladikoff I've reproduced this issue on a new profile with no data cached locally, using the "Firefox Notes" add-on version 1.9.0dev custom built on 11.23.2017.
The issue is not reproducible with the "Firefox Notes" version 1.9.0dev custom built on 11.22.2017. [Here ](https://goo.gl/TPG2Un)you will find both builds.

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (1.9.0rc1) on the latest Firefox release and Nightly.
