### ISSUE TITLE
An empty row is displayed above the formatted spaceless text after switching between sidebars

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#444]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0dev custom built on 11.23.2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type something on at least 2 rows, without spaces.
3. Click on the "Bold" format button.
4. Click on the switch button and choose another sidebar.
5. Click on the switch button and choose Notes sidebar.
6. Observe the way the text is displayed.

[Expected result]:
- The text is correctly displayed on the 2 rows, without extra empty rows.

[Actual result]:
- An empty row is displayed above the text.

[Notes]:
- The issue is also reproducible with "Italic" and "Strikethrough" options. 
- The issue is not reproducible with the "Lists" format and "Header" font sizes.
- The text re-arranges after clicking on it.
- The issue is not reproducible on older versions of Firefox Notes (Quills based).
- Attached a screen recording of the issue:

![extra row](https://user-images.githubusercontent.com/26000308/33183173-72d14696-d07f-11e7-8d97-20e063ed5fbe.gif)

**Comment by vladikoff** [comment]
Yeah, I've seen this. Good find 👍

**Comment by vladikoff** [comment]
I think this is a CKEditor issue, we shall follow up with them

**Comment by vladikoff** [comment]
This is "fixed" with multi-note and ckeditor update
