### ISSUE TITLE
The text is not formatted if you write the markdown language from right to left

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#448]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0rc1 build with CKeditor) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Type something in the Notes' editable area.
3.  Press "Shift" + "*" keys twice.
4. Focus the area right before the text.
5. Press "Shift" + "*" keys twice and observe what happens next. 

[Expected result]:
- The text is automatically bolded and the asterisks are no longer displayed.

[Actual result]:
- The text is not bolded and the asterisks remain displayed.

[Additional Notes]:
- The issue is also reproducible with "Italic" and "List" formats and underscore.
- The text is automatically formatted only if pressing "Enter" in order to start a new row.
- The issue is not reproducible with the following markdown language demo: https://markdown-it.github.io/
- Attached a screen recording of the issue:

![markdown](https://user-images.githubusercontent.com/26000308/33214808-1301b748-d136-11e7-849a-30cd21c83d99.gif)

**Comment by vladikoff** [comment]
good find, ckeditor autoformat issue + https://github.com/mozilla/notes/issues/414
