### ISSUE TITLE
The previously set "Show scroll bars" OS option wrongly persists in the "Firefox Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#449]
https://bugzilla.mozilla.org/show_bug.cgi?id=1420452

**[Notes]:**
- If the "Always" is already checked and at step 3 you changed to the "When scrolling" option, then the scroll bar will always be displayed.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Mac

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (1.9.0rc1) installed.
- Have enough content so that the vertical scroll bar is displayed in the sidebar.
- Have the "When scrolling" option, from the OS System preferences -> General -> Show scroll bars, checked.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Go to the OS System preferences -> General -> Show scroll bars and check the "Always" option.
3. Focus the browser and observe the sidebar.

**[Expected result]:**
- The scroll bar is displayed.

**[Actual result]:**
- The scroll bar is displayed only when scrolling. 

**[Additional Notes]:**
- The issue is no longer reproducible after switching or reopening the sidebar.
- The issue is reproducible with the "Firefox Notes" version from TxP.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33216025-c7837270-d13a-11e7-935a-73bd852f87f3.gif)

**Comment by vladikoff** [comment]
Need to confirm that this a Firefox bug

**Comment by Natim** [comment]
I am going to close this bug in favor of the Bugzilla one.
