### ISSUE TITLE
Enable greenkeeper

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#45]

**Comment by vladikoff** [comment]
@pdehaan Do you have access to add this?

**Comment by pdehaan** [comment]
@vladikoff Apparently not. Not sure who our resident Greenkeeper whisperer is that has access to enable this to the repo. FWIW, I think disabled greenkeeper on some other repos due to excessive PR noise. Plus, the fact all our dependencies are just devDependencies.

**Comment by vladikoff** [comment]
@pdehaan we should enable it from devDeps for now, and go from there :)

**Comment by groovecoder** [comment]
I enabled greenkeeper for this repo. ...

Note: @cr mentioned the [`quill`](https://www.npmjs.com/package/quill) dependency in today's meeting, and it's not listed in the `package.json` file here, so greenkeeper won't watch it unless it's moved to `package.json`, and configured to install into the `src/sidebar` directory.

**Comment by pdehaan** [comment]
Ref: #25 _"Add quill and kinto-http as npm dependencies?"_

**Comment by pdehaan** [comment]
Ref: #48 _"Action required: Greenkeeper could not be activated"_

I think this is currently blocked by #17; _"Add Circle-CI integration"_

**Comment by groovecoder** [comment]
Re-enabled.

**Comment by vladikoff** [comment]
@groovecoder great!! Thanks so much!!

**Comment by Natim** [comment]
Can we close that bug then?

**Comment by Natim** [comment]
How can we check that greenkeeper has our back already?

**Comment by Natim** [comment]
Apparently someone needs to click on the configure menu here: https://github.com/mozilla/notes/settings/installations

But I cannot.

**Comment by groovecoder** [comment]
Greenkeeper is configured to run on this repo. I'm not sure if/how we need to re-trigger it to run again.

**Comment by Natim** [comment]
Ok I will close the issue and we will make sure for the first releases that greenkeeper didn't miss an update.
