### ISSUE TITLE
[Enhancement] Limit the number of multileveled lists that can be created

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#451]
[Notes]:
- When you reach the 19th- 20th level of a list, you can no longer use them properly and any text will be written vertically. In my opinion we should limit the number of levels that can be created in a list.
- On the version from Test Pilot only 9 levels of a list can be created.

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest version of Notes (1.9.0-dev) installed on a clean new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Press the "Numbered List" button and write a letter.
3. Press Enter, Tab and write another letter
4. Repeat step 3 at least 20 times.
5. Observe the behavior.

[Expected results]:
- Lists should no longer be created after a set number.

[Actual results]:
- 20 levels of lists are created.

[Additional notes]:
- The issue is also reproducible with Bulleted lists.
- Attached a screen recording of the issue:
![multi level bulleted list](https://user-images.githubusercontent.com/18304511/33217751-04fa25b6-d142-11e7-9726-ad968afe2231.gif)

**Comment by vladikoff** [comment]
@johngruen says limit to 5
