### ISSUE TITLE
[Enhancement] The "Font Size" drop-down should be ordered by actual text size 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/notes#452]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest version of Notes (1.9.0-dev) installed on a clean new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Font size" button and observe the list.

[Expected results]:
- P, H3, H2, H1 is displayed.

[Actual results]:
- P, H1, H2, H3 is displayed.

[Notes]:
- In the version from Test Pilot we ordered the Font Size from smallest to largest (12 to 20).

**Comment by abyu** [comment]
Pull request at https://github.com/mozilla/notes/pull/457

**Comment by vladikoff** [comment]
Fixed!
