### ISSUE TITLE
Add Notes keyboard shortcut to sidebar menu

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#455]
We have it here:
<img width="372" alt="system menubar" src="https://user-images.githubusercontent.com/68213/33281673-fe123cf0-d373-11e7-976e-fd63291335ac.png">

Can we have it here too?
<img width="212" alt="sidebar menu" src="https://user-images.githubusercontent.com/68213/33281674-fe20e372-d373-11e7-93bd-e28aa87c10a8.png">

**Comment by vladikoff** [comment]
@ryanfeeley need to file a firefox bug for this I think

**Comment by Natim** [comment]
@ryanfeeley With linux it doesn't even show on the menu.

![shortcut](https://user-images.githubusercontent.com/229453/34727063-1749f8ee-f556-11e7-83ad-a66c523b3de8.png)

@ryanfeeley Can I let you create the bug in bugzilla?

**Comment by ryanfeeley** [comment]
@Natim Oh that's weird. The Notes icon should never be in that menu.

**Comment by vladikoff** [comment]
@ryanfeeley please file a firefox bug for this, this is out of our control
