### ISSUE TITLE
"Notes enabled!" modal slide nav's inactive circles cannot be seen

### ISSUE THREAD

**Issue by Nightfirecat** [mozilla/notes#456]
!["Notes enabled!" modal window, with introduction instructions](https://i.imgur.com/beCB1kc.png)

In this screenshot, `.modal .dot` are colored white, which cannot be seen against the white background of each of the slides. Perhaps they should be colored grey? (with a white border to maximize visibility regardless of background?)

**Comment by vladikoff** [comment]
Moved to https://github.com/mozilla/testpilot/issues/3100 

thanks for the report!
