### ISSUE TITLE
Notes sidebar doesn't sync with the content from a different profile if the default text has been replaced

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#459]
**[Notes]:**
- The issue is not reproducible if you follow the steps but leave the default text in the Firefox Notes sidebar.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have `xpinstall.signatures.required` set to `false` in "about:config".
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b2) installed.
- Have a Firefox Notes sync account.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Have some content in Firefox Notes, ready to be synced.
3. Open a new instance of the browser with a new Firefox profile.
4. Install the add-on from perequisites and add some text in the Firefox Notes sidebar.
5. Sign in to the same Firefox Notes account
6. Observe the sidebar content. 

**[Expected result]:**
- The Notes sidebar is updated with the content from the other profile.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- Attached a screen recording of the issue: https://goo.gl/kHeVbq

**Comment by SoftVision-EmilPasca** [comment]
Sync doesn't work anymore, retested this issue today with the same Notes build(2.0.0b2) as yesterday and the content is no longer synced even if the default text isn't replaced.
I've also observed the following error messages in the browser console:
`
account_updates error message. No Such Channel  WebChannel.jsm:148
WebChannel error: No Such Channel  acb991cb.main.en.js:20
Webconsole context has changed
Login succeeded Object { access_token: "678101b8925df4d91da237396db8722561d…", refresh_token: "081f6a562c19c33bde275093ed33dae52fc…", key: Object, metadata: Object }  background.js:73
Webconsole context has changed
<unavailable>  sync.js:245
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://kinto.dev.mozaws.net/v1/buckets/default/collections/notes/records?_sort=-last_modified. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)
Collection had record Object { data: undefined, permissions: Object }  sync.js:277
kinto-loaded Object { action: "kinto-loaded", data: null, last_modified: null }`

**Comment by Natim** [comment]
Please try if addon-2.0.0b5 fixes it: https://github.com/mozilla/notes/files/1514736/addon-2.0.0b5.zip

**Comment by vladikoff** [comment]
Should be fixed in latest beta 👍

**Comment by SoftVision-EmilPasca** [comment]
The issue is no longer reproducible on the latest "Firefox Notes" add-on version (2.0.0b7).

**Comment by vladikoff** [comment]
🥇
