### ISSUE TITLE
[Sync] If there is only default text then Sync should not conflict

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#462]
<img src=https://user-images.githubusercontent.com/128755/33409983-1a0f0dd2-d54c-11e7-98d8-76684fba767a.png width=150 />

cc @Natim 

If there is only default text and we login right away we should just paste what synced. (I think we can do this by `getData` to text and validating that is only the default text)

**Comment by Natim** [comment]
As far as we tested it yesterday it is the case. If you happen to have the default text and edit it it will save it an make a conflict.

**Comment by vladikoff** [comment]
I Will double check

**Comment by vladikoff** [comment]
Not an issue! Yay!
