### ISSUE TITLE
[Sync] Sync should log out if password reset

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#463]
We see a 400 but sync shows that it is still logged in. The synced time doesn't update anymore though

![screenshot from 2017-11-29 22-13-09](https://user-images.githubusercontent.com/128755/33411258-82266932-d552-11e7-97fb-3b3d0c2eb395.png)

**Comment by Natim** [comment]
400 means Bad Request so the request was malformed?
If the token expire we should have a 401

**Comment by vladikoff** [comment]
To use "Reconnect to Sync" yellow bar for this...

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/425/commits/aaf494b986d6637864c89c64b79651991606a344
