### ISSUE TITLE
Provide a button to open notes in a Tab

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#470]
The hardest part here is: we might not be able to hide the sidebar on our own, so we get 2 editors

**Comment by mlutfy** [comment]
Is there already a way to enter a specific URL in the tab bar to access Notes?

I would be curious to test this. It could be useful when using [Tree Style Tabs](https://addons.mozilla.org/fr/firefox/addon/tree-style-tab/) (I would pin the tab to the top of my tab list, since I keep forgetting the keyboard shortcut to open Notes).

**Comment by Natim** [comment]
It is something like: moz-extension://21f8860f-fcc5-4b8f-b433-e93e05363388/sidebar/panel.html

**Comment by mlutfy** [comment]
Thank you! I have not tested the code yet, but it works well in a tab using the moz-extension URL.

**Comment by vladikoff** [comment]
> The hardest part here is: we might not be able to hide the sidebar on our own, so we get 2 editors

We have the `.close` api that can close the sidebar (@cedricium you worked on that in "Send to notes")

@cedricium do you want to explore this? What are you thoughts on this feature? @ryanfeeley doesn't want this feature in the main UI but we might be able to hide it in the addon preferences via something like:

Open Notes in [X] Sidebar .  [ ] New Tab

**Comment by cedricium** [comment]
@vladikoff totally, would love to give this a try. Just to see if I'm picturing this correctly: if the setting option to "Open in New Tab" is checked / set, then any time Notes is opened, it should be in a new tab rather than opening the sidebar, correct?

So: using the keyboard shortcut, pressing the browser action button, using "Send to Notes", etc., should cause a new tab to open rather than the sidebar opening?

**Comment by vladikoff** [comment]
> if the setting option to "Open in New Tab" is checked / set, then any time Notes is opened, it should be in a new tab rather than opening the sidebar, correct?

> So: using the keyboard shortcut, pressing the browser action button, using "Send to Notes", etc., should cause a new tab to open rather than the sidebar opening?

This sounds about right. Play around with it and see if it is usable. 

There is one case: If user manually opens the Firefox sidebar and selects Notes + has the Notes tab open then they will get 2 editors, but this is sort of an "edge case"

**Comment by vladikoff** [comment]
@ryanfeeley 

> 2) Instead of opening Notes on the left side of each tab, please make Notes open as a whole new tab itself

> Would be nice if one could easily move Notes to a tab and back to the sidebar.

> Please allow 1) Moving the notes tab as per the user's liking 

> Feature requests: - ability to open notes as a tab instead of the sidebar - ability to create multiple notes 

> It would be cool, if notes sidebar could be moved to the right edge of the screen (It moves content too much off center with  "Tab Center" enabled), and possibly change its width based on window size.

> I'm really enjoying using the notes functionality. It would be amazing if we could make multiple notes in order to further organize our note-taking. Something like adding a button to the top of the title bar of the notes that opens up a new tab for note taking, similar to opening a new browsing tab in Firefox, will make this add-on even more useful for me.
Is it possible to move the notes sidebar? Right now it's on the left-hand side of my browser, but when there it interferes more with my ability to look at messages in email inboxes. So I would prefer to move it over to the right-hand side (or even the bottom of the window). If this is not yet possible to do, I strongly vote in favor of introducing such a feature.


> Needs shortcut to show/hide. Needs optional auto-hide, auto-show on mouse over. With separate show and hide delays. Not even this addon https://addons.mozilla.org/en-US/firefox/addon/sidebar-auto-showhide/ cuts it, as it takes time to render. Alt-Tab still faster and more comfortable.  Ability to have multiple pages / clickable elements / split between single page notes and open in main content window kind of notes would enhance the usability by a great margin.  And... Markdown? 

> Save notes and add new ones. A page to store and view all notes. also, a full page for note, that can be popped out (tab for note) annndd... a hotkey for notes :)  LOL thanks

> The Notes useful but here some stuff Mozilla could add: -More than one note; multiple notes e.g.: Shopping list, Schedule, etc -Folders for the notes -Also Subfolders -Notes full tab (for better UI)

> Couple of features I would like to see  1. Notes as a separate tab instead of occupying ̇the side bar space. Not enough to view notes in that space 2.  New pages for new notes instead of one page only - unless I am not able to figure out how to create new pages.

**Comment by ryanfeeley** [comment]
@vladikoff 10 responses out of 3024 = 0.3%.

If you can you show me how this doesn't complicate the design, I'm game.

**Comment by ryanfeeley** [comment]
![notes](https://user-images.githubusercontent.com/68213/36806360-c54d978a-1c8d-11e8-9d25-d5611e9f8285.gif)

**Comment by vladikoff** [comment]
Sorry @cedricium , I spent hours trying to sell this feature to @ryanfeeley but no luck :(

I had to close https://github.com/mozilla/notes/pull/730 for now.

**Comment by cedricium** [comment]
Haha no hard feelings 😄

**Comment by ryanfeeley** [comment]
You know I ❤️ you all, but we had to 🔪 it with 🔥.

**Comment by jimbo1qaz** [comment]
Seems like the developers have rejected this feature request. It would be *very* useful for me to pop out notes, seeing as I'm using Notes on a serious basis to edit some non-trivial documents.

Additionally, where is the feedback sent? Are feedback posts not publicly available?
