### ISSUE TITLE
You are wrongly disconnected from the FxA after changing the password and writing something in the sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#471]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b7) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Change your FxA password (https://support.mozilla.org/en-US/kb/change-your-firefox-accounts-password).
3. Focus the sidebar and write something.
4. Observe the message displayed in the bottom (part) of the sidebar.

**[Expected result]:**
- The "Synced at (hour)" string is displayed.

**[Actual result]:**
- The "Reconnect to Sync" string is displayed. 

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33553260-a1d72c1a-d900-11e7-9964-0bf12238008b.gif)

**Comment by vladikoff** [comment]
That's expected. the encryption key changes so we cannot sync anymore.

The yellow warning would go away after you restart notes or press Disable Sync in the menu

**Comment by vladikoff** [comment]
or you would reconnect by pressing the sync arrows icon

**Comment by vladikoff** [comment]
oh woops sorry, I missed that this was change password. With change password we reset the tokens (per https://github.com/mozilla/fxa-oauth-server/issues/481 ) so you have to reconnect 

cc @Natim
