### ISSUE TITLE
Undo option does not bring back content deleted in other windows

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#472]
**[Notes]:**
- The issue is also reproducible with user inputted text.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b7) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new window.
2. Select all content and delete it.
3. Switch back to the first window and focus the sidebar.
4. Press "Ctrl+Z" and observe the behavior.

**[Expected result]:**
- The content from step 2 is re-displayed.

**[Actual result]:**
- Nothing happens. 

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33558754-65d21f3c-d913-11e7-98e7-ffc29c2f60bd.gif)

**Comment by vladikoff** [comment]
https://github.com/ckeditor/ckeditor5-undo might help with this, but there could also be an easier solution

**Comment by Natim** [comment]
This would be handled with the beforeinput event implementation: https://bugzilla.mozilla.org/show_bug.cgi?id=970802
