### ISSUE TITLE
The tooltip text of the "Feedback" button is wrongly displayed before and after logging into the FxA

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#473]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b7 installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Move the arrow cursor over the middle area of the "Feedback" button and observe its tooltip.
3. Move the arrow cursor to the left/right side of the "Feedback" button and observe its tooltip.

[Expected result]:
2&3. "Click here to give us some feedback" tooltip text is displayed (as shown in the master build).

[Actual result]:
2. "feedback" tooltip text is wrongly displayed.
3. "Give Feedback" tooltip text is wrongly displayed.

[Notes]:
- The tooltip text is also wrongly displayed when logging into the Firefox account. In this case, the tooltip text is represented by the user's FxA email address. 
- Here is a screencast of the issue:

![tooltip diff](https://user-images.githubusercontent.com/26000308/33563177-e560c92c-d91f-11e7-8e9b-9a75ca58bf2e.gif)

**Comment by vladikoff** [comment]
this is strange

**Comment by vladikoff** [comment]
fixed in https://github.com/mozilla/notes/pull/425/commits/54c72425da3fb7a623d333b817f02439cf15c4a7
