### ISSUE TITLE
"Sync Your Notes" button doesn't have a hover effect after logging into the FxA

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#474]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b7 installed.
- Log into a valid FxA.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Hover the "Sync Your Notes" button and observe if any changes occur.

[Expected result]:
- The button displays a hover effect: its background color darkens a bit.

[Actual result]:
- Nothing happens, there is no hover effect.

[Notes]:
- The button has a hover effect before logging into the FxA account; also, the 3 dots menu button displays a hover effect after logging into the account. 
- Here is a screencast of the issue:

![hover sync button](https://user-images.githubusercontent.com/26000308/33563331-53bd0aca-d920-11e7-8c4c-8bca74922679.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/425/commits/54c72425da3fb7a623d333b817f02439cf15c4a7
