### ISSUE TITLE
"Saved at (time)" text is displayed with a noticeable delay after disabling Sync 

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#475]
[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b7 installed.
- Log into a valid FxA.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the 3 dots menu button.
3. Click on the "Disable Sync" button and observe the "Saved at..." area at the bottom of the Sidebar.

[Expected result]:
- The "Saved at (time)" text is displayed right after disabling Sync.

[Actual result]:
- The "Saved at (time)" text is displayed with a ~3 seconds delay after the Sync disabling animation.

[Notes]:
- Here is a screencast of the issue:

![delay sync](https://user-images.githubusercontent.com/26000308/33563403-897ec914-d920-11e7-902f-bedd9c9e57f1.gif)

**Comment by vladikoff** [comment]
Minor ux problem, moving to enhancement

**Comment by sebastienbarbier** [comment]
This has been resolved during the react migration 👍
![no-more-delay-on-disconnect](https://user-images.githubusercontent.com/3018618/36605641-989e6446-18c1-11e8-8088-b358fc74c251.gif)
