### ISSUE TITLE
Notes state doesn't go into "Reconnect to Sync" state only if the "Sync" button is clicked or  the content in Notes sidebar is updated

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#481]
**[Notes]:**
- The Notes state is updated into "Reconnect to Sync" state when the user clicks the "Sync" button or updates the content in Notes sidebar.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b7) installed.
- Have content in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://accounts.firefox.com/settings/clients
3. Revoke Notes and observe the "Notes" state.

**[Expected result]:**
- Notes goes into "Reconnect to Sync" state.

**[Actual result]:**
- Notes state doesn't change.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![revoke_access](https://user-images.githubusercontent.com/20083658/33620902-de07bd02-d9f1-11e7-855c-3b66853dc000.gif)

**Comment by vladikoff** [comment]
@SoftVision-EmilPasca 

> Revoke Notes and observe the "Notes" state.


Just like "Reset" and "Change" it will only go into the reconnect state after it tries to Sync. It doesn't get any other signals to trigger the "Reconnect" warning

**Comment by vladikoff** [comment]
This is expected, you should get "Reconnect to Sync" when you:

 Reopen the sidebar or change content (trigger sync).
