### ISSUE TITLE
The "Syncing changes..." message does not disappear in other windows after reconnecting

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#482]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b8) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open another window and change your FxA password.
3. In the second window, click on the "Sync Your Notes" button and enter your credentials.
4. Switch to the first window and observe the sync status in the bottom part of the sidebar.

**[Expected result]:**
- The "Sync at (hour)" message is displayed.

**[Actual result]:**
-  The "Syncing changes..." message is displayed and the animation plays continuously. 

**[Notes]:**
- The issue is still reproducible even after the sidebar is focused, you paste content or you are writing something into it.
- If you click the "Sync Your Notes" button, after following the steps, then the content will be synced.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33662175-8d3a4d0c-da93-11e7-8b52-ac6787ab999b.gif)

**Comment by vladikoff** [comment]
Should be fixed in https://github.com/mozilla/notes/pull/425/commits/cbc878d0cdb5f75d63425ee3b7fa29a17448720c

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest "Firefox Notes" add-on version (2.0.0rc2) installed.
