### ISSUE TITLE
"Insecure Connection" page appears if you navigate to the sign in URL in a normal tab and try to log in

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#484]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" v2.0.0b8 installed.
- Have valid Firefox account credentials.
- You are not logged in the Notes Firefox Account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and click the "Sync Your Notes" icon.
2. Copy the URL from the new opened "Sign in to continue to Notes" window.
3. Paste the URL in a normal tab.
4. Enter your Firefox account credentials and press the "Sign in" button.
5. Observe the behavior.

[Expected result]:
- You are successfully logged in.

[Actual result]:
- "Insecure Connection" page is displayed.

[Notes]: 
- This issue is also reproducible in the original "Sign in" window if you "Disable Sync" using the steps from #483. 
- Here is a screen recording of the issue:
![insecure connection page](https://user-images.githubusercontent.com/31244235/33666100-a280dba0-daa1-11e7-9416-dd3fdb6a2c31.gif)

**Comment by Natim** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1411646&sourceid=Mozilla-search

**Comment by Natim** [comment]
I guess that's expected because you are starting the login flow manually and then we are redirecting to an signaled URL that is not catched anymore. So I would fix it as a wontfix.

**Comment by vladikoff** [comment]
This is a WONTFIX for now, we shall keep an eye on it though.
