### ISSUE TITLE
Login animation briefly appears after you reopen the "Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#486]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" v2.0.0b8 installed.
- You are logged in a valid Notes Firefox Account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and close the "Notes" sidebar.
2. Reopen the sidebar and observe what is displayed in the bottom part.

[Expected result]:
- "Sync Your Notes" icon, "Synced at.." message and the three dots appear.

[Actual result]:
- Login animation briefly appears.

[Notes]: 
- This issue is also reproducible if you switch the sidebar to another section (eg. "Bookmarks") and return to "Notes".
- Here is a screen recording of the issue:
![login animation - notes](https://user-images.githubusercontent.com/31244235/33668914-bacc45d4-daa9-11e7-82a1-b3ea15d50990.gif)

**Comment by vladikoff** [comment]
Good find, unless @ryanfeeley really hates it , we shall fix it post sync release.

@ryanfeeley see the bottom left of the GIF, does it make you mad?

**Comment by ryanfeeley** [comment]
Seems janky. Fix after Sync release. People are dying for Sync!

**Comment by sebastienbarbier** [comment]
Just fixed this issue on PR #550.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v2.3.0dev (custom built on 2018-02-15), on latest Nightly build 60.0a1 (2018-02-14), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
