### ISSUE TITLE
Sync does not work if "Tabmarks" add-on is enabled

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#488]
**[Affected versions]:**
- Firefox 57.0.1 and up
- Tabmarks 1.0.0beta3

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b8) and Tabmarks (1.0.0beta3 - https://addons.mozilla.org/en-US/firefox/addon/tabmarks/) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Syne Your Notes" button and observe.

**[Expected result]:**
- The "Firefox Notes Account" window is opened.

**[Actual result]:**
- A blank new tab is opened.

**[Notes]:**
- Attached a screen recording of the issue:
![tabmarks_issue](https://user-images.githubusercontent.com/20083658/33669097-35de9380-daaa-11e7-9778-efe784259ca4.gif)

**Comment by vladikoff** [comment]
Firefox WebExtension bug it seems, @SoftVision-EmilPasca I will try to file a Firefox bug for this.

Pretty scary!

**Comment by Natim** [comment]
This seems to be pretty impacting for sure.

**Comment by SoftVision-EmilPasca** [comment]
Refs [bug 1429358](https://bugzilla.mozilla.org/show_bug.cgi?id=1429358).

**Comment by Natim** [comment]
I am going to close this bug and handle it in the Bugzilla issue.
