### ISSUE TITLE
[Windows] Sidebar's border is black instead of gray on Firefox Nightly

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#489]
[Affected versions]:
- Firefox Nightly 59.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b8 installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the color of the Sidebar's border.

[Expected result]:
- The color of the Sidebar's border is grey.

[Actual result]:
- The color of the Sidebar's border is black.

[Additional Notes]:
- This issue also applies to the other existing Sidebars: Bookmarks, History and Synced Tabs.
- Here is a screenshot of the issue:

![border is black](https://user-images.githubusercontent.com/26000308/33669278-aa8cc846-daaa-11e7-9c3a-6cdd1d449885.png)

**Comment by vladikoff** [comment]
Detailed find! Moving to Firefox Bug for now. This might be by design, they are trying to make the resize drag space easier to move

**Comment by SoftVision-CarmenFat** [comment]
This issue is no longer reproducible on latest Nightly 59.0a1 (2017-12-29).
