### ISSUE TITLE
The text is not saved nor synced if it's dragged and dropped on the content area of the Sidebar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#490]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b8 installed.
- Have a website with text opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Select some text from the opened website (e.g. www.wikipedia.org)
3. Drag and drop the selected text into the Sidebar.
4. Observe the bottom part of the Sidebar.

[Expected result]:
- "Saving changes..." string is displayed for a couple of seconds, then it's replaced with "Saved at (hour) AM/PM" string.

[Actual result]:
- Nothing happens, previous "Saved at (hour) AM/PM" string is still displayed.

[Additional Notes]:
- This is more visible if the user closes and reopens the Sidebar after dropping the text in the content area. After reopening it, the text that was previously dropped is no longer displayed in the Sidebar.
- This issue also happens when the user is logged into the FxA and tries to sync the information.
- The issue is not reproducible when copying and pasting the text with shortcut keys and through context menu.
- The dragged and dropped text seems to be saved if copying and pasting another (or the same text) right after that (even though it's saved, the string that shows its saving time it's not updated). 
- Here is a screencast of the issue:	

![drag and drop text](https://user-images.githubusercontent.com/26000308/33670107-ee05c5ee-daac-11e7-8082-a18a3fb1f42b.gif)

**Comment by vladikoff** [comment]
CKEditor bug, we are going to try to add a manual trigger

**Comment by vladikoff** [comment]
Needs changes to https://github.com/mozilla/notes/commit/a4510bdbaf38dceffd7206903871b9d69785d9f6

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/425/commits/bf64e701ef0a740442f1ef8164613dce04d98ac1

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with Firefox Notes v.2.0.0rc2.

**Comment by vladikoff** [comment]
yaaay
