### ISSUE TITLE
The text is erased when logging into Fxa if it was previously dragged and dropped on the Sidebar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#491]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b8 installed.
- Have some dragged and dropped text in the Sidebar.
- Have a valid FxA.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Sync Your Notes" button and log into the FxA.
3. Observe what happens with the dragged and dropped text after logging in the FxA. 

[Expected result]:
- The dragged and dropped is still displayed, alongside the synced data from the FxA. 

[Actual result]:
- The dragged and dropped text is erased; only the synced data from the FxA is displayed.

[Additional Notes]:
- The issue is not reproducible when copying and pasting the text with shortcut keys and through context menu.
- The dragged and dropped text seems to be saved if copying and pasting another (or the same text) right after that (even though it's saved, the string that shows its saving time it's not updated). 
- Here is a screencast of the issue:

![drag and drop text new acc](https://user-images.githubusercontent.com/26000308/33670167-1cc7c3aa-daad-11e7-8979-e06eabe6bd0f.gif)

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/425/commits/bf64e701ef0a740442f1ef8164613dce04d98ac1

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible with Firefox Notes v.2.0.0rc2.
