### ISSUE TITLE
The "Firefox Notes" sidebar has a noticeable delay when it's reopened or switched if the user is logged into the FxA

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#492]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0b8 installed.
- Have the "Firefox Notes" sidebar closed.
- Log into the FxA.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the "Show sidebars" button from the browser toolbar and observe the sidebar behavior.

[Expected result]:
- The sidebar is displayed almost instantly.

[Actual result]:
- The sidebar is displayed after a delay (~3 seconds).

[Notes]:
- The issue is reproducible only with the "Firefox Notes" sidebar.
- Attached a screen recording of the issue:

![delay fxa](https://user-images.githubusercontent.com/26000308/33670190-2ebc2cd6-daad-11e7-8dd2-34ddc941ab9e.gif)

**Comment by vladikoff** [comment]
Yeah, probably for post first Sync release, we shall try to speed it up

**Comment by sebastienbarbier** [comment]
This has been fixed in v4
