### ISSUE TITLE
Military time format isn't displayed when certain languages or locales are set

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#494]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" v2.0.0b8 installed.
- Have the Firefox profile language set to "German [de]".
- You are logged in a valid Notes Firefox Account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the displayed hour in the bottom part of the "Notes" sidebar.

[Expected result]:
- Military time is displayed.

[Actual result]:
- "AM/PM" format time is displayed.

[Notes]: 
- This issue is also reproducible if you change the Date/Time format of the OS.
- This issue is also reproducible if you're not logged into Notes Firefox Account.
- Here is a screen recording of the issue:
![military time format](https://user-images.githubusercontent.com/31244235/33672130-231d2efc-dab2-11e7-9660-e4e2e5baf3a7.gif)

**Comment by vladikoff** [comment]
@Softvision-CristinaBadescu this is an interesting one. The only way I found to see this "working" is if you download a localized build: https://www.mozilla.org/en-US/firefox/all/

Switching the locale doesn't help trigger the change to time format :(
Some more information here: https://github.com/mozilla/notes/issues/395

**Comment by vladikoff** [comment]
We just use:

```
return new Date(date).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'});
```

so we have no control over this. We will need to file a Firefox (WebExtension?) bug I think

https://github.com/mozilla/notes/pull/425/files#diff-d4283f712f8a9b9152bc585b8ad742d8R159

Marking this as a Firefox bug

**Comment by Softvision-CristinaBadescu** [comment]
Thanks for the information @vladikoff! Indeed, this issue is no longer reproducible when I use a localized build.

**Comment by pdehaan** [comment]
@vladikoff Do we need to use [**moment.js**](https://github.com/moment/moment) or [**luxon**](https://github.com/moment/luxon) or something similar?

**Comment by pdehaan** [comment]
Another possibility is passing `navigator.languages` array to `.toLocaleTimeString()`:

```js
navigator.languages // Array [ "de", "en-CA", "en" ]
new Date().toLocaleTimeString(navigator.languages) // "08:19:00"

navigator.languages // Array [ "en-CA", "en", "de" ]
new Date().toLocaleTimeString(navigator.languages) // "8:20:13 a.m."
```

**Comment by vladikoff** [comment]
@pdehaan Firefox should do that automatically, we need to figure out what happened to `useragent.locale`, see https://github.com/mozilla/notes/issues/395#issuecomment-345047300

**Comment by vladikoff** [comment]
Needs a firefox investigation...
