### ISSUE TITLE
Feedback button from the menu is wrongly the first item to be focused when Tab is pressed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#495]
**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0b8) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and press the "Tab" key once.
3. Press the "Enter" key and observe the behavior.

**[Expected result]:**
- The content is synced.

**[Actual result]:**
- The "Give feedback" page is opened. 

**[Additional Notes]:**
- The issue is also reproducible if you are not logged into "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33674362-f1e6dc06-dab7-11e7-9947-249318e6c232.gif)

**Comment by vladikoff** [comment]
Thanks! Fixed in https://github.com/mozilla/notes/pull/425/commits/487ccf2d2e650544849c101468d0f99145e8c0d3

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest "Firefox Notes" add-on version (2.0.0rc2) installed.
