### ISSUE TITLE
[Windows] Theme options aren't displayed for Notes in "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#498]
**[Notes]:**
- The issue is intermitent.

**[Affected versions]:**
- Firefox 57.0.1 and up

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and double-click on "Firefox Notes".
3. Observe the "Firefox Notes" theme options.

**[Expected result]:**
- "Firefox Notes" theme options are displayed.

**[Actual result]:**
- "Firefox Notes" theme options aren't displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![notes_issue_themeoptions](https://user-images.githubusercontent.com/20083658/33721218-076d322a-db6f-11e7-814a-fea2ef2bdba2.gif)

**Comment by vladikoff** [comment]
Firefox bug heh

**Comment by Natim** [comment]
Can I let you file a Bugzilla issue for this one?

**Comment by SoftVision-EmilPasca** [comment]
@Natim  sure, will do.

**Comment by SoftVision-EmilPasca** [comment]
Refs: https://bugzilla.mozilla.org/show_bug.cgi?id=1427983

**Comment by vladikoff** [comment]
WONTFIX https://bugzilla.mozilla.org/show_bug.cgi?id=1427983#a4084030_481559, please reopen if you see this happen with normal TestPilot installation process
