### ISSUE TITLE
[Nightly] Text and icon from the sidebar switcher door hanger are wrongly aligned to the left and the icon is replaced with a "check" sign when selecting Notes

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#499]
[Affected versions]:
- Firefox Nightly 59.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0rc2 installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the sidebars switch button and observe the way that "Notes" sidebar option is displayed.
BONUS:
3. Click on the "Notes" option from the drop down.
4. Click again on the sidebars switch button and observe the way that "Notes" sidebar option is displayed.

[Expected result]:
2. "Notes" text and icon are displayed centered and aligned with the rest of the sidebars.
4. A "check" sign is displayed on the left side of the "Notes" icon.

[Actual result]:
2. "Notes" text and icon are displayed to the left and are not aligned with the rest of the sidebars.
4. The "check" sign is displayed instead of the "Notes" icon.

[Additional Notes]:
- Here is a screencast of the issue:

![nightly icon and text](https://user-images.githubusercontent.com/26000308/33723079-54bbaac0-db74-11e7-96cc-615fa024a4f2.gif)

**Comment by Natim** [comment]
Can I let you create a Firefox Bugzilla issue for this one?

**Comment by SoftVision-CarmenFat** [comment]
Sure, filed issue: [1424259](https://bugzilla.mozilla.org/show_bug.cgi?id=1424259).

**Comment by Natim** [comment]
I will close this since it is a design choice that has been made by Firefox UX and the bug is open there.
