### ISSUE TITLE
Sync arrows button doesn't become blue when syncing if Dark theme is enabled

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#500]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0rc2 installed.
- Have Dark theme enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Sync Your Notes" button and observe what happens next.

[Expected result]:
- The Sync arrows are blue during sync animation.

[Actual result]:
- The Sync arrows remain white during sync animation.

[Additional Notes]:
- Here is a screencast of the issue:

![blue sync](https://user-images.githubusercontent.com/26000308/33723594-c77fb898-db75-11e7-80d1-d42f1e590e28.gif)

**Comment by vladikoff** [comment]
good find! 👍

**Comment by Natim** [comment]
@cedricium do you know if that's the expected behavior?

**Comment by Natim** [comment]
I would say that it is part of the design not to use blue here. @ryanfeeley feel free to disagree.
