### ISSUE TITLE
Text cursor doubles its width if the text is written with special characters

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#501]
[Affected versions]:
- Firefox 57.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" v2.0.0rc2 installed.
- Have Chinese, Japanese or Coreean text written in the Sidebar.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Make some random clicks through the characters and observe the text cursor.

[Expected result]:
- The text cursor is displayed at its proper width.

[Actual result]:
- The text cursor seems to double its width.

[Additional Notes]:
- Here is a screencast of the issue:

![special characters](https://user-images.githubusercontent.com/26000308/33723746-2181fcd4-db76-11e7-9782-25b9bb099658.gif)

**Comment by Natim** [comment]
If I am not wrong it is a feature of the browser so that we don't mix the cursor with characters parts.
