### ISSUE TITLE
Sync remains in reconnecting loop after signing in with valid credentials

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#503]
**[Affected versions]:**
- Firefox 57.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile with the latest "Firefox Notes" add-on version (2.0.0rc2) installed.
- Have valid FxA credentials.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button from the bottom-right part of the sidebar.
3. Sign in with the credentials from prerequisites.
4. Observe the sync status in the bottom part of the sidebar.

**[Expected result]:**
- The "Sync at (hour)" message is displayed.

**[Actual result]:**
- The "Reconnect to Sync" message is displayed. 

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/33763407-15b57360-dc19-11e7-9a5f-79bdb435c428.gif)

**Comment by Natim** [comment]
Can you give us more information especially the HTTP code that you get from kinto in the web console network panel?

**Comment by Natim** [comment]
I guess it could be the Insufficient Storage error and we should probably think about handling that error.

**Comment by Natim** [comment]
![boom](https://user-images.githubusercontent.com/229453/33770628-b25f2cdc-dc2e-11e7-8ca1-220584c14ace.png)

**Comment by Natim** [comment]
@vladikoff @rfk ^

**Comment by Natim** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1424277

**Comment by vladikoff** [comment]
@Softvision-MariusComan @SoftVision-EmilPasca @Natim We have identified a problem with the Firefox Accounts deploy, fix incoming for login in 1-2 hours. Sorry about that!

**Comment by vladikoff** [comment]
Tracking deploys here: https://bugzilla.mozilla.org/show_bug.cgi?id=1421486#c18

**Comment by vladikoff** [comment]
This was fixed!

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest version of Firefox Notes (2.0.0rc3) on the latest Firefox release and Nightly.
