### ISSUE TITLE
Bullets and numbered are one sized

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#51]
Is this just the library we're using?
<img width="122" alt="image" src="https://user-images.githubusercontent.com/68213/27195655-95b7eae4-51d5-11e7-8fdc-c30fc563b205.png">

**Comment by vladikoff** [comment]
Might be able to fix that up with some CSS changes to the theme

**Comment by Natim** [comment]
It is related both to the editor and the way HTML works.

When you change the text size, it changes the selection you made. However the list encompass the whole text so it stays with the quill.js editor size.

Are you expecting the 1 and 7 to be 12px, the 2 and 6 to be 14px, the 3 and 5 to be 16px and 4 to be 18px?

Would it work if in a list the font-size was set to the li directly?

**Comment by vladikoff** [comment]
@Natim Quill has this custom css file that hides the native bullets and replaces them with CSS `content: ...`. 

It might be a Firefox bug (didn't check Chrome) where the styles do not apply to `content: ` OR maybe we just need a bit of CSS.

**Comment by Natim** [comment]
Refs https://github.com/quilljs/quill/issues/409

**Comment by vladikoff** [comment]
@Natim good find!

**Comment by Natim** [comment]
I started to look at it be it is far from being trivial: https://github.com/quilljs/quill/pull/1592
