### ISSUE TITLE
Implement links using the ckeditor5-link plugin

### ISSUE THREAD

**Issue by cedricium** [mozilla/notes#514]
After doing some research into how to implement links that will follow @ryanfeeley's design ([mockup here](https://mozilla.invisionapp.com/share/6VBUYHMRB#/screens/235284916)), I think it will be best to use the `ckeditor5-link` plugin. There is some work needed for this to work which I outline below.

**Background:**
The `ckeditor5-link` plugin has a main class `Link` which sets up a `LinkFormView` inside the parent container (which is the `ContextualBalloon`, a single instance of `BalloonPanelView`).

**Proposal:**
Instead of using `ContextualBalloon`, I think creating a new class that extends `View` and is styled to be positioned at the top of the editor's editable content would be the best way to go. We can then edit `Link` to place the `LinkFormView` inside our newly-created class as a child element.

Thoughts? cc @vladikoff @Natim

**Comment by vladikoff** [comment]
Changes to `-link` plugin: https://github.com/ckeditor/ckeditor5/issues/645#issuecomment-362608165

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/notes/issues/396
