### ISSUE TITLE
The "Firefox Notes" sidebar does not focus if you drag and drop a text into it

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#518]
**[Affected versions]:**
- Firefox 57.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.18.2017) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any website and select a text from the page.
3. Drag the text into the sidebar and observe the behavior.

**[Expected result]:**
- The sidebar is focused.

**[Actual result]:**
- The sidebar is not focused. 

**[Notes]:**
- After following the provided STR, the website is focused instead of the sidebar, and you cannot perform any action on the text using keyboard. The actions are applied on the website.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34112513-73c0a520-e415-11e7-9b6c-eb625b15d738.gif)

**Comment by himanish-star** [comment]
@Softvision-MariusComan , I would like to give this a try . May I ?

**Comment by vladikoff** [comment]
Sure !

**Comment by Natim** [comment]
@himanish-star I would be interested to know if you think it is a Firefox Bug or rather a CKeditor one.

**Comment by himanish-star** [comment]
@Natim , I have no idea whether it's a Firefox Bug or a CKeditor Bug. Rather I heard CKeditor for the first time now. I believe I'll start debugging from editor.js file.

**Comment by himanish-star** [comment]
@Natim , I can't understand why `console.log()` doesn't work in `editor.js` file. Could you help ? The logging doesn't appear in the web console

**Comment by Natim** [comment]
I guess you need to open the debugger. Go to about:debugging and then click on the Debugger button for the Firefox Notes addon.

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed. Considering this, I am reopening the issue.

**Comment by himanish-star** [comment]
@Softvision-MariusComan , Ok I'm checking on this.

**Comment by Softvision-MariusComan** [comment]
Now the sidebar is focused when the text is dragged, but after that the text caret is not displayed in the sidebar and you cannot write or edit the content if you do not click on it.

**Comment by himanish-star** [comment]
>  but after that the text caret is not displayed in the sidebar and you cannot write or edit the content if you do not click on it.

@Softvision-MariusComan , the feature you are talking about didn't exist previously too(I recently checked), but if you want that feature too then I will try my level best to add that.

**Comment by Softvision-MariusComan** [comment]
@himanish-star, my mistake, I will open an enhancement for this feature. Thanks!

**Comment by himanish-star** [comment]
@Softvision-MariusComan , my pleasure and do notify me when you open the issue. I am eager to fix it
