### ISSUE TITLE
The "Firefox Notes Feedback" page is wrongly opened if you click the area around the "Notes" menu button

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#519]
**[Affected versions]:**
- Firefox 57.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.
- You are already logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click anywhere near the "Notes" (three dots) menu button.
3. Observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The "Firefox Notes Feedback" page is opened. 

**[Notes]:**
- The issue is also reproducible with the TxP version of "Firefox Notes".
- The issue is reproducible only if you are logged into "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34151566-519e7cde-e4b4-11e7-959b-58bca269ed45.gif)

**Comment by himanish-star** [comment]
I would like to try this

**Comment by vladikoff** [comment]
@himanish-star please!

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.12.2018) installed, on the latest Firefox release and Nightly.
