### ISSUE TITLE
Reduce indent on lists

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#52]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/68213/27195749-f3f5dcd8-51d5-11e7-984d-c282dac45592.png">

GitHub:
* has the left margin about right
* If you look at it

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/notes/issues/27 ?

**Comment by ryanfeeley** [comment]
@vladikoff Oops, yes.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/65/files
