### ISSUE TITLE
The text formatting buttons are grayed out if a formatted text from Edge browser is dragged in a new paragraph of the sidebar

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#520]
[Notes]:
- This issue is also reproducible in this case : #434.
- This issue is also reproducible for a non-formatted text, but you need to drag and drop it at least two times in the sidebar to encounter the issue.

[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Focus the "Notes" sidebar and press "Enter" key once in order to create a new paragraph.
3. Open Edge browser and navigate to a website that has formatted text (eg: https://en.wikipedia.org/wiki/Tree).
4. Drag a formatted text and drop into the "Notes" sidebar.
5. Observe the text formatting option buttons.

[Expected result]:
- The text formatting option buttons are correctly displayed and actionable.

[Actual result]:
- The text formatting option buttons are greyed out and unactionable.

[Additional notes]:
- After you type something while the text formatting buttons are greyed out, if you press "Enter" key it doesn't create a new paragraph.
- If you hit "Backspace" key the text formatting buttons become active again.
- Here is a screen recording of the issue:
![text formatting buttons](https://user-images.githubusercontent.com/31244235/34156565-6d22e492-e4c6-11e7-85fb-961a9dc180ac.gif)

**Comment by vladikoff** [comment]
This should be fixed! With the new CKEditor update

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest Firefox Notes v4.2.0dev, on latest Nightly build 63.0a1. Verified on Windows 10 x64.
