### ISSUE TITLE
The heading text is slightly moving when you click the "Bold" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#522]
[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.
- Have something written in the "Notes" sidebar.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Click inside the text from the sidebar and choose a heading font size.
3. Press "Bold" button.
4. Observe the behavior.

[Expected result]:
- Nothing happens.

[Actual result]:
- The text is slightly moving.

[Notes]:
- On Linux, for Heading 1 and Heading 2, this issue is reproducible only if you have text positioned below the heading text.
- This issue is not reproducible with other text editors such as Google Docs or LibreOffice.
- This issue is not reproducible for the "Paragraph" font size or for text organized in a list (bulleted or numbered).
- This issue is also reproducible when combining "Bold" and "Italic" formatting options.
- This issue is reproducible if you use the "Ctrl + B" and "Ctrl + I" keys combination.
- Here is a screen recording of the issue:
![slightly moving text](https://user-images.githubusercontent.com/31244235/34159504-29e3f62e-e4d2-11e7-8e56-df9d6c22f43d.gif)

**Comment by shikhar-scs** [comment]
This should not be an error. That's maybe because the font size gets increased a bit and so to accommodate the same font the text shakes a bit. Any other thoughts ?

**Comment by Natim** [comment]
Still the artefact is a bit weird.
