### ISSUE TITLE
[Multiple windows] New text entered after Notes was cleared is removed if pasted after "Saving changes...." state of sync occurs

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#524]
**[Notes]:**
- The issue is reproducible only if you paste/write the text right after the first "Saving changes...." message disappears, while the "Saved at (hour)" message is displayed.

**[Affected versions]:**
- Firefox 57.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.
- You are already logged into "Firefox Notes".
- Have content in the "Firefox Notes" sidebar.
- Have any content copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Press "Ctrl+N" to open a new window.
3. In the second window select and remove all the content.
4. After the "Saving changes...." message disappears, quickly paste the copied content from the prerequisites.
5. Observe the behavior.

**[Expected result]:**
- The content from step 4 is displayed.

**[Actual result]:**
- The content from step 4 is removed and the sidebar remains empty.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible if you write something instead pasting.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34160703-afe2eb82-e4d6-11e7-8f04-191628c6c7ec.gif)

**Comment by Natim** [comment]
Let's fix this by trying to figure out how to share the react state/redux store across opened sidebars.

**Comment by vladikoff** [comment]
This should be fixed in notes v4 beta 3
