### ISSUE TITLE
The content is duplicated if a new window is opened while the "Saving changes...." message is still displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#525]
**[Notes]:**
- The issue is reproducible only if the new window is opened while the "Saving changes...." message is still displayed.
- Also, the "**** On this computer: ****" message is wrongly displayed between the strings.

**[Affected versions]:**
- Firefox 57.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.19.2017) installed.
- You are already logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write/Paste some text into the "Firefox Notes" sidebar.
3. Open a new window while the "Saving changes...." message is still displayed.
4. Observe the behavior.

**[Expected result]:**
- Only the content from step 2 is displayed.

**[Actual result]:**
- The content from step 2 is duplicated and the "**** On this computer: ****" message is displayed between the strings.

**[Additional Notes]:**
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34163610-d9d8a23e-e4df-11e7-8fc6-196eaefd3799.gif)

**Comment by Natim** [comment]
I can reproduce anymore.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6 build) installed, on the latest Firefox release and Nightly.

**Comment by Softvision-CristinaBadescu** [comment]
I've managed to reproduce this issue using Firefox Notes v3.2.0dev (custom built on 2018-03-22) and also with Firefox Notes installed from Test Pilot experiments page, on latest Nightly build 61.0a1 and latest Firefox Release 59.0.1, on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.

Considering this, I'm going to reopen the issue.

**Comment by sebastienbarbier** [comment]
Should be fixed in v4.
