### ISSUE TITLE
Menu icon is not vertically centered

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#527]
It's off by 3 (HiDPI pixels)…
<img width="150" alt="screen shot 2017-12-18 at 4 49 02 pm" src="https://user-images.githubusercontent.com/68213/34167586-277c8e40-e4b0-11e7-9e2b-a5dd938d670e.png">

**Comment by himanish-star** [comment]
@ryanfeeley , I can fix this , May I ?

**Comment by vladikoff** [comment]
sure!
