### ISSUE TITLE
Remove left and right borders on Notes sidebar panels

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#529]
The left and right borders are not needed <img width="420" alt="screen shot 2017-12-13 at 2 52 27 pm" src="https://user-images.githubusercontent.com/68213/34173686-4dd42d3c-e4c4-11e7-9942-b308fcbba387.png">

**Comment by shikhar-scs** [comment]
@ryanfeeley If this issue is still up, I would love to solve this

**Comment by vladikoff** [comment]
Yeap those are the borders, you might have to modify some code to make that message show up

**Comment by shikhar-scs** [comment]
Ok thanx @vladikoff I'll work on it and file a PR soon
