### ISSUE TITLE
If you use Markdown formatting for "Bold" and "Italic", the "Notes" sidebar wrongly loses focus after saving or syncing changes

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#530]
[Regression]:
- This issue seems to be a regression. I've managed to find a regression-window. Here are the results:
Last good revision: 7fb001f811d183095e9cfdd958c9215484377396
First bad revision: d5e1ed773fefe2eb9d52402dd74b5fea19b8b4a4
Pushlog: https://goo.gl/kosEDa

Is there anything we can do to resolve this on the Notes side or should I file an issue in Bugzilla?

[Affected versions]:
- Firefox Nightly 59.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.20.2017) installed.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Type a bold word using markdown formatting (see this [screenshot](https://screenshots.firefox.com/jtS1KQxQnOl4A1pP/medium.com)).
3. Wait for the changes to be saved and observe the sidebar.

[Expected result]:
- The sidebar is focused.

[Actual result]:
- The sidebar loses its focus and the text caret disappears.

[Notes]:
- This issue is not reproducible for Heading, Ordered or Unordered lists.
- The text caret reappears if you press any key.
- Here is a screen recording of the issue:
![markdown formatting loses sidebar focus](https://user-images.githubusercontent.com/31244235/34207532-8f4e3c6a-e593-11e7-9e61-d09d40429bd6.gif)

**Comment by Natim** [comment]
Can you create a bugzilla issue for this one? Especially since you found the regression logs?

**Comment by Softvision-CristinaBadescu** [comment]
Of course :) I've filed it here: bug [1426348](https://bugzilla.mozilla.org/show_bug.cgi?id=1426348).

**Comment by Natim** [comment]
Thanks :)

**Comment by vladikoff** [comment]
@Softvision-CristinaBadescu  awesome 👍

**Comment by Natim** [comment]
After thinking about it again today, it is really possible for this to be a CKEditor bug.

**Comment by Natim** [comment]
@Softvision-CristinaBadescu I couldn't reproduce the focus loose but I had to type space multiple times.

@Mgsy I was able to reproduce in the https://ckeditor5.github.io/ are you aware of this bug already?

**Comment by Mgsy** [comment]
> @Mgsy I was able to reproduce in the https://ckeditor5.github.io/ are you aware of this bug already?

@Natim, I can't reproduce it in our editor. Can I ask you to provide exact steps to reproduce?

**Comment by Natim** [comment]
Yes,

Type a sentence in the editor using ** syntax to put a word in bold in the middle.

**Comment by Mgsy** [comment]
Thanks, I was testing it in `Firefox 57.0.4` and this bug is not reproducible with this browser version. After checking it in `Firefox 59`, I was able to reproduce it, so I guess it's not CKEditor issue.

**Comment by Natim** [comment]
Thank you for your investigation.

**Comment by Softvision-CristinaBadescu** [comment]
@Natim , I've still managed to reproduce this issue on Windows 10 x64,  on latest Nightly build 59.0a1 (2018-01-10), using the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) or "Firefox Notes" add-on version installed from Test Pilot experiment page: https://testpilot.firefox.com/experiments/notes.

Here is a screen recording with the issue: https://goo.gl/KtmE6k

I've also posted this information in the Bugzilla [filed bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1426348).

**Comment by Softvision-CristinaBadescu** [comment]
I've retested this issue and is no longer reproducible on latest Nightly build 60.0a1 (2018-01-24), using Firefox Notes from Test Pilot experiments page and Firefox Notes v2.2.0dev (custom built 2018-01-25), on Windows 10 x64, Mac 10.12.6 and Ubuntu 14.04 x64.
