### ISSUE TITLE
The background of the menu button is inconsistent on Default and Dark Themes

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#531]
[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with "Firefox Notes" (2.2.0dev custom build from 12.20.2017) installed.
- Have a valid FxA for Sync.
- Default Theme is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Sync Your Notes" button and observe the 3 dots menu button.
3. Type the valid credentials and log into the FxA.
4. Observe the 3 dots menu button.
5. Follow the steps above switching to Dark Theme and compare the menu button.

[Expected result]:
- The button looks the same on both Default and Dark Themes, even when in hover state.

[Actual result]:
1. Default Theme: 
- the button doesn't display any background when not hovering it.
- the button displays a dark background when hovering it. 

2. Dark Theme: 
- the button displays a dark background even when there is no hovering on it. 
- also, the button gains a hover state only when the user is logged into the FxA; when hovering it while verifying the account, the background of the button remains the same and no visual changes are displayed. 

[Notes]:
- Here is a screenshot of the issue:

![inconsistency menu button](https://user-images.githubusercontent.com/26000308/34217030-dfd7a670-e5b2-11e7-9e19-88fb5c2f3828.png)

**Comment by shikhar-scs** [comment]
@SoftVision-CarmenFat If this issue is still up,  I would like to work on this. May I?

**Comment by Natim** [comment]
> May I?

I think you can now assign yourself directly to issue, please just take one at the time though.

**Comment by Natim** [comment]
> Do we need to remove background change on hover completely ?

No the goal is to handle the hover background in both themes.

**Comment by shikhar-scs** [comment]
Ok I think I get the issue now, I'll enable hover now only when the cursor is actually hovering on the small rectangular div around three dots. I'll see for myself what the colors should be and meanwhile any of the mentors can also suggest the same.

> , please just take one at the time though. 

I'll keep that in mind for sure now.

**Comment by shikhar-scs** [comment]
This can be closed now

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.
