### ISSUE TITLE
Text isn't dropped in the text caret indicated position

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#532]
[Notes]:
- Also, you cannot drop text from "Notes" sidebar into another position in "Notes" sidebar.

[Affected versions]:
- Firefox 57.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 12.21.2017) installed.
- Have something written in the "Notes" sidebar.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to a website and select a text (eg. https://en.wikipedia.org/wiki/Tree).
3. Drag the text in a desired position in the "Notes" sidebar.
4. Drop it and observe where the text is placed.

[Expected result]:
- The text is placed in the indicated position by the text caret.

[Actual result]:
- The text isn't placed in the indicated position by the text caret, it's wrongly placed in the text caret last position.

[Additional notes]:
- This issue is not reproducible with other text editors, such as Google Docs or LibreOffice.
- Here is a screen recording of the issue:
![drop text in text caret indicated position](https://user-images.githubusercontent.com/31244235/34255503-af65b9bc-e659-11e7-8d77-e965aa1739bc.gif)

**Comment by himanish-star** [comment]
@Softvision-CristinaBadescu , I would like to take up this issue. May I  ?

**Comment by Softvision-CristinaBadescu** [comment]
This isn't up to me, but @Natim or @vladikoff  are entitled to say if you can start working on this. Thanks for understanding :)

**Comment by himanish-star** [comment]
@Natim, @vladikoff. I would like to take this issue. Also I want to know that how do we get the current cursor position in the CKeditor. I tried using [`getRanges`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_view_selection-Selection.html#getRanges) but it didn't work. Could anyone of you both guide me here

**Comment by vladikoff** [comment]
@himanish-star first check if the same bug is present on https://ckeditor5.github.io/

**Comment by vladikoff** [comment]
@himanish-star we need to confirm if it is a CKEditor bug or something else
