### ISSUE TITLE
Add toolbar button to open note sidebar

### ISSUE THREAD

**Issue by sebastienbarbier** [mozilla/notes#535]
Ref [Bug 1341126](https://bugzilla.mozilla.org/show_bug.cgi?id=1341126): 
Documentation: 
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction/open
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction/close

**Comment by vladikoff** [comment]
@Natim Leaving this Enhancement for Shield
