### ISSUE TITLE
Add selection context menu to send selection to note

### ISSUE THREAD

**Issue by sebastienbarbier** [mozilla/notes#536]
![contextmenusendtonotes](https://user-images.githubusercontent.com/229453/34514986-47d75dfc-f070-11e7-987c-1015fbd54a7b.png)

**Comment by vladikoff** [comment]
@cedricium if you have time, do you wanna check this one out? See if this works with Sidebar webextensions?

**Comment by cedricium** [comment]
@vladikoff sure thing! 👍
