### ISSUE TITLE
Start time should not be about 3 seconds

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#538]
When sync is enabled, start time is about 3 seconds: 

    Start time:  2851

We should aim at making it a couple hundreds milliseconds.

**Comment by shikhar-scs** [comment]
@Natim May I work on this issue ?
(If Yes)I know where to make the required changes, I'll try and do it ASAP.

**Comment by Natim** [comment]
Hi @shikhar-scs feel free to start a Pull-Request with what you have in mind it will definitely help.

**Comment by shikhar-scs** [comment]
@Natim Ok I'll start rightaway.

**Comment by shikhar-scs** [comment]
@Natim is there some precise time you would like me to set it to or may I put say 300ms for it ?

**Comment by Natim** [comment]
We want to reduce it as much as possible.

**Comment by himanish-star** [comment]
@shikhar-scs , If you don't mind could I take over this. If I make no way here then I will surely return you back this issue

**Comment by shikhar-scs** [comment]
Yeah Sure, go on its yours

**Comment by himanish-star** [comment]
Thanks @shikhar-scs
