### ISSUE TITLE
[Enhancement] Keep "Dark" theme on a synced account after reinstalling the add-on 

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#539]
[Affected versions]:
- Firefox 57.0.3 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version installed from Test Pilot experiment page (https://testpilot.firefox.com/experiments/notes).
- Be logged in a valid Firefox "Notes" account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select "Extensions" section.
3. Select Firefox "Notes" and choose "Dark" theme.
4. Remove the addon and refresh the page.
5. Install again the addon and log in the "Notes" account.
5. Observe the sidebar's theme.

[Expected result]:
- The sidebar's theme is "Dark".

[Actual result]:
- The sidebar's theme is "Default".

[Notes]:
- This issue is not reproducible if you remove the addon, don't refresh the "about:addons" page and press "Undo".
- This issue is also reproducible with the latest Firefox "Notes" add-on version (2.2.0dev custom build from 01.03.2018) installed.
- Here is a screen recording of the issue:
  
![keep dark theme](https://user-images.githubusercontent.com/31244235/34528235-eb2ec1a8-f0b0-11e7-8ed9-f65e94ac814c.gif)

**Comment by vladikoff** [comment]
if the user is connected to Firefox Sync and we use the `browser sync ` APIs we might be able to sync the prefs across profiles..
