### ISSUE TITLE
[User Feedback] Slack pasting adds extra line breaks

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#540]
> Spacing is really wide when I paste from the sidebar notes panel into Slack. It feels three times wider than it should be. Also, I’d prefer it if it could be plain text, not rich text. I don’t use it to get nicely formatted text that then lives inside Firefox — I use it to paste from, to elsewhere, and when I paste out of the sidebar the formatting gets stripped anyway (which prevents me from doing * bullet points that persist after pasting.)

**Comment by Natim** [comment]
Hpw can we handle Ctrl+Shift+V for plain text paste?

**Comment by Reinmar** [comment]
Works fine for me e.g. on https://ckeditor5.github.io. Can you check there?

**Comment by Natim** [comment]
Yes actually it works fine for me too. I am going to close this one as wontfix.
