### ISSUE TITLE
[User Feedback] Too many conflicts

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#542]
> Before the sync feature, I had a 104 lines note. CKEditor was starting to freeze, I wrote a feedback and remarked that the 104 lines note was transformed into a 9004 lines note with a lot of redundance prefixed by `***on the computer***`. What is that? How to get rid of those duplications?

**Comment by vladikoff** [comment]
If if we are shipping Sync in Shield we should try to fix this one

**Comment by Natim** [comment]
I believe fixing #546 should have fixed this

**Comment by Natim** [comment]
The question here is should we sync the conflict or wait for it to be resolved first before syncing it?

We could display a note telling the user to fix the conflict until we don't detect the merge conflict string in the content?

We could also wait for multiple notes and create two notes in case there is a conflict?

**Comment by Natim** [comment]
@ryanfeeley what do you think about that?

**Comment by vladikoff** [comment]
Being fixed as part of https://github.com/mozilla/notes/pull/743 and multi-note milestone
