### ISSUE TITLE
Add a limit to the number of char in the editor to avoid it breaking after 9000 lines

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#546]
Maybe we should port: https://ckeditor.com/old/forums/CKEditor-3.x/Character-Count-Plugin

**Comment by Natim** [comment]
Refs #541

**Comment by shikhar-scs** [comment]
@Natim I went over the documentation here [ https://ckeditor.com/old/forums/CKEditor-3.x/Character-Count-Plugin]( https://ckeditor.com/old/forums/CKEditor-3.x/Character-Count-Plugin).
I believe I'll be able to achieve this with a little bit of help.
I would like to take up this issue please.

**Comment by vladikoff** [comment]
@shikhar-scs if this helps, here's an example of a plugin for CKEditor 5: https://github.com/alexeckermann/ckeditor5-emptyness

**Comment by shikhar-scs** [comment]
Thanx @vladikoff for this

**Comment by shikhar-scs** [comment]
@Natim @vladikoff I've tried to incorporate changes taking inputs from [https://ckeditor.com/old/forums/CKEditor-3.x/Character-Count-Plugin](https://ckeditor.com/old/forums/CKEditor-3.x/Character-Count-Plugin) and [https://github.com/alexeckermann/ckeditor5-emptyness](https://github.com/alexeckermann/ckeditor5-emptyness) and also files already present in the main directory.
As of now I've made a few changes however they do not reflect on the notes side bar.

 And also I am unable to use console.log or the element-inspector in the` notes side view `because of which it is becoming really difficult for me to identify and rectify errors. Is there any substitute for the same ?

I've pushed all my current code [here](https://github.com/shikhar-scs/notes/commit/7452872fed6842f6f7d804f6ae0bb4fddb86f4ec).
Please have a look and review it

**Comment by shikhar-scs** [comment]
@vladikoff mind helping here a bit 😅

**Comment by Natim** [comment]
@shikhar-scs Make sure to run `npm run postinstall` if you change the ckeditor code so that it is rebuilt.
To open the console for the add-on, you need to go to `about:debugging` and then open the debugger for Firefox Notes

**Comment by shikhar-scs** [comment]
Ok @Natim I'll try this

**Comment by shikhar-scs** [comment]
@Natim of late this error is popping up since the last 2 hrs. The notes sidebar is blank throughout. Here's what I mean.
![screenshot from 2018-01-05 21-31-33](https://user-images.githubusercontent.com/25258877/34616984-ed47a35a-f25f-11e7-87b1-aa20f1ca522c.png)

This is really confusing and could you please help me on how to restore the original stuff. Because of this I am not being able to continue work on this original issue

**Comment by Natim** [comment]
It could be #512 can you look at the debugger to see what is up?

**Comment by shikhar-scs** [comment]
I went through #512 and my error there was solved.

I have made some new changes in pushed them in my local repo. Please have a look, though they don't completely solve the problem and also they have a bit of errors showing up in the console as follows

```
 "toolbarview-item-unavailable: The requested toolbar item is unavailable. Read more: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/framework/guides/support/error-codes.html#toolbarview-item-unavailable
" Object { name: "charcount" }  ckeditor.js:5:31899

```
and
```TypeError: n.editor is undefined
Stack trace:
init/<@moz-extension://39a20afa-894e-4338-b645-040f24c3d90b/sidebar/vendor/ckeditor.js:20:252
fire@moz-extension://39a20afa-894e-4338-b645-040f24c3d90b/sidebar/vendor/ckeditor.js:5:16926
create/</<@moz-extension://39a20afa-894e-4338-b645-040f24c3d90b/sidebar/vendor/ckeditor.js:5:194796
  panel.js:163:3
```

I tried looking out for them clueless and thought the mentors could be of more help.

My pushed code is here -> [https://github.com/mozilla/notes/compare/master...shikhar-scs:introducing-word-count](https://github.com/mozilla/notes/compare/master...shikhar-scs:introducing-word-count). Please have a look and guide me accordingly.

**Comment by shikhar-scs** [comment]
@Natim May I use something like [this](http://cssdeck.com/labs/charactercount/). It looks much simpler, easy to use,understand and incorporate. Please have a look there

**Comment by shikhar-scs** [comment]
@Natim I was trying to setup word count taking references from https://ckeditor.com/cke4/addon/wordcount . However,
```
3.    Extract the .zip folders for both the Word Count & Char Count and Notification plugin. After extraction, you should have a folder named **wordcount** and a folder named **notification**.
4.    Move the wordcount folder to /web/server/root/ckeditor/plugins/.  Move the notification folder to /web/server/root/ckeditor/plugins/.
5.    Add the following line of text to the config.js file, which is located at /web/server/root/ckeditor/.
```
Had a few doubts,
Plugins folder doesn't exist as of now, so should I create a new one ? And will `./ckeditor-build` be the equivalent of `root/ckeditor/.` folder being talked about above ?

**Comment by shikhar-scs** [comment]
@Natim mind helping a bit please.

**Comment by Natim** [comment]
Actually the wordcount plugin your are talking about is for ckeditor 4 rather than ckeditor 5.
I guess you would need to write a plugin for ckeditor5 that would take place in the `ckeditor-build/src` folder and be loaded somehow in `ckeditor-build/src/ckeditor.js`

**Comment by Natim** [comment]
@ryanfeeley Is this content acceptable ?

![is this correct](https://user-images.githubusercontent.com/229453/35339473-0560bce0-0121-11e8-94f6-980bbc3a14f3.png)

**Comment by shikhar-scs** [comment]
This does look good actually :+1:

**Comment by ryanfeeley** [comment]
@Natim Pretty good! Does this behave like a text input ``maxlength`` where you can’t enter more text? That, combined with showing this footer message is be perfect behaviour. Perhaps we should put the error first.

In terms of style, this is an error that so we should follow our [design system](https://design.firefox.com/photon/components/message-bars.html#error) colors. White type on a red background.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/68213/35354323-abd762cc-0117-11e8-9a50-e74aa721b825.png">

I am still thinking about copy... @Natim Is the 9K limit imposed on us by CKEditor?

**Comment by Natim** [comment]
> In terms of style

I reused the box we already had for the migration but I could probably add a new one with this style.

> Is the 9K limit imposed on us by CKEditor?

No it's not, eventually I used characters instead of lines and I start to display the message after 5000 characters and then forbid new characters after 6000.

For merge conflicts I allow for 12000 characters so that you can display both.
