### ISSUE TITLE
Notes loops on Save until closed and reopened

### ISSUE THREAD

**Issue by ddurst** [mozilla/notes#547]
I'm not sure how to trigger this, but it seems to be related to quickly typing something then selecting it and attempting to bold it? Maybe combined with the save?

The result is a loop: every approx three seconds, it alternates state from A to B and loops indefinitely, where A is prior to some keystroke and the status line reads "Saved at {time}" (worth noting that {time{ does get updated) and B is A with keystroke registered and the status line reads "Saving changes..." Any subsequent input attempts on Notes are added to B, but A remains as it was (and the infinite loop between and and B continues).

This appears to cause input lag in Firefox in general, until Notes is closed.

**Comment by vladikoff** [comment]
Thanks for the issue @ddurst !

@Natim I filed this for Shield perf fixes.

**Comment by Natim** [comment]
We will look into it, thanks for the bug report.

**Comment by Natim** [comment]
@ddurst I couldn't really reproduce, can you still reproduce with the current release of Notes?

**Comment by ddurst** [comment]
I can. Infact, I've had to stop using it because it got so severe. I'm not sure exactly how to trigger it, however.

My basic STR are:
- using Nightly (currently 59.0a1)
- open sidebar
- switch to Notes
- (I have about 5 screen heights worth of notes fwiw)
- add text quickly to the bottom of the Notes panel
- use standard keyboard shortcuts to navigate around in the text, then to the top of Notes and moving down via arrow keys to edit below

I just did this and it's now l‡ooping back to the point where the cursor is at the top of Notes -- and the lag is affecting my ability to write in this textarea on gitub. So I'm going to restart FF.

(It took 5 minutes for the text from ‡ to here to appear, in two or three chunks. All input and output in page was delayed, including closing the Notes panel, hiding the Notes panel, having the screen take up the regular page width once the panel was not shown, etc.)

**Comment by Natim** [comment]
Thank you for your feedback, I am so sorry to hear that you are having so much trouble with it.

**Comment by vladikoff** [comment]
@ddurst couple of questions to narrow this down:

- What OS are you using?
- Can you see if Firefox Stable has the same problem for you? 
- Did you have multiple sidebars going or was it a single Firefox window?

**Comment by ddurst** [comment]
@vladikoff:
* OSX 10.11.6
* without definitive STR, it's hard to tell. I do experience a lot of lag when I enter a lot of text. I'll keep trying.
* In nightly I was running 6-7 windows, with sidebars enabled in at least one, probably two, but not all.

**Comment by Natim** [comment]
@ddurst Could you try this build of the addon to see if you can reproduce this?

[notes-2.3.0dev3.zip](https://github.com/mozilla/notes/files/1726961/notes-2.3.0dev3.zip)

You can load it in about:debugging for instance.

**Comment by ddurst** [comment]
So far, so good. Overall it seems more responsive to typing (and less laggy in general). I'll keep using it and let you know if it recurs.

**Comment by vladikoff** [comment]
@ddurst thank you for extensive testing, it is appreciated! 🏅
