### ISSUE TITLE
"Firefox Notes" toolbar button does not work at all after the sidebar is closed in another window

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#553]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.08.2018) installed.
- Have the "Firefox Notes" sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and press "Ctrl+N".
2. Click the "Firefox Notes" button from the toolbar.
3. Focus the other window and click the "Firefox Notes" button from the toolbar.
4. Observe the behavior.

**[Expected result]:**
- The sidebar is closed.

**[Actual result]:**
- Nothing happens, the sidebar remains opened.

**[Notes]:**
- After step 3 if the sidebar is closed/switched, then the issue is no longer reproducible.
- The button will no longer work if the sidebar starts closed, a new window is opened, the sidebar is opened in the second window and you switch back to the first window.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34675736-2ffda17e-f493-11e7-9d74-e5fca52e161e.gif)

**Comment by johngruen** [comment]
This is blocked until 59

**Comment by Natim** [comment]
We should probably use the toogle feature here.

**Comment by Natim** [comment]
In the meantime, we should probably broadcast the signal to all sidebars to close when one receive the signal.

**Comment by Natim** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1429054

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.16.2018) installed, on the latest Firefox release and Nightly.
