### ISSUE TITLE
The "Firefox Notes" button's icon is wrongly changed after the sidebar is closed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#554]
**[Affected versions]:**
- Firefox 57.0.4
- Firefox Beta 58.0b14

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.08.2018) installed.
- Have the "Firefox Notes" sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Notes" button from the toolbar.
3. Observe the "Firefox Notes" button's icon.

**[Expected result]:**
- The icon is no longer highlighted.

**[Actual result]:**
- The icon is changed in a "jigsaw puzzle piece".

**[Regression Range]:**
First good revision: d9fad1593b8108e3742ecf2ef3c35bba0e83e0a0
Last bad revision: 2b3d24d13d278d8ef743679f56af80a0dd7e0bf1
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=2b3d24d13d278d8ef743679f56af80a0dd7e0bf1&tochange=d9fad1593b8108e3742ecf2ef3c35bba0e83e0a0

**[Notes]:**
- The issue is reproducible if the sidebar is closed from the "x" button placed in the upper-left corner of the sidebar.
- The issue is reproducible if the sidebar is closed by using the "Alt+Shift+W" shortcut. 
- The issue is reproducible if the sidebar is switched.
- The issue is not reproducible on the latest Nightly build (59.0a1).
- Attached a screen recording of the issue:
![rec of the issue 2](https://user-images.githubusercontent.com/31243259/34675794-57fac8dc-f493-11e7-9614-b6ed0e182cec.gif)

**Comment by vladikoff** [comment]
Saw this too, so strange :(

**Comment by Natim** [comment]
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1419940

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.16.2018) installed, on the latest Firefox release (57.0.4) and Firefox Beta (58.0b16).
