### ISSUE TITLE
The "Firefox Notes" button is no longer highlighted after the sidebar is closed in another window

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#555]
**[Affected versions]:**
- Nightly 59.0a1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.08.2018) installed.
- Have the "Firefox Notes" sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and press "Ctrl+N".
2. Click the "Firefox Notes" button from the toolbar.
3. Focus the other window and observe the "Firefox Notes" button.

**[Expected result]:**
- The button is highlighted.

**[Actual result]:**
- The button is not highlighted.

**[Notes]:**
- If you start with the sidebar closed, after following the STR the button will wrongly be highlighted.
- The issue is reproducible only on the latest Nightly build (59.0a1).
- Attached a screen recording of the issue:
![rec of the issue 3](https://user-images.githubusercontent.com/31243259/34675875-94b7f3c6-f493-11e7-83fa-df728f4d57c5.gif)

**Comment by Natim** [comment]
@johngruen : Let's remove the hightlight.

**Comment by johngruen** [comment]
I would recommend backing out the highlight

**Comment by vladikoff** [comment]
> I would recommend backing out the highlight

Removed this

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.16.2018) installed, on the latest Firefox release and Nightly.
