### ISSUE TITLE
Memory Error!

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#556]
@ryanfeeley to add details. This seems important.

**Comment by Natim** [comment]
I investigated this and there are multiple things that could mitigate this:

- [ ] We should accept only a merge conflict and no sync in kinto while there is the merge conflict string.
- [ ] We shouldn't allow for notes with more than 5000 signs (Refs #546)

**Comment by Natim** [comment]
I believe fixing #546 should have fixed this
