### ISSUE TITLE
The sidebar's content area should remain focused after dragging text into it

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#560]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Select any text from the website page and drag it into the sidebar.
3. Press the "Backspace" key and observe the behavior.

**[Expected result]:**
- One character should be deleted from the sidebar's content.

**[Actual result]:**
- The opened website goes back one page.

**[Notes]:**
- The issue is reproducible if at step 3 you press any other keys.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![enhancement](https://user-images.githubusercontent.com/31243259/34724666-544822ec-f557-11e7-930a-ce9c00b7b6a2.gif)

**Comment by shikhar-scs** [comment]
@Softvision-MariusComan I would like to take up this issue. May I?

**Comment by Natim** [comment]
Don't hesitate to assign yourself to issues you want to work on. Just try to be assign to only one at the time.

**Comment by vladikoff** [comment]
How do we get focus into the WebExtension after drag and drop? @ddurst would you know anything about that?

**Comment by ddurst** [comment]
I'm not sure I completely understand. I assume that a pane's focus is set via the .focus() call. Are you asking because that is not working, or is something else expected?
