### ISSUE TITLE
No clear how to "Reconnect to Sync"

### ISSUE THREAD

**Issue by peterbe** [mozilla/notes#561]
See screenshot. I appreciate that I have to do something to sign in again. But how?!
I tried clicking the text "Reconnect to Sync" but nothing happens. I tried clicking the three dots on the the right but neither options that displays are useful. 
<img width="1279" alt="screen shot 2018-01-09 at 9 09 09 am" src="https://user-images.githubusercontent.com/26739/34724883-5738ce1e-f51d-11e7-89e2-846e94314978.png">

(Yes, I (now) know that the trick is to click the little icon on the left but that was *not* clear)

**Comment by Natim** [comment]
We just landed the patch to click on Reconnect but in the meantime you need to click the arrow. #558
