### ISSUE TITLE
The sidebar background is not highlighted when dragging text over it, if Dark theme is enabled

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#562]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.09.2018) installed.
- Have the "Dark" theme selected for the "Firefox Notes" add-on from about:addons->Extensions tab->Notes.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to any website and select a text from the page.
3. Drag the text over the sidebar and observe the sidebar's background.

**[Expected result]:**
- The background is highlighted.

**[Actual result]:**
- Only the background's border is highlighted..

**[Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/34726548-0211d0ee-f55d-11e7-9ba4-177a8b5e23c0.gif)

**Comment by Natim** [comment]
@himanish-star can I let you look into that bug?

**Comment by himanish-star** [comment]
@Natim , no doubt about it. It's my pleasure.
