### ISSUE TITLE
Remove redundant GFM autoformat codes

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#563]
The CKEditor GFM has redundant autoformat codes that clutter the experience and our documentation. I spoke with our copywriter Meridel and we propose removing these features from the auto-format code:
1. Remove: \_\_bold__
1. Remove: \*italic*
1. Remove: \* unordered list item
1. Remove: 1) ordered list item

**Comment by vladikoff** [comment]
I use * and 1) all the time, instead we can just not mention them.  oh?

**Comment by ryanfeeley** [comment]
Damnit, why does GitHub support two?
<img width="250" alt="image" src="https://user-images.githubusercontent.com/68213/34744773-51db4926-f55c-11e7-94d6-90d877a036f4.png">

**Comment by vladikoff** [comment]
@ryanfeeley i think because that Apple Fireball dude invented it that way

**Comment by Natim** [comment]
I wouldn't bother customizing this since it is the standard Markdown behaviour. I agree that we don't need to document both. I am closing this bug.

**Comment by MeridelW** [comment]
If redundant auto-format commands are the norm then I think we should include them. I updated the text in green in the [Google doc](https://docs.google.com/document/d/1CWCb8N324mNrO6tBnp0ZzuLIwNo-i2HbZ_lc8VgeEho/edit?usp=sharing). 

I also changed the order we list the commands to align with the order in which they appear in the formatting toolbar.

**Comment by ryanfeeley** [comment]
Related: https://github.com/mozilla/notes/issues/564
