### ISSUE TITLE
Update boilerplate copy to me more helpful

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#564]
Below is a replacement to our boilerplate copy in Markdown written with Meridel. Please add the additional blank lines as shown in [this Google Doc](https://docs.google.com/document/d/1CWCb8N324mNrO6tBnp0ZzuLIwNo-i2HbZ_lc8VgeEho/edit?usp=sharing). If there is a problem doing so that a non-breaking space can't fix, let me know.

## Welcome to Firefox Notes!  
A simple tool for taking notes while you browse.

**To open Notes:**
* On Windows, Linux: `Alt+Shift+W`
* On Mac: `Opt+Shift+W`

**To access your notes from any laptop or desktop computer:**
* Select **Sync** to sign into your Firefox Account.

**To format your text,**  use the toolbar or these commands:
* Headings: Begin a line with `#` or `##` or `###` followed by a space to create a heading 1, heading 2, or heading 3
* Bold: `**text**` or `__text__`
* Italics: `*text*` or `_text_`
* Bulleted list: Begin a line with `*`  or  `–`  followed by a space
* Numbered list: Begin a line with `1.` or `1)` followed by a space
* Code: `` `text` ``

**Have a suggestion to improve Notes?** 
* Select **Give Feedback** in the Notes menu.

**That’s it**—you’re ready to take notes!

**Comment by ryanfeeley** [comment]
@Natim @vladikoff Let's wait for @MeridelW to decide if this text should be updated.

**Comment by ryanfeeley** [comment]
@Natim @vladikoff This was given a resounding 🎉 by @MeridelW. Update when ready!

**Comment by vladikoff** [comment]
Yesssss

**Comment by Natim** [comment]
@flodolo any idea of how we should do that in terms of translation?

**Comment by flodolo** [comment]
> @flodolo any idea of how we should do that in terms of translation?

Sadly, the only way is to split up the text in fragments (sentences).

**Comment by Natim** [comment]
Ok I will start doing that.
