### ISSUE TITLE
When using "Ctrl-Backspace" shortcut, only one character is erased 

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#566]
**[Notes]:**
- The issue is also reproducible when using the "Ctrl-Delete" shortcut keys.

**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hold the "Ctrl" key down and press the "Backspace" key.
3. Observe the deleted words/characters.

**[Expected result]:**
- The entire word is deleted.

**[Actual result]:**
- Only one character is deleted.

**[Additional Notes]:**
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![notes_backspace_issue](https://user-images.githubusercontent.com/20083658/34776402-6ee70d5c-f61f-11e7-93b9-8d0a19de681c.gif)

**Comment by vladikoff** [comment]
This was fixed per https://github.com/ckeditor/ckeditor5-typing/issues/92

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 21.06.2018) installed, on the latest Firefox release and Nightly. 
Tested on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
