### ISSUE TITLE
Pressing the "Tab" key wrongly focuses the "Give Feedback" option instead of aligning text

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#567]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.
- Have text in the "Firefox Notes" sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Move the text caret at the beginning of the sidebar's content.
3. Press the "Tab" key and observe the behavior.

**[Expected result]:**
- The ASCII 09 character is inserted.

**[Actual result]:**
- The "Give feedback" button is focused.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34778452-069de62e-f626-11e7-94c0-19a7d5d29090.gif)

**Comment by Natim** [comment]
I also encountered that bug and I can reproduce it on https://ckeditor5.github.io/

**Comment by Natim** [comment]
@Mgsy Are you aware of that bug already?

**Comment by Mgsy** [comment]
@Natim, the result from this issue is not a bug. At the moment we don't have a feature which will handle `text-indent`, so moving focus to other element is an expected behaviour.
