### ISSUE TITLE
The "Disable Sync" option background does not respect the Dark theme colors

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#568]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.10.2018) installed.
- Have the "Dark" theme selected for the "Firefox Notes" add-on from about:addons->Extensions tab->Notes.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Notes" menu button.
3. Observe the "Disable Sync" option's background.

**[Expected result]:**
- The "Disable Sync" option has the same background as the "Give feedback" one.

**[Actual result]:**
- The "Disable Sync" option's background is much darker than the "Give Feedback" option's background.

**[Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/34778673-b13efb7c-f626-11e7-9e9b-923d9ce2ee28.gif)

**Comment by Natim** [comment]
Fixes with #649

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc5 build) installed, on the latest Firefox release and Nightly.
