### ISSUE TITLE
Feature request: to be compatible with the addons such as `atomic-chrome`

### ISSUE THREAD

**Issue by Quantizen** [mozilla/notes#571]
Addons such as [atomic-chrome](https://chrome.google.com/webstore/detail/atomic-chrome/lhaoghhllmiaaagaffababmkdllgfcmc) make it possible to edit textareas and content editable elements directly in Atom or Sublime Text. It will be very convenient to make use of the functions of these editors.

It seems that  the addon `notes` is not compatible with the `atomic-chrome` when `notes` is opened in the sidebar in the firefox.

**Comment by Natim** [comment]
it is also because ckeditor5 doesn't use a content-editable div.

**Comment by johngruen** [comment]
This seems cool, let's add it to the backlog
