### ISSUE TITLE
The "Alt+Shift+W" shortcut does not close the sidebar in "about: *" pages

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#573]
https://bugzilla.mozilla.org/show_bug.cgi?id=1430072

**[Affected versions]:**
- Nightly 59.0a1

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.11.2018) installed.
- Have the "Firefox Notes" sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:support" page.
3. Press the "Alt+Shift+W" keys and observe the behavior.

**[Expected result]:**
- The sidebar is closed.

**[Actual result]:**
- Nothing happens.

**[Regression window]:**
Last good revision: 59a75c1808ec67d20fd1eade0d3b4fc0e930454f
First bad revision: 24aa7ff25c3d4334234a103b718ba4b643a4e397
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=59a75c1808ec67d20fd1eade0d3b4fc0e930454f&tochange=24aa7ff25c3d4334234a103b718ba4b643a4e397

- It seems that the Bug 1423208 caused the regression.

**[Notes]:**
- This behavior is not encountered if the "Ctrl+B" and "Ctrl+H" shortcuts are used instead of the "Alt+Shift+W" one.
- The issue is no longer reproducible if the e10s is disabled.
- The issue is not reproducible on Mac and Linux.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34835427-6fa8092e-f6fd-11e7-939f-b6cfc3ed9857.gif)

**Comment by Natim** [comment]
We should also file a Bugzilla issue for this one.

**Comment by Softvision-MariusComan** [comment]
Here it is: https://bugzilla.mozilla.org/show_bug.cgi?id=1430072

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.15.2018) installed, on the latest Firefox release and Nightly.
