### ISSUE TITLE
Last synced timestamp should be clickable and black

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#574]
Unlike the last saved timestamp, which is merely informational, the last synced timestamp is both informational and interactive.

Please make sure that it is clickable and black, as designed in the spec.
https://mozilla.invisionapp.com/share/6VBUYHMRB#/235284916_Desktop_Sidebar

**Comment by Natim** [comment]
It is clickable since #558

**Comment by ryanfeeley** [comment]
@Natim And black?

**Comment by willbmartin** [comment]
As my first issue, I would like to contribute to this ticket, and make the text black! Still needed?

**Comment by ryanfeeley** [comment]
@willbmartin Great! I'm doing design on this project and would love the extra help! I thought it was, but then a recent release candidate showed that it was not. I filed this issue more recently, kind of a duplicate I suppose. https://github.com/mozilla/notes/issues/621

**Comment by Natim** [comment]
@willbmartin Yes please go ahead 👍

**Comment by willbmartin** [comment]
Submitted a pull request 👍
