### ISSUE TITLE
The sidebar min-width should prevent the editor toolbar to be split in two lines.

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#580]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.15.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Resize the sidebar to its minimum.
3. Observe the "Numbered list" and 'Bulleted list" buttons.

**[Expected result]:**
- The icons inside the buttons are not clearly defined.

**[Actual result]:**
- The icons inside the buttons are blurred.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible with the "Firefox Notes" dark theme activated.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34944254-8c35a7ec-fa07-11e7-93ca-51bfab49ba7e.gif)

**Comment by Natim** [comment]
I don't think they should even get the opportunity to go to the lower line.

**Comment by Natim** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1431076

**Comment by anweshknayak** [comment]
Can I work on this ?

**Comment by Natim** [comment]
To be honest I am pretty convinced that there is no much we can do here. I opened a bugzilla issue and I am following there. You should probably try to pick another issue.

**Comment by Natim** [comment]
According to the bug it is impossible for us to set a minimum size.

**Comment by sebastienbarbier** [comment]
Should we trick ck-editor to **display a slider**? (ping @ryanfeeley )
Could also use **a meatball menu** but having header + footer + now editor would feels like too many in my opinion.

**Comment by ryanfeeley** [comment]
I just imagine it like this:
![crop](https://user-images.githubusercontent.com/68213/38035580-b8b3fab4-3272-11e8-8abc-c7c78b5d56ac.png)
