### ISSUE TITLE
The "Firefox Notes" toolbar button wrongly opens the sidebar only the second time it is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#581]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.16.2018) installed.
- Have the sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Close sidebar" button from the top-right corner of the sidebar.
3. Click the "Firefox Notes" toolbar button and observe the behavior.
4. Click again the "Firefox Notes" toolbar button and observe the behavior.

**[Expected result]:**
Step 3: The sidebar is opened.
Step 4: The sidebar is closed.

**[Actual result]:**
Step 3: Nothing happens.
Step 4: The sidebar is opened.

**[Notes]:**
- The issue is reproducible when switching the sidebars.
- The issue is not reproducible if the sidebar was previously closed from the "Firefox Notes" toolbar button.
- The issue is not reproducible with the "Firefox Notes" add-on (2.2.0dev custom build from 01.15.2018) installed.
- The issue is also not reproducible with the TxP version of "Firefox Notes".
- The behavior is not reproducible if you open the sidebar using the "Show sidebars" button or by using the "Alt+Shift+W" shortcut.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/34981907-a460b8ca-fab1-11e7-83c5-ae75580d7b8d.gif)

**Comment by Natim** [comment]
This is a current known limitaiton we are waiting for the isOpen API to improve it.

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1427431

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.1.0dev custom built on 10.05.2018) installed, on the latest Firefox release (60.0) and Nightly (62.0a1). Verified on Windows 10 x64, Mac 10.12 and Ubuntu 14.04.
