### ISSUE TITLE
[Keyboard navigation] Pressing "Enter" while the "Give Feedback" button is selected does not open the Feedback tab

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#588]
**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.17.2018) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Press the "Tab" key and then the "Enter" key.
3. Press the "Up" arrow once and then press the "Enter" key again.
4. Observe the behavior.

**[Expected result]:**
- The "Give Feedback" page is opened.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is reproducible only for the "Give Feedback" option from the "Notes" menu.
- The issue is not reproducible if the "Disable Sync" option is selected instead of the "Give Feedback" one.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35052460-4d3a32ba-fbb0-11e7-817d-debbae6d4ce8.gif)

**Comment by Natim** [comment]
Fixed in #619 (2.2.0rc3)

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6 build) installed, on the latest Firefox release and Nightly.
