### ISSUE TITLE
The "Notes" menu can wrongly be triggered even if you are not logged into a Sync account

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#591]
**[Notes]:**
- On Mac, it is enough to press the "Tab" key once.

**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.17.2018) installed.
- You are not logged into "Firefox Notes"

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Press the "Tab" key twice and then press the "Enter" key.
3. Observe the bottom part of the sidebar.

**[Expected result]:**
- The opened page is focused.

**[Actual result]:**
- The "Notes" menu is displayed.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes" if the "Tab" key is pressed for three times instead of two.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35100767-aadc6004-fc65-11e7-85c2-95c5ffc51a88.gif)

**Comment by Natim** [comment]
Nice catch, I guess a fix would be to remove the onClick listener when the menu is hidden 👍

**Comment by anweshknayak** [comment]
> target.addEventListener(type)
which type it would be ?  
and something like this should work ? 
`if(giveFeedbackMenuItem.style.display == "none"){

  giveFeedbackButton.addEventListener(type, (e) => { });
}`

**Comment by Natim** [comment]
I would rather remove the listener

**Comment by Natim** [comment]
@anweshknayak Are you working on this or should I investigate?

**Comment by anweshknayak** [comment]
@Natim please go ahead. I tried but couldn't solve it.

**Comment by Natim** [comment]
Ok thanks

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6 build) installed, on the latest Firefox release and Nightly.
