### ISSUE TITLE
Right to left shortcut doesn't reverse Note's items correctly

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#592]
[Notes]:
- See also #[409](https://github.com/mozilla/notes/issues/409).
	
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.1.1RC) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Focus Notes sidebar.
3. Press "Ctrl" (Cmd)+"Shift"+"X" keys and observe Note's items (both header and footer).

[Expected result]:
- All the items reverse their positions.
OR
- Nothing happens, the shortcut doesn't affect Note's items.

[Actual result]:
- The buttons from the footer are the only ones that change their position: 
-> the "Feedback" button moves to the left,  
-> the "Sync" button moves to the right  
-> the area that contains the time when the changes were last saved is in between the 2 previous mentioned buttons.

[Additional Notes]:
- Attached a screen recording of the issue:

![rtl](https://user-images.githubusercontent.com/26000308/35103755-813e8538-fc6f-11e7-8e57-0976fecb65a4.gif)

**Comment by vladikoff** [comment]
Need to check with latest CKEditor version....
