### ISSUE TITLE
The "Give Feedback" button/option can be wrongly dragged in the sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#593]
**[Notes]:**
- Given that the "Give Feedback" button and option are the only ones that can be dragged, we should restrict this behavior in order to have them all behave consistently.

**[Affected versions]:**
- Firefox 57.0.4 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.1.1rc2) installed.
- You are not logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click and drag the "Give Feedback" button in the sidebar.
3. Observe the behavior.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- A CSS code line is displayed in the sidebar.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible if you are logged into "Firefox Notes" and you drag the "Give Feedback" option from the "Notes" menu. However in that case the "Give Feedback" string is displayed into the sidebar.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35105583-b13cd5fa-fc74-11e7-92d2-57933cd26f4b.gif)

**Comment by anweshknayak** [comment]
Hey can I take this up ?
