### ISSUE TITLE
"Saving changes" and "Saved..." states wrongly appear twice after editing if more than one window is opened

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#594]
[Notes]:
- In order to easily observe this issue, resize the windows so you can fully see the "Notes" sidebars.
- No matter how many windows you'll open, the saving changing state appear twice.

[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-01-18) installed.
- Be logged in a Firefox Notes account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites and write something in the sidebar. 
2. Open a new window and focus the sidebar.
3. Type again something and observe the changing states from the bottom part of the sidebar.

[Expected result]:
- The "Saving changes" -> "Saved" -> "Synced at.." states appear.

[Actual result]:
- The "Saving changes" -> "Saved" -> "Saving changes" -> "Saved" -> "Synced at.." states appear.

[Additional notes]:
- This issue is also reproducible with Firefox Notes installed from Test Pilot experiment [page](https://testpilot.firefox.com/experiments/notes) and with Firefox Notes v2.1.1.rc2.
- Here is a screen recording of the issue:
![saving state displayed twice](https://user-images.githubusercontent.com/31244235/35107778-75ff564c-fc7a-11e7-8cd2-51f23ad83938.gif)

**Comment by Natim** [comment]
This was fixed with #623

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes [v2.2.0rc5](https://github.com/mozilla/notes/pull/619#issuecomment-362590630), or Firefox Notes v2.2.0dev (custom build 2018-02-05), on latest Nightly build 60.0a1 (2018-02-04), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

However, you can briefly observe the transition from "Saved" -> "Synced..", but only for such a short moment, that I cannot even catch on screenrecording.
