### ISSUE TITLE
Markdown autoformat italics bug

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#595]
from a user:

> I was writing some notes and tried writing wrote word1_word2_word3 and while writing it, it did word1word2word3 and word 2 was in italics. I am assuming that's because of the underlines but I am not sure this is intentional behavior. Thanks! 

STEPS TO REPRODUCE
1. Type: word_1 and word_2

EXPECTED RESULTS
* word_1 and word_2

ACTUAL RESULTS
* word*1 and word*2

**Comment by Natim** [comment]
Refs https://discourse.mozilla.org/t/use-markdown-as-text-file-format/22541/8

**Comment by ryanfeeley** [comment]
User feedback:
> If there is a way of changing the settings so  that prefix/ suffix underscores don't make the text between them  italicised that would be very useful- essentially turning off this  feature. I use the notes field for a lot of typing of conventionally  named items which feature underscores such as file_name_a_and_b and  being able to do this without it just italicising and removing the  punctuation would be great.

**Comment by memnoch** [comment]
Has there been any progress on being able to turn markdown completely on or off with a keybinding and menu option?
