### ISSUE TITLE
Use syncing instead of saving while logged in

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#597]

**Comment by Natim** [comment]
## STEPS TO REPRODUCE

    Enable Syncing of Notes
    Edit a note

## EXPECTED RESULTS

    After a note has been edited, footer should say "Syncing…"
    Before a note has been edited it shoudl say "Last Synced HH:MM"

## ACTUAL RESULTS

    It does this but also has Save and Saving…

**Comment by himanish-star** [comment]
@Natim , I would like to fix this issue. May I ?

**Comment by Natim** [comment]
Yeah sure go ahead.
