### ISSUE TITLE
Correct save and sync language

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#598]
STEPS TO REPRODUCE
1. Enable Syncing of Notes
2. Edit a note

EXPECTED RESULTS
* After a note has been edited, footer should say "Syncing…"
* Before a note has been edited it shoudl say "Last Synced HH:MM"

ACTUAL RESULTS
* It does this but also has Save and Saving…

**Comment by Natim** [comment]
Duplicate of #597
