### ISSUE TITLE
The previously used Sync email is wrongly displayed as a tooltip after logging out

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#599]
[Affected versions]:
- Firefox 57.0.4 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-01-19) installed.
- Be logged in a Firefox Notes account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Click the three dots button and select the "Disable sync" option.
3. Hover the "Saved at.." text from the bottom part of the sidebar.
4. Observe the behavior.

[Expected result]:
- Nothing happens.

[Actual result]:
- A tooltip displays the Firefox Notes account you were previously logged in.

[Notes]:
- If you have another window opened, follow the steps, switch to the other window, hover the "Saved at.." text, a tooltip with the "null" text appears.
- This issue is not reproducible if you switch or close the sidebar.
- This issue is also reproducible with Firefox Notes installed from Test Pilot experiment [page](https://testpilot.firefox.com/experiments/notes) and with Firefox Notes v2.1.1.rc2.
- Here is a screen recording of the issue:
![disable sync issue](https://user-images.githubusercontent.com/31244235/35142749-ed144e94-fd07-11e7-9b16-1ddb9f87e7b8.gif)

**Comment by Natim** [comment]
Good catch thanks !

**Comment by Natim** [comment]
@himanish-star Do you want to tacle this one as well?

**Comment by himanish-star** [comment]
@Natim , Yeah sure !!

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v2.2.0dev (custom built 2018-01-30), on latest Nightly build 60.0a1 (2018-01-29), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.
