### ISSUE TITLE
Although notes has been enabled into the firefox its not showing up in the preferences

### ISSUE THREAD

**Issue by P-Shivkumar** [mozilla/notes#602]
I have enabled the notes pilot but its not available to drag and drop in the preferences

**Comment by Natim** [comment]
Can you provide a screenshot of what you mean ? You can use the sidebar button that should have shown up or the Alt+Shift+W shortcut to show it up.

**Comment by P-Shivkumar** [comment]
![screenshot from 2018-01-22 19-33-46](https://user-images.githubusercontent.com/22441163/35226687-186c6b38-ffb2-11e7-9987-e6c4bee5f9c9.png)

In this(above image) I can't see notes option for drag and drop 

![screenshot from 2018-01-22 19-33-18](https://user-images.githubusercontent.com/22441163/35226744-4ae2fc12-ffb2-11e7-96e1-0f514ffdbae3.png)

In this (above image) its clear that i have notes enabled

**Comment by Natim** [comment]
Ok so you are talking about the toolbar button. In the current version of notes, it is the sidebar button (the one hovered in your second screenshot). We are shipping a version this week with the #515

**Comment by Natim** [comment]
The release is out, if you check for updates you should have the toolbar button no :) Thank you for reporting it!
