### ISSUE TITLE
The "Notes" menu button wrongly shakes while resizing the sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#613]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.25.2018) installed.
- The sidebar was moved to the right.
- You are logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Resize the sidebar to its minimum and observe the "Notes" menu button while doing that.

**[Expected result]:**
- The button maintains its position.

**[Actual result]:**
- The button shakes while resizing the sidebar.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible if the sidebar is placed in the left part of the browser's window.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35384018-aa2a4c54-01cc-11e8-95fc-e59e6d765827.gif)

**Comment by Natim** [comment]
@Softvision-MariusComan Could you try again with current master or with this version of the add-on? We made some changes that might help.

[notes-2.3.0dev3.zip](https://github.com/mozilla/notes/files/1727748/notes-2.3.0dev3.zip)

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest version of the "Firefox Notes" add-on (2.3.0dev3) installed.

**Comment by johngruen** [comment]
I believe this is platformy
