### ISSUE TITLE
Extra lines are pasted in "Firefox Notes" when a cell with text is copied from Google Sheets

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#616]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0dev custom build from 01.25.2018) installed.
- Have a "Google Sheets" cell with text copied to clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and paste the text from prerequisites.
3. Observe the pasted content.

**[Expected result]:**
- Only the text is pasted.

**[Actual result]:**
- The text is pasted together with a code line.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35397887-505191ba-01f9-11e8-8ae9-a76e9da923a9.gif)

**Comment by anweshknayak** [comment]
Hey, I can give this a try

**Comment by johngruen** [comment]
We can use a CK editor transformation to better handle copy/paste?
