### ISSUE TITLE
Upgrade message boxes to Photon colors

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#618]
Today we have a wild range of colors.

![migration](https://user-images.githubusercontent.com/229453/35339473-0560bce0-0121-11e8-94f6-980bbc3a14f3.png)

![SyncPopup](https://user-images.githubusercontent.com/26000308/27691699-87dcf0b8-5ced-11e7-8d1b-e092213953f5.png)

We should use the Photon guideline: https://design.firefox.com/photon/components/message-bars.html#error

**Comment by Natim** [comment]
@anweshknayak would you like to tackle this issue?

**Comment by anweshknayak** [comment]
@Natim sure :) On it
