### ISSUE TITLE
Checkboxes / ToDo list

### ISSUE THREAD

**Issue by tradewatcher** [mozilla/notes#620]
Add a second menu row with a drop down menü to select note, a + to add note and a - to remove note. 

An extra standard "ToDo" (checklist note) should always be selectable in this drop down menu there and undeleteable. 

And i miss Checkboxes.

A finish date/time under each entry could be an idea if you add a small remember popup in firefox and play a PIEP at finish date/time.

**Comment by johngruen** [comment]
Thank you for the ideas. We are actively working on multi-note support, and the underlying editor is working on checkbox support.

**Comment by vladikoff** [comment]
Multi note bug : https://github.com/mozilla/notes/issues/725

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/notes/issues/218
