### ISSUE TITLE
Syncing user footer fixes

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#621]
Not sure which of these are already fixed, but doesn't hurt to file twice.

1. `Synced at` should just be `Synced`
1. Text should be black
1. Hover text is missing on `Synced` text
1. Hover text should be: `Sync to user@example.com`

![synced](https://user-images.githubusercontent.com/68213/35453027-ac4c8afe-0296-11e8-9310-f8d5a9a02af0.gif)

**Comment by Natim** [comment]
Can you please check with https://github.com/mozilla/notes/files/1668378/notes-2.2.0rc2.zip ?

**Comment by ryanfeeley** [comment]
@Natim Done! But all issues remain. Although I did see `user@example.com` on `Synced at` hover.

![rc3](https://user-images.githubusercontent.com/68213/35459409-0ae5bc18-02ae-11e8-9dbd-be0c443302bc.gif)

**Comment by Natim** [comment]
@anweshknayak would you like to tackle this issue?

**Comment by anweshknayak** [comment]
@Natim sure :100:

**Comment by flodolo** [comment]
Can someone explain the rationale for "Sync to foo@example.com"? It sounds confusing to me, as if it's sending something to that email, not the account.

Wouldn't something like "Current account: foo@example.com" be less open to interpretations?

**Comment by ryanfeeley** [comment]
> Can someone explain the rationale for "Sync to foo@example.com"? It sounds confusing to me, as if it's sending something to that email, not the account.

I can! We currently don't show the account email anywhere in the UI. This seemed like a harmless place for it. Tapping anywhere on the row will invoke a manual Sync, and "Sync to foo@example.com" is I suppose a shorter way to say "Sync with account foo@example.com"

> Wouldn't something like "Current account: foo@example.com" be less open to interpretations?

That doesn't let the user know that tapping it will invoke a sync.

Make sense or other ideas?

**Comment by flodolo** [comment]
Thanks, that helps. Since this is a tooltip, and there are really no space constraints, why not using "Sync with account foo@example.com" then? That seems clearer.

**Comment by ryanfeeley** [comment]
@flodolo If you're not worried about it being too long, then I approve! Thanks for making it better.

**Comment by flodolo** [comment]
Yes, tooltips is one of the few ares where lenght is not much of a concern.
