### ISSUE TITLE
The INITIAL_CONTENT text does not disappear after logging into "Firefox Notes"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#623]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button.
3. Insert you credentials and click the "Sign in" button. 
4. Observe the content displayed in the sidebar.

**[Expected result]:**
- Only the synced content is displayed in the sidebar.

**[Actual result]:**
- The placeholder text is displayed in the sidebar under the synced content.

**[Additional Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35502577-159c284c-04e6-11e8-8564-20ee20ed00de.gif)

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6) installed. Considering this, I am reopening the issue.
Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35868530-6b34183e-0b65-11e8-85ec-b535b02b9a83.gif)

**Comment by Natim** [comment]
Ok I can't reproduce with locale fr, let me try with locale en.
