### ISSUE TITLE
Connection not secure on log in

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/notes#626]
![screenshot from 2018-01-29 16 33 08](https://user-images.githubusercontent.com/8139783/35507663-8f2e5892-0513-11e8-9881-48a1995913cf.png)

Can't log in to sync.

and cannot scroll the page to *Add Exception*

**Comment by johngruen** [comment]
@anweshknayak could you provide more details about how you hit this screen?

**Comment by vladikoff** [comment]
@anweshknayak 

- Did you trigger login twice?
- Do you have other extensions installed?

**Comment by anweshknayak** [comment]
>Did you trigger login twice?
Certainly No. Have tried multiple times with the login.

>Do you have other extensions installed?
Yes

**Comment by anweshknayak** [comment]
It wasn't working with Firefox Developer version. But it is now working with Firefox 58(Quantum)

**Comment by Natim** [comment]
I am closing this bug, it is a known Firefox Bug that was fixed in 58.

Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1416872
