### ISSUE TITLE
Recently added content is wrongly deleted if it is added after the max size warning is displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#627]
**[Notes]:**
- After following the scenario below, if you continue to add new lines with/without text, try to synchronize and close the message several times, then all the previously synchronized and the new content will be deleted and only the placeholder text will be displayed (see the second attached video).

**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.
- You must be logged into "Firefox Notes".
- Have enough content in the sidebar that the max size warning is displayed

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste or add extra content.
3. Close the max size warning and click on the "Sync Your Notes" button.
4. Observe the content's behavior.

**[Expected result]:**
- Once the notes limit has been reached, no additional content can be written/added.

**[Actual result]:**
- A part or all of the recent added content (from step 2) is deleted.

**[Additional Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
1. 
![rec of the issue](https://user-images.githubusercontent.com/31243259/35513282-2f25c2bc-050b-11e8-9ee6-af8d1b9ec0eb.gif)

2. 
![rec of the issue 2](https://user-images.githubusercontent.com/31243259/35513302-47f08fde-050b-11e8-80b3-ebcfa88b59a8.gif)

**Comment by anweshknayak** [comment]
hey @Natim can I try?

**Comment by Natim** [comment]
Actually that 's a feature I've added while fixing #546 
I am waiting for @ryanfeeley to tell me if he is ok with that behaviour or if we need to do a better job.

**Comment by vladikoff** [comment]
@ryanfeeley to close up this bug we want to know: 

Are you okay with Notes warning users at 15000 characters and then blocking input on 25000 characters? Please unblock 🐶 

<img src=https://identicons.appspot.com/i/shield/v1/rfeeley.svg width=100 />

**Comment by Natim** [comment]
![https://identicons.appspot.com/i/shield/v1/M3LW4M.svg](https://identicons.appspot.com/i/shield/v1/M3LW4M.svg)

**Comment by Softvision-MariusComan** [comment]
This behavior is still reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc5) installed. Considering this, I am reopening the issue.
Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35863089-3d2652f4-0b56-11e8-890d-e1f7970bcaea.gif)

**Comment by Natim** [comment]
This was merged in rc6 not rc5

**Comment by Softvision-MariusComan** [comment]
@Natim My mistake, this issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc6 build) installed, on the latest Firefox release and Nightly.
