### ISSUE TITLE
Content loses the "Bold" formatting option when it is pasted in "Firefox Notes" from Google Docs

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#630]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.
- Have content with the "Bold" formatting option applied, copied to clipboard from "Google Docs".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste the content from prerequisites.
3. Observe the pasted content.

**[Expected result]:**
- The pasted content is bold.

**[Actual result]:**
- The pasted content is no longer bold.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible on https://ckeditor5.github.io.
- The issue is not reproducible if the "Italic" or the "Underline" formatting options are used instead.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35571443-ce486b68-05da-11e8-8619-89e69982b8e8.gif)

**Comment by vladikoff** [comment]
Need to find upstream ckeditor bug for this...
