### ISSUE TITLE
The "Firefox Notes Feedback" page is not opened in a new tab

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#631]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Give Feedback" button from the bottom right part of the sidebar.
3. Observe the behavior.

**[Expected result]:**
- The "Firefox Notes Feedback" page is opened in a new tab.

**[Actual result]:**
- The "Firefox Notes Feedback" page is opened in the same tab.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec-of-the-issue](https://user-images.githubusercontent.com/31243259/35575393-ee3917ce-05e4-11e8-975a-ff548f750036.gif)

**Comment by apoorvaagupta** [comment]
Hello, May I take up this issue if no one else is working on it?

**Comment by Natim** [comment]
Yes please go ahead @apoorvaagupta
