### ISSUE TITLE
The project won't run if you have some other version of Firefox installed instead

### ISSUE THREAD

**Issue by bhavyaagg** [mozilla/notes#632]
The project runs by default on Firefox. I have checked this in MacOS. This is because web-ext by defaults run the default firefox. We should have an option to run this project on different versions of firefox.

**Comment by vladikoff** [comment]
@bhavyaagg there is start-nightly: https://github.com/mozilla/notes/blob/master/package.json#L77

You can tweak that or add a new script option

**Comment by bhavyaagg** [comment]
@vladikoff Should i add a script for running this on Developer Edition?

**Comment by vladikoff** [comment]
@bhavyaagg 

under `web-ext run --help` 


```
 --firefox, -f, --firefox-binary  Path or alias to a Firefox executable such as
                                   firefox-bin or firefox.exe. If not specified,
                                   the default Firefox will be used. You can
                                   specify the following aliases in lieu of a
                                   path: firefox, beta, nightly,
                                   firefoxdeveloperedition.             [string]
```

It's up to you, I think a PR for `npm run start-deved` or something would be okay. We only just needed Nightly and Stable for most of our purposes

**Comment by bhavyaagg** [comment]
@vladikoff Sure. Will do that. Thank you for your quick response. :)
