### ISSUE TITLE
Add a scribble board

### ISSUE THREAD

**Issue by apoorvaagupta** [mozilla/notes#636]
Addons like a scribble board would be a nice way to save drawings/notes in one's own handwriting. 
It would be a great tool especially for users using the browser on touch screen laptops or tablets.
Different colours and stroke widths can be added to enhance the feature.

I would like to work on this issue, if approved by the mentors.

**Comment by vladikoff** [comment]
@apoorvaagupta we would have to triage this feature request. 

Right now we are focused on multi note support and features outlined in this design: 

https://mozilla.invisionapp.com/share/WSDA1YM7H#/screens/250693253_Default

Also see v3.0 column and the enhancements col under https://waffle.io/mozilla/notes

**Comment by apoorvaagupta** [comment]
Thankyou @vladikoff for reviewing!
If in future, you plan to implement it, please let me know as I would love to work on it!
Meanwhile, I would contribute on other issues.

**Comment by vladikoff** [comment]
No plans to add this, but we might reopen this in the future
