### ISSUE TITLE
After logging off from "Firefox Notes", the "Give Feedback" button is not displayed in the other opened windows

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#638]
**[Notes]:**
- The "Give Feedback" button is displayed only on the window where the log off action was taken.

**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.
- Have the "Firefox Notes" sidebar opened.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new window and click on the "Notes" menu button from the bottom-right part of the sidebar.
3. Click the "Disable Sync" option and focus the first window.
4. Observe the bottom of the sidebar.

**[Expected result]:**
- The "Sync Your Notes" and the "Give Feedback" buttons are displayed.

**[Actual result]:**
- Only the "Sync Your Notes" button is displayed.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is no longer reproducible after the sidebar is reopened or switched.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35615723-b7ae87e2-067b-11e8-82d1-9fffcd307e75.gif)

**Comment by himanish-star** [comment]
I think I may be able to fix this. Shall I ?

**Comment by Natim** [comment]
Yes @himanish-star please give it a try

**Comment by himanish-star** [comment]
@Natim, I have fixed this. :smiley:

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (2.2.0rc5 build) installed, on the latest Firefox release and Nightly.
