### ISSUE TITLE
A text with a heading format applied, is wrongly reset to "Body" format when it's pasted on a new row

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#640]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.
- Have the "Firefox Notes" sidebar opened.
- Have content with any heading format applied.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select and copy the text from prerequisites.
3. Go to a new row and paste the text from above.
4. Observe the format of the pasted text.

**[Expected result]:**
- The format is not changed.

**[Actual result]:**
- The format is reset to "Body".

**[Additional Notes]:**
- The issue is reproducible if the "Cut" option is used instead.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35623405-2f9e9b3a-0694-11e8-8346-3de88b2d3c32.gif)

**Comment by vladikoff** [comment]
Might have to file a ckeditor bug on this one,....
