### ISSUE TITLE
If a numbered/bulleted list is pasted on a new row under a similar one, the lists will wrongly merge

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#641]
**[Affected versions]:**
- Firefox 58.0 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.
- Have a numbered list displayed in the sidebar.
- Have another numbered list copied to the clipboard.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Move the text caret at the end of the numbered list.
3. Press the "Enter" key two times and paste the list from the prerequisites.
4. Observe the content behavior.

**[Expected result]:**
- The pasted list is correctly displayed under the existing one.

**[Actual result]:**
- The lists are merged.

**[Additional Notes]:**
- The issue is reproducible if the "Bulleted" list is used instead.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35626573-d109c8be-069e-11e8-8e78-931d396d0a93.gif)

**Comment by Natim** [comment]
I had got this bug today, it is indeed quite annoying when you want to have two lists without a blank line in between.

**Comment by vladikoff** [comment]
@mgsy could you confirm this one if you have a moment?

**Comment by vladikoff** [comment]
@Mgsy could you check this still happens on latest? Basically if you wanted to create 2 lists with reset ordering, CKEditor seems to be combining the lists

**Comment by Mgsy** [comment]
@vladikoff, this behaviour is caused by the way how we represent lists in the model. After a short talk, we decided to create a ticket, where it would be discussed - https://github.com/ckeditor/ckeditor5-list/issues/99. You'll find there more information about this case and feel free to join the discussion.
