### ISSUE TITLE
The "Firefox Notes" toolbar button does not work correctly on older supported browser versions

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#642]
**[Affected versions]:**
- Firefox 54
- Firefox 55
- Firefox 56

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.2.0rc2) installed.

**[Steps to reproduce]:**
1. Open one of the affected browsers with the profile from prerequisites.
2. Observe and click the "Firefox Notes" toolbar button.

**[Expected result]:**
- The "Firefox Notes" toolbar button is displayed correctly and it works as expected.

**[Actual result]:**
- The "Firefox Notes" button is not displayed correctly and also does not work at all.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible on Firefox 57.0 and up.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/35631580-e74e2134-06ac-11e8-98d6-098a2005405d.gif)

**Comment by Natim** [comment]
That's true, the API didn't exist at the time.

**Comment by Natim** [comment]
Maybe we should just upgrade the minimum acceptable version for notes then.

**Comment by vladikoff** [comment]
> Maybe we should just upgrade the minimum acceptable version for notes then.

👍

**Comment by Natim** [comment]
According to https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction it is 57

**Comment by vladikoff** [comment]
Ref: https://github.com/mozilla/notes/pull/643

**Comment by Natim** [comment]
After talking with @Softvision-MariusComan on IRC we want to bring this question to the next meeting and determine if we should ship a 2.1.1 without the button before shipping a 2.2.0 so that people with notes and a lower version of Firefox don't stay stuck with a non working button.

**Comment by vladikoff** [comment]
from mtg: closing as WONTFIX
