### ISSUE TITLE
"Synced ..." text is no longer so visible on Dark Theme

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#645]
[Notes]:
- "Syncing changes..." text is also displayed with black characters.

[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-02-01) installed.
- Be logged in a Firefox Notes account.
- Have Dark theme enabled.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Observe the color of the "Synced ..." text.

[Expected result]:
- The text is displayed with gray characters.

[Actual result]:
- The text is displayed with black characters which makes it not so visible.

[Additional notes]:
- Here is a screen shot with this issue:
![black text](https://user-images.githubusercontent.com/31244235/35671742-0773a806-0745-11e8-9926-066a5e06854b.png)

**Comment by Natim** [comment]
@ryanfeeley Can you signoff for this? I think you asked *Synced* instead of *Synced at*, are you sure that's what you want? I know that @vladikoff and @flodolo changed that once already.

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes [v2.2.0rc5](https://github.com/mozilla/notes/pull/619#issuecomment-362590630), or Firefox Notes v2.2.0dev (custom build 2018-02-05), on latest Nightly build 60.0a1 (2018-02-04), on Windows 10 x64, Mac 10.12.6 and Arch Linux 4.12.

However, this issue has not been fixed entirely because the text color consistency is not respected: the "Synced.." text color is "FFFFFF" code, which is slightly different from the other text such as "Syncing changes", "All changes saved", "Opening login" and also it's different from the Test Pilot Firefox "Notes" v2.1.1, where the text color code is: "969696", as you can see in the screenshots below:
- "Synced..." text
![notes - synced -text](https://user-images.githubusercontent.com/31244235/35808647-2460cc26-0a8f-11e8-8259-3fe06d5c9115.png)
- Other text in dark theme, such as "Syncing changes..."
![notes - syncing changes](https://user-images.githubusercontent.com/31244235/35808668-38016f60-0a8f-11e8-80e3-fe7ac3737e0d.png)
- Firefox Notes from Test Pilot experiments page
![notes test pilot](https://user-images.githubusercontent.com/31244235/35808685-46cb49bc-0a8f-11e8-937d-bdcc9ec05302.png)


Considering this, I'm going to reopen this issue.

**Comment by vladikoff** [comment]
@ryanfeeley is this fine?

Should action be `white` (clickable) and progress in grey?

**Comment by ryanfeeley** [comment]
@vladikoff Yes, exactly! It's the opposite of light theme.
