### ISSUE TITLE
"Sync with..." tooltip is wrongly displayed when hovering the "Give Feedback" button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#661]
[Affected versions]:
- Firefox 58.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0rc5 from https://github.com/mozilla/notes/files/1689535/notes-2.2.0rc5.zip) installed.
- Be logged in a Firefox Notes account.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Click on the three dot button at bottom of the sidebar.
3. Hover the "Give Feedback" button and observe the "Tooltip".

[Expected result]:
- "Give Feedback" tooltip is displayed.

[Actual result]:
- "Sync with..." tooltip is displayed.

[Notes]:
- If the user is not logged in, "Give Feedback" tooltip is correctly displayed.
- Here is a screen recording with this issue:
![tooltip](https://user-images.githubusercontent.com/20083658/35809602-e5494452-0a91-11e8-9e1a-ab47b218b212.gif)

**Comment by vladikoff** [comment]
@himanish-star see above , I think this needs to be tweaked a bit

**Comment by himanish-star** [comment]
I'll surely look into this. :+1:

**Comment by vladikoff** [comment]
sounds good @himanish-star !

**Comment by himanish-star** [comment]
@vladikoff, Please give me one more day. Tomorrow I'll do it for sure.

**Comment by himanish-star** [comment]
I have started my work on this I will soon update you
