### ISSUE TITLE
Add simplified Chinese to list of supported languages

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#664]
[Description]: I found that the Firefox notes could not be entered in simplified Chinese. I recommend adding the function to make the text change.

[Affected versions]: Unknown; feedback from January survey.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]:

[Actual result]:

[Additional Notes]:

**Comment by Natim** [comment]
I tried to type in chinese and I couldn't reproduce the issue:

![can't reproduce](https://user-images.githubusercontent.com/229453/35918439-248d8516-0c12-11e8-8b7b-fb5d7dc7b892.png)

**Comment by vladikoff** [comment]
@Natim yeah same, i tried to this on OS X as well and it was fine :\

**Comment by aerowolf** [comment]
I used Firefox 63.0 on Ubuntu 18.04, it's 64bit.
I tried to type, but input bar (Fcitx) flickers repeatedly.
In the Input box of Notes, I can paste Chinese.
