### ISSUE TITLE
Sync issues/duplication/conflicts

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#669]
[Description]:

1. Very useful tool, I'm used to open an external notepad often. Maybe the ability to save notes as *.txt could make it even better.  I've trying Notes for a few days and randomly appears repeated text before " **** En este ordenador: **** "
2. When enabling sync, I very often see a lot " **** On this computer: **** " followed by the text. I can delete these of course, but they seem to re-appear and multiply.
3. Please make a delay for the sync, it start syncing a soon as I start typing. So while writing a test, it's continuously syncing (inducing lag while typing test in the note)
4. This is an excellent extension.  However, I have noticed that when a lot of information is added to the notepad it begins to lag.  This is probably just a simple issue, but I felt you should know so you can work to resolve this issue.
5. Notes isn't syncing?

[Affected versions]: Unknown; from January survey feedback.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]:

[Actual result]:

[Additional Notes]:

**Comment by Natim** [comment]
Some of this are fixed:

- Please make a delay for the sync

The multiple *** On this computer *** message is handled by #542
