### ISSUE TITLE
General editor lag

### ISSUE THREAD

**Issue by marniepw** [mozilla/notes#670]
[Description]:

1. It was wonderful while it lasted. Then you messed with the settings and now it's useless. The delay when I try to enter anything, even when I press the enter key to make a paragraph space, is so long that I begin to think the whole page has hung. Oh Mozilla, what did you do to my favourite Firefox feature?  :-(((((
2. Congrats on the Syncing! Here it is a bit overzealous, and getting in the way of writing. Cursor jumps to the beginning of File, and lagging occurs. Will it ever sync with Android?
3. There is a performance problem as every keyboard input is saved and it takes some seconds to react. 

[Affected versions]: Unknown; from January survey feedback.

[Prerequisites]:

[Steps to reproduce]:

[Expected result]:

[Actual result]:

[Additional Notes]: Some overlap with: https://github.com/mozilla/notes/issues/669

**Comment by Natim** [comment]
A bunch of changes have been made in 2.2.0 to fix that. It is something we should keep monitoring but I believe that those are fixed:
- The delay when I try to enter anything, even when I press the enter key to make a paragraph space, is so long that I begin to think the whole page has hung
- Cursor jumps to the beginning of File, and lagging occurs.
- every keyboard input is saved and it takes some seconds to react.
