### ISSUE TITLE
"All changes saved" action text is wrongly displayed in gray, when Dark Theme is enabled

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#671]
[Notes]:
- Considering the discussion from #645 , it seems that the action text should be displayed in white, for Dark theme.

[Affected versions]:
- Firefox 58.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0dev custom build from 2018-02-06) installed.
- Have Dark theme enabled.

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Observe the color of the "All changes saved" action text.

[Expected result]:
- The text color is white.

[Actual result]:
- The text color is gray.

[Additional notes]:
- Here is a screen shot with this issue:
![color text](https://user-images.githubusercontent.com/31244235/35862244-a7c11fb6-0b53-11e8-9ab7-0d9aacd03e1d.png)

**Comment by Natim** [comment]
I know what you mean, in the current form of Notes you can click there to activate the sync but it shouldn't be the case, the action is only on `Synced {time}` we will fix when we move to react. In the meantime it is fine to have it grey since iti si not supposed to be clickable.

**Comment by sebastienbarbier** [comment]
I quickly gave a try and fixed it in pull request #550 with light color. This is current result: 
![dark-theme-text-color](https://user-images.githubusercontent.com/3018618/36021908-d613ec8c-0db9-11e8-8985-f32f564aef99.gif)
Should be merged next week so by then we will be able to do more tests and provide feedbacks.

**Comment by sebastienbarbier** [comment]
After feedback from natim, non clickable is back to gray, and clickable is white 😊.

![dark-theme-text-color](https://user-images.githubusercontent.com/3018618/36023996-eac8c786-0dc0-11e8-9643-12e143e07a5b.gif)

**Comment by Natim** [comment]
@ryanfeeley Does this looks like what you wanted? ^

**Comment by vladikoff** [comment]
from mtg: ship it says @ryanfeeley
