### ISSUE TITLE
Leverage the new isOpen sidebarAction API to be able to open/close with the toolbar button

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#675]
For Firefox >= 59 we know have a isOpen info that tells if the sidebar is open or not.
We could use it to be able to use the toolbar button to close the addon.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction/isOpen

**Comment by Natim** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1438465

**Comment by vladikoff** [comment]
Not needed for now...
