### ISSUE TITLE
"Notes" sidebar is not closed when clicking the "Firefox Notes" toolbar button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#676]
[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (2.2.0 installed from TestPilot)

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Click the "Firefox Notes" toolbar button.
3. Observe the "Firefox Notes" sidebar.

[Expected result]:
- "Firefox Notes" sidebar is closed.

[Actual result]:
- "Firefox Notes" sidebar is not closed.

[Notes]:
- Here is a screen recording with this issue:
![notes_toolbar_button](https://user-images.githubusercontent.com/20083658/36097795-18488886-1005-11e8-9c7b-e89f3b949a0b.gif)

**Comment by Natim** [comment]
Dup of #675

**Comment by vladikoff** [comment]
Waiting on Firefox 59 for the api

**Comment by vladikoff** [comment]
for version below 59 it will be as in the GIF

**Comment by Natim** [comment]
This is trickier than I though...
Apparently because isOpen is a promise we can't decide to open or close the sidebar based on its result...

**Comment by vladikoff** [comment]
@Natim kind of related, see https://github.com/mozilla/notes/pull/655#discussion_r167917713 cc @cedricium
