### ISSUE TITLE
The empty rows are not pasted into Firefox Notes regardless of where they are copied from

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#677]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.3.0dev custom build from 12.02.2018) installed.
- Have the following text copied to clipboard: https://goo.gl/wxqUf6.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Focus the sidebar and paste the text from prerequisites.
3. Observe the pasted text.

**[Expected result]:**
- The text is displayed in the same format as in the original document.

**[Actual result]:**
- The empty rows are not pasted.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible if the text is copied from "Thunderbird", "LibreOffice" and partially reproducible if text is copied from "Notepad++" or "Skype" (~4 rows pasted out of 10 copied).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36104176-eefdc36e-1019-11e8-9d91-5b743c3fd0fc.gif)

**Comment by kekkc** [comment]
Any ideas here, what's causing this?

**Comment by kekkc** [comment]
Propably the main bug why notes got not integrated in FF directly. Does anyone know what needs to be done here (apart from simply upgrading Ckeditor after 2 years)?
