### ISSUE TITLE
The Headings are wrongly changed to previous row's size when it is deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#680]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (2.3.0dev custom build from 14.02.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Press the "Enter" key and change the heading from the top-left part of the sidebar.
3. Write something and move the text caret to the beginning of the previous row.
4. Press the "Delete" key and observe the behavior.

**[Expected result]:**
- The row is deleted and all other text is unaffected.

**[Actual result]:**
- The row is deleted and remaining row's heading is changed.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is also reproducible on the "https://ckeditor5.github.io/" website.
- The issue is not reproducible with "Google Docs" and "Thunderbird".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36205235-bd28a1a0-1196-11e8-90f4-de5198f845df.gif)

**Comment by vladikoff** [comment]
this seems fixed with the CKEditor update
