### ISSUE TITLE
Multinote sync update strategy

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#690]
@natim Going to ask this async.

For example, if I have 40 notes and sync them. What is the plan to have each note "updated" on a separate machine.
Does kinto take care of that? Does it pull 40 records down and check if they changed?

**Comment by Natim** [comment]
Kinto will handle that and update the notes that haven't changed locally with the remote one, the one that changed on both will use the conflict strategy.

Today our conflict strategy is to have both content in between
