### ISSUE TITLE
Not working on Arch Linux

### ISSUE THREAD

**Issue by arpitjindal97** [mozilla/notes#696]
### [Description]:
I am on Arch Linux x86_64 bit. I installed Firefox Notes on it but it isn't working.
The tab opens but i can't write anything on it not even the cursor appears. It is working fine on Windows.

### [Affected versions]:

- Firefox 58.0.2-1

### [Prerequisites]:

- Arch Linux
- "Firefox Notes" add-on from [official website](https://testpilot.firefox.com/experiments)

### [Additional Notes]:

![firefox_notes](https://user-images.githubusercontent.com/15676216/36319306-8039e9ce-1368-11e8-9388-15172d4d6544.png)

**Comment by Natim** [comment]
You might see this bug #512 can you try to remove all `cache/` repository in your profile storage folders and retry?

**Comment by vladikoff** [comment]
@arpitjindal97 see also https://github.com/mozilla/notes/issues/512#issuecomment-363822635

**Comment by arpitjindal97** [comment]
removing .mozilla worked for me. I previously had firefox-esr installed.

Thanks you guys
