### ISSUE TITLE
Source code tree modifications

### ISSUE THREAD

**Issue by Natim** [mozilla/notes#700]
I find it a bit hard to cope with the new architecture of the files:

To access the Editor, I need the following path: `src/sidebar/app/components/editor/Editor.js`

What about:
```
sidebar
└──  app
    ├── app.js
    ├── components
    │   ├── Editor.js
    │   ├── Footer.js
    │   ├── FeedbackIcon.js
    │   ├── SyncIcon.js
    │   └── Panel.js
    ├── data
    │   ├── constants.js
    │   ├── editor.js → editorConfig.js
    │   └── initialContent.js
    └── utils
        ├── editor.js
        ├── theme.js
        └── utils.js → time.js
```
Basically I would remove the editor/ layer

**Comment by sebastienbarbier** [comment]
I like that suggestion, looks good!
You can assign to me if you want.
