### ISSUE TITLE
Formatting is not kept when text is sent to "Notes" using the "Send to Notes" context-menu option

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#704]
[Notes]:
- After copying a formatted text and pasting it into "Notes" using the "Paste" context-menu option, the text formatting is kept.

[Affected versions]:
- Firefox 58.0.2 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest "Firefox Notes" add-on version (3.0.0rc2 installed from https://github.com/mozilla/notes/pull/697#issuecomment-366712158)

[Steps to reproduce]:
1. Open Firefox browser with the profile from prerequisites. 
2. Select any formatted text.
3. Choose the "Send to Notes" option from the context-menu.
3. Observe the text formatting in the "Notes" sidebar.

[Expected result]:
- The text formatting is kept.

[Actual result]:
- The text formatting is not kept.

[Additional Notes]:
- Here is a screen recording with this issue:
![send_to_notes](https://user-images.githubusercontent.com/20083658/36385075-2bfb6a20-159a-11e8-916d-4951f87cf1bd.gif)

**Comment by Natim** [comment]
This is a known limitation of the send context API.

**Comment by Natim** [comment]
However this might help: https://github.com/mdn/webextensions-examples/blob/master/context-menu-copy-link-with-types/clipboard-helper.js

**Comment by Natim** [comment]
I created the following Bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1439384
