### ISSUE TITLE
Disable the "Sync Your Notes" button while "Syncing changes" status is displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#708]
**[Notes]:**
- If the "Sync Your Notes" button is active and actionable while the "Syncing changes" status is displayed, then the behavior from issue #479 will be reproducible again.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.0.0rc2) installed.
- You are logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Write something in the sidebar.
3. Observe the "Sync Your Notes" button while the "Syncing changes" status is displayed.

**[Expected result]:**
- The "Sync Your Notes" button is inactive.

**[Actual result]:**
- The "Sync Your Notes" button is active and actionable. 

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36429824-54310244-165c-11e8-9055-83477fe105e7.gif)

**Comment by vladikoff** [comment]
@sebastienbarbier is this easy to fix with React?
