### ISSUE TITLE
The "Send to Notes" option its wrongly displayed in the Notes context menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#710]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.0.0rc2) installed.
- Have content in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and select any amount of text from the sidebar.
2. Right click the selected text and observe the context menu options.

**[Expected result]:**
- The following context menu options are displayed:
	- "Undo"
	- "Copy"
	- "Paste"
	- "Delete"
	- "Select All"
	- "Search Google for"
	- "View Selection Source"
	- "Check Spelling"
	- "Languages"
	
**[Actual result]:**
- The "Send to Notes" option is also displayed. 

**[Additional Notes]:**
- If the "Send to Notes" context menu option is clicked , then the selected content will be duplicated.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36433177-9456de22-1664-11e8-94e6-b82bfafadf34.gif)

**Comment by vladikoff** [comment]
@cedricium is there a way to fix this?

**Comment by cedricium** [comment]
@vladikoff not that I can think of. There's nothing in the `contextMenu` or `sidebarAction` API about disabling it. The best I could do is block the event from occurring, but the `Send to Notes` item will be there still.

**Comment by cedricium** [comment]
@vladikoff spoke too soon - found a simple solution with PR #714.
