### ISSUE TITLE
The recently changed headings are not saved, if the sidebar is reopened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#711]
**[Notes]:**
- The issue is only reproducible if the sidebar is reopened/switched and the heading is changed.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.0.0rc2) installed.
- You are logged into "Firefox Notes".
- Have content in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Close and reopen the sidebar.
3. Select any amount of text from the sidebar
4. Change the heading of the selected text.
5. Observe the bottom part of the sidebar.

**[Expected result]:**
- The "Syncing changes..." message is displayed.

**[Actual result]:**
- The "Synced at "hour" message is displayed.

**[Additional Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible if a formatting style option is used instead (bold, italic, strikethrough etc.)
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36433831-2e63b408-1666-11e8-9ad5-b890ac2bb631.gif)

**Comment by anweshknayak** [comment]
@Softvision-MariusComan it is working fine on my end?

**Comment by Natim** [comment]
I am also having a hard time reproducing this issue.

**Comment by Natim** [comment]
As @Softvision-MariusComan explained to me we need to first close and reopen the sidebar before reproducing.

**Comment by vladikoff** [comment]
> As @Softvision-MariusComan explained to me we need to first close and reopen the sidebar before reproducing.

Ah okay, yea it's a bit of an edge case but not blocking

**Comment by vladikoff** [comment]
Bumping this out v3.1.0, only happens when sidebar reopened.
