### ISSUE TITLE
The "Disable Sync" option is wrongly selected when the "Tab" key is pressed if the "Notes" menu is opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#717]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.0.0rc2) installed.
- You are logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Press the "Tab" key three times and press the "Enter" key.
3. Press the "Tab" key again and observe the behavior.

**[Expected result]:**
- The opened page is focused.

**[Actual result]:**
- The "Disable Sync" option is focused.

**[Additional Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36476385-74feb516-1706-11e8-9f49-273d6c7e0b89.gif)

**Comment by vladikoff** [comment]
> The opened page is focused.

We should check if we can focus the tab instead.

From meeting:

* If we are in the text editing area we want the tab the text
* Tab should highlight the sync button
* Tabbing on the menu should not open the menu
* Once you open the menu the menu does not tab

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (3.1.0rc3 build) installed, on the latest Firefox release and Nightly. Considering this I am closing this issue.
