### ISSUE TITLE
The "Give Feedback" option is missing and the "Export as HTML" option is displayed outside the menu, if it is opened before logging in

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#721]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom build from 22.02.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button and click the "Three dots" menu button.
3. Switch to the "Log In" window and insert your credentials.
4. Observe the "Notes" menu's options.

**[Expected result]:**
- The "Export as HTML", "Disable Sync" and "Give Feedback" options are displayed in the "Notes" menu.

**[Actual result]:**
- The "Export as HTML" option is displayed outside the menu and the "Give Feedback" option is not displayed at all.

**[Additional Notes]:**
- The issue is reproducible if the "Log In" window is closed instead of logging in.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- The issue is no longer reproducible if the menu is reopened.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/36540403-de84ebe0-17e2-11e8-9462-f698a85841cc.gif)

**Comment by vladikoff** [comment]
Good find!

**Comment by vladikoff** [comment]
![image](https://user-images.githubusercontent.com/128755/36855963-d5e1af4a-1d42-11e8-8035-d086db6d679a.png)

**Comment by sebastienbarbier** [comment]
Menu is handled by material library, which need to be manually refreshed if its DOM is updated using `componentHandler.upgradeAllRegistered();`. My guess is on `sync-authenticated` event we need to do it, should be easy to fix.

**Comment by anweshknayak** [comment]
In black theme everything appears normal except `Give Feedback` is missing
![screenshot from 2018-03-07 15-25-11](https://user-images.githubusercontent.com/8139783/37085734-d0951292-221b-11e8-8f7d-393810a99346.png)

**Comment by sebastienbarbier** [comment]
Same issue in light theme ... Should be fixed in #748

**Comment by vladikoff** [comment]
This should be now fixed :)
