### ISSUE TITLE
The "Sign In" window is not brought in foreground when the "Sync Your Notes" button is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#724]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom build from 22.02.2018) installed.
- You are not logged into "Firefox Notes"

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Sync Your Notes" button and switch back to the first window.
3. Click the "Sync Your Notes" button again and observe the behavior.

**[Expected result]:**
- The "Sign In" window is displayed in the foreground.

**[Actual result]:**
- Nothing happens.

**[Additional Notes]:**
- The issue is reproducible if the "Verify your account..." string is clicked instead.
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/36550327-ae9e796c-17fd-11e8-83fc-e6aa1994e0d7.gif)

**Comment by sebastienbarbier** [comment]
More than likely related to our latest fix regarding #712.
