### ISSUE TITLE
Support for multiple notes

### ISSUE THREAD

**Issue by nareshv** [mozilla/notes#725]
### [Description]:

Right now there is only one note book which gets overloaded when too many things needs to be recorded

### [Affected versions]:
All

### [Steps to reproduce]:
Open sidebar notes

**Comment by vladikoff** [comment]
@nareshv thanks for the bug! we are working on that right now. Design here: https://mozilla.invisionapp.com/share/6VBUYHMRB#/screens

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/notes/issues/40
