### ISSUE TITLE
Dark theme color issue on footer

### ISSUE THREAD

**Issue by sebastienbarbier** [mozilla/notes#726]
### [Description]:
On dark theme, footer has some colour issues.

### [Affected versions]:
3.0.0

### [Steps to reproduce]:
- Start note add-on with dark theme
- Click on sync button
- Close login page

### [Additional Notes]:
<img width="318" alt="dark-theme-wrong-colors" src="https://user-images.githubusercontent.com/3018618/36680057-0faa5fb8-1b15-11e8-8c60-4b899b871533.png">

**Comment by vladikoff** [comment]
cc @cedrecium

**Comment by vladikoff** [comment]
cc @cedricium
