### ISSUE TITLE
The formatting options are greyed out and a new row is created at the beginning, if the scrollbar is clicked right after the sidebar was opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#732]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 28.02.2018) installed.
- Have enough content so that the vertical scrollbar is displayed in the sidebar.
- Have the sidebar closed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Notes" toolbar button.
3. Click the scrollbar and observe the top part of the sidebar.

**[Expected result]:**
- The formatting options are active and no extra lines are created in the sidebar.

**[Actual result]:**
- The formatting options are greyed out and a new row is created at the beginning.

**[Notes]:
- The "Space" and the "Enter" key does not work on the created row at the beginning.
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is no longer reproducible if you click inside the sidebar's content area.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/36794715-c8678a36-1ca9-11e8-946f-2bb6de829ec1.gif)

**Comment by vladikoff** [comment]
Ah yes, that's some CKEditor business i think

**Comment by vladikoff** [comment]
This is "fixed" because with multinote I don't think we can get into this scenario...

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.2.0dev custom built on 21.06.2018) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
