### ISSUE TITLE
The export file is not displayed in the downloads panel if it is downloaded in a Private Window

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#733]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 28.02.2018) installed.
- Have the sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a New Private Window.
2. Close the Normal Window (non-private).
3. Click the "Three dots" button from the bottom-right part of the sidebar.
4. Choose the "Export as HTML" option.
5. Click the "Download Arrow" button and observe the displayed downloads.

**[Expected result]:**
- The export file is displayed in the downloads panel.

**[Actual result]:**
- No downloads are displayed for this session.

**[Notes]:
- Although the "notes.html" file is not displayed in the "about: downloads" page, the file it was downloaded and can be find in selected folder for downloads.
- If you also have a normal window opened then the export file will be displayed in the normal window's downloads panel, instead of the private window's one.
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/36795182-050cf2ea-1cab-11e8-87d7-1ac469c397eb.gif)

**Comment by vladikoff** [comment]
@ryanfeeley I guess Firefox Desktop hides the downloads button in the private window. What do you want to do here?

<img src=https://user-images.githubusercontent.com/128755/36795374-e20c3a42-1c70-11e8-8e8c-bdb4c9e980ca.png width=200 /> 

The photon animation actually happens in the non-Private window.


@Softvision-MariusComan this doesn't happen if this is set

<img src=https://user-images.githubusercontent.com/128755/36795478-22da7dc2-1c71-11e8-934d-c8f90833490a.png width=300 />


<img src=https://user-images.githubusercontent.com/128755/36795407-f93841de-1c70-11e8-9507-366e1be1197b.png width=300 />


so at least this is nice

**Comment by cedricium** [comment]
@vladikoff if we add `saveAs: true` to the following code:

```js
// Footer.js, L165-168
browser.downloads.download({
  url: exportFilePath,
  filename: exportedFileName
});
```
This will cause the file chooser to appear even if the user has the "Save files to" option selected. That will help with the visibility with Private mode.

Refs: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/downloads/download

**Comment by vladikoff** [comment]
> This will cause the file chooser to appear even if the user has the "Save files to" option selected

@ryanfeeley I think we should do that, otherwise it looks like "Export" doesn't do anything even in non-Private browsing

**Comment by vladikoff** [comment]
> Does this allow users to save as text (markdown) too?

Unrelated.

**Comment by vladikoff** [comment]
@cedricium let's add the `saveAs: true` please 🍰 !
