### ISSUE TITLE
The "Sync Your Notes" button does not have any hover effect when the "Dark" theme is activated

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#734]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 28.02.2018) installed.
- Have the "Dark" theme activated from about:addons>Extensions>Firefox Notes>Dark.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover the "Sync Your Notes" button from the bottom part of the sidebar.
3. Observe the behavior.

**[Expected result]:**
- The "Sync Your Notes" button is highlighted.

**[Actual result]:**
- The "Sync Your Notes" button does not have any hover effect.

**[Notes]:
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible if the "Default" theme is used instead.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/36795337-74b6235a-1cab-11e8-87c6-cf211a6a3ae7.gif)

**Comment by vladikoff** [comment]
@ryanfeeley @cedricium what should this do?

**Comment by cedricium** [comment]
@vladikoff @ryanfeeley the light theme has a hover effect, I'll go ahead and add it to the dark theme unless there are any objections?

**Comment by sebastienbarbier** [comment]
@cedricium I did try to refactor theming with some CSS variable to avoid having darktheme.css overriding everything. I was hoping this would be easier to maintain but stopped after few hours when I realised this was too much work. Can you check the branch `refactor-theming`I just pushed  and let me know what you think about it 😊 ? It's not working, just proof of work, but should enough to start a discussion.

**Comment by sebastienbarbier** [comment]
@cedricium My issue was having to explicitly define EVERY colors for ckeditor but i really liked the idea. Also would be nice to simplify values to a set of few very clear variableas/colors. Let me know anytime if you want some help or discuss about it, would be awesome to see some improvement here 👍

**Comment by vladikoff** [comment]
@sebastienbarbier @cedricium can we deploy a simple fix just for the hover button?

**Comment by vladikoff** [comment]
Moving this out of 3.1

**Comment by cedricium** [comment]
@vladikoff made the simple fix in #763, it's ready to be looked at.
