### ISSUE TITLE
Add current date and time to Export as HTML

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#735]
### [Description]:

Add current date and time to Export as HTML

### [Steps to reproduce]:

Export notes as HTML via the menu

### [Expected result]:

`notes-2018-02-28-10_38am.html`

@ryanfeeley can you suggest formatting on the file for MAXIMUM UXing?

### [Actual result]:
![image](https://user-images.githubusercontent.com/128755/36796416-85133fb8-1c73-11e8-9716-4b029b3e1a37.png)

**Comment by ryanfeeley** [comment]
@vladikoff Looking at my screenshots, this 24:00 clock format seems to work well. Sorts nicely.

``Firefox Notes 2017-12-24 21.23.31.html``

**Comment by vladikoff** [comment]
@cedricium this fix we will land for sure ^ if you have time

**Comment by cedricium** [comment]
@vladikoff I can have this in at the end of the day (Pacific time) 👍

@ryanfeeley you want the spaces included in the filename?

**Comment by ryanfeeley** [comment]
@cedricium My Windows knowledge is extremely poor. I know that Dropbox includes spaces and periods on the Mac client. Not sure how big a sin this is on Windows and/or Linux.

**Comment by ryanfeeley** [comment]
@cedricium OK, I spoke with the higher powers. We should follow was Firefox does when you **Save Page As…** and just use the title of the note.

e.g ``Mattress Shopping.html`` no time stamp

If the note is blank use: ``blank.html`` or better, disable the export note option in that state.

**Comment by vladikoff** [comment]
> We should follow was Firefox does when you Save Page As… and just use the title of the note.

@ryanfeeley we don't have multi note with this yet though, do you want to get the first Heading or first sentence of the notepad?

**Comment by vladikoff** [comment]
Almost done in https://github.com/mozilla/notes/pull/738
