### ISSUE TITLE
Unable to indent or using tab key while in notes.

### ISSUE THREAD

**Issue by rvelazq2** [mozilla/notes#736]
### [Description]:
Unable to indent or tab when taking notes using the tab key.

### [Affected versions]:
All versions.

### [Steps to reproduce]:
1. Type notes.
2. Tab using the tab key on keyboard.

### [Expected result]:
Make an indent or tab(multiple spaces) in the notepad.

### [Actual result]:
When using the tab key on the keyboard, it tabs you back into the website.

### [Additional Notes]:
Using the tab key would be a great addition, as many people indent and use tabs to take notes for organization.

**Comment by vladikoff** [comment]
Need to investigate...

**Comment by cedricium** [comment]
@vladikoff I think this is a relevant ckeditor issue - https://github.com/ckeditor/ckeditor5/issues/457.

**Comment by vladikoff** [comment]
@cedricium yea they told me it's not on their roadmap, but we might be able to add it on our end via https://github.com/ckeditor/ckeditor5/issues/457#issuecomment-306058137

**Comment by cedricium** [comment]
@vladikoff I'm trying to follow the steps outlined in [this SO post](https://stackoverflow.com/questions/47611200/how-to-programatically-insert-link-at-current-position-in-ckeditor-5) from the ckeditor team for inserting text (in this situtation, the tab character `&#09;`) but it's not working.

Was going to ask for help on gitter, just wanted to confirm that we are on `Before 1.0.0-beta` right?

**Comment by vladikoff** [comment]
> Was going to ask for help on gitter, just wanted to confirm that we are on Before 1.0.0-beta right?

Yes, but let's fix it in beta 1 (see branch https://github.com/mozilla/notes/pull/775) if that's easier, this way we won't have to ask twice 😄

**Comment by cedricium** [comment]
That was going to be my second question - should we just wait to do this after updating ckeditor. Sounds good then, we'll keep this on the back-burner for now 👍

**Comment by vladikoff** [comment]
@cedricium you can checkout that branch and then branch off that to use latest CKEditor APIs, then I can merge your fix into that branch
