### ISSUE TITLE
The sidebar wrongly becomes blank for a second after you send text using the context menu option

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#740]
[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 2018-03-02) installed.
- Be logged in a valid Firefox Notes account.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://en.wikipedia.org/wiki/Tree" page.
2. Select a text and right click on it.
3. Click the "Send to Notes" option and observe the behavior.

[Expected result]:
- The text is instantly sent to the Notes sidebar.

[Actual result]:
- The sidebar becomes blank for a second and only afterwards the sent text is displayed in it.

[Regression]:
- I've managed to find a regression window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/3o4Et5

From the pushlog it seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) might have caused this.

[Notes]:
- This issue is reproducible even if you are not logged in Firefox Notes account.
- This issue is not reproducible on latest Firefox Release 58.0.2.
- I am not authorized to see the bug from the pushlog.
- Here is a screen recording of the issue: 
![notes - sidebar becomes blank when you send text](https://user-images.githubusercontent.com/31244235/36906884-c864235e-1e3f-11e8-9c64-237e227af4c8.gif)

**Comment by cedricium** [comment]
Yikes, great catch! Will investigate further

**Comment by vladikoff** [comment]
@mixedpuppy any ideas?

**Comment by mixedpuppy** [comment]
ISTM that notes is calling sidebarAction.open all the time.  You should first check if it is open by calling sidebarAction.isOpen.  I don't know enough about notes code to make any more detailed suggestion.

**Comment by mixedpuppy** [comment]
You'll want to follow Bug 1445080

**Comment by vladikoff** [comment]
Should be fixed in Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-03-22), on latest Nightly build 61.0a1 (2018-03-21), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
