### ISSUE TITLE
The "Send to Notes" context menu option is no longer working

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#741]
[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://en.wikipedia.org/wiki/Tree" page.
2. Select a text and right click on it.
3. Click the "Send to Notes" option and observe the behavior.

[Expected result]:
- The text is instantly sent to the Notes sidebar.

[Actual result]:
- The sidebar becomes blank for a second and the text is not sent into the sidebar.

[Regression]:
- I've managed to find a regression window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/3o4Et5

From the pushlog it seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) might have caused this.

[Notes]:
- This issue is reproducible even if you are logged in a Firefox Notes account.
- This issue is not reproducible on Windows 10 x64.
- I am not authorized to see the bug from the pushlog.
- This issue might be related to #740.
- Here is a screen recording of the issue: 
![cannot send text via context menu](https://user-images.githubusercontent.com/31244235/36977166-e73e65a0-2088-11e8-9041-09b745a42391.gif)

**Comment by vladikoff** [comment]
cc @mixedpuppy

**Comment by Softvision-CristinaBadescu** [comment]
It seems that this issue is now also reproducible on Windows 10 x64, using Firefox Notes v3.1.0dev (custom built on 2018-03-13), on latest Nightly build 60.0a1 (2018-03-13). Considering this, I'm going to update the title.

**Comment by vladikoff** [comment]
Should be fixed in Nightly 61.0a1 (2018-03-15) (64-bit)
