### ISSUE TITLE
The sent text is duplicated after ~1 min of inactivity if the sidebar was empty

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#742]
[Notes]:
- This issue is a regression that has the same pushlog result as #740 and #741 issues.

[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 2018-03-05) installed.
- Be logged in a valid Firefox Notes account.
- Have nothing written in the sidebar.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to "https://en.wikipedia.org/wiki/Botany" page.
2. Select text and right click.
3. Click the "Send to Notes" option and observe the behavior.

[Expected result]:
- The text is instantly sent to the Notes sidebar.

[Actual result]:
- The text is duplicated and the "**** On this computer: ****" message is displayed between the strings.

[Regression]:
- I've managed to find a regression window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/3o4Et5
From the pushlog it seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) might have caused this.

[Additional notes]:
- This issue is also reproducible with the Firefox Notes version from Test Pilot experiments page.
- This issue is also reproducible if you had written, dragged or pasted text in the sidebar.
- This issue is not reproducible if you already had text in the sidebar sent via context menu option.
- This issue is not reproducible on latest Firefox Release 58.0.2.
- This behavior cannot be tested on Linux and Mac OS'es due to #741 issue.
- Here is a screen recording of the issue: 
![notes - duplicated content](https://user-images.githubusercontent.com/31244235/37027298-9fca5a74-2139-11e8-8e0a-56fc9f7dc522.gif)

**Comment by vladikoff** [comment]
@Softvision-CristinaBadescu, hey if you have time could you file a new regression bug ? Normally we would comment in the existing bug but no access :(

**Comment by Softvision-CristinaBadescu** [comment]
Sure thing, @vladikoff . Since bug #741 is major I've filed that one here , [bug 1443749](https://bugzilla.mozilla.org/show_bug.cgi?id=1443749), and mentioned the other two (#740 and #742).

**Comment by vladikoff** [comment]
@Softvision-CristinaBadescu Thank you!!

**Comment by vladikoff** [comment]
Should be fixed in Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-03-22), on latest Nightly build 61.0a1 (2018-03-21), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
