### ISSUE TITLE
Give feedback menu item should not be dragable

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/notes#745]
### [Description]:
Give feedback menu item should not be dragable

### [Affected versions]:
All linux

### [Steps to reproduce]:
Click on feedback menu -> drag

### [Expected result]:
Should not be draggable

### [Actual result]:
![notes](https://user-images.githubusercontent.com/8139783/37083428-8216a0e6-2215-11e8-9346-8916491a9aee.gif)

**Comment by sebastienbarbier** [comment]
Today 'Give feedback' is using <a> markup, **should be using a button** instead to be compliant with react-a10y and solve this dragging issue 😁
