### ISSUE TITLE
Dark theme: Footer colour enhancement

### ISSUE THREAD

**Issue by anweshknayak** [mozilla/notes#747]
### [Description]: 
Colour of navbar is too contrasted as compared to the dark theme. 

### [Expected result]:
Shouldn't be so contrasting the dark theme and the footer color

### [Actual result]:

![screenshot from 2018-03-07 15-13-19](https://user-images.githubusercontent.com/8139783/37085198-6a510a14-221a-11e8-9aec-8a2a1bc27f28.png)

**Comment by sebastienbarbier** [comment]
I would guess: ckeditor toolbar is darker than content background. Also footer color looks a bit agressive next to dark content background (same yellow color for light and dark theme) ... Might be a sign we need to improve our CSS managment (ref talk in #734 😉).
@ryanfeeley any feedback about this? I'm not sure we have time to define a dark theme mockup with multi-notes going on right now.
