### ISSUE TITLE
The sidebar wrongly becomes blank for a second when clicking the "Notes" toolbar button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#750]
[Notes]:
- This issue is a regression that has the same pushlog result as #740, #741 and #742 issues.

[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" (3.1.0) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click on the "Notes" toolbar icon and observe.

[Expected result]:
- Nothing happens.

[Actual result]:
- The sidebar becomes blank for a second.

[Regression]:
- I've managed to find a regression window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/3o4Et5
From the pushlog it seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) might have caused this.

[Additional notes]:
- The issue is also reproducible with "Firefox Notes" installed from TestPilot.
- Here is a screen recording of the issue: 
![notes_blank](https://user-images.githubusercontent.com/20083658/37094059-44e75f62-221a-11e8-9534-8cd284b29fec.gif)

**Comment by mixedpuppy** [comment]
You'll want to follow Bug 1445080

**Comment by vladikoff** [comment]
Should be fixed in Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-03-22), on latest Nightly build 61.0a1 (2018-03-21), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
