### ISSUE TITLE
The "Send to Notes" context menu option is no longer working in other windows if the sidebar was empty

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#751]
[Notes]:
- This issue is also reproducible if you had text in the first opened window and only afterwards you send text via context menu in the new opened window.
- This issue is a regression that has the same pushlog result as #740, #741, #742 and #750 issues.

[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" (3.1.0) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Delete all text from the sidebar and open a new window.
3. Navigate to a website, select text and right click.
4. Click the "Send to Notes" option and observe the behavior.

[Expected result]:
- The text is instantly sent to the Notes sidebar.

[Actual result]:
- The text is not sent to the Notes sidebar.

[Regression]:
- I've managed to find a regression window using the Mozregression tool. Here are the results:
Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog: https://goo.gl/3o4Et5
From the pushlog it seems that bug [1398713](https://bugzilla.mozilla.org/show_bug.cgi?id=1398713) might have caused this.

[Additional notes]:
- The issue is also reproducible with "Firefox Notes" installed from TestPilot.
- For a brief moment, the text appears in the first opened window's sidebar.
- Here is a screen recording of the issue: 
![notes - not working in other windows](https://user-images.githubusercontent.com/31244235/37095822-9e9f2ae4-221f-11e8-90ff-c11412d5bfda.gif)

**Comment by vladikoff** [comment]
Should be fixed in Nightly 61.0a1 (2018-03-15) (64-bit)

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-03-22), on latest Nightly build 61.0a1 (2018-03-21), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
