### ISSUE TITLE
[Enhancement] The "Notes" toolbar button's icon does not change to the selected "Themer" add-on toolbar icon color

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#754]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 28.02.2018) installed.
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.27 custom build from 08.03.2018) installed from the "about:debugging" page.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Themer" toobar button.
3. Observe the "Notes" toolbar button's icon.

**[Expected result]:**
- The icon has the same color as the rest of the toolbar icons.

**[Actual result]:**
- The icon has a different color.

**[Notes]:
- The "Test Pilot", "Firefox Multi-Account Containers" and "Themer" toolbar button icons all change according to the icon color set by the "Themer" add-on.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37159821-6d224e5a-22f7-11e8-9b55-0f4f85076c99.gif)

**Comment by vladikoff** [comment]
Ref https://github.com/mozilla/notes/issues/772

**Comment by vladikoff** [comment]
Should be fixed in latest v4 build
