### ISSUE TITLE
The "Export as HTML" option is wrongly selected when the up arrow key is pressed if the "Notes" menu is opened

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#759]
[Affected versions]:
- Nightly 60.0a1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Click the three dots button.
3. Press the up arrow key and observe the behavior.

[Expected result]:
- The "Give Feedback" option is focused.

[Actual result]:
- The "Export as HTML" option is focused.

[Notes]:
- The issue is also reproducible with the TxP version of "Firefox Notes".
- If you are logged in, the "Disable Sync" option is wrongly selected.
- On Firefox release 58.0.2, no option is focused if you click the three dots button and press the up arrow key. You can focus the option using the up arrow key only if you focus the three dots menu using the "Tab" key.
- Attached a screen recording of the issue:
![notes - focus](https://user-images.githubusercontent.com/31244235/37348220-403cf0e6-26dc-11e8-8d6e-368fc6459a7d.gif)

**Comment by vladikoff** [comment]
Bumping this out of v3.1, out of time and minor issue. Set for v4 release

**Comment by vladikoff** [comment]
Should be now fixed in v4

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-03-28), on latest Nightly build 61.0a1 (2018-03-28), on Windows 10 x64, Mac 10.13.3 and Arch Linux 4.12.
