### ISSUE TITLE
[Regression] The Notes menu no longer respects the Dark theme

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#760]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 13.03.2018) installed.
- Have the "Dark" theme activated from "about:addons>Extensions>Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Notes" menu button from the bottom-right part of the sidebar.
3. Observe the menu's background color.

**[Expected result]:**
- The background is dark and the text is white.

**[Actual result]:**
- The background is white and the text is black.

**[Notes]:
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37357599-88a427d6-26f1-11e8-9ad2-4ef1d4cb44dc.gif)

**Comment by vladikoff** [comment]
that is by design, see part 2 in comment https://github.com/mozilla/notes/pull/752#issuecomment-371574646 This is to match what Firefox does
