### ISSUE TITLE
The "Sync your Notes" button does not work while the "Saving changes..." message is displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#761]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0dev custom built from 13.03.2018) installed.
- You are not logged into "Firefox Notes".
- Have the Notes sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste or write something in the sidebar.
3. Click the "Sync your Notes" button while the "Saving changes..." message is displayed.
4. Observe the behavior.

**[Expected result]:**
- The "Log In" window is opened.

**[Actual result]:**
- The "Sync Your Notes" button appears to be pressed, but nothing happens.

**[Notes]:
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37357755-df25074c-26f1-11e8-85c0-b11db77de132.gif)

**Comment by vladikoff** [comment]
Going to slate this for a post-3.1 release, unless this is a major, let me know

**Comment by sebastienbarbier** [comment]
I fixed for v3.x, was just a boolean to add.
No more saving state in v4, but I should be careful since this is not the first time we have this kind of issue. Thanks Marius 👍
