### ISSUE TITLE
The HTML file is not downloaded or is wrongly named if the first paragraph's length is over 220 characters

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#766]
**[Notes]:**
- Due to the fact that the first paragraph is auto completed as the file name in the "Save As" window, we have a few suggestions on how to this behavior could be improved:
	- The file name is not auto completed in the "Save As" window, leaving the user to name it him/herself.
	- After the multi-notes feature is implemented, the exported file could inherit the note's title.
	- The filename's length could be limited to under 220 chars.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc2) installed.
- Have a paragraph of 219 characters in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Notes" menu button and select the "Export as HTML" option.
3. Go to the download folder and observe the downloaded file.
4. Add four more characters to the paragraph and export it.
5. Go to the download folder and observe the downloaded file.
6. Repeat Steps 4 & 5.

**[Expected result]:**
- Step 3, 5 & 6: The file is successfully saved each time.

**[Actual result]:**
- Step 3: Under 220 chars, the file is saved successfully.
- Step 5: Over 220, but under 224 chars, the download fails.
- Step 6: Over 225 characters a blank file (without an extension) is saved and named only with the first letter of the paragraph.

**[Additional Notes]:**
- On Mac, the download fails if the paragraph has over 246 characters.
- On Linux, the download fails between 244 and 246 characters and an error is displayed if the paragraph is over 246 characters.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37415428-11ddc81e-27b4-11e8-8115-571185e41065.gif)

**Comment by vladikoff** [comment]
cc @cedricium

**Comment by vladikoff** [comment]
Limited chars to 200 to avoid these edge case issues
