### ISSUE TITLE
Disable the "Export as HTML" option while the "Saving changes..." message is displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#767]
**[Notes]:**
- This issue is much more easily encountered when you are logged in and the "Syncing changes..." message is displayed.

**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc2) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste or write something in the sidebar.
3. Quickly click the "Notes" menu button.
4. Observe the "Export as HTML" option while the "Saving changes..." message is still displayed.

**[Expected result]:**
- The "Export as HTML" option is inactive.

**[Actual result]:**
- The "Export as HTML" option is active and clickable.

**[Additional Notes]:
- If the "Export as HTML" option is clicked while the "Saving changes..." message is displayed then the downloaded HTML file will not contain the latest changes.
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37417083-12444568-27b8-11e8-9067-de364fdffc1e.gif)

**Comment by vladikoff** [comment]
good find!!
