### ISSUE TITLE
[Dark Theme] The "Notes" menu button wrongly remains highlighted after the menu is dimissed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#770]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.
- Have the "Dark" theme activated from "about:addons>Extensions>Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Notes" menu button from the bottom-right part of the sidebar.
3. Click the "Notes" menu button again.
4. Hover away and observe the "Notes" menu button.

**[Expected result]:**
- The button is no longer highlighted.

**[Actual result]:**
- The menu button remains highlighted.

**[Additional Notes]:
- The issue is not reproducible withe the "Notes" default theme.
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37470165-9797d146-286f-11e8-95a7-9e59acd1bb09.gif)

**Comment by vladikoff** [comment]
cc @cedricium

**Comment by vladikoff** [comment]
Cannot reproduce this here on OS X :(

**Comment by Softvision-MariusComan** [comment]
@vladikoff  sorry for any inconveniences. The issue is reproducible only on Windows and Linux. I will update the bug description as well.

**Comment by vladikoff** [comment]
👍
