### ISSUE TITLE
Add CD 10: is user syncing

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#771]
this should be a boolean...we can use this to sort whether syncers retain better.

**Comment by johngruen** [comment]
@ryanfeeley suggests instead of boolean we do `syncing`, `needs verification` etc. Will provide all strings

**Comment by ryanfeeley** [comment]
All the states:
* Not Syncing
* Opening Login Window
* Not Yet Verified
* Mid-Sync
* Syncing
* Syncing >1 Devices
* Forced to Reauthenticate

**Comment by vladikoff** [comment]
Moved to v4
