### ISSUE TITLE
Make browserAction match theme

### ISSUE THREAD

**Issue by johngruen** [mozilla/notes#772]
Since this is a moz-signed add-on you can set 

`fill="context-fill` and `fill-opacity="context-fill-opacity"` in the browserAction SVG and it will inherit theme colors, see  [this example](https://raw.githubusercontent.com/mozilla/Themer/master/src/images/icon.svg) from Themer

**Comment by vladikoff** [comment]
cc @cedricium

**Comment by cedricium** [comment]
Dup of #754.

@vladikoff mind helping with this one? I made the changes per John's comment above and the Notes icon still won't change color when using Themer. I also tried:
- adding `fill="context-fill"  fill-opacity="context-fill-opacity"` to `src/icons/notes.svg` in the `<g>` and `<path>` elements, neither worked.
- adding `-moz-context-properties: fill, fill-opacity;` in the `<style>` tag for the `<path>` element
- unrelated to this but trying to set the color of the svg to `red` or something else didn't work

Kinda at a loss here.

**Comment by vladikoff** [comment]
@johngruen  ^

**Comment by johngruen** [comment]
@cedricium the extension has to have a mozilla.org id for this to work...depending on how you're loading your add-on to preview FF may be generating some random cache busting hash to add to the ID, this will break the regex so context fill won't work
