### ISSUE TITLE
The top part of the "Synced (hour)" button is not clickable

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#779]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the area above the "Synced (hour)" string and observe the behavior.

**[Expected result]:**
- The syncing sequence is started.

**[Actual result]:**
- Nothing happens and the "Sync Your Notes" button is highlighted.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue 2](https://user-images.githubusercontent.com/31243259/37524839-be929528-2933-11e8-8878-b86e1719b2a7.gif)

**Comment by sebastienbarbier** [comment]
Saw this bug too, already fixed in v4 when redesigning the new footer. Let me know if this major and needed in v3.2. (@vladikoff  should we close this ?)

**Comment by vladikoff** [comment]
> already fixed in v4 when redesigning the new footer

Then we can add a `Fixes ....` in the PR for multi-note and this will be auto-closed 👍
