### ISSUE TITLE
"Show sidebars" button is still highlighted after closing the sidebar and opening a new window

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#78]
[Notes]:
- The issue is intermittent:
	- on Mac, 5/10 times.
	- on Windows, 9/10 times.
- The issue is not reproducible without "Firefox Notes" add-on installed.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes v1.2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Notes add-on version (1.2 -dev, built on 16/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new window and click on the "Show sidebars" button in order to hide the "Firefox Notes" sidebar.
3. Open a new window and observe the "Show sidebars" button.

[Expected result]:
- The "Show sidebars" button is no longer highlighted in the browser toolbar.

[Actual result]:
- The "Show sidebars" button is still highlighted in the browser toolbar.

[Notes]:
- Attached a screen recording of the issue:
![notes_toolbar_highlight_button](https://user-images.githubusercontent.com/20083658/27231982-256c3d88-52bd-11e7-9311-fd730edb0fe2.gif)

**Comment by vladikoff** [comment]
Another great find! We might need to file Firefox UX Bugzilla bugs for this 

cc @ryanfeeley

**Comment by ryanfeeley** [comment]
That's a Firefox bug alright. I know this feature is still in development. I'll file it.

**Comment by wresuolc** [comment]
@ryanfeeley please link to the bug here, thanks

**Comment by Natim** [comment]
@ryanfeeley do you know what bug number it is? I am closing in favour of the implementation in Firefox.
