### ISSUE TITLE
The "„" character is wrongly inserted in the sidebar instead of closing it when the "Alt+Shift+W" shortcut is pressed on Mac OS

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#780]
**[Affected versions]:**
- Firefox 58.0.2 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.1.0rc3) installed.
- The "Firefox Notes" sidebar is opened

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and focus the sidebar.
2. Press the "Alt+Shift+W" keys and observe the behavior.

**[Expected result]:**
- The sidebar is closed.

**[Actual result]:**
- The "„" character is inserted.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- The issue is not reproducible on Windows and Linux.
- Attached a screen recording of the issue: 
![rec of the issue 3](https://user-images.githubusercontent.com/31243259/37524920-03a23402-2934-11e8-9214-3d9a92e09a22.gif)

**Comment by vladikoff** [comment]
@cedricium I think we can fix this , can we bind to the shortcut combo from within notes to hide the pad?

**Comment by vladikoff** [comment]
> [Expected result]:

> The sidebar is closed.

Agreed!

**Comment by cedricium** [comment]
@vladikoff should be doable using ckeditor's api, will go ahead and give this a shot.

Refs: https://docs.ckeditor.com/ckeditor5/latest/api/module_core_editingkeystrokehandler-EditingKeystrokeHandler.html

**Comment by vladikoff** [comment]
@cedricium if you are looking at key strokes, see if you can get `<tab>` to tab https://github.com/mozilla/notes/issues/736

**Comment by vladikoff** [comment]
@cedricium this might help https://github.com/ckeditor/ckeditor5/issues/868#issuecomment-369880325 not sure if the code mentioned in that thread is real or what. TAB works on empty list items to indent those might be helpful

**Comment by cedricium** [comment]
@vladikoff opened a PR for this issue. Will take a look at the `tab` problem now 👍
