### ISSUE TITLE
An empty row is wrongly inserted after sending text to notes when the sidebar is empty

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#782]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom build from 19.03.2018) installed.
- Have the sidebar empty.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to any website.
2. Select any text from the opened page and right click on it.
3. Click the "Send to Notes" option and observe the behavior.

**[Expected result]:**
- The content is inserted starting with the first row.

**[Actual result]:**
- The content is inserted after an empty row.

**[Additional Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue: 
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/37603863-41a7a866-2b98-11e8-841c-db6ea4ca7436.gif)

**Comment by sebastienbarbier** [comment]
Same in v4. It's because how send-to-note works, it just add a new paragraph after whatever is in current note.
```note.content = note.content + `<p>${action.content}</p>`; ```
By default, ckeditor replace our empty note ```''```with `<p>&nbsp;</p>`. We need to implement an explicit behaviour for this.

**Comment by vladikoff** [comment]
@sebastienbarbier can we do this in v4 or too much work?

**Comment by sebastienbarbier** [comment]
I'll do it today, should not take long !
