### ISSUE TITLE
Send to Note + Multi-Note + Multi-Window

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#787]
### [Description]:

- [x] Make sure "Send to Note" can work with multiple windows open (sidebars)
 If you have 3 windows it will create 3 notes

Extracted from: https://github.com/mozilla/notes/pull/743

**Comment by sebastienbarbier** [comment]
Right now send-to-note is performed by react which means having two windows with note sidebar open will perform the action twice. We need to move this action in background script.
