### ISSUE TITLE
Remove user data when Firefox Account is deleted

### ISSUE THREAD

**Issue by wresuolc** [mozilla/notes#788]
The FxA team is working on building some kind of notification service that an account has been deleted.  We should monitor that service and when an account is deleted remove any data we have stored for that account.

We should also document this somewhere so we can point to it easily.

**Comment by andymckay** [comment]
That API already exists, @vladikoff should know about it.

**Comment by andymckay** [comment]
I'm also going to /cc in @glasserc who has some ideas about how to do this for the storage.sync API, I'm hoping the solution can be re-used.

**Comment by rfk** [comment]
Oh hey, we actually have documentation about this now:  https://github.com/mozilla/fxa-auth-server/blob/master/docs/service_notifications.md#account-deletion-event

**Comment by vladikoff** [comment]
I believe this is done in prod now, cc @glasserc  👍
