### ISSUE TITLE
The updated permissions are a little too powerful to grant.

### ISSUE THREAD

**Issue by Pomax** [mozilla/notes#789]
![image](https://user-images.githubusercontent.com/177243/37735837-6d4ca4e2-2d0c-11e8-8e44-56b7b17be07d.png)

![image](https://user-images.githubusercontent.com/177243/37735686-0a8ca334-2d0c-11e8-9a20-df26d41145f6.png)

If this extension is going to gain the power to violate the expectation of a true download history, it should come with configurable options that allows you to say "no, you do not have permission to modify my download history" (especially since not giving those permissions right now means you can't get updates to the plugin).

Especially since the current options are fairly spartan:

![image](https://user-images.githubusercontent.com/177243/37735917-a91e45c0-2d0c-11e8-8da9-e88a1e8e2c6e.png)

**Comment by vladikoff** [comment]
Some rough thoughts on this issue:

I guess I do agree with you that the permission description is scary. However, this project is open source, you can see the source right here: https://github.com/mozilla/notes/blob/7fca11b8282e6d00ddf3f58c3590f293e4951729/src/sidebar/app/components/Footer.js#L230 That's all we use that permission for. You can take the extension apart and verify that this is it. From there on you can audit every extension update to see what changed and if the permission is doing something new. 

Anyway,  some solutions for the future:

1. Soon the `downloads` permission will become optional, Firefox 60 or 61, this way we can only request it when users press "Export". 

2. Instead of using the download API we can just open a new tab with a `data` url with the contents and we can later expect the user to just press "Save as" from there. Rough UX but maybe we can combine that with solution from # 1.

**Comment by Pomax** [comment]
While true, that is not something that can reasonably be expected from people who've opted into the test pilot program. Plenty of non-tech folks who have no idea how to do this, and also plenty of tech folks who don't have the luxury of time when it comes to auditing a plugin codebase to see if it's safe to grant some permissions.

The main reason to file this is not so much "can this code be trusted" but "can it be made explicit what the plugin will use the permissions for, and can options be added to ensure that users who accepted the permissions can revoke them again post-update".

If the intent is to export, as I recall we can effect that in FF by using the html5 `download` attribute on a dynamically created `<a>` element, which makes FF pop up the save dialog when `a.click()` is called. That should also make the download chronicling simply happen "because it should" rather than having to access the download history object itself.

**Comment by vladikoff** [comment]
> If the intent is to export, as I recall we can effect that in FF by using the html5 download attribute on a dynamically created <a> element, which makes FF pop up the save dialog when a.click() is called. That should also make the download chronicling simply happen "because it should" rather than having to access the download history object itself.

Yeah exactly, that sounds like a solution we can attempt

**Comment by vladikoff** [comment]
> If the intent is to export, as I recall we can effect that in FF by using the html5 download attribute on a dynamically created <a> element, which makes FF pop up the save dialog when a.click() is called. That should also make the download chronicling simply happen "because it should" rather than having to access the download history object itself.

@cedricium something to explore if you have time, instead of using the downloads api can we just open a window that has HTML in it and let the user go from there (save as, print it , etc)

**Comment by vladikoff** [comment]
We can bring the downloads api back in FF60 or w/e when it is an optional permission

**Comment by cedricium** [comment]
@vladikoff to clarify - on our end we would just open a new tab with that note's content and that's it? The user would then need to manually `Save as...` themselves?

**Comment by sebastienbarbier** [comment]
What about something like this : https://stackoverflow.com/questions/2897619/using-html5-javascript-to-generate-and-save-a-file ?

**Comment by sebastienbarbier** [comment]
@cedricium What about something like this : https://stackoverflow.com/questions/2897619/using-html5-javascript-to-generate-and-save-a-file ?

**Comment by cedricium** [comment]
@sebastienbarbier ahh, nice find! I think initiating the download ourselves makes sense to do here - I'll go ahead and code a solution similar to the SO post.

**Comment by sebastienbarbier** [comment]
@cedricium Any work done on this one ? Can I suggest something ?

**Comment by sebastienbarbier** [comment]
Found this amazing library which does everything me : https://github.com/eligrey/FileSaver.js

**Comment by Pomax** [comment]
awesome, thanks!
