### ISSUE TITLE
Investigate creating a "title" field for the note

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#796]
### [Description]:

This might be good for multi-note, but also good for mobile performance. This way we only download the note ids and titles, thus avoiding download the whole note content.

We can slate for later releases if too complicated.

**Comment by vladikoff** [comment]
@sebastienbarbier thoughts?

**Comment by sebastienbarbier** [comment]
True we could do some optimisation here, but I have difficulties to believe requesting all notes is that of an issue ... what about creating a metrics to see how long that request take (should be related to the size and number of notes I guess).

**Comment by vladikoff** [comment]
@sebastienbarbier, @ryanfeeley was pasting 700kb documents into thing, that's why im freaking out a bit 😋😥

**Comment by vladikoff** [comment]
Moved out of v4
