### ISSUE TITLE
The title of a note cannot be edited

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#803]
**[Affected versions]:**
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom built on 2018-03-26) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button.
3. Try to edit the note's title.

**[Expected result]:**
- The title can be edited.

**[Actual result]:**
- The title cannot be edited.

**[Notes]:**
- The title is composed from the note's first paragraph.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37916980-f0421c66-3125-11e8-854e-80be816e0a52.gif)

**Comment by ryanfeeley** [comment]
Implemented as designed (similar to Apple Notes)

**Comment by SoftVision-PaulOiegas** [comment]
@ryanfeeley @johngruen can you guys tell us any major concerns/limitations why this won't be implemented? To be honest, I don't think the end users would appreciate to have their Notes forcefully named by the first paragraph of their text. I expect they will complain about this as soon as this will reach the public.

Also, and please don't be upset on us about this, Apple software should not be considered standard when the Firefox users base is mostly on Windows OS. 
Unless the Firefox Notes users base is different (do we have any metrics?), I don't think we should limit something like this.

**Comment by vladikoff** [comment]
@SoftVision-PaulOiegas Hey! thanks for the message. 

> @ryanfeeley @johngruen can you guys tell us any major concerns/limitations why this won't be implemented? To be honest, I don't think the end users would appreciate to have their Notes forcefully named by the first paragraph of their text. I expect they will complain about this as soon as this will reach the public.

There is some complexity in note structure that would need to be tweaked. I think we probably won't do this in this release. We need to change the format and encrypt both the title and the contents. Also this makes it a bit more complex for the mobile app, where we would need to add an extra field fo the title. There's already very limited space on mobile.

> Also, and please don't be upset on us about this, Apple software should not be considered standard when the Firefox users base is mostly on Windows OS.
Unless the Firefox Notes users base is different (do we have any metrics?), I don't think we should limit something like this.

:) No worries, no one is upset. This is good feedback! Ryan Feeley is closely monitoring the feedback and i am sure he will file a bug right away if he sees a lot of requests for note title.

**Comment by ryanfeeley** [comment]
None taken! I love the passion! It's true that we can be too Apple-centric.

Having the title taken from the first line has these advantages:

1. Low maintenance. Just works and is easy to understand.
1. Does not require data structure changes.

It has these disadvantages:

1. Waste of space when space is limited. Duplicates first line.
1. Difficult to edit when UI is limited (mobile, sidebars)

I expect that we will get a small but vocal amount but I think the first-line title will serve the majority best.
