### ISSUE TITLE
The "Back" toolbar button does not have a tooltip

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#804]
**[Affected versions]:**
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom built on 2018-03-26) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button.
3. Hover the "Back" button from the left of the note's title.
4. Observe the behavior.

**[Expected result]:**
- A tooltip is displayed.

**[Actual result]:**
- There is no tooltip displayed.

**[Notes]:**

- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/37917188-71704f60-3126-11e8-80a8-455f86c68e7c.gif)

**Comment by ryanfeeley** [comment]
@sebastienbarbier Seeing as Firefox desktop uses sentence case we should say: "Back to all notes"

**Comment by vladikoff** [comment]
👍

**Comment by sebastienbarbier** [comment]
Duplicate with #795 when this has been done.
