### ISSUE TITLE
[Enhancement] Each note from the list should have a delete button

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#805]
**[Affected versions]:**
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom built on 2018-03-26) installed.
- Have minimum a note in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover any note from the sidebar and observe the behavior.

**[Expected result]:**
- A "Delete" button should be displayed.

**[Actual result]:**
- There is no "Delete" button displayed.

**[Notes]:**
- We consider that adding a "Delete" button for each note would improve the user experience.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37918922-1cc7496e-312b-11e8-9040-fff867df4f94.gif)

**Comment by ryanfeeley** [comment]
I propose we provide a contextual menu.

@vladikoff @sebastienbarbier Something like this?

<img width="249" alt="image" src="https://user-images.githubusercontent.com/68213/37932267-0d9c42f6-3116-11e8-9a32-1fded160cb1f.png">

**Comment by vladikoff** [comment]
@ryanfeeley probably not for initial v4 release but we can explore that

**Comment by sebastienbarbier** [comment]
I like that, quite simple and intuitive for everyone. 
What about sliding for actions ?
![touchactions](https://user-images.githubusercontent.com/3018618/37940947-943dda8e-3195-11e8-8a3d-17058f721415.gif)

**Comment by vladikoff** [comment]
Moving out of v4
