### ISSUE TITLE
Make drag border colour the same as system focus

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#806]
### Drag border colour:
![drag](https://user-images.githubusercontent.com/68213/37934268-a3d78ffa-311b-11e8-8df1-41332e3c536c.gif)

### [Steps to reproduce]:
* Drag text from web onto Notes

### [Expected result]:
* Drag border colour is the same as system highlight colour (in my case, light blue)
* Content does not shift

### [Actual result]:
* Color is green
* Content shifts

### [Additional Notes]:
Mac example:
<img width="133" alt="screen shot 2018-03-26 at 5 30 46 pm" src="https://user-images.githubusercontent.com/68213/37934322-d09b99dc-311b-11e8-9590-d8e8471998b0.png">

**Comment by vladikoff** [comment]
Moved out of v4

**Comment by ryanfeeley** [comment]
@vladikoff Is the green hard coded?

**Comment by cedricium** [comment]
@ryanfeeley it is: https://github.com/mozilla/notes/blob/master/src/sidebar/static/scss/ckeditor.scss#L100

I have a fix for it here: https://github.com/mozilla/notes/pull/1269
