### ISSUE TITLE
The buttons from the title bar are wrongly highlighted with a darker color than the rest of the buttons

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#807]
**[Affected versions]:**
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom built on 2018-03-27) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover "Back" button from the left part of the note's title and observe its highlight color.
3. Hover any other buttons excepts the ones from the title bar and observe their highlight color.
4. Compare the highlight color of the both buttons.

**[Expected result]:**
- All buttons have the same highlight color.

**[Actual result]:**
- The highlight color of the "Back" button is darker.

**[Notes]:**
- I have used the "Color Picker" application and it seems that the HTML code color of the highlighted area for the "Back" button is "D7D7D" and for the rest of the sidebar buttons is "EBEBEE".
- The issue is reproducible for all the buttons from the title toolbar.
- Attached a screenshot of the issue: 
![notes](https://user-images.githubusercontent.com/31243259/37973415-14c98a7a-31e3-11e8-92ac-ed91099b0c2f.png)

**Comment by vladikoff** [comment]
good catch! @ryanfeeley confirm?

**Comment by ryanfeeley** [comment]
Design system to the rescue (of me)!
https://design.firefox.com/photon/components/buttons.html#ghost-3

<img width="709" alt="image" src="https://user-images.githubusercontent.com/68213/37993265-133c50c2-31dc-11e8-8a33-be6680a465fe.png">

**Comment by vladikoff** [comment]
@cedricium possible to fix?

**Comment by cedricium** [comment]
@vladikoff should be doable 👍

**Comment by sebastienbarbier** [comment]
@cedricium Can i quickly fix this one ?

**Comment by vladikoff** [comment]
@cedricium otherwise if you already have code for this, send a PR and @sebastienbarbier will review.

We are tracking stuff for v4 in here: https://github.com/mozilla/notes/projects/4

**Comment by cedricium** [comment]
@sebastienbarbier sure thing, go for it!
