### ISSUE TITLE
[Enhancement] The active area of the buttons from the bottom toolbar should be larger

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#808]
**[Affected versions]:**
- Firefox 59.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev custom built on 2018-03-26) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover the buttons from the bottom toolbar and observe their active areas.

**[Expected result]:**
- The active areas should be larger.

**[Actual result]:**
- The active areas are too small.

**[Notes]:**
- In the TxP version the button's active area is larger that in the current version.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37974055-8d774f42-31e4-11e8-9213-4e623d5b2dfe.gif)

**Comment by vladikoff** [comment]
Moving out of v4

**Comment by vladikoff** [comment]
@ryanfeeley thoughts on the issue though?

**Comment by ryanfeeley** [comment]
Good eye! It does look like our buttons are too small @sebastienbarbier.

Pixel specifications are here: https://design.firefox.com/photon/components/buttons.html#default-3
