### ISSUE TITLE
Animation from our Photon menu system

### ISSUE THREAD

**Issue by sebastienbarbier** [mozilla/notes#813]
Switching from note list to note editor should trigger an animation like in Firefox Photon menu system.
@ryanfeeley can you provide a description regarding the animation to implement ? (like a slow motion video may be 😁)

**Comment by ryanfeeley** [comment]
Regular speed and slow-motion speed attached.
[Doorhanger Menu.zip](https://github.com/mozilla/notes/files/1856542/Doorhanger.Menu.zip)
