### ISSUE TITLE
Add spillover menu to editor options

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#825]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 3) installed.
- "Firefox Notes" sidebar is displayed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover the right margin of the sidebar until the "double arrow" is displayed.
3. Click and drag the margin to its minimum width.
4. Observe the "Bulleted List" and the "Numbered List" buttons.

**[Expected result]:**
- The buttons are visible and active.

**[Actual result]:**
- The buttons are not longer visible.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/38019364-0752e402-3280-11e8-9693-9cbd18d02d2c.gif)

**Comment by vladikoff** [comment]
by new design, @ryanfeeley confirm?

**Comment by sebastienbarbier** [comment]
Looks like when sidebar is at normal width, there is a 4px white line bottom of ckeditor toolbar.
![capture d ecran 2018-03-28 a 20 30 56](https://user-images.githubusercontent.com/3018618/38032152-22d5fc2c-32c7-11e8-9a10-b56d11441179.jpg)

**Comment by ryanfeeley** [comment]
This is as designed until we have a proper spillover menu as depicted in the mockup:

https://mozilla.invisionapp.com/share/6VBUYHMRB#/281041484_Firefox_Notes

**Comment by ryanfeeley** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/68213/38039059-69f78776-327a-11e8-8317-573c572a4d13.png">
