### ISSUE TITLE
Font Size (Heading style) dropdown is wrongly displayed under the content area

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#826]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 3) installed.
- "Firefox Notes" sidebar is displayed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on "Font size" dropdown and choose a different font.

**[Expected result]:**
- The "Font size" dropdown is displayed and you can succesfully choose a different font size.

**[Actual result]:**
- The "Font size" dropdown is displayed under the content area and you can no longer choose a different font size.

**[Notes]:**
- Attached a screen recording of the issue: 
![fontsize_dropdown](https://user-images.githubusercontent.com/20083658/38025784-4952277a-3292-11e8-9965-ae99681e68bd.gif)

**Comment by vladikoff** [comment]
Ah yess, need to adjust that
