### ISSUE TITLE
You are wrongly logged out from "Firefox Notes" after reopening the sidebar if two notes were previously deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#827]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 3) installed.
- You are logged into "Firefox Notes".
- Have minimum two notes in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click on a note and press the options menu button from the right side of the title.
3. Select the "Delete Note" option.
4. Repeat steps 2 and 3.
5. Close and reopen the sidebar.
6. Observe the bottom toolbar.

**[Expected result]:**
- The "Synced(hour) message is displayed.

**[Actual result]:**
- You are logged out and the "Sign in to Sync" message is displayed..

**[Notes]:**
- The issue is reproducible if you switch the sidebar or if you restart the browser.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38027793-9b37f5f4-3299-11e8-9720-cc88c13819fd.gif)

**Comment by sebastienbarbier** [comment]
Currently working on this one, similar to #802

**Comment by sebastienbarbier** [comment]
Playing with delete feature, I receive 500 from server (Kinto team actually reported it on github : https://github.com/Kinto/kinto/issues/1557).
One other issue I received was the following error message:
```
TypeError: resolution is undefined
Stack trace:
syncKinto/</<@moz-extension://79a6ec10-37db-ae4f-9f84-fbf82f43c79f/sync.js:220:15
syncKinto/<@moz-extension://79a6ec10-37db-ae4f-9f84-fbf82f43c79f/sync.js:192:28
```
So hopefully ... handling or fixing those two might solve this problem.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5 build) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
