### ISSUE TITLE
The Note list is wrongly displayed if you delete all text from a Note and open a new window

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#831]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev) installed.
- Have at least one note in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button and paste some text.
3. Select all the text and delete it. 
4. Open a new window and switch back to the other window.
5. Observe the "Notes" sidebar.

**[Expected result]:**
- The "New Note" is displayed.

**[Actual result]:**
- The "New Note" is deleted and the note list is displayed.

**[Notes]:**
- This issue is also reproducible if you create a New Note, don't have text and open a new window.
- Attached a screen recording of the issue:
![delete text and open window](https://user-images.githubusercontent.com/31244235/38040269-cc09c9be-32b7-11e8-8741-95ad7e041ad4.gif)

**Comment by vladikoff** [comment]
```
[Expected result]:

The "New Note" is displayed.
[Actual result]:

The "New Note" is deleted and the note list is displayed.
```

@Softvision-CristinaBadescu hey, so every time we open a new window we should open to the Notes ListView, does that clarify this?

**Comment by sebastienbarbier** [comment]
There is a feature in listView which hide and delete empty notes. 
When opening a new window, we sync the other window state which include the empty note we work one ... then listPanel delete it 😅. Works well if note is not empty.

**Comment by vladikoff** [comment]
> Have at least one note in the sidebar.

Oh I was confused about the initial state, if I understand the issue correctly then good find @Softvision-CristinaBadescu !!

**Comment by Softvision-CristinaBadescu** [comment]
Hey @vladikoff :) Yes, that would be great. In this way, we'll keep a consistency and in every opened window we'll see the same thing.

**Comment by Softvision-CristinaBadescu** [comment]
Hey @sebastienbarbier , actually I can intermittently reproduce this behavior with only one letter.
See the screen recording below:
![intermittently with 1 letter](https://user-images.githubusercontent.com/31244235/38043805-c14ece12-32c0-11e8-8f85-bea2b7514d96.gif)

**Comment by sebastienbarbier** [comment]
😱. Thanks a lot, will make sure that’s gone by tomorrow 😈.

**Comment by vladikoff** [comment]
Could you check this one?
