### ISSUE TITLE
[Enhancement] Text caret should appear in the sidebar when you click the "New Note" button

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#833]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev) installed.
- Have Firefox Notes sidebar open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "New Note" button and type something.

**[Expected result]:**
- The text is displayed.

**[Actual result]:**
- No text is written.

**[Notes]:**
- You need to click inside the sidebar in order to focus it.
- Attached a screen recording of the issue:
![firefox notes enhancement](https://user-images.githubusercontent.com/31244235/38042066-feb267fa-32bb-11e8-9e26-8cc7afad2bba.gif)

**Comment by vladikoff** [comment]
Good find! 👍 this would be great to have

**Comment by vladikoff** [comment]
@sebastienbarbier let's see if we can do this for v4. We couldn't focus the editor on sidebar-open before but it might work with React views

**Comment by vladikoff** [comment]
Good find! we might be able to fix that

**Comment by vladikoff** [comment]
Yay!
