### ISSUE TITLE
Dark Theme improvements

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#834]
![image](https://user-images.githubusercontent.com/128755/38042488-86748568-3282-11e8-877f-33ffeeb99f82.png)

@cedricium I merged the main PR 👍 looks good, minor improvements we can make:

- [ ] Let's make the title bar fit the same style as the `+ Add Note` bar.
- [ ] Can we make the scrollbar dark?
- [ ] The editor background looks dark, can it match the same colour as the title bar?

**Comment by cedricium** [comment]
@vladikoff working on these dark theme improvements now.

> Can we make the scrollbar dark?

Not possible - this has [been an issue for a looong time](https://bugzilla.mozilla.org/show_bug.cgi?id=77790) (17 years to be exact lol)

**Comment by vladikoff** [comment]
> Not possible - this has been an issue for a looong time (17 years to be exact lol)

@cedricium ah yes, I knew that then forgot, remembered and forgot again. i also saw devtools had a darker sidebar but maybe they are doing some voodoo. No worries then 👍  thanks

**Comment by vladikoff** [comment]
@cedricium also sources tell me that 2018 is finally gonna be the year of a styled scrollbar (https://bugzilla.mozilla.org/show_bug.cgi?id=1432935), so hopefully we will be able to get this done before the original bug is [old enough to buy alcohol in Canada](https://en.wikipedia.org/wiki/Alcoholic_drinks_in_Canada#Age).
