### ISSUE TITLE
You are not brought back to the previous Notes view after the sidebar is switched or reopened

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#843]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 4) installed.
- Have at least one note in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Switch the sidebar to "Bookmarks" (or any other sidebar). 
3. Switch back to Notes and observe the sidebar.

**[Expected result]:**
- The previously Notes view is displayed.

**[Actual result]:**
- The "Notes" list view is displayed.

**[Notes]:**
- This issue is also reproducible when closing and reopening Notes.  
- Attached a screen recording of the issue:
![note_sidebar](https://user-images.githubusercontent.com/20083658/38095469-39efc886-3379-11e8-9dde-8297be2027a6.gif)

**Comment by vladikoff** [comment]
@ryanfeeley do you want this?

**Comment by vladikoff** [comment]
from mtg: yea we should try to do our best to re-open where the user was. Not worrying about multi-window too much

**Comment by vladikoff** [comment]
Pulling this out of v4, @SoftVision-EmilPasca let us know if this is critical

**Comment by SoftVision-EmilPasca** [comment]
I don't think this is necessary a critical issue. However, this issue could be quite annoying for users who are frequently navigating through different sidebars or who might have other sidebar addons enabled such as tab center redux.
@ryanfeeley @johngruen any thoughts on this?

**Comment by ryanfeeley** [comment]
Oops, I thought I had thrown support for this. This is a very important feature to engage interested users.
