### ISSUE TITLE
The "Firefox Notes" toolbars and buttons do not respect the "Dark" theme colors

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#844]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 4) installed.
- Have the "Dark" theme activated from "about:addons>Extensions>Notes".
- A note is opened in the sidebar.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Observe the sidebar's toolbars.

**[Expected result]:**
- The toolbars backgrounds respect the "Dark" theme color.
- The toolbars' buttons are fully visible.
- The toolbars' strings respect the "Dark" theme color.

**[Actual result]:**
- Both toolbar background color is the same as the one from the "Default" theme.
- The buttons' colors are almost the same color as the toolbar.
- The toolbars' strings have the same color as the ones from the "Default" theme.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38095094-474a1604-3378-11e8-9275-0d7c8f19bdb7.gif)

**Comment by vladikoff** [comment]
cc @cedricium 

Almost full dup of https://github.com/mozilla/notes/issues/834 keeping it open

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5 build) installed, on the latest Firefox Release and Nightly. Verified on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
