### ISSUE TITLE
The "Disable Sync" option is slightly moved down after the bottom toolbar menu is opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#845]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 4) installed.
- You must be logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the menu button from the bottom toolbar and observe the "Disable Sync" option.

**[Expected result]:**
- The menu is opened and the "Disable Sync" is correctly displayed.

**[Actual result]:**
- The "Disable Sync" option is slightly moved down after the menu is opened.

**[Notes]:**
- The issue is not reproducible on Mac 10.12 and Ubuntu 14.04 x64.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38095669-ad6cbfd0-3379-11e8-99aa-18a4651fdf6f.gif)

**Comment by vladikoff** [comment]
Something to do with the css `EMs`

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5 build) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64.
