### ISSUE TITLE
There is no confirmation message displayed when a note is deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#853]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have a note opened in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Menu" button from the right side of the note's title.
3. Select the "Delete Note" option and observe the behavior.

**[Expected result]:**
- A delete confirmation message is displayed.

**[Actual result]:**
- The note is deleted.

**[Notes]:**
- Considering that this is a "destructive" action we should be sure that the user really wants that and is not done by mistake.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38137078-3691388e-342b-11e8-81c7-edeba086753c.gif)

**Comment by vladikoff** [comment]
Out of v4

**Comment by vladikoff** [comment]
@ryanfeeley can add some designs for this in a bit

**Comment by ryanfeeley** [comment]
Following our copy conventions established by existing strings:

RENAME MENU ITEM
* Delete Note… (add the ellipsis as the action is now reviewable)

CONFIRMATION DIALOG COPY
* Are you sure you want to delete this note?

PRIMARY BUTTON
* OK

SECONDARY BUTTON
* Cancel

**Comment by heyakyra** [comment]
Might be better to implement #1028 instead
