### ISSUE TITLE
[Enhancement] A new note should be created when text is dragged in the list view mode

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#855]
**[Notes]:**
- If the "Send to Notes" context option is used under the same circumstances, then the text is displayed in the sidebar as a new note. Considering this we think that we should do the same for the drag and drop action.

**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have the sidebar in the list view mode.
- Have a website opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and select any text from the opened website.
2. Click and drag the selected text in the sidebar.
3. Observe the behavior.

**[Expected result]:**
- A new note containing the dragged text is created.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38137671-ba708e86-342e-11e8-80c4-7f8e474a8a2b.gif)

**Comment by vladikoff** [comment]
Out of v4 for now
