### ISSUE TITLE
The "Undo" context menu option is wrongly grayed out if text is pasted/dragged/sent to the sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#856]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have a note opened in the sidebar.
- Have a website opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and select any text from the opened website.
2. Click and drag the selected text in the sidebar.
3. Right click in the sidebar and observe the "Undo" context menu option.

**[Expected result]:**
- The "Undo" option is active and usable.

**[Actual result]:**
- The "Undo" option is grayed out.

**[Notes]:**
- The issue is reproducible if the text is dragged in the sidebar or if the "Send to Notes" option is used.
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38141409-b659b504-3440-11e8-8f02-b6e0178e53dc.gif)

**Comment by cedricium** [comment]
I was able to reproduce, but also when typing or removing text the "Undo" is always grayed out as well. I found an issue from the W3C - https://github.com/w3c/editing/issues/150 - which calls for the removal of the browser "Undo" option and CKEditor was listed as supporting this.

> It was pointed out that the browser's undo stack would be entirely useless once the JS editor interrupt the default behavior even in just a few limited cases.
>
> In addition, the following JS editor projects were contacted and all of them responded that the browser's undo stack and default undo behavior was either useless or harmful:
> - CKEditor

CKeditor5-undo has an open issue for handling system undo - https://github.com/ckeditor/ckeditor5-undo/issues/67

It does seem that using the system keyboard shortcut for "Undo" (<kbd>Ctrl</kbd>/<kbd>⌘</kbd> + <kbd>Z</kbd>) works.

**Comment by vladikoff** [comment]
Out of V4
