### ISSUE TITLE
The "Sign In" window is not closed when the "Cancel Setup" option is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#859]
**[Notes]:**
- If the "Log In" window is not closed, when you will try logging in again, the "Your connection is not secure" message will be wrongly displayed in the "Log In" window.

**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have the sidebar opened.
- You are not logged into "Firefox Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Sync Your Notes" button.
2. Switch back to the first window and click the "Menu" button from the bottom-right part of the sidebar.
3. Select the "Cancel Setup" option and observe the behavior.

**[Expected result]:**
- The "Log In" window is closed and the "Sign in to Sync" message is displayed in the bottom toolbar.

**[Actual result]:**
- The "Sign in to Sync" message is displayed in the bottom toolbar, but the "Log In" window remains opened.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38200851-99ba7cde-369e-11e8-9215-f3650ae29f51.gif)

**Comment by vladikoff** [comment]
Yeah I have looked at this before, I don't think we have an API to close this window :(

This is the only api we have: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/identity/launchWebAuthFlow  Which is `launching` only.

@mixedpuppy, any ideas? I was thinking we can call a `win.close()` if `launchWebAuthFlow` gave us a Window, but it's a Promise.

**Comment by mixedpuppy** [comment]
Not much we can do here.  I'm not sure why a cancel is in the ui at this stage when it couldn't do anything in the first place.  Bug 1320862 would possibly let you address it better.

**Comment by vladikoff** [comment]
@mixedpuppy Thanks for the quick response!

@sebastienbarbier I think we should pull the `Cancel Setup` button then

**Comment by mixedpuppy** [comment]
Just a thought.  If there is more to the setup than auth, you could introduce the button once the auth promise is resolved.

**Comment by vladikoff** [comment]
Out of v4, we can clean the ui with "Cancel Setup", but we cannot close windows
