### ISSUE TITLE
The "Firefox Notes" doorhanger is wrongly placed under the sidebar switcher button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#86]
[Notes]:
- Based on the other sidebar switcher options, when selected, the doorhanger starts at a small distance from the left browser margin, right under the sidebar switcher option icon.
- I have a hunch that this issue might be due the fact that there is no "Firefox Notes" icon in the sidebar switcher.

[Affected versions]:
- Firefox 53.0 and up
- Firefox Notes v1.2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes Notes add-on version (1.2 -dev, built on 19/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the sidebar switcher "Notes" button.
3. Observe the position of the displayed doorhanger.

[Expected result]:
- The "Firefox Notes" doorhanger is displayed at the same position as the other sidebar switcher options.

[Actual result]:
- The "Firefox Notes" doorhanger is wrongly placed closer to the browser left margin and also covers the bottom part of the sidebar switcher button. 

[Additional Notes]:
- Attached a screenshot of the issue:
![notes_switcher](https://user-images.githubusercontent.com/20083658/27289422-8c51fb30-5512-11e7-891b-32445a163b08.png)

**Comment by wresuolc** [comment]
This is the expected place for web extensions.
