### ISSUE TITLE
The "Disable Sync" option does not have any hover effect, if the "Notes" dark theme is activated

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#860]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have the sidebar opened.
- You are logged into "Firefox Notes".
- Have the "Dark" theme activated from "about:addons>Extensions>Notes".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Menu" button from the bottom toolbar and hover the "Disable Sync" option.
3. Observe the behavior.

**[Expected result]:**
- The "Disable Sync" option is highlighted and a tooltip is displayed.

**[Actual result]:**
- The tooltip is displayed, but the "Disable Sync" option is not highlighted.

**[Notes]:**
- The issue is not reproducible when the "Notes" default theme is activated.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38201370-c297b7fa-36a0-11e8-9613-0db1a1e09fa4.gif)

**Comment by vladikoff** [comment]
Out of v4 unless @cedricium will have time

**Comment by cedricium** [comment]
@vladikoff  I can work on this - mind updating `ckbuilt` branch?

**Comment by vladikoff** [comment]
@cedricium will do! I will let you know when that is done

**Comment by vladikoff** [comment]
@cedricium Hey! I force pushed to https://github.com/mozilla/notes/commits/ckbuilt

So delete the branch locally and pull it again, don't forget to `npm install` after that

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0rc1 build) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.12 and Ubuntu 14.04.
