### ISSUE TITLE
The title of a note is wrongly displayed if the note contains only a list

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#861]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- Have the sidebar opened.
- Have a blank note opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the "Bulleted List" list button.
2. Write a word and press the "Enter" key.
3. Repeat step 2 for three times.
4. Observe the displayed title.

**[Expected result]:**
- The title is composed of the first line of the list.

**[Actual result]:**
- The title is composed of all the elements from the list and are merged into one single word..

**[Notes]:**
- The issue is also reproducible with the "Numbered List".
- Attached a screen recording of the issue:
![rec of the issue 1](https://user-images.githubusercontent.com/31243259/38201404-db039994-36a0-11e8-91d4-3fd4ad6ca1d0.gif)

**Comment by vladikoff** [comment]
> [Expected result]:

> The title is composed of the first line of the list.

@ryanfeeley can you confirm what this should do again?

was it supposed to be `test test test` ?

**Comment by sebastienbarbier** [comment]
I did fix this exact issue with the content summary 🤣. Let me check this should take a second to fix.

**Comment by sebastienbarbier** [comment]
@ryanfeeley: I did implement same as content formating.

![formattitle](https://user-images.githubusercontent.com/3018618/38232240-64a0d2d0-3740-11e8-8827-8dc9a1010d12.gif)

**Comment by ryanfeeley** [comment]
Correct. Only the first line should be shown in the title. Subsequent lines can appear in the second line excerpt on the list view.
