### ISSUE TITLE
Cannot not input any "notes" into the the "notes" panel

### ISSUE THREAD

**Issue by HydrophobaHalibut** [mozilla/notes#866]

**Comment by sebastienbarbier** [comment]
Wow that's an extreme situation, I don't recall such issue yet. @HydrophobaHalibut do you have some info about how this occur ? Which version of Firefox are you using, how did you install the notes addon ? best would be if you could copy/paste logs you are having when starting the addon.

To see them, you need to open `Browser Toolbox` in toolbar menu : `Tools` > `Web developer` > `Browser Toolbox`, or in Hamburger menu using `Web developer` > `Browser Toolbox`. `Console` should open with some very precise feedbacks.

@ryanfeeley, @vladikoff anyone else ever had such issue ? Any clue ?

**Comment by ryanfeeley** [comment]
@sebastienbarbier This happens to many users. I usually tag this feedback as a "Performance & Stability" issue in our etherpad doc. Very critical problem.

**Comment by HydrophobaHalibut** [comment]
Yes, I think so. I’ve got a “Notes” sidebar heading, with a dropdown menu (apparently for the option of using the sidebar for another purpose: “Bookmarks”, “History”, “Synced Tabs”, “Notes”. “uBlock Logger”, “Move sidebar to right”, and “Close Sidebar” are the dropdown choices listed there).
But aside from the word “Notes” and the caret beside it that opens the dropdown menu, the entire “sidebar” column is blank space with no input fields of any kind.

**Comment by vladikoff** [comment]
@HydrophobaHalibut If you switched between Nightly and Stable firefox builds that could break your profile storage. there are some workarounds in that bug on how to fix that. This can also be caused by other issues

**Comment by HydrophobaHalibut** [comment]
I don't know if i replied to the most recent replies to my question (I'm new to this Github forum format).
Yes, all i see is a blank panel (with a "Notes" icon, the word "Notes", and a drop-down carat symbol).
Yes i think it's probably the same as described in issue #512 .
No, i don't think I've switched between Nightly and Stable builds. I don't think I've ever installed the Nightly build at all. The edition i'm running is 59.0.2 (64-bit).
However, a while back i *did* uninstall it a couple times, reinstalling the pre-Quantum edition (i still dislike the new Quantum changes, and i still wish i could get all my old extensions back, but i caved to the all the scary security warnings it kept throwing at me, and eventually re-upgraded to Quantum [59.0.2]).

**Comment by vladikoff** [comment]
@HydrophobaHalibut let's continue with that in https://github.com/mozilla/notes/issues/512

**Comment by vladikoff** [comment]
@HydrophobaHalibut left a comment for you in https://github.com/mozilla/notes/issues/512#issuecomment-380194795
