### ISSUE TITLE
The text from the "Welcome to Firefox Notes!" default note wrongly remains in the sidebar after the "New Note" button is clicked from the sidebar's header menu

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/notes#867]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (3.2.0dev) installed.
- Have Firefox Notes sidebar open.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Welcome to Firefox Notes!" default note.
3. Click the sidebar's header menu.
4. Select the "New Note" option and observe the behavior.

**[Expected result]:**
- A new note is created and the sidebar has no text.

**[Actual result]:**
- "New Note" title is displayed, but the previous text remains in the sidebar.

**[Notes]:**
- This issue is also reproducible using Firefox Notes v4.0.0, Beta 6.
- You need to click again the "New Note" button from the sidebar's header menu in order to overpass this issue.
- Attached a screen recording of the issue:
![notes - new note from default text](https://user-images.githubusercontent.com/31244235/38240069-2d7e43a4-3737-11e8-99ac-a8f71fe1bdad.gif)

**Comment by vladikoff** [comment]
should now be fixed , will be in the next beta

**Comment by Softvision-CristinaBadescu** [comment]
The issue is no longer reproducible using Firefox Notes v3.2.0dev (custom built on 2018-04-04), on latest Nightly build 61.0a1 (2018-04-04), on Windows 10 x64, Mac 10.13.3 and Ubuntu 14.04 x64.
