### ISSUE TITLE
Text cannot be undo-ed after using the "Send to Notes" option

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#871]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 Beta 5) installed.
- The "Firefox Notes" sidebar is opened in the note view mode.
- Have any website opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select any text from the opened website and right click on it.
3. Click the "Send to Notes" option and focus the sidebar.
4. Press the "Ctrl+Z" keys and observe the behavior.

**[Expected result]:**
- The recently added text is removed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Also, after the text was sent to "Notes", the "Undo" context menu option is grayed out.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![undo rec of the issue](https://user-images.githubusercontent.com/31243259/38256139-43ed2e50-3766-11e8-89c8-745177a749ee.gif)

**Comment by vladikoff** [comment]
Out of v4
