### ISSUE TITLE
"Send to Notes" doesn't add text if note is empty after pressing "+ New Note"

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#877]
### [Description]:

![a](https://user-images.githubusercontent.com/128755/38289046-37fcb246-37a2-11e8-824a-bed95facc40f.gif)

# STR

* Press "New Note"
* Do not enter any text, use "Send to Notes"

**Comment by vladikoff** [comment]
Could be related to https://github.com/mozilla/notes/issues/872

**Comment by sebastienbarbier** [comment]
Ouuuh well done finding this one! It actually create a note outside of the editor. Bug caused by refactoring deleting process in beta.6. Not sure how to fix let me give a look.
