### ISSUE TITLE
Mobile: What to show when there are no notes

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#899]
@antlam what should we do in the mobile app when there are no notes?

No notes synced down from WebExtension or the user never used the WebExtension

* Show a "Welcome Note" / create one for them
* Tell users to go install Test Pilot extension?
* Other ideas?

### [Current view]:

![image](https://user-images.githubusercontent.com/128755/38344422-882a3d46-3857-11e8-9d77-aa8691c38d02.png)

**Comment by antlam** [comment]
Good question! 

@ryanfeeley and I were talking about this. Especially since all users default to having 1 note in Desktop. That also creates some extra cases for us.

When there are no notes at all I think we could at least show a screen with an image and some text as a more delightful empty state. I can work on a placeholder design for you in the meantime. 

Will post in a bit!

**Comment by antlam** [comment]
![screen shot 2018-04-05 at 9 58 29 am](https://user-images.githubusercontent.com/1994820/38380233-fc6f724c-38b7-11e8-977b-3b2768d12881.png)

@vladikoff

**Comment by vladikoff** [comment]
@antlam thank you so much!

**Comment by ryanfeeley** [comment]
For inspiration: https://material.io/guidelines/patterns/empty-states.html#empty-states-avoiding-completely-empty-states

**Comment by antlam** [comment]
@vladikoff just FYI I'm also going to ping out Content Strategy team to see if we can get an illustration going for this page, so I'll keep you posted. 

If we can, it will just add to this with an image on top of the text.

**Comment by vladikoff** [comment]
@ryanfeeley @antlam sounds great 👍

**Comment by ryanfeeley** [comment]
This is less of a problem on desktop at the "New Note" is on top.

**Comment by vladikoff** [comment]
@ryanfeeley plus we have a Welcome Note :)

**Comment by ryanfeeley** [comment]
@vladikoff We would also have the name welcome note on android, no?

**Comment by antlam** [comment]
I'm confused. 

I thought that notes were synced? Given that, they can also be erased. So we still need a design for this. Maybe we should take this discussion onto Slack to clear up?

**Comment by ryanfeeley** [comment]
@antlam OK, join #notes on Slack.

**Comment by vladikoff** [comment]
Improvements to this moved to v7

**Comment by vladikoff** [comment]
We got some text for this now
