### ISSUE TITLE
The sidebar wrongly flickers when the "Firefox Notes" toolbar button is clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#901]
**[Affected versions]:**
- Firefox 60 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 RC1) installed.
- Have the sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Notes" toolbar button and observe the sidebar.

**[Expected result]:**
- Nothing happens.

**[Actual result]:**
- The sidebar flickers.

**[Regression window]:**
- Considering the fact that the issue is not reproducible on Firefox Release (59.0.2), using the Mozregression tools, I have managed to find the regression window:

Last good revision: 7433031c9274b8299c3e2d50613de74352684bc1
First bad revision: 95a6bd5b90452da6eee11eb8ee53ef80c91565c6
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=7433031c9274b8299c3e2d50613de74352684bc1&tochange=95a6bd5b90452da6eee11eb8ee53ef80c91565c6

From the pushlog it seems that Bug 1398713 has caused this behavior.

**[Notes]:**
- The issue is not reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38356466-7b85bc66-38c8-11e8-9cbc-a32bc5cd54d0.gif)

**Comment by vladikoff** [comment]
Ah, this bug comes back all the time, but i think i know how to fix it up , \o/


Thank you Marius

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" add-on (4.0.0 RC2 build) installed, on the latest Firefox release and Nightly. Verified on Windows 10 x64, Mac 10.13 and Ubuntu 14.04 x64.
