### ISSUE TITLE
Figure out localization for the mobile app

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#910]
Hey @flodolo,

I'm trying to figure out how to add localization to the mobile app. 

So far I found this module https://github.com/AlexanderZaytsev/react-native-i18n#installation that uses i18n-js ( https://github.com/fnando/i18n-js ) library. I assume we would need to convert the pontoon format to that. 

I will look into alternative solutions as well. Let me know if you have any suggestions.

**Comment by flodolo** [comment]
Since you're looking into React, you should check if you can use Fluent, and chat with @stas or @pike for any questions. A couple of links: 
* [Fluent](http://projectfluent.org/)
* [fluent-react](https://github.com/projectfluent/fluent.js/)
