### ISSUE TITLE
Add Android App Icon

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#916]
Hey @antlam,

We don't have an app icon, the only graphic we have is this:
<img src=https://user-images.githubusercontent.com/128755/38476587-878614aa-3b7c-11e8-950a-6b6ae48635e1.png width=200 />

What should we do for Android? Also does the 'blue' in that icon match your 'app blue' colour? (should it match?)

**Comment by antlam** [comment]
Let me reach out to the team that helped us with the Focus and Fennec icons to get us something... stay tuned!

**Comment by vladikoff** [comment]
cc @johngruen

**Comment by vladikoff** [comment]
@johngruen If you send me a new icon I will add it
