### ISSUE TITLE
Add promotion for the mobile app in the webextension

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#918]
Maybe a single notification?
and a link in the meatball

**Comment by vladikoff** [comment]
@ryanfeeley could you post something into here before you PTO?

**Comment by vladikoff** [comment]
After chatting with @ryanfeeley this is the mock / rough design idea and text:

![image](https://user-images.githubusercontent.com/128755/39581716-39594152-4eba-11e8-9b7c-e22124af3ab8.png)

**Comment by cedricium** [comment]
@vladikoff what's the link to be used for the "Get app..." item?
