### ISSUE TITLE
Save the attempt to Sync into local store

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#92]
We already send a GA event, but we want to have the ability to notify users that "Sync is available now" once it ships. Should we bother notifying just those who pressed "Sync notes" or should we just tell everybody?
 
Ref: https://github.com/mozilla/notes/blob/master/src/background.js#L29

**Comment by Natim** [comment]
We already save it: https://github.com/mozilla/notes/blob/master/src/background.js#L27

**Comment by vladikoff** [comment]
HERO @Natim !!
