### ISSUE TITLE
Selected text is wrongly deleted when the "Windows" key is pressed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#924]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 RC2) installed.
- Have "Firefox Notes" opened in the note view.
- Have content in the sidebar.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Select the text and press the "Windows" key.
3. Observe the behavior.

**[Expected result]:**
- The "Start" (Windows) or the "Search" (Linux) menu is opened.

**[Actual result]:**
- The selected content is deleted and the "Start" (Windows) or the "Search" (Linux) menu is opened..

**[Notes]:**
- The issue is also reproducible on Mac, if you are using "Synergy" and the "Windows" key is pressed from another PC keyboard.
- The issue is not reproducible if the "Windows" key is pressed from a "normal" keyboard that is plugged into a Mac.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38555402-99bb08a8-3cce-11e8-986b-652c97dbc869.gif)

**Comment by vladikoff** [comment]
@Softvision-MariusComan  hey, can you repro this on https://ckeditor5.github.io/ ?

**Comment by Softvision-MariusComan** [comment]
Yes, this behavior is also reproducible on https://ckeditor5.github.io/.

**Comment by vladikoff** [comment]
Filed https://github.com/ckeditor/ckeditor5/issues/955
