### ISSUE TITLE
Only the first level from a multileveled list is pasted into the "Firefox Notes" sidebar

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#925]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0 RC2) installed.
- Have "Firefox Notes" opened in the note view.
- Have a multilevel list copied to the clipboard (https://goo.gl/uj5FT2).

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Paste the list from prerequisites and observe the behavior.

**[Expected result]:**
- All the levels of the multileveled list are pasted in the sidebar.

**[Actual result]:**
- Only the first level from a multileveled list is pasted.

**[Notes]:**
- The issue is reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38558314-5aae87b6-3cd8-11e8-9ca7-54ad949139c1.gif)

**Comment by vladikoff** [comment]
Could you try it on https://ckeditor5.github.io ?

**Comment by Softvision-MariusComan** [comment]
I have tested this issue on https://ckeditor5.github.io/ and it seems that the behavior is a little bit different. On the "CKEditor" website only the content from the first levels is pasted, without the bullets or numbers and it is pasted backwards from the third line to the first one.
I've attached a screen recording:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38568409-406021da-3cf1-11e8-9d1b-4b2ca270f37c.gif)

**Comment by vladikoff** [comment]
Filed https://github.com/ckeditor/ckeditor5/issues/956
