### ISSUE TITLE
Lighten bottom border of notes in list view

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#927]
The bottom of the New Note button and top of Sign in to Sync should remain the same, but let's use Grey 20 (#ededf0) for the bottom border of notes in the list view.
https://design.firefox.com/photon/visuals/color.html#grey

![border](https://user-images.githubusercontent.com/68213/38577237-55d7fb46-3cce-11e8-8f15-bd63072ed7c0.png)

**Comment by sebastienbarbier** [comment]
Hi @pamellaazevedo 👋, would be awesome to get some help, please give it a try and let us know if you have any questions 😁.
