### ISSUE TITLE
"Bullet list button" is no longer displayed if the user shrinks the Sidebar to the minimum

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/notes#93]
[Notes]:
- The user has to resize the Sidebar again if he wants to have access to "Bullet list" button.

[Affected versions]:
- Firefox 54.0 and up
- Firefox Notes v1.3

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Firefox Notes Notes add-on version (1.3 -dev, built on 20/06/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click and drag the Sidebar border to the maximum left.
3. Observe the formatting option buttons from top of the Sidebar.

[Expected result]:
- All the formatting option buttons are visible and reachable.

[Actual result]:
- "Bullet list" button is no longer visible.

[Additional Notes]:
- Please see the following screencast:

![button](https://user-images.githubusercontent.com/26000308/27345121-38b57bac-55f1-11e7-8689-467e65c85a19.gif)

**Comment by vladikoff** [comment]
thanks for the report! this is by design for now
