### ISSUE TITLE
[Windows] The "Notes" sidebar's UI do not change accordingly when Windows "High Contrast" is activated

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/notes#931]
**[Affected versions]:**
- Firefox 59.0.2 and up

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on(4.0.0) enabled from https://testpilot.firefox.com/.

**[Steps to reproduce]:**
1. Open the browser with the profile from the prerequisites.
2. Go to Windows High Contrast Settings and change the Windows theme option to "High Contract #1".
3. Focus the browser and observe the UI of the "Notes" sidebar.

**[Expected result]:**
"Notes" sidebar's UI is changed accordingly in High Contrast mode.

**[Actual result]:**
"Notes" sidebar's UI remains unchanged.

**[Notes]:**
-"Bookmarks", "History" and "Synced tabs" change accordingly to the "High Contrast" mode.
-Attached a screen recording of the issue:
![high contrast](https://user-images.githubusercontent.com/37875464/38615700-431e6f04-3d9a-11e8-8eaa-ef7324758413.gif)

**Comment by vladikoff** [comment]
dup of https://github.com/mozilla/notes/issues/417 ?
