### ISSUE TITLE
The "New Note" string is wrongly displayed as title if you have 20 empty rows before actual text

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#933]
**[Affected versions]:**
- Firefox 59.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Firefox Notes" add-on (4.0.0) installed.
- Have the "Notes" sidebar opened.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and click the New Note button.
2. Write a word and move the text caret at the beginning of the row.
3. Press the enter key 20 times and observe the behavior.

**[Expected result]:**
- The "New Note" string is displayed in the title toolbar regardless of how many empty rows exist.
or
- The first row of text is displayed as a title regardless of how many rows exist.

**[Actual result]:**
- Under 20 empty rows : The first row with text is displayed in the title field.
- Over 20 empty rows : The "New Note" string is displayed in the title field.

**[Notes]:**
- If you have text on the first line, then 20 empty rows and after that you will have text again, the first paragraph of the second text will be displayed as content preview, if the sidebar is in the note list view.
- The issue is also reproducible with the TxP version of "Firefox Notes".
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/38623981-ac89d6da-3daf-11e8-886e-d722ba958429.gif)

**Comment by vladikoff** [comment]
Good find! I hope no one does this in real life, that's just a silly thing to do 😜
