### ISSUE TITLE
What should the version string be in mobile for Google Analytics?

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#947]
Hey @johngruen @chuckharmston 

What version string should we send to GA for the mobile app to avoid confusion and create better dashboards? Right now Notes Android is at `1.0`.  Ideas?

**Comment by chuckharmston** [comment]
For mobile, I'd suggest formatting the request very differently, using GA's app tracking parameters https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#apptracking

**Comment by vladikoff** [comment]
@chuckharmston I captured an example of sending a `login-success` event here:

```
sr=1080x1776&
ec=notes&
cid=37ee584a-5442-4b08-8762-1c01808c29b2&
_v=ma11.0.20&
_s=4&
av=1.0&
a=323121906&
v=1&
an=Notes&
t=event&
ul=en-us&
tid=UA-101177676-1&
ea=login-success&
aid=com.notes&
ht=1523937773844&
qt=5086&
_gmsv=12.5.21
```

Let me know how that looks

**Comment by chuckharmston** [comment]
That looks great! You'll also want to make sure to set [`ds`](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ds) to `web`.

**Comment by vladikoff** [comment]
This was fixed
