### ISSUE TITLE
prevent Save As default action when I cmd + s inside an active Note

### ISSUE THREAD

**Issue by miketaylr** [mozilla/notes#955]
### [Description]:

When I hit cmd/ctrl + s inside Notes, I don't want to save the adjacent webpage.

### [Affected versions]:
Latest.

### [Steps to reproduce]:
1. open Notes
2. inside a note, hit cmd/ctrl +s

### [Expected result]:

Nothing, or a Sync.

### [Actual result]:
Save As dialog (for the tab that just happens to be open).

### [Additional Notes]:
I'm trying to move over from Evernote, and cmd+s is a habit of mine -- it forces a sync there.

Also, Notes is the greatest. Thank u for ur service.

**Comment by vladikoff** [comment]
@cedricium Did you have experience with adding this shortcut handling? can we capture cmd/ctrl + s when the editor is focused? I think we probably cannot when it is not focused.

**Comment by vladikoff** [comment]
@cedricium I'm thinking `do nothing` because we already sync pretty aggressively at the moment.

**Comment by cedricium** [comment]
@vladikoff was going to make a PR with the fix for this but I may have messed up the `ckbuilt` branch. My actual fix is in 82b71c09362d8e7dc604c6964e7aa297973ab455, but it looks like I brought in a bunch of over commits into that branch as well.

Hopefully you can help lol
