### ISSUE TITLE
Align single list view

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#960]
if no second line, the first line is misaligned

![](http://v14d.com/i/5ad8b5ba8bbe6.jpg)

**Comment by pamellaazevedo** [comment]
Hello, can I try to contribute to this bug?

**Comment by sebastienbarbier** [comment]
@pamellaazevedo Thanks for asking 😍 ! I suspect this is related to some issue with our sync/encrypt/editor ... basically corrupted note content (empty line) ... I'm currently refactoring it and hope this issue will be fixed automatically. Let's wait few days to have more info 👍, I'll keep you up to date 😉
