### ISSUE TITLE
Editor view "Synced" does not look centered

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#974]
![](http://v14d.com/i/5adbef3a410d2.jpg)

**Comment by vladikoff** [comment]
it seems shifted a bit to the left

**Comment by sebastienbarbier** [comment]
Seams like our meat ball menu have extra space on its right. I assume if we fix this then 'synced' text would be centred. @pamellaazevedo you feel like giving a try and making a PR ? 😁
Should be somewhere in `native/app/components/EditorPanelHeader.js`.

<img width="997" alt="capture d ecran 2018-04-25 a 10 53 27" src="https://user-images.githubusercontent.com/3018618/39225499-eeffd24a-4876-11e8-99ec-3342f8135692.png">
