### ISSUE TITLE
Chinese character input method won't work 

### ISSUE THREAD

**Issue by NiceGuyAlex** [mozilla/notes#977]
### [Description]:
My Chinese character input method (Sogou) won't work if I try to type in the start of a line.
Its window just flicks and dissapears every time I type in a letter. 

### [Affected versions]:
4.0.0

### [Requirements]
OS: Deepin 15.5 unstable
Kernel: x86_64 Linux 4.14.0-deepin2-amd64
Mozilla Firefox Nightly 62(64 bit)

### [Steps to reproduce]
Try to type in anything without a letter(e.g. letter a) in front of it in Sogou input method

### [Expected Result]
The window of the input method should stay on the screen until you leave the input window or press  space and type in something

### [Actual Result]
The window just flicks and dissapears when I try to type

**Comment by vladikoff** [comment]
@NiceGuyAlex Hey! are you able to use Chinese input on this example editor page: https://ckeditor5.github.io/

 ?

**Comment by vladikoff** [comment]
Should be fixed in 4.2.0
