### ISSUE TITLE
[Android] The keyboard is not triggered when a new note is opened

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#987]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0alpha1) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Tap the "New Note" button and observe the behavior.

**[Expected result]:**
- The keyboard is triggered and the text caret is placed at the beginning of the content area.

**[Actual result]:**
- The keyboard is not triggered and the text caret is not displayed.

**[Notes]:**
- The keyboard is triggered only when you tap somewhere in the top half part of the screen.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39250879-9cf0b314-48aa-11e8-8514-a4a3a802b695.gif)

**Comment by vladikoff** [comment]
Dup of https://github.com/mozilla/notes/issues/941 

Filed at facebook/react-native#18965

**Comment by vladikoff** [comment]
I also copied the contents of the issue into there, it's better than what was there before
