### ISSUE TITLE
Clean up requests and syncing in mobile updating logic

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#988]
Currently typing `qwerty` slowly results in the following requests.

**This is just too much. There are 6 requests to batch, for 6 letters.**

![image](https://user-images.githubusercontent.com/128755/39251271-df19aa14-4870-11e8-8dd8-b5ef6d63b2ce.png)

Let's debounce the Syncing such that:

* The editor waits until you stop typing or navigate away from the Note, then it Syncs
* When you start typing the word "Syncing..." disappears. 
* After there is some pause we start showing "Syncing..." and actually sync

**Comment by sebastienbarbier** [comment]
Fix via #999
