### ISSUE TITLE
[Android] If opened, the keyboard is not closed after a note is deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#989]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0alpha1) installed.
- Have at least one note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open any note and tap anywhere on the displayed text.
3. Tap the "More" menu button from the top right part of the application.
4. Select the "Delete" option and observe the behavior.

**[Expected result]:**
- The note is deleted, you are returned to the list view and the keyboard is closed.

**[Actual result]:**
- The note is deleted, you are returned to the list view but the keyboard is still opened.

**[Additional Notes]:**
- After following the steps, if you write something, the deleted note is redisplayed and the entered string is added to it.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39251472-0a807396-48ac-11e8-85ea-b1ede3a7c028.gif)

**Comment by vladikoff** [comment]
Good find! 👍

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v1964) installed. Verified on on Samsung S7 Edge(Android 7.0).
