### ISSUE TITLE
[Android] The keyboard can only be triggered when the row with text is tapped

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#990]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0alpha1) installed.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Create a new note with one word and go back to the list view.
3. Reopen the note and tap anywhere except the row with the word. 
4. Observe the behavior.

**[Expected result]:**
- The keyboard is triggered.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- If the row with the word is tapped, the keyboard is triggered.
- The issue is not reproducible when the note is created (see notes from #987).
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39251619-6de97770-48ac-11e8-875a-6c59a448832b.gif)

**Comment by vladikoff** [comment]
Related to https://github.com/mozilla/notes/issues/970

**Comment by Softvision-MariusComan** [comment]
@El-Dringo-Brannde I have retested this issue and it seems that it is still reproducible on Samsung S8. However, the issue is not reproducible on the Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0) devices.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v2516 custom built on 25.06.2018) installed. Verified on Samsung S8 (Android 8.0.0), Huawei P8 Lite (Android 6.0) and Pixel (Android 8.0.0).
