### ISSUE TITLE
[Android] The "Text Selection" pointer is still displayed after a note is deleted

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#993]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (1.0alpha1) installed.
- Have at least one note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open any note and tap on any word from it.
3. Tap on the "More" menu from the top right part of the application.
4. Select the "Delete" option and observe the behavior.

**[Expected result]:**
- The note is deleted, you are returned to the list view and the "Text Selection" pointer is no longer displayed.

**[Actual result]:**
- The note is deleted, you are returned to the list view, but the "Text Selection" pointer is still displayed.

**[Notes]:**
- After following the steps, if you tap on the "Text Selection" pointer a menu is open and you are able to copy, cut, paste or select the text from the previous deleted note.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/39253585-dceb225a-48b0-11e8-8a75-ffb90168ce5f.gif)

**Comment by vladikoff** [comment]
@sebastienbarbier I think the "EditorPanel" needs to be destroyed **harder** in this case 💥 . Even though we reset the navigation I Think the view still lives on

**Comment by vladikoff** [comment]
Might be related: https://github.com/react-navigation/react-navigation/issues/1056

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v1964) installed. Verified on on Samsung S7 Edge(Android 7.0).
