### ISSUE TITLE
The previously deleted notes are wronlgy shown when tapping the "Back" button

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/notes#994]
*[Affected versions]:*
- LG G5 (Android 7.0)
- Samsung Galaxy S7 edge (Android 7.0)

*[Prerequisites]:*
- Have the latest version of the "Firefox Notes" application (1_0-qa-v1938) installed.
- Have at least one note created.

*[Steps to reproduce]:*
1. Open the Notes application and log in if needed.
2. Open any note and tap on the "More" menu from the top right part of the application.
3. Select the "Delete" option.
4. Tap the "Back" button and observe the Notes behavior.

*[Expected result]:*
- The previously deleted note is not shown.

*[Actual result]:*
- The previously deleted note is wronlgy shown.

*[Notes]:*
- The issue is also reproducible when deleting more notes and tapping the "Back" button several times.
- Attached a screen recording of the issue:
![20180426_102756](https://user-images.githubusercontent.com/20083658/39292089-c6e5914c-493d-11e8-8569-43cdb9bd2ab9.gif)

**Comment by sebastienbarbier** [comment]
Might be fixed with PR #986 ... let's test again after merging it.

**Comment by sebastienbarbier** [comment]
I believe #986 fixed it, back button now close the app.

**Comment by SoftVision-EmilPasca** [comment]
This issue is no longer reproducible, tested with the latest notes-1_0-qa-v2184.apk
