### ISSUE TITLE
[Android] If the "Back" button is tapped while the "Syncing..." message is still displayed, the saved changes are only displayed in the list view

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/notes#996]
**[Affected Platforms]:**
- Samsung Galaxy S7 edge (Android 7.0)

**[Prerequisites]:**
- Have the latest version of the "Firefox Notes" application (notes-1_0-qa-v1938) installed.
- Have at least one note created.

**[Steps to reproduce]:**
1. Open the Notes application and log in if needed.
2. Open any note from the list view.
3. Edit the note's content and press the back button while the "Syncing..." message is still displayed.
4. Observe the modified note from the list view.
5. Open the same note again and observe the content.

**[Expected result]:**
- Step 4: The note's title and content preview are correctly updated according with the latest changes.
- Step 5: The content is correctly upddated according with the latest change.

**[Actual result]:**
- Step 4: The note's title and content preview are correctly updated according with the latest changes.
- Step 5: The content is displayed without the changes from step 3.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/39297405-18888938-494c-11e8-998a-1afba1e5ae51.gif)

**Comment by sebastienbarbier** [comment]
I believe this is the exact same issue as #982. Should be fixed with PR #986.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Notes" application (notes-1_0-qa-v1964) installed. Verified on on Samsung S7 Edge(Android 7.0).
